### ISSUE TITLE
unmodified artist 'Body' field gets bumped in recent changes in wiki listing

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#1021]
when updating an artist db record (e.g. other names and urls) but not touching the 'Body' field (wiki) the wiki entry is still bumped up in the recent changes (left-hand side column) and [Sitemap->Wiki->Listing](http://danbooru.donmai.us/wiki_pages).

this is quite misleading since viewing the individual wiki page history shows nothing got changed. and this could become potentially problematic if a user or script fixes a lot of urls alone which could flood the recent changes.

example:
http://danbooru.donmai.us/wiki_page_versions?search%5Bwiki_page_id%5D=10921 (the wiki was last modified 2010-08-19 02:49) but it got bumped up lately when new entries to the artist db fields were added http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=27504 (e.g. new other names, urls)

however, [Sitemap->Wiki->Changes](http://danbooru.donmai.us/wiki_page_versions) doesn't show the bumped unmodified artist wikis, which is correctly done.

related: https://github.com/r888888888/danbooru/issues/586

**Comment by evazion** [comment]
Fixed by #3501.
