### ISSUE TITLE
help:post_moderation wiki blank

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1151]
Not sure how I missed this up until now, but the help:post_moderation wiki linked in the "this post is pending" message is still blank.

What is it supposed to link to? I can't find a /help/post_moderation on the old site to copy from. The closest thing we currently have is about:mod_queue.

If there is no old help page to copy from, we could just copy about:mod_queue to help:post_moderation.

**Comment by Type-kun** [comment]
Was fixed in 1de2374a60524464fb6099aeaf6d65c619148644
