### ISSUE TITLE
Bring back the front page and catgirls post counter

### ISSUE THREAD

**Issue by CoconutEx** [r888888888/danbooru#1157]
Is there a reason it was removed?  I miss the catgirl post counter.

_ghostrigger edit: updated title_

**Comment by Hasshu** [comment]
Count me in.

Without the front page, guest (and logged-out) users are forced to see all kinds of... stuff in order to do a tag search.

@Type-kun 
> Maybe also make 'how to search' link on the front page, below the search textbox, which would open an expandable block containing basic search principles and, optionally, examples.

This. Or just make the link refer to "help:cheatsheet".

**Comment by lunaisnotaboy** [comment]
Would copying the relevant code from Danbooru v1 and adding it to a fork work @r888888888? I'm assuming it would, as I don't see why it wouldn't.
