### ISSUE TITLE
Bookmark tags

### ISSUE THREAD

**Issue by Sal-N** [r888888888/danbooru#1184]
Many users including me just need a place to put all favourite tags so that we can click and check on new posts, instead of typing them out. When you have a few hundred tags to keep up with, it's impossible to remember all. Subscriptions are not ideal because there's a limitation of 5 x 20 tags.

Such a personal tag list doesn't need updating, which is heavy on the server and the reason why subscriptions had a limitation. Without updating, I imagine this tag list can be unlimited, or have a limit of 10 000 tags or something.

These tags should be listed in the user's main account page for quick access, maybe called "Bookmark tags". Like subscription tags, users should also be able to create multiple bookmark tag groups and have the option to turn public visibility on/off.

**Comment by ToksT** [comment]
fixed
