### ISSUE TITLE
add automatically pixiv member id url during artist creation

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#1196]
with https://github.com/r888888888/danbooru/issues/1149 fixed, a valid pixiv source like http://i2.pixiv.net/img110/img/midoria/34403488.jpg will be added in the `URLs` field automatically.

it would be a nice feature if the artist pixiv member id url will be added as well like http://www.pixiv.net/member.php?id=4766344 (for the previous example) because many users forget.

and if this is indeed workable, maybe add the pixiv handle name (e.g. 水鳥Ａ) in the `Other names` field too.

**Comment by Type-kun** [comment]
This should be doable now, with all the API calls implemented lately.
