### ISSUE TITLE
Ability to tag pools

### ISSUE THREAD

**Issue by Sal-N** [r888888888/danbooru#1201]
The number of pools are near 6k. I think it's big enough to warrant a systematic tagging mechanism to enhance sorting and searching. 

Relying on users to write a good pool description so that the others can search is like relying on comments to find pictures. And the amount of effort to maintain <a href="http://danbooru.donmai.us/wiki_pages/29346">Wiki Pool Groups</a> would be better spent on tagging pools, which is much more precise, consistent and succint.

**Comment by r888888888** [comment]
I think the need for this is obviated with categories and full text search.
