### ISSUE TITLE
Short sequences should get an anonymous pool instead of a parent/children relationship

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1231]
>TODO [said](https://github.com/r888888888/danbooru/blob/ac98d7db37054254f645395766e96af143c691e4/TODO):

>Replace parent/child relationships with anonymous pools. Each post would have a related posts field. This would drive the creation of an anonymous pool.

---

>NWF Renim [said](http://danbooru.donmai.us/forum_posts/86115):

>Just an idea, but perhaps if there were nameless pools. Those that don't appear on the default list of "named" pools (but still on a not defaultly shown full/all list of pools for like moderating and similar) that could be used for these types of sequences/comics (probably with a size limit as well, since those that are large should be named imo). If there needs to be a name in the pool bar these pools could just use an automatically generated name of like "nameless pool starting with post #<id>" or something like that.

>At minimum such small sets of images should be linked together. Normally it's been done using parent/child relationships and in some cases through comments. Personally under the current setup I'd say use a combination of parent/child for linking them to the first page and then comments with links for ordering if nothing else. Though really, I'd rather we have an alternative to that as well, and I do not believe normal current pools is that answer.

---

I think limiting parent/child relationships to minor variations only would be quite helpful. (I don't think parent/child relationships should be removed completely, though.)

**Comment by r888888888** [comment]
Was in the middle of implementing this and realized there are some complications. A post should only belong to one anonymous pool, but enforcing that is difficult. There's no way to atomically guarantee a 1-to-1 relationship.

Maybe it doesn't matter too much practically, but posts can get in weird states where they belong to two or more anonymous pools which causes strange behavior during traversal and deletion. And I don't think the label "related posts" implies that sort of exclusionary behavior.

**Comment by Type-kun** [comment]
>A post should only belong to one anonymous pool, but enforcing that is difficult. There's no way to atomically guarantee a 1-to-1 relationship.

Table of `post_id | sequence_id | position` with unique key on post id? Then compose/parse string representations on edits.

**Comment by Type-kun** [comment]
I've been thinking about it, and there's an easy way of creating 1-to-1 relationship - place `sequence_id` in the post table. Post can have no more than 1 sequence, so it fits the model. Sure, it's not atomic, and concurrency can create a situation where multiple sequence strings have post id inside. However, the only negative consequence I can see is navigation issue when sequence navigation brings user to the post with different `sequence_id`. When this happens, navigation will jump to the sequence specified in the post. Maybe it's not that critical. Possibility of desynchronization is not pretty, though.

Another quite simple way, similar to what I suggested above, is to get rid of any additional tables and store `sequence_id` and `sequence_position` directly in the post table. This is not atomic either, but it does guarantee 1-to-1 relationship. "related posts" string can be composed on demand. Updating the sequence is as simple as 
* getting the `post_id` as array, and `sequence_id`
* updating posts `where sequence_id = <sequence_id> and id not in <id_array>` to set `sequence_id` and `position` to null
* updating posts `where id in <id_array>` to set `sequence_id` to `<sequence_id>`. Now, calculating the position could be tricky, but the position doesn't need to be _consecutive_. So we can use the same trick with `position()` function as with ordpool metatag (see #2089). Or, use activerecord capabilities to get the post group and update it
* The entire procedure could be wrapped in a transaction to ensure it doesn't fail midway.

The latter approach seems pretty solid to me. Concurrency is still an issue, but post will never belong to multiple sequences. Creating another table with FK to posts and unique constraint on post ID is an option, too, but it actually seems unnecessary unless I'm missing something.

I'm wondering about another thing, though. Imagine a situation where a post is already in a sequence. Then user includesit in another sequence. How should that be handled? Automatically remove the post from the first sequence or throw an error?

**Comment by r888888888** [comment]
I think it's a lot of complexity that doesn't add much to the current system. Parent/child is conceptually simple, and promoting it to a full fledged pool (maybe a process could be added to streamline this) isn't hard either.

Instead of trying to come up with a new system I think the effort would be better spent improving the UI for the existing systems.
