### ISSUE TITLE
Some posts have is_banned set to true although they aren't from a banned artist

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1268]
[Example.](http://danbooru.donmai.us/posts/1370322)

[Search to find some such posts](http://danbooru.donmai.us/posts?utf8=%E2%9C%93&tags=status%3Adeleted+status%3Abanned+-banned_artist+&commit=Go) (although it's not completely accurate).

It looks like all deletion reasons that include the word "request" set the post to banned, although that isn't completely accurate, as the uploader can request deletion as well.

**Comment by r888888888** [comment]
I've undeleted all deleted+banned posts, which affects 609 posts.
