### ISSUE TITLE
When appending tags with reltags, add them to the category-specific line

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1291]
> Type-kun said:
> BTW, if we're keeping the newlines, it'd be nice if the tag were concatenated to an appropriate line instead of the end, but that's pretty much impossible for current engine.

This doesn't seem impossible to me, unless I'm missing something. The only difficult case is when not all 4 categories are present. One way to get around that would be to leave blank lines for blank categories. Although that might not look nice.

**Comment by Type-kun** [comment]
Well, I don't know how it didn't occur to me 2 years, but it's perfectly possible if we simply keep 4 javascript variables representing tag count for each category. Initial values can be derived from post data, and then incremented for each reltag click. If user inputs something manually, assume it to be a general tag and don't increment anything.

P.S. Nevermind the necroposting, just browsing older issues to figure out if we missed some good ideas (yes, we did, but those are still too crazy, like pool tags :3)
