### ISSUE TITLE
On upload, add a new field: "download from URL"

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1312]
Currently, there is a file field and a source field on upload. If the file is provided, that is used for the image. Otherwise, the image is downloaded from the source given.

But there are some cases where uploaders wants to have the image downloaded from one URL, but set the source as something else.

For example, when uploading from twitpic, the URL of the image itself might look like: `http://d3j5vwomefv46c.cloudfront.net/photos/large/755221918.gif`. But the more useful link, which contains the artist's name, commentary, etc, would be: `http://twitpic.com/chn0ym/full`. The latter link seems like the better choice to set the source as.

This can currently be worked around in two ways: 1) Download the image to your computer and upload that, while setting the source to the desired link. 2) Upload the image from the direct URL in the source field, then go back and change the source. Neither of these are ideal; having another field would make it easier and give the user more control.

The site would check the fields in this order for the image: File, Download from, Source. So this would only be used when no file is provided. If neither the file nor the  download location are specified, then it would use the source field, like it currently does.

**Comment by evazion** [comment]
It's possible to achieve this by tagging the upload with `source:<whatever>`. However this is rarely necessary, as the bookmarklet now fixes the source automatically for most sites.

The idea of posts having multiple sources is a whole other issue.
