### ISSUE TITLE
Search by creation time for comments, notes, users, edits, etc...

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#1321]
The equivalent of the date/[age](https://github.com/r888888888/danbooru/issues/1225) metatags, but for comments, notes, edits, users, etc...

And for [either version](https://github.com/r888888888/danbooru/issues/1098) of the `group_by` parameter where applicable.

**Comment by evazion** [comment]
This was added in #3431. Use `search[created_at]` and `search[updated_at]`. The synax is the same as the date metatag.

Example: http://danbooru.donmai.us/tags?search[created_at]=2017-12-18..2017-12-25
