### ISSUE TITLE
Give indication when there are blacklisted posts in pools

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1425]
>Zelinkokitsune said:

>http://i.imgur.com/xC14GD4.png

>In Danbooru 1 there would be a box labeled BLACKLIST or something like that to indicate that there were images in that pool with a blacklisted term, you'd never know about the lost pages due to that behavior. But if you go to the posts view and clicking the black listed term it'll show up.

---

>Explosion said:

>I personally like this behavior. I'd like to see it stay around or if this isn't as intended I'd like to see it remain at least as an option in account settings.

**Comment by Moebius-Strip** [comment]
This appears to have been fixed somewhere down the road since the inline blacklist bar definitely shows up in pools now.

**Comment by ToksT** [comment]
Yeah was fixed in 1fffc2977f641c6087f39635aeb9e65ca9036685
