### ISSUE TITLE
Allow existing notes to be resized up/left

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1509]
Like #1498, but for existing notes, as opposed to only when creating a new note.

**Comment by Type-kun** [comment]
If no one is opposed to the concept, it can be fixed with replacing `handles: "se",` with `handles: "nw, se",` as `.resizable` option in `notes.js`. This will add another visual handle to the upper left corner of the note, like there is one currently in the lower right.

**Comment by ToksT** [comment]
Note that jquery ui styles the upper left resize handle so that it's invisible and slightly smaller than the bottom right one. It still works fine though, just less obvious.
