### ISSUE TITLE
Mark red no-post subscription tags

### ISSUE THREAD

**Issue by Sal-N** [r888888888/danbooru#1524]
If a user subscribes a tag and later that tag was moved to another tag (because it was too ambiguous to alias), that user's subscription will be broken and they won't be aware of it immediately. In some cases, the realization might be very late or never at all.

Ideally there would be some kind of marking for subscription tags that have no posts (e.g. link is red instead of blue). Then when a user looks in their profile, they immediately knows which subscription is broken and update it accordingly.

**Comment by ToksT** [comment]
A way of implementing it without performance problems would be to keep track of which lines of the subscription return no posts *while it's being processed* once per day, and store that information in a new `dead_queries` column. Then that column column could be used to figure out which queries to mark red without have to make a ton of searches every time someone views your profile.

**Comment by r888888888** [comment]
wontfix
