### ISSUE TITLE
Dtext: italics do not work in wiki links

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1779]
Example: http://danbooru.donmai.us/wiki_pages/6981

This dtext: `[[list_of_to_aru_majutsu_no_index_characters|List of [i]To Aru Majutsu no Index[/i] Characters]]`

Renders as: [List of &lt;em>To Aru Majutsu no Index&lt;/em> Characters](http://danbooru.donmai.us/wiki_pages/show_or_new?title=list_of_to_aru_majutsu_no_index_characters)

It should render as: [List of <em>To Aru Majutsu no Index</em> Characters](http://danbooru.donmai.us/wiki_pages/show_or_new?title=list_of_to_aru_majutsu_no_index_characters)

**Comment by evazion** [comment]
The first issue (`[[list_of_touhou_characters|List of [i]Touhou[/i] Characters]]`) would be doable (basically do https://github.com/r888888888/dtext_rb/pull/35, but for wiki links). However, this is such a niche thing I don't think it's really worth the trouble.

The second issue (`{{-artist_tag site:http://www.user.com/*}}` being misparsed) is no longer a problem.
