### ISSUE TITLE
Keyboard shortcuts don't work on non-english layout

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#1852]
Events "keydown.w", "keydown.s" etc. don't fire when I'm using russian keyboard layout. The keycode contained in the keydown event object should be the same for every layout, so I think it's a bug.

**Comment by Type-kun** [comment]
Still broken. Can we update jquery.hotkeys? We are, unfortunately, using the version prior to merging https://github.com/jeresig/jquery.hotkeys/pull/31 , which supposedly restores keydown functionality.

**Comment by Type-kun** [comment]
@r888888888 - requesting deploy to testbooru, don't want another set of broken shortcuts, should be tested first.

**Comment by ToksT** [comment]
ftr I did test it with Russian keyboard layout.

**Comment by Type-kun** [comment]
Oh, good to know it works, then :3 I just wanted to check that all shortcuts still work properly after jquery.hotkeys update.

**Comment by r888888888** [comment]
Hmm, asset precompilation fails. Likely there's a JS syntax error somewhere.

**Comment by r888888888** [comment]
Nevermind, it just deployed cleanly. It's on Testbooru now.

**Comment by Type-kun** [comment]
Yep, all shortcuts work in all layouts. Tested everything except tag scripts and approval, 'cause I have neither on testbooru.
