### ISSUE TITLE
Regenerate all samples and thumbnails

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1862]
The way samples and thumbnails are created has changed since Danbooru 1 (see #1239 and #1665). Existing ones should be regenerated for consistency.

**Comment by evazion** [comment]
#3235 made it possible to do this using post replacements. There are about 5000 posts under `transparent_background id:<=1361925 status:any` that would need to be replaced. This could be scripted if there are any approvers interested in doing so.
