### ISSUE TITLE
Improvements to artist finder and constraints on the image source field

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#1866]
First, some common suggestions:

1) Prefer pages containing the image info (like artist name, profile link and comments) over direct links for image source for twitter, twitpic and niconico, maybe for some other sites as well.
2) Make artist finder more intelligent: e.g. when possible, try to normalize given link to find out the page containing artist info, download and parse it, then look up artist in the database.
3) Try to automatically normalize the given link before saving the image; e.g. get pixiv direct link from member_illust.php, get nicoseiga image info page from direct link etc. Also sometimes requires downloading and parsing the page.
4) Warn user it's impossible to normalize the link automatically, e.g. for twitter and twitpic images. Ask to specify the link manually, show the link to wiki pages describing how to do so, allow to force upload.

I think having a link that allows to see author and his comments is more important than having direct image links, as it sometimes becomes overly hard to identify the artist, especially when it was overlooked upon upload which happened some time ago. Normalizing links automatically is a lot of work, but it can help tagging and will keep the database organized.

**Comment by r888888888** [comment]
This ticket is getting a little too long. If people want to add (or fix) support for other sites they should create new tickets instead of attaching it to this one.
