### ISSUE TITLE
First post of forum topic doesn't show "updated by" message

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#1903]
It seems that the OP of http://danbooru.donmai.us/forum_topics/9668 was edited and the thread was bumped as it should be. But the "updated by" message doesn't appear at the bottom of the OP.

**Comment by r888888888** [comment]
Are you sure? I just edited it now and it appears. Looking at the database it doesn't look like it was edited previously.

**Comment by ToksT** [comment]
One way of reproducing this is to delete a topic then undelete it. This bumps the thread because the topic was updated. But the first post wasn't updated, so it doesn't show the updated by message.

In other words, I think the first post should mention any edits to the topic.

**Comment by r888888888** [comment]
Unfortunately I don't we reliably keep track of who modifies the topic itself.

**Comment by ToksT** [comment]
What if when the topic is deleted/locked/stickied, we call `original_post.touch`?

**Comment by r888888888** [comment]
That would probably work.
