### ISSUE TITLE
dtext support for notes

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#1911]
when referencing links on-site, users resort to the anchor tag. ideally, the href attribute should be relative.  but this is not always the case. some users type the absolute address which results jumping to another domain  (danbooru vs. hijiribe).

**Comment by evazion** [comment]
> Regarding the links themselves, I've had an idea to automatically transform any http://*.donmai.us/... to internal /... link,

#3170 does this for notes, which should fix the issue at hand. I'll leave the broader idea of dtext in notes to #1531.
