### ISSUE TITLE
Incorrect artist results when searching by url and no match is found

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2011]
Let's say you do an artist search or use the artist finder for the url [https://twitter.com/some_artist_that_doesnt_exist_in_the_database](http://danbooru.donmai.us/artists?utf8=%E2%9C%93&search[name]=https%3A%2F%2Ftwitter.com%2Fsome_artist_that_doesnt_exist_in_the_database&search[order]=date&commit=Search). You would get these 8 results:

```
00ichiko
00tuma00
00tea
00zumou
00919
00mochio00
@@@
[]
```

The reason is that those are the first artists alphabetically that have any twitter.com url.

But those results shouldn't be returned when searching for the above url. Since no matches were found, nothing should be returned. Returning incorrect artists is misleading.

This bug isn't limited to twitter.com. It happens with pretty much any website that isn't limited to a specific artist. Some other examples include nicovideo, drawr, dlsite, yfrog, suimy, tinami, twipple, blog.fc2.com, and I'm sure there are others.

This was fixed for pixiv specifically after issue #1573.

**Comment by evazion** [comment]
This is a duplicate of #2696. Twitter in particular was fixed in #2703, but not other sites.

**Comment by evazion** [comment]
Closing as duplicate.
