### ISSUE TITLE
Indicate in note history if note was moved

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2012]
If a note was moved or resized, the note version should give some sort of indication that this happened. Like the text "note was moved" at the right of the row, and hovering over it will give the exact numbers it was moved by.

**Comment by Type-kun** [comment]
I'd want to see that implemented, too. See http://danbooru.donmai.us/forum_topics/11582 for some considerations. 

As for the implementation, it would probably require two additional columns in the versions table? As far as I see in the code, versions are just printed as-is, so unless we store change info, we'll end up with additional query for each version line...

**Comment by ToksT** [comment]
> As for the implementation, it would probably require two additional columns in the versions table? As far as I see in the code, versions are just printed as-is, so unless we store change info, we'll end up with additional query for each version line...

That's how post version diffs already work though, so I don't think doing the same thing here would be the end of the world.

**Comment by Type-kun** [comment]
Well, having `previous` version handy allows more freedom, certainly. If that's not too expensive, why not.

**Comment by ToksT** [comment]
![note movement](https://cloud.githubusercontent.com/assets/3627189/7107444/d4981924-e133-11e4-961c-37266cfac82f.png)

Any other suggestions?

**Comment by kxz** [comment]
I'd prefer something more concise, like

> 221×217 @ 771,321 → 141×144 @ 550,139

but that's just me.

**Comment by Type-kun** [comment]
> (deleted) (body not changed)

`(deleted)` should be the only notice, because body never changes on deletion?

BTW, while we're at it, why not display the note coordinates somehow? Perhaps, add `title` attribute to `946310.3` links, saying `221×217 @ 771,321` or something like that.

**Comment by ToksT** [comment]
> (deleted) should be the only notice, because body never changes on deletion?

Technically it's possible via the api.

It's also possible if two people are editing the post at the same time. One person deletes the note, then the second person who already had the post loaded edits the note.

These aren't exactly common occurrences, though.

**Comment by ToksT** [comment]
> BTW, while we're at it, why not display the note coordinates somehow? Perhaps, add title attribute to 946310.3 links, saying 221×217 @ 771,321 or something like that.

That seems like a slightly unintuitive place to put it. Though I guess in the body column is too. Maybe we should just add a new column:

![note movement 2](https://cloud.githubusercontent.com/assets/3627189/7116793/498010d2-e1c2-11e4-883d-fddfaf247c1b.png)
