### ISSUE TITLE
disable merge when changing non-pixiv sources

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#2055]
i understand merge occurs within one hour. after reading [topic #10024](http://danbooru.donmai.us/forum_topics/10024), it may be possible that some users may upload from deviantart, using the direct link. then change the source to the artist-friendly version. if this action occurred within an hour, the direct link will be lost in the tag history.

related:
issue #2027
issue #1866
issue #1863

**Comment by r888888888** [comment]
Would prefer to just develop the deviantart rewrite adapters. Should message people who persist in using the direct link to use the html page instead.
