### ISSUE TITLE
Update user _count fields when expunging posts/wikis

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2062]
The fields `post_upload_count` and `favorite_count` will fail to be decremented when one of the user's uploads/favorites is expunged. This can lead to those fields being higher than they actually should be.

Similarly, `wiki_page_version_count` might become inaccurate if a wiki page is permanently deleted.

**Comment by evazion** [comment]
`post_upload_count`, `post_update_count`, `note_update_count`, and `favorite_count` are the fields that need to be updated when a post is expunged.

Wikis aren't permanently deleted any more, so `wiki_page_version_count` doesn't need to be fixed.
