### ISSUE TITLE
div-tags in notes behaving strangely

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2072]
I noticed two possibly connected div-tag-related note issues in [post #1576423](https://danbooru.donmai.us/posts/1576423):

Firstly, this is the content of the note as I entered it:
```HTML
<div style="background-color:#000; color:#fff">
<span style="font-size:3em">Black Rabbit Group</span>

- Blak Rabbit -

<tn>Missing letter in the original</tn>
</div>
```
This is the content of the note now, shown when trying to edit it:
```HTML
<div style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);">
<span style="font-size:3em">Black Rabbit Group</span>

- Blak Rabbit -

<tn>Missing letter in the original</tn>
</div>
```
The colour codes have been exchanged and spaces introduced into the CSS. That's fine but shows that some modification is going on.

This is what's shown in the note's history:
```HTML
<div style="background-color:#000; color:#fff"><span style="font-size:3em">Black Rabbit Group</span>
- Blak Rabbit -</span>
<tn>Missing letter in the original</tn>
```
The CSS is still as I entered it, but one of the tags has been changed and incorrectly at that: The closing `div` was moved to in front of the `tn` and was changed into a `span`, which doesn't make sense to me.

Secondly, the spacing above and below the note's content is off. There's a blank line each at the top and the bottom in the rendered note, which I didn't expect.

In [post #1576621](https://danbooru.donmai.us/posts/1576621), I noticed that the spacing of the top blank line depends on the font size for the (first?) `div` tag. The note in question uses a font size of 900%, which resulted in lots of blank space at the top. The note's contents were only that `div` tag with no translation note and it had no extra space at the bottom. The note's been changed back to use a `span` tag to get rid of the huge extra space at the top.

Maybe related to issue #1691.

**Comment by ToksT** [comment]
The extra newlines was a bug with Sanitize that was fixed in version 3.0.0. So this issue can be closed if Danbooru's version of Sanitize was updated to 3.0.0 (currently using 2.1.0).
