### ISSUE TITLE
finding 0-post artist records left active

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#2104]
some records in artist db are not deactivated properly, leaving them active like http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=105463 and http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=105071 . sometimes urls too were left resulting more than 1 active match for the same artist.

**Comment by evazion** [comment]
Fixed by a05c517 (added `empty_only=true`) and by #3002 (made `empty_only` accessible in the search form).

**Comment by evazion** [comment]
Closing, as noted this is now achievable by searching `/artists` with `Active = Yes` and `Has tag = No`:

https://danbooru.donmai.us/artists?search%5Bhas_tag%5D=false&search%5Bis_active%5D=true
