### ISSUE TITLE
security certificate has expired

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#2118]
as reported in http://danbooru.donmai.us/forum_posts/95716

when accessing https://danbooru.donmai.us now a warning appears. the validity was only from march 20, 2013 up to march 23, 2014 (today).

**Comment by kittey** [comment]
The certificate for danbooru.donmai.us expired at 2015-04-24 21:59:06 GMT.

Remember to get certificate with SHA256 if your CA still offers SHA1 ones. :)

**Comment by r888888888** [comment]
Damn it, I had two SSL certs at one point and I let the wrong one expire. It should be setup again now.
