### ISSUE TITLE
last_noted_at doesn't get updated sometimes

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#2154]
http://danbooru.donmai.us/posts/1686238

1 out of 7 of opening the browser, i get all the notes. most of the time only the 3 top-most translation notes are loaded.

on failure and when i viewed the html source, the other translation notes were missing together with their div containers.

this has been confirmed and reported by multiple users in the [forum](http://danbooru.donmai.us/forum_topics/9127?page=55#forum_post_96966).

when checked on other browsers, the notes all loaded successfully.

probably related: issue #2072

**Comment by ToksT** [comment]
Figured out the cause. Rails only updates a note's `updated_at` if at least one of the note's fields have actually changed. However, Danbooru updates the post's `last_noted_at` with the note's `updated_at` value regardless of whether anything changed or not. So if someone re-saved a note without changing it then it would cause this bug.

I fixed it to only update `last_noted_at` when the note is changed.
