### ISSUE TITLE
Tags with negative/inflated post count

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2171]
Could have swore we had an old issue about this but apparently not.

Some tags' `post_count` field is in the negatives even though that should be impossible. This seems most common with tags that have been aliased to another tag. For example, [food_in_pussy](http://danbooru.donmai.us/tags?commit=Search&search[hide_empty]=no&search[name_matches]=food_in_pussy&search[order]=count&utf8=%E2%9C%93) has zero posts and is aliased to a different tag, but its post count is listed as -19.

It's easy to fix these manually with a tag correction and I don't think they actively harm anything, so it's not a serious issue, but iiirc this has been an issue ever since the Danbooru 2 upgrade so it would be nice if fixing it is possible.

**Comment by ToksT** [comment]
Maybe the clean up could be run on the tag after the alias is finished running, instead of it being run daily for all tags?

Currently there's a period of up to 24 hours between the alias being made and the post count being corrected, which isn't that bad but could be improved.

**Comment by Type-kun** [comment]
It looks like creating an alias quite consistently gets both antecedent and consequent tag to have wrong post post count - the former goes to negative numbers, while the latter is inflated by the same number. When I approved bulk update request for artists, it happened for every single alias, so multiple jobs updating the same post doesn't seem to be the cause.
But it actually does sound like concurrency problem - could it be that two workers are taking up the same task? Are workers running simultaneously on multiple servers, perhaps?

**Comment by Type-kun** [comment]
Also, could it be that some exception happens during `process!` in tag_alias.rb, and `retry` causes it to repeat everything anew, messing up the counts somehow? @r888888888, maybe you could add some sort of temporary logging to see when `process!`  begins execution, and when exception happens? This way, we could find out whether worker concurrency or exception repeats are actually causing this.
