### ISSUE TITLE
Allow searches for source strings containing spaces

### ISSUE THREAD

**Issue by kxz** [r888888888/danbooru#2178]
As requested in [forum #97507](https://danbooru.donmai.us/forum_posts/97507).

Using underscores for this as we do with tags might be a problem, since underscores are already quite common in URLs. Something like `source:"string with spaces"` would be nice, but this would require a fairly significant refactoring of the query parsing code, and could additionally cause confusion with wildcards (are those escaped inside quotation marks?).

**Comment by evazion** [comment]
Fixed in #2679.
