### ISSUE TITLE
A way to search all posts that are in series/all posts that are NOT in series

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2239]
Suppose there's an artist that has several short stories uploaded along with regular images. Once I read all the stories and took a liking for the artist, I want to see the rest of the images... except I can't filter out pools I already visited, except specifying those one by one in the search string, which in turn becomes hell if there are dozens of pools. `pool:none` doesn't quite work because it also filters out collection pools. It would be nice if I could specify something like `-pool:series` and get what I need. The same could be done for collection pools.

Probably the only way to make it work fast enough is to add `pool:series` and `pool:collection` pseudotag to regular pool string every image has.

**Comment by Type-kun** [comment]
Lots of time passed, and I still miss that feature, hence reviving :3

>Hm, that's a pretty clever solution... until someone changes the category of a pool and every image in the pool needs to have its pool_string updated. 

Well, category of large pools is rarely changed, and it's indeed a task for a delayed job. As for issue #1309, is it still bugged? I've checked the images mentioned in the issue, and they have correct tag counts now. Also, either way, even if it's bugged, if it works for the majority of images, it's enough.

**Comment by ToksT** [comment]
> Well, category of large pools is rarely changed, and it's indeed a task for a delayed job. As for issue #1309, is it still bugged? I've checked the images mentioned in the issue, and they have correct tag counts now. Also, either way, even if it's bugged, if it works for the majority of images, it's enough.

I think the problem might be that a delayed job updating those fields at the same time as a user or a second delayed job causes them to become inaccurate. I guess it's not that common for that to happen unless someone's actually trying to do it.

Also I think those fields get recalculated when the post is saved or you run a tag correction so it should be fixable when you come across posts like that.

**Comment by ToksT** [comment]
The script `script/fixes/032_add_pool_category_pseudo_tags.rb` will need to be run to update existing posts on the site

**Comment by Type-kun** [comment]
Are these fix scripts need to be run manually? Because series/collection metatags are currently added only to new/recently edited posts.

**Comment by ToksT** [comment]
Yes `script/fixes/032_add_pool_category_pseudo_tags.rb` still needs to be run

**Comment by Type-kun** [comment]
Well then, gotta call @r888888888 here.

**Comment by ToksT** [comment]
btw, the script has to update like 300,000 posts and it slowed down my laptop test server quite a bit while running, dunno if it will slow down the live server or not but maybe run it at a low traffic time of day in case.

**Comment by Type-kun** [comment]
@r888888888 , it's been a month already, but the script is still yet to be run.

**Comment by ToksT** [comment]
Turns out it's a good thing the script wasn't run yet, there was a bug where if you used the pool: or -pool: metatags to add/remove a post to a pool the pseudo tags wouldn't be added/removed. When the script is run it should have the double effect of populating pseudotags on old posts and fixing the newer posts affected by this bug.

**Comment by ToksT** [comment]
I think the script was run at some point, there don't seem to be any posts missing the pseudotags now
