### ISSUE TITLE
New gesture support breaks JS on older browsers

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2243]
The recent addition of gesture support for the mobile page breaks almost all JavaScript on Danbooru on pre-ES5 browsers because hammer.js uses the non-existent Object.create() function during setup.

Was that by accident or is that accepted collateral damage?

**Comment by evazion** [comment]
From https://danbooru.donmai.us/forum_topics/9127?page=202#forum_post_136523:

> Separate note- I'm sure other people have gone over it by now, but while browsing on mobile, images have been loading scaled to a different size even though the rest of the page loads scaled to the mobile resolution. See this example:

> https://i.imgur.com/S7U5yVk.png
> https://i.imgur.com/Dv3Cnnm.png

Reopening because I suspect the above issue may be caused by Javascript breaking due to a lack of ES5 support in legacy browsers. Including a ES5 shim/polyfill should fix this.
