### ISSUE TITLE
Add toggle/link and/or option for linking back to the list-style Pools index

### ISSUE THREAD

**Issue by mseymour** [r888888888/danbooru#2255]
There should be a way to either set the pool index view by default, switch between gallery view and list view, or both.

Right now, the Pools navigation link only goes to http://danbooru.donmai.us/pools/gallery, and clicking on "Listing" obviously does the same thing.

**Comment by ToksT** [comment]
So how about we change the gallery back to the default view when you click "Pools" now? I fixed the things people didn't like about the gallery view. There's also a link on the gallery back to the listing so it's still possible to access that.

Alternatively, add a user setting for which one should be the default.

**Comment by Type-kun** [comment]
If you make gallery a default, add a user setting, please. I can't speak for other users, but I primarily use pool listing to search for a specific pool, so neat table of titles is more handy than gallery. Gallery is fine for browsing pools, as a preview tool, so I use it occasionally as well, but only occasionally.
