### ISSUE TITLE
Pixiv image link format change

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2261]
See http://danbooru.donmai.us/forum_topics/9127?page=71 , starting at Ars' message 100521.
The dreaded image URL format change finally happened, and they no longer have artist moniker in them, thus breaking artist finder capabilities and `source:pixiv/` tag.

The new urls basically have the format based on post timestamp and id, `http://i*.pixiv.net/img-original/img/YYYY/MM/DD/HH24/MI/SS/<IMAGE_ID>_p0.jpg` Source link redirection is also currently broken, but can easily be fixed, because it only needs illustration ID to work. Multi-page illustrations seem to be unaffected... for now.

http://danbooru.donmai.us/posts/1803476 is the result of uploading the image with new URL format.

It seems that repairing artist finder would require rewriting the code to make a query and parse it. It can be beneficial for other websites with similar problem, but that's a lot of work, of course.

**Comment by ToksT** [comment]
@Type-kun What about `source:pixiv/NAME/` searches? Doesn't that still need to be fixed?

**Comment by Type-kun** [comment]
Oh, right. Got a bit cross-eyed there and thought #2266 covers that too. It should be a separate issue, perhaps?

**Comment by ToksT** [comment]
> Oh, right. Got a bit cross-eyed there and thought #2266 covers that too. It should be a separate issue, perhaps?

That makes sense, it is somewhat difficult and separate from the url parsing in this issue. I'll make one.
