### ISSUE TITLE
pagination on some forum topics doesn't appear on title after 20 posts

### ISSUE THREAD

**Issue by ghostrigger** [r888888888/danbooru#2305]
not sure if this related to issue #2244 or some recent updates, but just noticed that there is no `page 2` in the forum topic http://danbooru.donmai.us/forum_topics/11123 despite having 2 pages worth of posts (29 as of now).

**Comment by ToksT** [comment]
Another one off by a page http://danbooru.donmai.us/forum_topics/7805

**Comment by ToksT** [comment]
Another http://danbooru.donmai.us/forum_topics/8282
