### ISSUE TITLE
has_active_children of parent not always updated on deletion of child

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2310]
Example child: http://danbooru.donmai.us/posts/1846567
Example parent: http://danbooru.donmai.us/posts/700422

When the child was deleted the parent should have had has_active_children set to false but it wasn't updated for some reason.

This bug doesn't seem to occur 100% of the time a post is deleted, though it has happened quite a few times from what I see looking through recently deleted posts.

Manually editing the child's parent_id does force the parent to be updated to the correct state.

**Comment by evazion** [comment]
AFAIK this isn't an issue any more. I haven't seen any reports of this still happening at least.
