### ISSUE TITLE
Artist search - NicoSeiga - not finding artist entries from partial URLs

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2319]
I tried to search for an artist using the URL
> http://seiga.nicovideo.jp/user/illust/5961847

and didn't get a result.

The artist entry has the URL 
> http://seiga.nicovideo.jp/user/illust/5961847?target=illust_all

**Comment by r888888888** [comment]
This isn't even really useful, is it? There's no information about the artist in the URL so at best you're matching a single illustration.

**Comment by ToksT** [comment]
> This isn't even really useful, is it? There's no information about the artist in the URL so at best you're matching a single illustration.

Is there any other way to find if a seiga artist has an entry on Danbooru yet, other than searching on one of these two urls? If there's not it seems useful so that people don't create duplicate artist tags for the same artist.

**Comment by ToksT** [comment]
Maybe we can fix this by simply normalizing away the ?target=illust_all part out of the url in the `normalized_url` field. Then the search should work. Would need to update the existing artists in the database though.

**Comment by ToksT** [comment]
Script still needs to be run

**Comment by r888888888** [comment]
Run.
