### ISSUE TITLE
Nonexistant dmail filter deletes all mail

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2325]
Users that don't have a dmail filter will have `is_deleted=true` set for all their incoming mail since the empty regex `//` matches everything.

**Comment by ToksT** [comment]
As of commit 67e46f6e5c73c2aa950723b19e4f4bd8a0d02c72 filtered dmails will no longer appear in the messages list at all.

But dmails sent while this bug (#2325) still existed were all filtered, so 67e46f6e5c73c2aa950723b19e4f4bd8a0d02c72 is going to make these dmails become inaccessible. These dmails should have is_deleted set to false in order to unfilter them, otherwise people looking through their old messages will have some dmails missing.

**Comment by ToksT** [comment]
Oh, also applies during the period that #2419 existed.

**Comment by r888888888** [comment]
What I can do is since deleted dmails were never hidden in the first place is just set is_deleted=false for them all. Users can redelete them if it bothers them.

**Comment by r888888888** [comment]
This only affects 33 dmails so apparently the delete functionality wasn't use much.

**Comment by ToksT** [comment]
> What I can do is since deleted dmails were never hidden in the first place is just set is_deleted=false for them all. Users can redelete them if it bothers them.

Yeah, I think that should solve it.

> This only affects 33 dmails so apparently the delete functionality wasn't use much.

I think filters are the only thing using is_deleted, with manual deletions permanently destroying the record? It's fewer than I expected either way though.
