### ISSUE TITLE
Deadlock detected while editing multiple posts

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2329]
I was sometimes getting deadlock errors when making multiple post edits at once, until I added some additional locking on my end.

```
post #1548272 - 500 Internal Server Error:
ERROR:  deadlock detected
DETAIL:  Process 12036 waits for ShareLock on transaction 117361609; blocked by process 15586.
Process 15586 waits for ShareLock on transaction 117361610; blocked by process 20853.
Process 20853 waits for ExclusiveLock on tuple (922,2) of relation 17211 of database 16386; blocked by process 12036.
HINT:  See server log for query details.

post #952606 - 500 Internal Server Error:
ERROR:  deadlock detected
DETAIL:  Process 15586 waits for ShareLock on transaction 117361610; blocked by process 20853.
Process 20853 waits for ExclusiveLock on tuple (922,2) of relation 17211 of database 16386; blocked by process 12034.
Process 12034 waits for ShareLock on transaction 117361609; blocked by process 15586.
HINT:  See server log for query details.
```

**Comment by evazion** [comment]
This can happen when updating a pair of parent/child posts at the same time. I was able to reproduce it by running two `rails server` instances, setting a breakpoint on `Post.update_parent_on_save` with `binding.pry`, then updating both posts at the same time:

```
ERROR:  deadlock detected
DETAIL:  Process 3364 waits for ShareLock on transaction 5389050; blocked by process 5915.
        Process 5915 waits for ShareLock on transaction 5389047; blocked by process 3364.
        Process 3364: UPDATE posts SET has_children = 't', has_active_children = 't' WHERE id = 2609136
        Process 5915: UPDATE "users" SET post_update_count = post_update_count + 1 WHERE "users"."id" = $1
HINT:  See server log for query details.
CONTEXT:  while locking tuple (13817,13) in relation "posts"
STATEMENT:  UPDATE posts SET has_children = 't', has_active_children = 't' WHERE id = 2609136

ERROR:  deadlock detected
DETAIL:  Process 3364 waits for ShareLock on transaction 5389065; blocked by process 5915.
        Process 5915 waits for ShareLock on transaction 5389062; blocked by process 3364.
        Process 3364: UPDATE posts SET has_children = 't', has_active_children = 't' WHERE id = 2609136
        Process 5915: UPDATE "users" SET post_update_count = post_update_count + 1 WHERE "users"."id" = $1
HINT:  See server log for query details.
CONTEXT:  while locking tuple (13817,17) in relation "posts"
STATEMENT:  UPDATE posts SET has_children = 't', has_active_children = 't' WHERE id = 2609136
```

**Comment by evazion** [comment]
When a post is updated three things happen: the post itself is updated, then the updater's `post_update_count` is incremented, then the parent post's `has_children` flag is set. I think this is what happens:

* The child updates its `tag_string`. This locks the row for child post until the transaction ends.
* The child updates the user's `post_update_count`. This locks the user.
* The parent updates its `tag_string`. This locks the parent.
* The parent tries to update the user's `post_update_count`. The user is locked by the child, so this blocks until the child finishes.
* The child tries to update the parent's `has_children` flag. The parent is locked so this blocks.
* Deadlock.

I think setting the `has_children` flag only when the parent changes would fix the immediate problem. Currently it's set on every update, but I don't think it needs to be.

**Comment by kittey** [comment]
To me as someone who doesn’t know the Danbooru internals, it sounds like steps two and three should be swapped: set the parent post’s `has_children` flag before incrementing the updater’s `post_update_count`, because if a lock on the user would only be needed for the very last step, the deadlock could not happen. Would that be possible?

**Comment by evazion** [comment]
I tested it and that does seem to work. Or at least, I can't trigger the deadlock any more. I'm honestly not sure whether that solved it or makes it harder to trigger.

**Comment by kittey** [comment]
It should look like this now:

* The child updates its tag_string. This locks the row for child post until the transaction ends.
* The parent updates its tag_string. This locks the parent.
* The parent tries to update the user's post_update_count. This locks the user.
* The child tries to update the parent's has_children flag. This needs to lock the parent, but is it unlocked by now?
* The child updates the user's post_update_count. This locks the user.

I know little about row locking and transactions. Is everything getting unlocked properly up there? If everything stays locked until the very end, it might still run into a deadlock. If the parent and user are unlocked between steps 3 and 4, it should be alright.

**Comment by evazion** [comment]
> I know little about row locking and transactions. Is everything getting unlocked properly up there? If everything stays locked until the very end, it might still run into a deadlock.

Everything stays locked until the very end. In rails, saving a post runs the entire saving process inside a transaction. And in postgres, updating a row has the implicit side effect of locking out other writers to that row until the transaction completes. These locks are implicit, so they can't be explicitly unlocked earlier, the only way to unlock them is to finish the transaction.

> Edit: I just read your posts again and I guess that you have one process doing only the modifications on the parent and user and the other does only modifications on the child and the user? And the transaction you speak of is actually one per process? So if the process modifying the parent post and user’s post_update_count is done, it finishes its transaction and releases all its locks so that the process for the child post can continue?

This is correct. I should've been more clear: the client sends two HTTP requests, one to update the child post and one to update the parent post. The web server handles each request in a separate Unix process. Each process has its own SQL transaction.

> What I applied was a standard solution to resolve deadlocks by reordering resource usage so that all competing processes request them in the same order, making deadlocks impossible. If the parent and user are unlocked between steps 3 and 4, this deadlock scenario should not be possible anymore.

Locking everything in a defined order is what needs to be done, but that's difficult to follow in practice. I'm fairly convinced now that this ordering solves this deadlock, but in general updating a post can touch on so many different things - not just the updater and parent, but also tags, pools, favorites, favgroups, votes, flags, etc - that it's not at all obvious what order things would have to go in to avoid deadlocks.
