### ISSUE TITLE
Eliminate some post indexes

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2333]
One of the few remaining issues with post uploads is the timeout from trying to insert into posts. I believe this could be alleviated by getting rid of some indexes.

**Comment by r888888888** [comment]
Here's a query of the various indexes on posts and their size/usage:

```
-[ RECORD 1 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_approver_id
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 424 MB
unique          | N
number_of_scans | 2596768
tuples_read     | 2744953877
tuples_fetched  | 2422207
-[ RECORD 2 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_created_at
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 104 MB
unique          | N
number_of_scans | 31665547
tuples_read     | 48290892057
tuples_fetched  | 10204361356
-[ RECORD 3 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_file_size
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 97 MB
unique          | N
number_of_scans | 6176892
tuples_read     | 1284463235
tuples_fetched  | 331860025
-[ RECORD 4 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_image_height
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 289 MB
unique          | N
number_of_scans | 431181
tuples_read     | 47337657472
tuples_fetched  | 13820251
-[ RECORD 5 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_image_width
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 304 MB
unique          | N
number_of_scans | 567384
tuples_read     | 35788415789
tuples_fetched  | 8630140
-[ RECORD 6 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_last_comment_bumped_at
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 27 MB
unique          | N
number_of_scans | 1972848
tuples_read     | 195149349
tuples_fetched  | 55217700
-[ RECORD 7 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_last_noted_at
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 12 MB
unique          | N
number_of_scans | 1088679
tuples_read     | 104258938734
tuples_fetched  | 46426924
-[ RECORD 8 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_md5
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 184 MB
unique          | Y
number_of_scans | 37268531
tuples_read     | 234120508040
tuples_fetched  | 234106977806
-[ RECORD 9 ]---+--------------------------------------
tablename       | posts
indexname       | index_posts_on_mpixels
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 213 MB
unique          | N
number_of_scans | 28592
tuples_read     | 6671616662
tuples_fetched  | 117156
-[ RECORD 10 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_parent_id
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 6696 kB
unique          | N
number_of_scans | 385282589
tuples_read     | 2141817597
tuples_fetched  | 792894888
-[ RECORD 11 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_pixiv_id
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 122 MB
unique          | N
number_of_scans | 5782453
tuples_read     | 13440913
tuples_fetched  | 167970
-[ RECORD 12 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_source
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 635 MB
unique          | N
number_of_scans | 0
tuples_read     | 0
tuples_fetched  | 0
-[ RECORD 13 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_source_pattern
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 431 MB
unique          | N
number_of_scans | 8177165
tuples_read     | 2891321200
tuples_fetched  | 50498672
-[ RECORD 14 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_tag_index
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 5372 MB
unique          | N
number_of_scans | 615727574
tuples_read     | 1805639490083
tuples_fetched  | 0
-[ RECORD 15 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_uploader_id
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 295 MB
unique          | N
number_of_scans | 14091506
tuples_read     | 49359653395
tuples_fetched  | 478459607
-[ RECORD 16 ]--+--------------------------------------
tablename       | posts
indexname       | index_posts_on_uploader_ip_addr
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 256 MB
unique          | N
number_of_scans | 0
tuples_read     | 0
tuples_fetched  | 0
-[ RECORD 17 ]--+--------------------------------------
tablename       | posts
indexname       | posts_pkey
num_rows        | 1.87671e+06
table_size      | 3573 MB
index_size      | 78 MB
unique          | Y
number_of_scans | 11132313643
tuples_read     | 6695201658794
tuples_fetched  | 6624632513666
```

Of particular interest are mpixels (not used often), source (not used at all), and uploader_ip_addr (not used at all).

**Comment by r888888888** [comment]
fixed in d2b4065951550921c1ffd16362f691665a8b96d4

**Comment by r888888888** [comment]
I've realized the existing source index does nothing for LIKE queries, which is why it was never used. However there is a way to build a text index that does support LIKE: http://stackoverflow.com/questions/1566717/postgresql-like-query-performance-variations

I'm wondering if it's worthwhile trying to build this index. I imagine it'd be much larger in size but it may finally solve issues with source queries being slow.

**Comment by r888888888** [comment]
Ping @RaisingK @evazion @Type-kun anyone else interested.

**Comment by ToksT** [comment]
> I've realized the existing source index does nothing for LIKE queries, which is why it was never used. However there is a way to build a text index that does support LIKE: http://stackoverflow.com/questions/1566717/postgresql-like-query-performance-variations

So this would help with wildcards at the start or middle of source searches like `source:*[C85]*` and `source:*deviantart*by_tsuaii*`?

**Comment by r888888888** [comment]
It would not help with those. I believe something like source:*last_word can be optimized but anything beginning and ending with wildcards can't be optimized AFAIK.

**Comment by ToksT** [comment]
> It would not help with those. I believe something like source:*last_word can be optimized but anything beginning and ending with wildcards can't be optimized AFAIK.

Are you sure? I tried doing what the stackoverflow answer said:

```sql
CREATE INDEX posts_source_gist_trgm_idx ON posts USING gist (source gist_trgm_ops);
```

Then I tried LIKE wildcard searches that have a wildcard at the beginning and end and sometimes the middle, and they seemed faster. And EXPLAIN said the above index was getting used.

**Comment by Type-kun** [comment]
Sure, dropping non-used indexes is a must. However, all remaining indexes are useful and we're going to hit the very same problem as they grow a little more in size. 

So, how about trying to tackle the problem from a different angle? 

First of all, isn't it possible to just selectively increase timeout for insert operations? Not like it gives us any security implications. If there's some sort of per-session config option, it would be more than enough, but brief googling gave me nothing.

Next, how frequently are the timeouts occurring, can they be reproduced at test environment, at least somewhat reliably? I mean, are we even sure indexes are at fault, and not some crontab job or autovacuum process putting locks on some tables/indexes? Also, if timeouts are occurring regularly, every once in a while, this might as well be the cause: http://www.postgresql.org/docs/9.3/static/gin-implementation.html - Index "update" mentioned is row insert/update/delete, of course.

>Another disadvantage is that, while most updates are fast, an update that causes the pending list to become "too large" will incur an immediate cleanup cycle and thus be much slower than other updates.

Also, well, index take much time to update due to large number of rows, so maybe partition the posts table? I don't really know how postgres handles it, but If every table partition has its own index, and select works like a view with `UNION ALL`'s, partitioning may be beneficial in both inserting AND updating. At least it seems worth trying out.

Last, it's reinventing the wheel, but it's possible to create our own "cache" or "partitioning" - another table with structure and indexes completely identical to `posts` which would gather posts for the whole day. Then run a job daily that would bulk-insert the new rows, clear the temporary table and rebuild/vacuum the indexes. All select/update/delete queries would need to go through a view combining both tables, armed with `instead of` triggers for update/delete.

**Comment by Type-kun** [comment]
>Then I tried LIKE wildcard searches that have a wildcard at the beginning and end and sometimes the middle, and they seemed faster. And EXPLAIN said the above index was getting used.

Yeah, trigram index is exactly for non-anchored LIKE searches, if I remember it correctly. However, it's gin/gist, so it will be slower than regular b-tree.

**Comment by r888888888** [comment]
Rather than increasing timeout i think it makes better sense to just fail fast and retry. I've never seen the timeouts happen locally or on testbooru. Partitioning posts is a good idea but it'd be a lot of work. It doesn't partition as cleanly as it does for favorites.

I'm going to deploy these index changes first and see if they affect performance and then I can investigate whether adding a new source index makes sense.

**Comment by r888888888** [comment]
Also, if the need is just source searches then that could theoretically be moved to a secondary service with a separate table or database. I've been toying with the idea of setting up a separate reporting server that could house a lot of data like that.

**Comment by Type-kun** [comment]
> Partitioning posts is a good idea but it'd be a lot of work. It doesn't partition as cleanly as it does for favorites.

If we're not looking for query speedup based on partitioning rules (like splitting on date and then querying on said date) but just for balanced partitioning, it would suffice to check on post id modulo partition count, like `id%10 = 1`, `id%10 = 2` etc. for 10 partitions.

**Comment by r888888888** [comment]
The problem is how would searches work? You'd have to perform the search on all partitions and then somehow aggregate them.

**Comment by r888888888** [comment]
The timeouts may actually be caused by the tag subscription processing running all at once. I'm going to try distributing the updates across 4 hours and see if that helps.

**Comment by r888888888** [comment]
Reverted in 5063e326e356395777b4b01a382f9727a472e585
