### ISSUE TITLE
Tag search with empty parameter fails

### ISSUE THREAD

**Issue by Lightforger** [r888888888/danbooru#2339]
Just searching for something like "knee'" ends up with "Cannot redirect to a parameter hash!" error if "category" & "has wiki page" aren't selected.
http://danbooru.donmai.us/tags?utf8=%E2%9C%93&search[name_matches]=knee&search[category]=&search[order]=count&search[hide_empty]=yes&search[has_wiki]=&commit=Search

**Comment by ToksT** [comment]
Fixed already, see #2338
