### ISSUE TITLE
Artist URLs: auto add 'http', remove non-links

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2346]
The default `browser.urlbar.trimURLs` Firefox setting removes `http://` from URLs, and sometimes users add things to the URL field that aren't any kind of URL.

If an edit to an artist entry places something in the URL field that doesn't start with a protocol, test it with `http://` and remove the line if the "link" doesn't work.

**Comment by r888888888** [comment]
What about cases where it should be https vs http?

**Comment by kxz** [comment]
We could use the same test as for source links (`^https?://`).

**Comment by Availu** [comment]
You can just put "//" before the url, the browser will automatically switch depending on wheter there's a certificate available.

**Comment by kxz** [comment]
That's not correct. Protocol-relative links use the protocol of the current page, so they'll point to `http://site.example/` for Danbooru over HTTP, and `https://site.example/` over HTTPS. Relatively few sites are available on both, so this would break a vast number of links.

**Comment by Availu** [comment]
Oh, true. My bad.
