### ISSUE TITLE
Updating alias/implication forum threads on approval or rejection

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#2348]
It's hard to tell when an alias or implication has been looked over now outside of seeing whether the proposed change is still pending, active, or deleted from the database.  Could you make it so that when the proposed change has been approved or removed it puts an update in the forum thread related to the proposed change?  Perhaps it could add a "(approved)" or "(not approved)" at the end of the title of the thread.

**Comment by ToksT** [comment]
One way of doing this would be to automatically create a forum post in the topic and attribute it to the approver, saying "Approved" or "Rejected". The benefit of this approach is that it would keep track of the exact time at which the request was approved and who approved it as well.

**Comment by r888888888** [comment]
fixed
