### ISSUE TITLE
Use :orig instead of :large for Twitter

### ISSUE THREAD

**Issue by MayhemYDG** [r888888888/danbooru#2349]
I see this has been pointed at in #2222, but danbooru is still using :large.
:orig files are usually the same as :large, but when it's not, it's totally worth it:

https://twitter.com/sumisu_/status/566930541455233024
https://pbs.twimg.com/media/B94kUq7CcAA5_GN.jpg:large
https://pbs.twimg.com/media/B94kUq7CcAA5_GN.jpg:orig

**Comment by r888888888** [comment]
fixed
