### ISSUE TITLE
Warn and ask uploader when there's a similar image with better quality

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2350]
Since we have IQDB in-house now, it might be nice to make the check automatic and mandatory.

So that, when:
* there is an image already on danbooru with 95%+ similarity to the one being uploaded
* said image has higher resolution and/or filesize
* there is no `revision` tag on the image that's being uploaded

the uploader should be warned that he's likely to upload a duplicate and asked for confirmation, and reminded to tag `revision` as such.  I'm not sure if current UI model allows intermediate interface pages providing user input, effectively "pausing" the upload, though.

**Comment by r888888888** [comment]
I believe this can only be done when the uploader posts, because we don't have information about the file until then. I suppose we could try and fetch a HTTP HEAD request on the image while sitting at uploads/new to get the size at least.

**Comment by r888888888** [comment]
fixed
