### ISSUE TITLE
Underscore/space inconsistency in API results

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2352]
The user name fields returned by the Post and Note API use spaces instead of underscores, whereas the other APIs I've checked use underscores:
- http://danbooru.donmai.us/posts/1940087.json - `"uploader_name":"dizzy c"`
- http://danbooru.donmai.us/notes.json?group_by=note&search[creator_id]=431453 - `"creator_name":"dizzy c"`
- http://danbooru.donmai.us/users/431453.json - `"name":"dizzy_c"`
- http://danbooru.donmai.us/post_versions.json?search[post_id]=1940087 - `"updater_name":"dizzy_c"`
- http://danbooru.donmai.us/pools.json?search[creator_id]=431453 - `"creator_name":"dizzy_c"`

**Comment by Type-kun** [comment]
Looks like this requires surprisingly much work, since from we can't easily tell `serializable_hash` and `to_xml` to serialize a method under another name. In other words, another method should be created for "pretty" creator/uploader name, and all calls to old method should be replaced.

**Comment by evazion** [comment]
> In other words, another method should be created for "pretty" creator/uploader name, and all calls to old method should be replaced.

After some grepping around, I only found one user-visible place that actually uses any of these fields, and that is in the thing that builds the tooltips on post thumbnails. I just fixed it inline.
