### ISSUE TITLE
Weird Error when trying to upload pictures

### ISSUE THREAD

**Issue by tranquilitycal** [r888888888/danbooru#2356]
Whenever I try to upload a file to Danbooru I see this instead of the image

```
An error occurred: error: Magick::ImageMagickError - unable to open image `/home/danbooru/danbooru/public/data/preview/4ff4a4b056f94b01b4bdf192aaef2c71.jpg': No such file or directory @ error/blob.c/OpenBlob/2709 
```

I know I can fix the second error by simply making the directory but the first one is my main one for worry right now. I think ImageMagick isn't working right.

**Comment by Type-kun** [comment]
Hm, first/second? I see only one error in what you provided - Imagemagick complaining it can't open the image in `-quotes, which it attempted to do in `blob.c` source file on line 2709. Probably. Not sure how to interpret `error/blob.c/OpenBlob/2709`, exactly, but still, that's a single error. Multiple `Error: err: errror:` is a simple side-effect of error reporting chain, each handler adds its own prefix. 

Anyway, either there's a permission problem (quite common when you sudo things) or the file is, in fact, missing, which might indicate some misconfiguration if it was uploaded without trouble. Search for 4ff4a4b056f94b01b4bdf192aaef2c71.jpg? Does it exists anywhere in the filesystem? If it does, and it is in the `/home/danbooru/danbooru/public/data/preview/` directory, then check for rights and owners with `ls -la`, or execute `sudo -u danbooru ls /home/danbooru/danbooru/public/data/preview/` to see if `danbooru` user can actually see the file and not get an Access Denied. Also check if `/home/danbooru/danbooru/public/data/preview/` directory actually exists - IM probabkly tries to open the file for writing, and will not create missing dirs in the process. If the file doesn't exists, then loading the image failed midway and you should examine logs. However, I believe you would not get to resizing the preview step if that was the case.

**Comment by tranquilitycal** [comment]
Yeah I actually fixed that this morning now the images are uploading like they should. Now my only issue is getting Nginx to work >_> 

I swear things are just not going as I hoped lol. I got Nginx configured as everyone is apparently saying however its not working I keep getting a 502 Bad Gateway error with nothing in the logs. Gonna go turn on verbose logging and see if I get anything there.

**Comment by tranquilitycal** [comment]
Alright, for all intensive purposes I decided to try and reinstall due to noticing a few things out of order and I notice this

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/danbooru/.rbenv/versions/2.1.5/bin/ruby extconf.rb 
checking for Ruby version >= 1.8.5... yes
checking for gcc... yes
checking for Magick-config... no
Can't install RMagick 0.0.0. Can't find Magick-config in /home/danbooru/.rbenv/versions/2.1.5/bin:/home/danbooru/.rbenv/libexec:/home/danbooru/.rbenv/plugins/ruby-build/bin:/home/danbooru/.rbenv/shims:/home/danbooru/.rbenv/bin:/home/danbooru/.rbenv/shims:/home/danbooru/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/danbooru/.rbenv/versions/2.1.5/bin/ruby

extconf failed, exit code 1

Gem files will remain installed in /home/danbooru/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rmagick-2.13.3 for inspection.
Results logged to /home/danbooru/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/rmagick-2.13.3/gem_make.out
An error occurred while installing rmagick (2.13.3), and Bundler cannot
continue.
Make sure that `gem install rmagick -v '2.13.3'` succeeds before bundling.
```

Not sure what is causing it but I also tried gem install rmagick -v '2.13.3' and still not good

```
root@hexbug:/home/danbooru# sudo -u danbooru bash -l -c "cd ~/danbooru ; gem install rmagick -v '2.13.3'"
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    /home/danbooru/.rbenv/versions/2.1.5/bin/ruby extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for gcc... yes
checking for Magick-config... no
Can't install RMagick 0.0.0. Can't find Magick-config in /home/danbooru/.rbenv/versions/2.1.5/bin:/home/danbooru/.rbenv/libexec:/home/danbooru/.rbenv/plugins/ruby-build/bin:/home/danbooru/.rbenv/shims:/home/danbooru/.rbenv/bin:/home/danbooru/.rbenv/shims:/home/danbooru/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/danbooru/.rbenv/versions/2.1.5/bin/ruby

extconf failed, exit code 1

Gem files will remain installed in /home/danbooru/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rmagick-2.13.3 for inspection.
Results logged to /home/danbooru/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/rmagick-2.13.3/gem_make.out
```

**Comment by r888888888** [comment]
The line:

```
checking for Magick-config... no
```

Means ImageMagick was not correctly installed on your system. Usually installing it with apt-get will set up everything correctly, at least on Debian/Ubuntu.

**Comment by tranquilitycal** [comment]
I'm on Debian 8 and I did install it correctly, I'll try uninstalling and reinstalling it and see if that helps.

**Comment by tranquilitycal** [comment]
```
checking for ImageMagick version >= 6.4.9... yes
```

got it to see Imagemagick but now its complaining about the MagickWand.h that it can't find now. Is there any specific versions I'm suppose to have of Imagemagick or is Debian just being a package breaker?

**Comment by r888888888** [comment]
Installing rmagick is a pretty well described problem on the internet. I'd look for hints elsewhere.
