### ISSUE TITLE
Note sets

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#2357]
Not sure if this idea or similar was proposed already, but looking at how one can have more than one tag script and swap between them got me thinking. Would it be possible to be able to link the notes on an image and have the contents of the notes registered to a specific set and be able to shift to say a different set of contents for the notes?  For example "User A" puts notes on an image and links them together registering the contents as "set 1", another user, "User B," comes by and using the same existing notes adds their own translation and registers the contents as "set 2." A user looking at the image with the notes then can swap the contents of the notes between Set 1 and Set 2, which shifts the written content visible in the notes, but not the position, size, or anything else.

**Comment by Type-kun** [comment]
This would require certain UI  and database changes. First of all, contents would be separated from note size and coordinates, which would in turn complicate versioning. Like, if someone changes the note size or position, reverting it later should not affect contents of any sets. Likewise, if contents of Set 1 is changed and reverted, Set 2 should never be affected even if it was changed after Set 1. That could get somewhat complicated.

Also, what use would it be other than translation to multiple different languages? This is definitely a valid use-case and I support it even though I wouldn't need it myself, but this would probably require another issue opened, as there are other  problems to address with multiple languages in notes, like varieties of `translated` tag and writing guidelines, and maybe some specific set naming if it's only used for multilanguage notes. 

Anyway, having multiple translations to the same language could provoke conflict. "Why'd you edit MY translation? Go create your own!", etc, turning collaborative effort into a competition. Also, suppose there's a pool translated by, say, Moonspeaker and ChaosKnight, in two different sets, "M" and "C". When user switches to the next image in the pool, he would desire to stay with the same set he selected on the previous image... but how would we know which it was? It would either require having the sets named exactly the same across the images, or marking/locking the set with the user that created it, or linking sets one into another between images. Last option is already giving me a headache on how to implement, locking or marking the set is going to turn into a variety of small problems, like when wrong user created the set and "garbage" sets. Exact naming would work, but will not be very user-friendly for the translators.

**Comment by r888888888** [comment]
I think it's a cool idea (and useful for cases like multilingual) but it would clutter up a UI that's already pretty cluttered for a use case that isn't common on the site right now. A deployment of Danbooru that was more centered around notes would probably find better use for it (and maybe an optimized UI for translation).

**Comment by RenimLS** [comment]
I figured it would be rather complicated, though didn't realize it would be quite that complicated. Also didn't take into consideration potential conflicts, not that I haven't already seen a case or so of those who seem to take offense when their notes get edited.

The idea was primarily geared toward a multilingual use, but on the issue of having more than one version of the same language, was thinking more along the lines of preferences. Some people prefer to leave out things like honorifics, or leave out verbal tics of characters, while others leave them in or put in effort to retain a characters verbal tic in some manner. It's also sometimes interesting how different people may approach a joke or pun in different ways.

Anyways I didn't really expect to see something like this get implemented at any time, more of throwing out an idea for something far into the future I guess.
