### ISSUE TITLE
Specific thing (and location) tag type

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#2358]
Just proposing that there might be some potential value in at least one new tag type. The site goes the step of covering general character types with general tags like "elf" and we cover specific characters with the character tags (for example the elf Deedlit), but we don't do something similar for locations or things. This has kind of caused some issues where unique things (particularly mecha and vehicles) and they end up getting tagged character tags, because we lack a similar tag type to cover specific/unique things. Some people feel they're more specific than what a general tag would imply (for example many gundam units are character tags), and so end up tagging them as characters. So it may be worthwhile to make a new tag type to lump unique things and locations to stand out from general tags, but also not take up space amongst the character tags.

I suggest locations as well, though less importance on covering them as there is on covering specific things (and not an issue if locations got lumped together with specific things as a tag type), but at minimum specific locations like Mount Fuji, Tokyo, London, etc should probably be pulled out of the general tag category along with things like M1 Abrams, Unicorn Gundam, Zaku, etc.

Examples

General: Elf
Specific: Deedlit
General: Succubus
Specific: Morrigan Aensland 
General: Mecha
Specific: RX-78-2 (ie the Gundam)
General: Battleship
Specific: USS Iowa (BB-61)
General: City
Specific: New York

Will admit potential risks of flooding of some tags (particularly with gun tagging), but those tags would still be used regardless, just in general tag form anyway. The matter on whether those tags should be used at all is also a matter for discussion of the forum instead.

**Comment by Type-kun** [comment]
Hm, not to say I can't see your point, but I don't think your analogy is entirely correct. We don't tag specific Elf as Deedlit - rather, we tag Deedlit as character because she is, well, a character in RoLW, and "elf" is one of her taggable properties, like "blonde_hair". So Deedlit and Morrigan should remain in character category, even if something new is introduced.

Also, I think only one category should be added. There are enough places in the code making use of conditions based on tag category, and all of those places must be amended for every new category. Maybe it's not as dramatic as I think it to be, though. Anyway, how should that new category be called to cover locations, mechas and arms alike? "Specifics"? "Named"?

**Comment by r888888888** [comment]
I think it makes more sense to change what Character and Copyright mean. Character really should be Name, Copyright should be...Property? But if that's the only change needed there's not much sense in trying to change everything now.

In practical terms, adding a new type only makes sense if we differentiate it visually.

**Comment by RenimLS** [comment]
I think users would prefer characters separate though. I get the feeling there would be a big argument if all of a sudden things like named guns, locations, and machines were grouped together with people/persons (even if there are gray areas, like say a gundam mecha versus a transformer, the former being a named thing and the latter being a "person").

**Comment by RenimLS** [comment]
Was thinking about this again, and thought maybe another approach would be having subtypes for the current tag types.  They might not need to visually need to be colored differently, but say ordered differently. For example have copyright broken into the 3 subtypes of Franchise (name covering several titles, like Final Fantasy), Title (specific titles, like Final Fantasy 7), and Brand (things like Amazon, and Coca-Cola).  When looking at a post the only difference would be that the ordering of copyright tags would be Franchise tags go first, titles go second, and brands last.

Some ideas of subtypes would be:

Copyright: Franchise, Title, Brand
Character (name change?): Character, Location, Vehicle, Object
Artist: Artist and Circle (maybe?) 

For General that's a bit more complicated and ideas might be:
Image Composition: Cover things that define characteristics of the image, so like watercolor, pov, transparent background, watermark, 3D, game cg, number of characters, solo, etc.
Character Characteristics: Things that describe the characters present, such as hair length, color, outfits.
Location Characteristics: things that describe the location, so tags like ocean, beach, pool, room, train interior, forest.
Object Characteristics: things that define the objects present, such as tank, animal, flower, ship, pen, desk, etc.

My primary interest would be the expansion on the copyright and character tags. For copyright it would be especially on separating brands from titles, as most brands don't represent any characters.  As for characters, it would be nice to incorporate especially the location and vehicles.

**Comment by r888888888** [comment]
I feel that coming up with new tags is an acceptable workaround for confusion with copyright/character tags. Yeah sometimes people get confused, but adding a performance+cognitive burden for every other case isn't worth the cost IMO.

Let's take the recent console tag stuff as an example. An Xbox could be an object or it could be be a personification. I assume you still want tag names to be unique so we'd need two tags: xbox_(console) and xbox_(personification). If that's the case then where is the value of subtypes?

If you think tag names shouldn't be unique, that's a huge change in the paradigm of how tagging works in the system. I think an acceptable workaround is just set up a disambiguation wiki page for xbox pointing to the above two.

**Comment by RenimLS** [comment]
Well my primary goal right now is with the idea that specific/unique non-people should be placed into either their own new category or in the second idea a subcategory of what is currently the character category (going to refer to it as the "identity category" after this point).  I'm afraid I didn't explain my view well enough with the second idea, but with your xbox example the starting point is that xbox to begin with is a specific identity, and so would fall under the "identity category" regardless on if it was or wasn't a personified.  An xbox is a specific game console, and so should be identified as a unique identity and not lost amongst the general tags.

The subcategories come in and simply aid in ordering the tags; ideally in a manner where more important tags appear toward the top.  A subcategory of the identity category would be one to cover people and imo would be set as to appear in order first before the other subcategories. I'd expect that people would find that Cloud Strife and Tifa Lockheart would be more important than their flying ship Highwind, but would view them as all specific identities.

An example of how tags would appear:

Copyrights
Final_Fantasy
Final_Fantasy_VII

Identities
Aerith_Gainsborough (Identity Category. Person Subcategory)
Cloud_Strife (Identity Category. Person Subcategory)
Tifa_Lockheart (Identity Category. Person Subcategory)
Highwind (Identity Category. Vehicle Subcategory)
Midgar (Identity Category. Location Subcategory)
Buster Sword (Identity Category. Object Subcategory).

Artist
Kiyose_Nodoka

Tags
1boy
3girls
Airship
City
Sword
Weapon

The obvious ones are Aerith, Cloud, and Tifa because they're actual characters, so they get placed under the identity category, but since they're people they also specifically get into whatever subcategory we use people as well. Highwind is a very specific airship and so it is an identity that should get placed under the identity category as well (the tag is currently a character tag).  The importance of the vehicle though is likely not as important as characters and so it gets placed below the subcategory that belong to people.  Likewise Midgar is a city, but its refers to a specific city with a specific appearance and so falls under the primary category of identity, but then fits into the subcategory of location which is again below that of the subcategory for people.  All the same applies for Buster Sword as it's a very specific sword.

I mostly wanted get this idea down while it was still on my mind. There are plenty of other more pressing issues to contend with at the moment, so I'm certainly not going to push or expect anything from this idea any time soon. I'll likely revisit this issue several months from now when the other issues will hopefully have died down.
