### ISSUE TITLE
If there are no aliases, alias listing shows errors

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2365]
See http://testbooru.donmai.us/tag_aliases - I guess it's the same for other things like implications.

**Comment by ToksT** [comment]
This isn't because there are no aliases. It's because on testbooru, tag records do not exist for some aliases like `101 -> 10100`, so it can't get the category of those tags since they don't exist. This was a bug that only occurred a long time ago and has since been fixed.

**Comment by Type-kun** [comment]
Well, someone, please fix testbooru then. Can't do it myself...

**Comment by ToksT** [comment]
> Well, someone, please fix testbooru then. Can't do it myself...

You actually could create all the missing tag records yourself, if you really wanted to. Would probably be a pain though.

**Comment by r888888888** [comment]
I've updated testbooru.
