### ISSUE TITLE
IQDB find similar doesn't work for any posts

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2369]
For all the posts I've tried it with, find similar returns "No matches found". This applies to both new and older posts. It applies to both create_by_url and create_by_post.

Just a shot in the dark but was `Danbooru.config.iqdb_hostname_and_port` set to an invalid value with the last update? Only thing I can think of that would totally break it seeing as how there were no code changes. Or `Danbooru.config.iqdb_file`.

**Comment by r888888888** [comment]
I've restarted the iqdb processes.

**Comment by ToksT** [comment]
Seems like it's working again now. Except for a small number of posts, but they all seem to be ugoiras so I think it's a separate issue.
