### ISSUE TITLE
Autocomplete cache shouldn't be permanent

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2370]
The autocomplete cache only gets cleared if it exceeds a certain size. So for someone that doesn't use it all that often they could wind up with some very outdated values in the cache, which is bad since newly created tags wouldn't show up for them for a long time, and #2363 isn't going to work for them.

It should keep track of the date each entry was put in the cache and delete ones over a week old.

**Comment by r888888888** [comment]
Instead of changing the storage format (which has issues with migrating existing data), maybe create a new store that has just the expiration dates.

**Comment by Type-kun** [comment]
Um, I'm pretty sure it already has expiration date, set for a week. Take a look at what Opera inspector shows: http://puu.sh/hhp7K.png

**Comment by Type-kun** [comment]
Also, a week, huh. While fixing it, it might be smart to insert some kind of force-reload mechanism, in case we change something yet again and want everyone to refresh their storage. Some kind of constant which will be written to the javascript source code and to the local storage both, and which would trigger complete pruning on mismatch.

**Comment by ToksT** [comment]
> Um, I'm pretty sure it already has expiration date, set for a week. Take a look at what Opera inspector shows: http://puu.sh/hhp7K.png - it's just never used, currently.

Now that you mention it, I think I remember what happened. I think Albert coded this feature a while ago, but it caused a bug that made all the javascript on the site stop working so he removed it (but the expiry date remained).

I couldn't figure it out back then, but now I think I know the cause of the bug. Other things besides autocomplete use the localstorage (such as the addthis thing). But it seems the library Danbooru uses, jquery.storageapi.js, isn't prepared to handle these things so it causes an error.

So if we add a check so that we only touch the cache entries starting with `ac-` (for autocomplete) it should work.

**Comment by Type-kun** [comment]
Yes, that happens in the commit 2cfc66a60a45abd5e92cb287b398febab29f20ed. Still, I have my doubts about performance of traversing the entire local storage to prune it, since it happens on every page reload.

**Comment by ToksT** [comment]
> It seems to be just a matter of rewriting prune_local_storage in autocomplete.js. Traversing the local storage might be expensive, though - maybe it's better to check expired at fetch time and requery if it's too old.

I implemented it so it only checks expiry at fetch time. Downside is that unused entries can stay around past their expiry, but if the cache ever gets larger than 4000 entries it will just empty the whole thing then so it won't be a problem.

> Also, a week, huh. While fixing it, it might be smart to insert some kind of force-reload mechanism, in case we change something yet again and want everyone to refresh their storage. Some kind of constant which will be written to the javascript source code and to the local storage both, and which would trigger complete pruning on mismatch.

I added an AUTOCOMPLETE_VERSION constant that can be incremented to empty everybody's autocomplete cache.

**Comment by Type-kun** [comment]
I'm pretty sure that didn't work as expected. I currently have `danbooru-autocomplete-version` in the local storage set to 1, and hundreds of `ac-...` entries, including from weeks ago. Maybe that's for the better, since aliases' post_count didn't update, either.

**Comment by Type-kun** [comment]
Manually setting the variable to 0 and refreshing twice did help, though, so it's probably a one-time problem. Manually deleting the variable also clears the cache. Weird. Well, that was just a one-time thing, perhaps?

**Comment by ToksT** [comment]
It happened to me too, I had to manually delete the `danbooru-autocomplete-version` cache for mine to delete old entries. I thought maybe I had just set the cache as part of testing before the update but if you had the same problem that's not likely. Strange.
