### ISSUE TITLE
IQDB doesn't work for some ugoira

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2371]
Not all but some ugoira don't ever get returned by find similar:
https://danbooru.donmai.us/posts/1985627
https://danbooru.donmai.us/posts/1986796
https://danbooru.donmai.us/posts/1983287
https://danbooru.donmai.us/posts/1984262
https://danbooru.donmai.us/posts/1837933
https://danbooru.donmai.us/posts/1851818
https://danbooru.donmai.us/posts/1986928

Unlike normal posts ugoira thumbnails get created a couple seconds after the post is uploaded via delayed job. So maybe the function to update iqdb is getting run before the thumbnail is created for these posts? If this is the case we should delay the iqdb update job until after the thumbnail creation job is over.

**Comment by r888888888** [comment]
I've also run the iqdb updater for these posts.

**Comment by ToksT** [comment]
There's also more currently broken posts. A script to regenerate the iqdb entries for all ugoira should probably be run.

**Comment by r888888888** [comment]
Done.
