### ISSUE TITLE
RecordNotFound exception for /users/upload_limit

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2374]
Since `about:upload_limits` had a broken link to `/user/upload_limit`, out of curiosity, I tried `/users/upload_limit` instead and got `ActiveRecord::RecordNotFound exception raised`.  Not saying it ought to point to anything in particular, but throwing an exception seems like an issue, albeit a minor one.

'/users/upload_limit.json?id=#' is apparently a thing, but all the values I tried returned `{"success": false, "message": "That record was not found"}`

**Comment by ToksT** [comment]
It's trying to find the user with the numerical id `upload_limit`, which doesn't exist of course. So RecordNotFound is appropriate, since there is no record with that id.

about:upload_limits was a 4 years outdated page, I updated it and removed that link in the process.
