### ISSUE TITLE
Automatically link to Github releases page on Danbooru

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2377]
The version release in the footer can link automatically to Github.

**Comment by Type-kun** [comment]
Yeah, but it's probably better to link to https://github.com/r888888888/danbooru/releases , not to the exact tag, to see what changed recently rather than in this particular version.

**Comment by ToksT** [comment]
> Yeah, but it's probably better to link to https://github.com/r888888888/danbooru/releases , not to the exact tag, to see what changed recently rather than in this particular version.

Though that could result in release notes that aren't live yet getting displayed. Like the 2.78.1 release notes being there now even though the site is on 2.78.0.

**Comment by ToksT** [comment]
> Though that could result in release notes that aren't live yet getting displayed. Like the 2.78.1 release notes being there now even though the site is on 2.78.0.

I linked it to https://github.com/r888888888/danbooru/releases anyway since release notes from the future aren't that common and people will probably notice the difference in version number anyway.
