### ISSUE TITLE
Automatically rename aliased wikis/artists for alias requests

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2379]
Currently done for bulk update requests but not alias requests

**Comment by r888888888** [comment]
I'm thinking this should always be done as long as conflicts are notified.

**Comment by ToksT** [comment]
> I'm thinking this should always be done as long as conflicts are notified.

I think with this one added it is always done. The batch importer uses the same code as bulk requests, and the /new page doesn't exist anymore.
