### ISSUE TITLE
Yet another pixiv layout change

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2382]
Pixiv changed their layout again, breaking our code *again*.

Among things broken are:
* Translated tags
* Uploading using mode=medium urls
* Upload bookmarklet

Artist finder still works, surprisingly.

From the looks of it, they got rid of `mode=big`; instead, they have a hidden div with class `_illust_modal` on the `mode_medium`.

**Comment by ToksT** [comment]
All of those work fine on my server, but not the production site, so it might not be a code problem.

Perhaps the cached Pixiv session became invalid when Pixiv updated. If I set the session cache on my server to something invalid it starts acting like it does on the production site. @r888888888 Might want to manually clear the cache, it's only set to automatically expire once per month.

**Comment by ToksT** [comment]
For the future we might want to implement some method of detecting when the cached session has become invalid so it can be deleted. It seems the body element gets the class `not-logged-in` when the user isn't logged in so it should be easy.

**Comment by r888888888** [comment]
I've reset the cached sessions. Seems to work now.

**Comment by Type-kun** [comment]
Hm, turns out I was using a non-official or obsolete bookmarklet, which tried to find the image inside the page. 

So, we don't rely on `mode=big` anywhere? That's good to know, it's just the matter of session reset and not so important then.
