### ISSUE TITLE
Pixiv api change

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2383]
Pixiv removed their old smart phone api that danbooru relies on. Instead it seems they have a different "Public API" that Danbooru will have to switch over to using.

This appears to be an implementation of using it we can use to base our implementation on: https://github.com/upbit/pixivpy

**Comment by r888888888** [comment]
I've disabled the API calls for now in 5457d9ed4e51a3cebab64734461fae209399b1db

**Comment by r888888888** [comment]
Ugh, the public api relies on using access tokens. It would introduce another step in the interaction.

**Comment by r888888888** [comment]
It also requires a client id/secret, although the library seems to just use the iOS ones.

**Comment by ToksT** [comment]
btw, I can't remember anything the api has that the html page doesn't, so worse case scenario we can always switch to the html page. Would be slower and more likely to break when Pixiv updates their layout though.

**Comment by Type-kun** [comment]
Can we get a hotfix disabling uploads from `mode=medium` until this is fixed? We gonna end up with lots of 600px uploads otherwise.

**Comment by r888888888** [comment]
A rough implementation of the public api in 17cc8735ada344e35edbdbfa2d46ee7e1bc8ac38. Needs more error handling and fixed tests.

**Comment by ToksT** [comment]
In `rewrite_new_medium_images`, what it's doing now is deriving most of the full sized image url from the thumbnail url, then extracting the file extension from the full sized url that the api gave us, and putting that extension onto the end of the derived url to go back to the full sized url again.

It would be simpler and more reliable to just return the full sized url that the api gave us (this can be found at `metadata[image_urls][large]`).

**Comment by r888888888** [comment]
For the curious here's a sample api response for the works endpoint:

```
{"status":"success","response":[{"id":49270482,"title":"ツイログ","caption":null,"tags":["神崎蘭子","双葉杏","アイドルマスターシンデレラガールズ","Star!!","アイマス5000users入り"],"tools":["CLIP STUDIO PAINT"],"image_urls":{"large":"http://i3.pixiv.net/img-original/img/2015/03/14/17/53/32/49270482_p0.jpg"},"width":1200,"height":951,"stats":{"scored_count":8247,"score":81697,"views_count":191630,"favorited_count":{"public":7804,"private":745},"commented_count":182},"publicity":0,"age_limit":"all-age","created_time":"2015-03-14 17:53:32","reuploaded_time":"2015-03-14 17:53:32","user":{"id":341433,"account":"nardack","name":"Nardack","is_following":false,"is_follower":false,"is_friend":false,"is_premium":null,"profile_image_urls":{"px_50x50":"http://i1.pixiv.net/img19/profile/nardack/846482_s.jpg"},"stats":null,"profile":null},"is_manga":true,"is_liked":false,"favorite_id":0,"page_count":2,"book_style":"none","type":"illustration","metadata":{"pages":[{"image_urls":{"large":"http://i3.pixiv.net/img-original/img/2015/03/14/17/53/32/49270482_p0.jpg","medium":"http://i3.pixiv.net/c/1200x1200/img-master/img/2015/03/14/17/53/32/49270482_p0_master1200.jpg"}},{"image_urls":{"large":"http://i3.pixiv.net/img-original/img/2015/03/14/17/53/32/49270482_p1.jpg","medium":"http://i3.pixiv.net/c/1200x1200/img-master/img/2015/03/14/17/53/32/49270482_p1_master1200.jpg"}}]},"content_type":null}],"count":1}
```

**Comment by r888888888** [comment]
For now I've deployed the public api version to address the problem with medium images getting uploaded.

**Comment by r888888888** [comment]
So this public api is pretty powerful, returning a lot of useful data from just the illust id. The question is whether we should rewrite everything to rely on a sorta undocumented api. It would clean up the Pixiv code a lot however.

**Comment by ZipFile** [comment]
New android app looks less obfuscated, so it's easier to extract endpoints. I'm going to document api this weekend and share it with community.

Also:
```ini
userAgent="PixivAndroidApp/4.6.0"
clientId="BVO2E8vAAikgUBW8FYpi6amXOjQj"
clientSecret="LI1WsFUDrrquaINOdarrJclCrkTtc3eojCOswlog"
bearer="8mMXXWT9iuwdJvsVIvQsFYDwuZpRCMePeyagSh30ZdU"
```

**Comment by lgreib** [comment]
"8mMXXWT9iuwdJvsVIvQsFYDwuZpRCMePeyagSh30ZdU"

This token seems to be permanent, but doesn't work for R-18 images. Does anyone know of one that does?

**Comment by ZipFile** [comment]
@lgreib, it is a public token to signup through app. It won't work everywhere.

**Comment by mkrss** [comment]
Hi, I want to ask about something, sorry maybe this is out of topic but I don't know where to ask about this.

I was using the old api to make rss for new works of the artists I followed, I just noticed that there's no more rss until recently.

Is there a function like that in the new api? (bookmark_new_illust)

Thanks

**Comment by ZipFile** [comment]
Try [/me/following/works.json](https://gist.github.com/ZipFile/e14ff1a7e6d01456188a#file-pixiv-public-api-L718)

**Comment by ToksT** [comment]
> So this public api is pretty powerful, returning a lot of useful data from just the illust id. The question is whether we should rewrite everything to rely on a sorta undocumented api. It would clean up the Pixiv code a lot however.

The things we can already do with url rewriting I don't think we should change to making a request to the api, since it's slower to make a http request than rewrite a url.

For things we already need to make a request to Pixiv's html page for, it may be faster to request the api instead? Haven't tested.

But the original flag doesn't seem to be included in the api still, so we still need to request the html page anyway to get that. Requesting html page + api would have to be slower than just html page.

As far as reliability goes, Pixiv's html page layout sometimes changes, Pixiv's api sometimes changes, Pixiv's url formats sometimes change, it's all pretty much about equally unreliable.

**Comment by Type-kun** [comment]
If anything, pixiv api seems to return moniker properly. IIRC, currently it's derived from some sort of secondary layout elements, like blog feed or something. 

By the way, is speed really a concern? I don't remember anything using the mechanism except upload page and artist search; both can live with additional half-a-second delay, methinks. As for reliability, somewhat future-proof way would be to query HTML first (since API doesn't contain original flag), and then query API if something is amiss in the returned results. That's a lot of work, though, and I'm not even sure if that's necessary - it's not broken currently.

**Comment by ToksT** [comment]
> If anything, pixiv api seems to return moniker properly. IIRC, currently it's derived from some sort of secondary layout elements, like blog feed or something.

Currently, the artist finder first tries to get moniker from the url, if that's missing then it gets it from the api.

The code for parsing the html page does get the moniker from the "Feed" link. I don't think we actually use that for anything though?

> By the way, is speed really a concern? I don't remember anything using the mechanism except upload page and artist search; both can live with additional half-a-second delay, methinks.

Fetch source data, too. And it's closer to 1.5 seconds in my experience.

1.5s isn't really that slow, but keep in mind it has to be done 3 times every time you upload (artist finder, source fetcher, upload). We might want to avoid making it any slower than it currently is.

**Comment by mkrss** [comment]
@ZipFile Thank you! it's working :) :+1:

**Comment by r888888888** [comment]
Closing this for now since all the tests have been updated.
