### ISSUE TITLE
Fix tag category cache when user tries to change category

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2384]
There's that bug that often happens with new artist tags where the tag's category will be artist, but the cache will be set to general for some reason making it look general. Users that see this often try to tag `artist:tagname` to change it to artist but this does nothing since the category is already artist.

Maybe change it so a user doing the above will just clear the tag's category cache. That would fix the bug for that specific tag and avoid the whole "its stuck as a general tag and can't be changed" illusion.

**Comment by r888888888** [comment]
I guess this could happen when the tag already exists as a general, then is tagged as artist but the change hasn't yet propagated to the other server.
