### ISSUE TITLE
API returns inconsistent data for various posts under certain tags

### ISSUE THREAD

**Issue by rcdailey** [r888888888/danbooru#2387]
Using the danbooru API I am noticing some inconsistent response data. I have reviewed the API documentation but I do not see any information that would explain this.

If I search "one_piece" and "straight_shota" together, I get 6 posts back (correct count) but there is no 'md5' or file URL properties in the json objects for each of these posts. This is unusual as most other posts will have this data.

Here is the URL I'm using in the test:

http://danbooru.donmai.us/posts.json?tags=one_piece+straight_shota&page=1&user=yourusername&limit=100&api_key=yourapikey

(Obviously "yourusername" and "yourapikey" should be replaced as needed per your own test account)

Interestingly, if I open this URL in my browser I see the md5 properties. However, the same URL made via my python script does not yield these properties. I have provided a link to the response data I received back from the API below. Please ignore any character formatting in the text file, this was copied from Python's HTTP API which still has some metadata in it (since the response is binary encoded at this point).

http://pastebin.com/DFXyndCe

**Comment by ToksT** [comment]
See #2096 - md5 and file extensions are hidden for loli/shota/toddlercon posts. Only gold and higher users are allowed to view them.

> http://danbooru.donmai.us/posts.json?tags=one_piece+straight_shota&page=1&user=yourusername&limit=100&api_key=yourapikey

You're not authenticating correctly. It should be &login=yourusername.

**Comment by rcdailey** [comment]
I don't really understand. Why are they hidden at all? What is the motivation for that? Are paid users not gold rank? How does one get gold status?

**Comment by r888888888** [comment]
Gold users are paid.

They're hidden because of complaints from advertisers and Visa.

**Comment by ToksT** [comment]
>How does one get gold status?

You must already be gold or higher because you said "Interestingly, if I open this URL in my browser I see the md5 properties." If you were a basic member it wouldn't show up in your browser either.

**Comment by rcdailey** [comment]
So then the question still remains: If I am gold, why would I see different results in browser vs API? When I make the API call I'm using my username and API key from my "gold" account, so should the results still be filtered?

**Comment by ToksT** [comment]
> So then the question still remains: If I am gold, why would I see different results in browser vs API? When I make the API call I'm using my username and API key from my "gold" account, so should the results still be filtered?

Did you miss my answer earlier? "You're not authenticating correctly. It should be &login=yourusername."

Since you're not authenticating correctly, the site defaults you to being an anonymous user, thus it gets censored.

**Comment by rcdailey** [comment]
I didn't miss the answer, it just seemed like an "oh by the way" suggestion. Your original responses lacked your last paragraph which pieces everything together.

**Comment by ToksT** [comment]
> I didn't miss the answer, it just seemed like an "oh by the way" suggestion. Your original responses lacked your last paragraph which pieces everything together.

I wrote it as the second paragraph because I figured it out second. Maybe I should have reversed the order of the paragraphs.

**Comment by rcdailey** [comment]
I updated my script to use `login=` per your recommendation:

    http://danbooru.donmai.us/posts.json?limit=100&api_key=myapikey&login=myusername&tags=one_piece+straight_shota&page=1

I don't get any different results.

**Comment by ToksT** [comment]
Is the account you're using with your script a basic member? Basic members can't view shota as mentioned earlier.

**Comment by rcdailey** [comment]
I donated a few years back. My profile says "Level: Gold".

**Comment by ToksT** [comment]
> EDIT: I regenerated another API key and its working fine now. Strange. My API key used to work fine before and I haven't regenerated it in a year or two.

API keys were changed a year ago with #2166, so that's probably why.
