### ISSUE TITLE
Filter out implications in humanized essential tag string

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2390]
Consider something like http://danbooru.donmai.us/posts/1979632 for example. `pokemon_rgby` implicates `pokemon_(game)` implicates `pokemon`, so essential tag string reads `natsume (pokemon, pokemon (game), and pokemon rgby) drawn by akira (natsumemo)` - three series instead of one.

Perhaps, it would be possible to filter out implicated tags of the same category from the essential strings, leaving only the smaller subsets in the string? This way, `pokemon (game)` will be removed as an implication of `pokemon rgby`, and `pokemon` as an implication of `pokemon (game)`, leaving only `pokemon rgby` in the essential string. This would require at least one additional query to the implication table, though.

**Comment by r888888888** [comment]
It would be nice to do this without having to load up the implication since essential tag string is loaded on every post. Your method is one way although that would require some way of maintaining a list of all tags with implications. It may also be possible to programmatically figure out implications in a string by searching for common words.

**Comment by Type-kun** [comment]
>Your method is one way although that would require some way of maintaining a list of all tags with implications. 

Eh? We have a database table for post implications already, don't we?

Loading implications for every tag via ruby active record model will be horrendously slow, but there's a way to do that with one query using `IN`: we already have tags split by categories, so all we need is to join chartags and copytags and pass them to `select * from implications where antecedent-name in (?)` which should, supposedly, work quite fast because it'll be using an index for exact match. Then we could traverse the initial data and resulting array, and filter out tags if:

1. the tag is present as consequent_name
2. the antecedent_name tag is of the same category

**Comment by r888888888** [comment]
Yeah the issue is looking up that info for every post, potentially multiple times in a listing page. It's just nice to avoid those queries if it's possible.

**Comment by Type-kun** [comment]
Perhaps, put the implications for chartags and copytags to Cache? There's not much of either, I think. If that's too much work/resources, though, it's fine to drop the issue, since it's just a minor cosmetic change.
