### ISSUE TITLE
Testbooru is misconfigured

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2402]
I tried to upload the post, but http://testbooru.donmai.us/data/646f4168b9c5c7ee32edf10a9fd95099.png gives me a 403.

**Comment by Type-kun** [comment]
Huh, it's working now. Still, something WAS wrong, and the thumbnails are still broken. See http://testbooru.donmai.us/posts

**Comment by r888888888** [comment]
It was the referer getting blocked by nginx. It's fixed now.
