### ISSUE TITLE
Can't unsubscribe from forum topic without creating a new post

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2403]
The only way to unsubscribe from a forum topic is to make a new post in the thread.

**Comment by Type-kun** [comment]
It seems impossible to subscribe without posting, as well. [Un]subscribe link should be in subnavbar next to "Reply" link.

**Comment by Type-kun** [comment]
You accidentally nested the [un]subscribe buttons inside a `editable_by?(CurrentUser.user)` condition, so the link is never shown unless you can edit the topic's OP.
