### ISSUE TITLE
Refactor source strategies to use referer url if it provides better data

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2404]
Specifically this is useful when uploading from Twitter galleries because the pbs.twimg.com urls can't be used with artist finder.

**Comment by ToksT** [comment]
TIL we don't already do this. I somehow thought the posts with the direct image source were just uploaded by people that don't use the bookmarklet.

Sites this would be useful for: twimg, tumblr, nijie, blogs (like fc2, probably lots of different ones)

Wouldn't do much for sites `Post#normalized_source` can already rewrite.

**Comment by r888888888** [comment]
Deployed to testbooru for testing

**Comment by r888888888** [comment]
I'm not sure if this addresses #2395 since I'm not altering the source.

**Comment by ToksT** [comment]
> I'm not sure if this addresses #2395 since I'm not altering the source.

Oh, so is this just for the artist finder? Looking again, it seems you did mention the artist finder specifically and I missed that part...

Also, the commit has an error: Downloads::RewriteStrategies create a source with a call like `::Sources::Strategies::Pixiv.new(url)`, but now a second referer parameter is required so it throws an argument error.

**Comment by ToksT** [comment]
The artist finder no longer works on the upload page since this was put live. It searches for the referer correctly but ignores the regular source field, so when the referer isn't present it doesn't work.

**Comment by ToksT** [comment]
`$("#referer_url,#upload_source,#post_source")` returns both the fields we want, but when calling `.val()` it only gets the value of the first one, not all of them. We'd have to extract the value from each in a loop I think.

But then the artist finder itself only takes one url, not a list of them.
