### ISSUE TITLE
Automated janitor invitation/demotion system

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2408]
Janitor invites should go out on a monthly basis, and the list of active janitors should be pruned. Proposed criteria for invites:

* Account must be at least 6 months old
* User must have logged within the past week
* User level must be between Member and Contributor
* At least 200 favorites
* Median score of favorites (400 count sample) should be between 3 and 10

Acceptance will create a message, which upon response an admin can decide whether or not to create a janitor trial.

Janitors who have not approved a post in 2 months will be automatically messaged and demoted (no user feedback created).

**Comment by ToksT** [comment]
> Janitors who have not approved a post in 2 months will be automatically messaged and demoted (no user feedback created).

Shouldn't a neutral record still be created? It's almost impossible to keep track of who used to be what level and when they stopped being whatever level and what reason they were promoted/demoted for if these neutral records aren't created; that's why they were added.

**Comment by kittey** [comment]
> Median score of favorites (400 count sample) should be between 3 and 10

No idea why you would even want to have an upper limit, but especially the lower limit seems awfully low.

I know I'm overly picky with my favorites, but at the moment the median of my 111 favorites is 13. I'd have to add another 20 images with scores <= 10 to bring the median down to 10 (disregarding the requirement of 200 favs). That seems rather counter-intuitive.

Let's get some statistics by looking at a rather randomly chosen sample size of 100k images:
`id:1400000..1500000 status:any score:..2` -> 1849 pages of results
`id:1400000..1500000 status:any score:3..` -> 3150 pages
`id:1400000..1500000 score:..2` -> 1686 pages
`id:1400000..1500000 score:3..` -> 3096 pages
In other words, a score of at least 3 have 63% of all posts and 65% of all approved posts.

I think it's pretty hard for users to have fav score medians below 3 unless they're idiots and favorite only crap or stuff that nobody else likes for some other reason.

According to `id:1400000..1500000 order:score` the median of those 100k posts is 4, so randomly favoriting 200 posts will get you a janitor invitation.

I suggest raising the lower limit to <i>at least</i> 6. Considering the amount of crap (IMO) that our current janitors approve, I'd raise that much higher.

I'm not sure why you would even want to have an upper limit at all. If that's supposed to be abuse protection (just fav the 200 highest-scoring posts?), that's too easily circumvented to be of any use.

I wonder how many users would actually match the criteria at the moment or even after raising the limits. If 50% of all (active) users get janitor invitations, it seems kinda useless.

If you're calculating the fav score median of almost all users every month anyway, why not order them by that and invite the top 10 users (that haven't declined yet) or something?

> Account must be at least 6 months old

From my experiences on Danbooru, that might not be enough. I suggest at least 1 year. Unless you increase the lower score limit to 15 or something, I don't think you'll have trouble finding enough users that stuck around for more than a year.

Sorry for the long reply. :-/

**Comment by RaisingK** [comment]
I see that inactive Janitors not in the trial system are always demoted back to Gold, and Janitors who pass the trial system are removed from it.  Could we retain records of Janitors' original levels even after they pass, so we can still restore their original level later if they go inactive?

**Comment by ToksT** [comment]
> I wonder how many users would actually match the criteria at the moment or even after raising the limits. If 50% of all (active) users get janitor invitations, it seems kinda useless.

> If you're calculating the fav score median of almost all users every month anyway, why not order them by that and invite the top 10 users (that haven't declined yet) or something?

It doesn't send out invitations to everyone that meets the criteria. It selects 5 random people that meet the criteria each month and sends those an invitation. So it's actually only calculating 5 medians a month, I'm assuming this is because calculating everyone's medians and ordering by that would have poor performance.

> I see that inactive Janitors not in the trial system are always demoted back to Gold, and Janitors who pass the trial system are removed from it. Could we retain records of Janitors' original levels even after they pass, so we can still restore their original level later if they go inactive?

+1

**Comment by ToksT** [comment]
The message automatically sent when a janitor trial starts includes this part:

>Over the next several weeks your approvals will be monitored. If the majority of them are quality uploads, then you will be promoted to full janitor status which grants you the ability to delete and undelete posts, ban users, and revert tag changes from vandals.

This doesn't seem to be true looking at the code. From what I can see test janitors already have every ability of regular janitors, including deleting posts.

On the other hand, neither test janitors nor regular janitors have the ability to ban users as it says there.

**Comment by r888888888** [comment]
There isn't much point in seeking out janitors who prefer super high score posts. The small percentage of those get approved instantly anyway. The complaint is that good but worksafe or original or obscure copyright art gets ignored. The median score just acts as a filter. The final decision will be made by me either way.

The janitor's previous level is stored in the JanitorTrial record. I think it makes sense to never delete these. Instead I'll add a status field.

I select only 5 (at most) because we probably don't need a flood of dozens of new janitors at once. It'd make it harder to judge their performance and introducing them gradually makes more sense.

**Comment by ToksT** [comment]
The record given on demotion is sometimes neutral, sometimes negative. Shouldn't it be one or the other?

**Comment by RaisingK** [comment]
Shouldn't there also be criteria of some sort based on the user's own uploads (within a given period of time)?

**Comment by Type-kun** [comment]
> Shouldn't there also be criteria of some sort based on the user's own uploads (within a given period of time)? They'd be bypassing the mod queue as new janitors, after all...

Not only that: I meet all of your criteria except favcount and median fav score. Nothing really stops me or anybody else from creating a script for favoriting all posts older than two months, having score between 3 and 10. I'd rather have the invitations based on quality of uploads. Perhaps use both uploads and favorites.

**Comment by Type-kun** [comment]
Also, some more points:

1) If there's not many candidates, there's a chance some of them will get invitations every month. Last invitation time should be stored somewhere, probably, and recently (6 months?) invited users should be excluded.

2) Promoting users to test janitors is done too stealthily, even if it does generate a user record and another line in test janitor list. I think that test janitor activity should be monitored by community more closely, so it seems appropriate to create a forum topic mentioning that certain users are test janitors now, so that people can voice their dissatisfaction there. Perhaps one topic for every new group of janitors or every new janitor, like it's done with aliases.

**Comment by ToksT** [comment]
> 1) If there's not many candidates, there's a chance some of them will get invitations every month. Last invitation time should be stored somewhere, probably, and recently (6 months?) invited users should be excluded.

It already checks if there's a dmail invitation via title and ignores already invited users.

**Comment by Type-kun** [comment]
> It already checks if there's a dmail invitation via title and ignores already invited users.

Right, I missed that, sorry. Though now I wonder what is the chance of an invitation being sent at all, given that 5 random users are picked before percentile check and invitation check.

**Comment by kittey** [comment]
> The complaint is that good but worksafe or original or obscure copyright art gets ignored. The median score just acts as a filter.

If your idea is to find people with more diverse interests, maybe you should try to create a criterion for that. I feel that the fav score median isn’t very meaningful in that regard.

Two alternate suggestions:
Idea 1: Find users that don’t favorite just popular copyrights.
- Determine the top <i>n</i> “common” copyright tags (excluding `original`).
- Get 400 samples from a user’s favorites.
- Determine percentage of posts in the sample set that have one of the “common” copyright tags.
- Put an upper limit on that percentage.

Idea 2: Find users that favorited lots of different copyrights.
- Get 400 samples from a user’s favorites.
- Discard all posts that have more than <i>m</i> copyright tags (mass crossovers).
- Count unique copyright tags seen in the remaining posts.
- Scale count if the user has less than 400 favorites.
- Place a lower limit on that count.

If you want to make “worksafe” a criterion (which I would welcome), you should just calculate the percentage of safe posts in a user’s favorites and put a lower limit on that.
