### ISSUE TITLE
Uploads stuck processing

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2409]
http://danbooru.donmai.us/uploads/703528
http://danbooru.donmai.us/uploads/703530
http://danbooru.donmai.us/uploads/703531
http://danbooru.donmai.us/uploads/703533

They've been stuck processing for a up to 30 minutes. Seems they're all ugoira.

**Comment by r888888888** [comment]
Processing these manually seems to work. I wonder if it's a factor of the size.

**Comment by ToksT** [comment]
Happened again today to about 100 uploads. I can't notice a pattern between them, except that they all took place over the course of about an hour and then uploads after that don't have the problem. Though not 100% of the uploads that took place over that hour are stuck processing.
