### ISSUE TITLE
Remove janitor user level

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2417]
The right to approve posts should not be tied to user level. Some things must be done:

* Create a new user flag for can_approve_posts
* Move existing janitor role checks to either builder or moderator
* Migrate existing janitors
* Rework janitor trials to support the user flag

**Comment by Type-kun** [comment]
Will there be any indication on user page that the user can approve posts? What about username coloring, perhaps add some icon to approvers?

**Comment by r888888888** [comment]
I think adding a unique color/icon is kinda overkill, considering anyone could just view their profile page to see the exact permissions they have.

**Comment by ToksT** [comment]
I think it would be convenient so you can tell who's an approver immediately, rather than having to go to the profile page of each individual person you see in order to tell if they're an approver.

If we're not going add an official style I added a css class to approver usernames so custom css can be used for this. I'll probably use something like this for my css:

```css
.user-post-approver::after { content: " ✔"; font-size: 85%; color: green; }
```

**Comment by Type-kun** [comment]
Uh, are you sure approving/rejecting aliases/burs/implications should be builder+, not mod+? It seems pretty critical to me.

**Comment by ToksT** [comment]
> Uh, are you sure approving/rejecting aliases/burs/implications should be builder+, not mod+? It seems pretty critical to me.

Approving is admin only, not builder+ nor mod+.

Rejecting used to be janitor+ but is now builder+.

**Comment by ToksT** [comment]
Editing is also builder+ now.

And I don't think it's much of an issue, I'm often the one that points out that someone messed up the format of a request so this would let me or other builder+ users to fix this type of mistake from new users.
