### ISSUE TITLE
Favgroup listing pagecount is buggy

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2420]
http://danbooru.donmai.us/favorite_groups doesn't show anything, despite there are existing favgroups with IDs 1,5,6,9 and 10. Additionally, despite there being only 5 favgroups at all, listing shows page count for pages 1 to 7 and sometimes to 10 (http://danbooru.donmai.us/favorite_groups?page=6 for example). Something seems wrong about that - if favgroups are supposed to be private, I shouldn't be able to see them using links like http://danbooru.donmai.us/favorite_groups/9 or http://danbooru.donmai.us/favorite_groups?search%5Bcreator_id%5D=415157 (with search by id).

**Comment by Type-kun** [comment]
Wait, I see, http://danbooru.donmai.us/favorite_groups shows your own favgroups. Page count is still off, though.

**Comment by ToksT** [comment]
> if favgroups are supposed to be private

Favgroups are not private. They can be viewed by anyone.

Maybe it would be good to add an optional "Private" checkbox though, like with subscriptions.

**Comment by ToksT** [comment]
> Page count is still off, though.

I'll just get rid of the paginator. No one can have more than 10 favorite groups anyway, so one page is enough.
