### ISSUE TITLE
Notice about bookmarklet on upload page

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2425]
The upload page when not using the bookmarklet should have some kind of obvious advertising for the bookmarklet like "**You should be using the [official upload bookmarklet](http://danbooru.donmai.us/static/bookmarklet)!**"

I believe the only way currently for someone to learn of the bookmarklet is to go to site map > bookmarklet, which isn't very obvious. There are uploaders both experienced and new that are uploading posts with incorrect sources that the bookmarklet fixes automatically as of #2395, perhaps these uploaders are not aware it exists.

**Comment by Type-kun** [comment]
By the way, there's currently no way to track bookmarklet changes except searching through issues/ release notes. Version number should be passed as an url param, perhaps, so that the notice could urge users to upgrade?

**Comment by ToksT** [comment]
> By the way, there's currently no way to track bookmarklet changes except searching through issues/ release notes. Version number should be passed as an url param, perhaps, so that the notice could urge users to upgrade?

The bookmarklet itself hasn't changed a single time since it was added in the Danbooru 2 upgrade. Changes to how the bookmarklet work are done internally through Danbooru's code to avoid the need for users to upgrade; all the bookmarklet does is bring users to the upload page and give Danbooru access to the user's referer.

If we ever do need to change the bookmarklet itself for some reason then that would be a good idea.

This is the bookmarklet's code fyi:

```js
javascript:location.href='http://danbooru.donmai.us/uploads/new?url='+encodeURIComponent(location.href)+'&ref='+encodeURIComponent(document.referrer)
```

**Comment by Type-kun** [comment]
Huh. I was sure referrer was added to the bookmarklet recently, never realized it was there all along.

**Comment by ToksT** [comment]
> Huh. I was sure referrer was added to the bookmarklet recently, never realized it was there all along.

Yeah, the bookmarklet always passed the referer to the upload page, but it never got used for anything significant until a few weeks ago.

This confused me too. Until recently I thought #2395 or something similar to it was a feature that already existed for a long time but it turns out it wasn't.
