### ISSUE TITLE
Circumvent source hotlinking protection when using bookmarklet

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2426]
When uploading from pixiv using the bookmarklet, the image on upload page goes missing sometimes - for example, when using  bookmarklet on `http://www.pixiv.net/member_illust.php?mode=medium&illust_id=N` page directly - because pixiv uses hotlinking protection, thus not allowing to embed images. Hotlink protection is actually pretty common on other websites, too.

However, it should be possible to build a danbooru page that accepts direct image URL and referrer URL as arguments and acts as a transparent proxy - returning whatever it gets from the URL - except faking referrer header when making the request. This page should be specified as `src` in `img` element, thus effectively hijacking the hotlink protection.

We pretty much always know a valid referrer - if URL is a direct link, then it's passed as one of bookmarklet parameters; if URL is work page, it should be used as a referrer.

Does that seem possible to implement?

**Comment by ToksT** [comment]
That's clever. I didn't realize it was possible to use Danbooru as a proxy.

**Comment by Type-kun** [comment]
That was fast, thanks :3
Can we make it a bit more intelligent, though? If I use bookmarklet on work page, i.e. http://www.pixiv.net/member_illust.php?mode=medium&illust_id=51211993, then normalized url is http://i2.pixiv.net/img-original/img/2015/07/03/03/23/18/51211993_p0.png and referrer is either null or set to irrelevant page like previous work or artist profile. There probably should be a normalized referer in cases when we transform the url.

**Comment by ToksT** [comment]
> If I use bookmarklet on work page, i.e. http://www.pixiv.net/member_illust.php?mode=medium&illust_id=51211993, then normalized url is http://i2.pixiv.net/img-original/img/2015/07/03/03/23/18/51211993_p0.png and referrer is either null or set to irrelevant page like previous work or artist profile.

If the referer is the previous work or artist profile then that's fine. The referer just has to be on the pixiv domain to work.

Though now that you mention it it's possible someone found a work on some other site (like Danbooru) in which case the referer wouldn't be on pixiv and wouldn't work so I'll have to fix that.

Also as a performance improvement maybe this proxy should only be used for known sites that prevent hotlinking. When I tested it the proxy only slowed things down by about 200ms, but it still might be good to reduce bandwidth usage on Danbooru and only use the proxy when necessary. Right now the only site I can think of that prevents hotlinking is pixiv, do you know any other ones I should add?

**Comment by Type-kun** [comment]
Yeah,limiting the sites for proxying is a good idea. It also limits the possibilities of its usage by a third party - it was possible, though unlikely.

>Right now the only site I can think of that prevents hotlinking is pixiv, do you know any other ones I should add?

Not really, but I don't upload that much, it's probably better to ask contributors in the forums. I guess the issue can be closed now.
