### ISSUE TITLE
Prevent removing all tags from post

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2427]
If a user tries to remove every tag from a post then it's almost definitely vandalism so the change should result in an error.

Vandalism would still be possible by removing only some tags at a time. But it seems the most common form of vandalism is removing every tag from a post, so this change should help at least a little.

**Comment by kittey** [comment]
Maybe use a threshold for the amount of tags, maybe 90 % removed or removed everything except for one or two tags.

I remember seeing vandalism where someone removed all tags except for one or replaced everything with one nonsensical tag.

Would it be possible to show the user an empty tag list after submitting the change, even though no tags were actually removed? Just pretending that the vandalism actually worked as the user intended.

**Comment by r888888888** [comment]
Yeah I'm worried about vandals just switching to deleting everything except one tag.

Are there any patterns to the vandal accounts? Maybe only allow tag addition if your account is young, or require a captcha for major changes.

**Comment by ToksT** [comment]
> Are there any patterns to the vandal accounts? Maybe only allow tag addition if your account is young, or require a captcha for major changes.

Often they seem to vandalize a specific artist by removing all tags, removing just the artist tag, removing the source, or some combination of those. Possibly the artist themself doing it.

In other cases vandals add nonsense tags to posts (in other words, tags with 0 post count).

Not allowing new users <1 week old to remove tags sounds good. And maybe don't let them add new tags with 0 post count either.

Possibly still allow them to remove tagme/copyright_request/etc - looking through tag changes by new users, the only legitimate removals I see are those request-type tags because the user is fulfilling the request.

**Comment by ToksT** [comment]
They can still remove one tag at a time. So if the vandalism involves only removing one tag it doesn't stop them. And removing multiple tags can be done by multiple edits.
