### ISSUE TITLE
Automatic testbooru deployment

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2429]
It'd be nice to have a chance to test new commits without gearing up own server instance and pulling fresh version from git. Perhaps, changes should simply be deployed to testbooru once a day automatically? It'll help iron out bugs on major changes, because any willing user will be able to help.

**Comment by r888888888** [comment]
I would suggest a better way is to just get an SSH account on testbooru. I can create new user acccounts which would allow you to deploy whenever, even specific branches if desired.

**Comment by Type-kun** [comment]
Perhaps you're right. Though I wonder if there will be deployment conflicts when more people will have access.
