### ISSUE TITLE
Translation Bump functionality

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2430]
While browsing through older forum posts I encountered this one: http://danbooru.donmai.us/forum_topics/9493

Sure, I was opposed to it two years ago, but on the second thought that might actually be a nice idea. It basically suggests to allow users to give post marked with `translation_request` a special kind of upvote, indicating that users are interested in seeing it translated; then, translators will be presented with a list of "most requested" posts to know where their work won't go unnoticed and unappreciated. Amount of bumps allowed per time period should be limited and differ depending on user level, obviously, becoming another upgrade incentive.

I understand that more indexes will (probably) slow the post table down, but in this particular case the info never exists on post upload, so it's possible to work around it by using two separate tables: one for keeping track of separate "bumps" per post per user, and one for keeping track of bump count per post id, only for posts that have `translation_request`. 

Another way would be to employ a partial index (see http://www.postgresql.org/docs/9.4/static/indexes-partial.html ). We'd only be interested in posts with `bump_score >0`, so it seems like a perfect use-case and shouldn't slow down inserts because most posts won't get indexed at all.

Seems like a bit of hassle to implement, but perhaps worth considering.

**Comment by ToksT** [comment]
It should have metatags too, similar to `score:x..` and `order:score`. The benefit of metatags is that translators could filter out comics, filter down to only copyrights they like, or whatever.

**Comment by ToksT** [comment]
How would this work for comics? Each user can't just bump every page in the comic individually because of bump limits, and it'd be a pain anyway. So basically each person would only bump one or two pages from a comic even though they actually want the whole comic translated.

If bumps from different users are split across different pages of the same comic then it would look like less people want the translation. 30 posts with +1 bump each from 30 different users would be much lower on the list than 1 post with +20 bumps even though more people want the 30-page comic to be translated.

**Comment by r888888888** [comment]
As an alternative to this what about a bounty system? I've thought of this in the past but couldn't think of a currency that would entice translators.

**Comment by Type-kun** [comment]
>It should have metatags too, similar to  score:x..  and  order:score . The benefit of metatags is that translators could filter out comics, filter down to only copyrights they like, or whatever.

Seems relatively easy if implemented with partial index. Though it's mandatory to append `>0` clause in those cases and mobitor that `x` in `score:x..` is above zero.

>How would this work for comics? Each user can't just bump every page in the comic individually because of bump limits, and it'd be a pain anyway. So basically each person would only bump one or two pages from a comic even though they actually want the whole comic translated.

Well, yes, that's a bit harder. Perhaps, have a similar but accumulated bump score metric for series pools, based on total bump score for its posts having `translation_request` tags. Though, this way it would drop as comic gets partially translated. 

Another way is to count bump score of all posts having either `translation_request` or `translated` tags, but that has two side-effects: first, it requires additional flag to keep track if there is any untranslated post in the pool; second, long ongoing pools would get bumped to the top as soon as a new post appears, even if that new post has no bumps yet. Imagine, for example, the pool of size like "Hang in there, Kogasa-san", where posts have as little as 1 bump per post. When a new post gets uploaded, the pool would be on the top of the list with 1000+ score. 

If going with second way, though, it's probably possible to conjure a formula, like applying a 0.1 coefficient for `translated` posts score, or varying coefficients depending on posts age, or something. 

> As an alternative to this what about a bounty system? I've thought of this in the past but couldn't think of a currency that would entice translators.

Thought of that as well, but I don't know what danbooru might offer to translators, either. Other than  another e-points metric in the profile, I can only think of temporary "limit breaks" to relax timeouts, tag limits etc for a period of time when translator requests it.
