### ISSUE TITLE
"Session not found" when uploading from seiga

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2431]
Example: http://danbooru.donmai.us/uploads/new?url=http%3A%2F%2Fseiga.nicovideo.jp%2Fseiga%2Fim5026559

This error seems to be raised when Danbooru can't find the user_session cookie after logging in. Maybe that means Danbooru isn't logging in successfully?

It seems to log in successfully on my server, so there's a possibility it has something to do with Danbooru's seiga account?

**Comment by r888888888** [comment]
I suspect this will be fixed in 71347ae5f0101678174de20d4eb51995fdfe17c2

**Comment by ToksT** [comment]
It's not fixed.

I don't think a bug related to the cache could cause this:

```ruby
session = mech.cookie_jar.cookies.select{|c| c.name == "user_session"}.first
if session
  Cache.put("nico-seiga-session", session.value, 1.month)
else
  raise "Session not found"
end
```

It throws the error when the cookie doesn't exist in the cookie jar, not when it doesn't exist in the cache.

**Comment by r888888888** [comment]
I believe the login was incorrect. This should be fixed now.
