### ISSUE TITLE
Eliminate Post.fast_count calls for RSS feeds

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2432]
Several of the database timeouts are originating from the posts Atom feed which really shouldn't have to worry about the post count.

**Comment by ToksT** [comment]
Why was fe7f3d8204011b4ed8e2c913b2f6d4e14a9a87cc reverted? Did it break something?

**Comment by r888888888** [comment]
I don't think I reverted the entire commit. I believe is_deleted is a protected attribute so using update_attributes didn't actually update it. It was causing a test to fail. Is there a regression?

**Comment by ToksT** [comment]
> I don't think I reverted the entire commit. I believe is_deleted is a protected attribute so using update_attributes didn't actually update it. It was causing a test to fail. Is there a regression?

My bad, forgot that the role needs to be passed when using update_attributes so it totally broke deleting both forum posts and topics. Fixed in 0691477a3bd4bf1b0ec4d699554b472e60a0f8c2
