### ISSUE TITLE
Hide/filter deleted comments

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2435]
* Allow filtering of deleted comments (a `search[is_deleted]` parameter)
* Hide deleted comments by default (the comment listing currently just shows the post thumbnail with a blank space instead of a comment for deleted comments)
* Don't include deleted comments in user profile comment counts.

It's a bit vexing having posts show up for `comm:RaisingK` that only have deleted comments (which I can't see except through the API), too...

**Comment by ToksT** [comment]
> Don't include deleted comments in user profile comment counts.

This could have performance problems.

And deleted forum posts are counted on the user profile too.

**Comment by ToksT** [comment]
> Allow filtering of deleted comments (a search[is_deleted] parameter)
> Hide deleted comments by default (the comment listing currently just shows the post thumbnail with a blank space instead of a comment for deleted comments)

See 52c73efc284fafc117ebb8b47a68ea59dcc77a77 9f47a9da1b1af33182b43518e1004c92aac668ed
