### ISSUE TITLE
Partial database dump

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2437]
I'd like to have a partial database dump for easier analysis of statistics methods discussed in http://danbooru.donmai.us/forum_topics/11837?page=4 

Existing dump is obsolete, way too large in size and contains lots of extra info which is not needed for that case; building my own copy via api is slow and will bombard the site with requests, which seems suboptimal if I can ask directly.

Any format should suffice. Easiest are probably CSV and INSERT script. No table structure dump is necessary, only the data. Also, archived if possible, plaintext should compress well.

For now, the following data from `posts` table is enough:

* id
* created-at
* rating
* tag-string
* score
* fav-count
* uploader-id
* approver-id
* is-deleted

I believe this will be enough for research / number crunching even if some alternative methods are suggested. Thanks.

**Comment by r888888888** [comment]
https://www.dropbox.com/s/j6wqdoqc6krrs9e/dump.csv.bz2?dl=0

**Comment by r888888888** [comment]
This also includes up_score, down_score, and is_flagged.
