### ISSUE TITLE
Sequential paginator for order: queries

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2441]
The sequential paginator doesn't work for ordered queries, similar to the problem with the sequential post nav in #728.

Now that basic members are forced to use the sequential paginator, this means they can only view the first page of an order query and then subsequent pages will show incorrect results.

**Comment by Type-kun** [comment]
Is sequential pagination even necessary with #2439 fixed? Usability is pretty severely impaired for normal users, it doesn't even come close to regular pagination.

**Comment by ToksT** [comment]
> Is sequential pagination even necessary with #2439 fixed?

#2439 never actually affected anything. The documentation says expiration times up to 30 days work fine, and 30 days is the largest expiration time that Danbooru uses anywhere. I just tested it to confirm and it's true, 1.month works correctly while 1month+1.second expires immediately.

**Comment by r888888888** [comment]
It definitely affected the post count caching, which for popular tags could exceed a year. This was causing counts for large tags like touhou to be constantly calculated.

Basic members rarely use any of the metatags but since they're limited to two tags anyway I'll tweak the logic on slow_query.

**Comment by ToksT** [comment]
> It definitely affected the post count caching, which for popular tags could exceed a year. This was causing counts for large tags like touhou to be constantly calculated.

Didn't realize post count cache expiry was dynamic.

So looking at the formula searches with a post count more than 10800 would have been affected.

**Comment by Type-kun** [comment]
Just a note that the counts in user profile (like `X  comments in Y posts`) currently shows 1000000 for Y for regular members, apparently because it uses metatags and insta-fails before even attempting to count. e25bc38 apparently should fix that, until limits are reintroduced. 

Also, perhaps there are other ways to improve count performance than by setting low timeout?

**Comment by ToksT** [comment]
The sequential paginator is still being used for searches where fast_count times out.
