### ISSUE TITLE
Feature request: JSONP support on the API.

### ISSUE THREAD

**Issue by chris-l** [r888888888/danbooru#2444]
It would be great to have JSONP support, for cross-domain, frontend-only apps!

**Comment by r888888888** [comment]
Ironic, I started implementing this in reportbooru. Can you give any specific use cases? I assume you mainly mean posts.

**Comment by r888888888** [comment]
Actually it looks like just enabling CORS on the posts endpoint should be good enough, unless you needed other resources as well.

**Comment by chris-l** [comment]
I'm planning to do create a Web component that will be something like a viewer of posts that people can embed on their websites, so yeah, I will pretty much only doing `GET` requests to /posts and CORS should be good enough.
