### ISSUE TITLE
Display disapproval counts in status bar to uploader and approvers

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2447]
It's good to see that additional reasons were introduced to mod queue, but I think that counts should be shown at post page, too. Not all approvers work in queue, some use searches and approve/disapprove post from status bar. They should see disapproval counts as well. Also, when it was suggested, it was meant as communication tool both between approvers and between approver and uploader. So, it'd be nice if uploader saw the counts as well, preferably in both "pending" and "deleted" status bars. Perhaps approvers should also see the counters on deleted status bar, for example to help reconsider appealed posts.

UI-wise, there are already buttons with disapproval reasons; just put numbers near them, like `breaks rules (2) | poor quality (5)`. For uploaders and in deleted status bar, show it the same way, but disable the buttons.

**Comment by Type-kun** [comment]
Wait, I think that these comments should also be visible in "deleted" bar.

**Comment by r888888888** [comment]
Wow, didn't notice disapprovals weren't being pruned.

**Comment by Type-kun** [comment]
Not yet :3

`status:flagged` also should show these, because post is technically pending at the moment.

Also, are these messages supposed to be multiline? Additional `<p>`s would be necessary then.

**Comment by ToksT** [comment]
> Also, are these messages supposed to be multiline? Additional `<p>`s would be necessary then.

I don't think that's going to accomplish anything but take up more vertical space. And if we add more than 3 reasons later it will be even more noticeable.
