### ISSUE TITLE
Include search[is_deleted]=false by default in comment searches

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2449]
Include `search[is_deleted]=false` by default in all comment searches once #2450 is resolved.

Mods can have an extra dropdown menu in the HTML search options for true/false/neither.

**Comment by ToksT** [comment]
I'm not sure if this is a good idea. Searches with search[is_deleted]=false are more than 3 times slower than normal when I tested it on the live site just now. I think a rare blank in results is preferable to slowness.
