### ISSUE TITLE
Heuristic for determining high compression images

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2457]
I've been wondering if there's a way to guess whether or not an image has high JPEG compression. You can sometimes guess by file size + image dimensions but that's not a foolproof method since it's dependent on how compressible the image is. It would be nice to warn the uploader, or at least tag it with compression_artifacts or similar.

**Comment by ToksT** [comment]
Simplest method would be to use imagemagick to look at what jpeg quality the image was saved at. If it's below X% artifacts are likely to be noticeable. Would depend on the image though, not sure how reliable this method would be. Also doesn't account for jpeg-compressed images that were resaved as pngs or something.

**Comment by r888888888** [comment]
wontfix
