### ISSUE TITLE
Use "text":[link] for links in commentary loaded by bookmarklet

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2458]
In the pixiv commentary loaded by the bookmarklet, `<a href="http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16265924">illust/16265924</a>` becomes just `http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16265924`.

`<a href="URL">TEXT</a>` should be translated as `"TEXT":[URL]` instead, like `"illust/16265924":[http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16265924]`.

As it is now, you can end up with malformed URLs if the right spacing/etc... doesn't follow.

**Comment by Type-kun** [comment]
Hm, I tried to look into it, but the commentary text pulled from pixiv api is not `<a href="http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16265924">illust/16265924</a>`, but rather `http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16265924` - my guess is that `illust/16265924` is added by pixiv post-processor. I'm not even sure if pixiv allows html in commentary.

Now, we probably can automatically transform those URLs into `pixiv #N` DText. Though I'm curious, is there any commentary current source that actually allows HTML? I can try to implement some (very basic) html -> dtext conversion if we do.

Oh, also, for whatever reason our current sanitizer fucks up `&`s in URLs, even through it's specifically told not to with `encode_special_chars: false` option set. I'll look into that, too.
