### ISSUE TITLE
Support @username syntax

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2466]
It should also trigger a message when a user is mentioned.

**Comment by Type-kun** [comment]
How would it handle spaces? It's entirely possible to have both `Username` and `Username 2` as users; will mentioning `@Username 2` link to first or second?

Possible solutions are either to use underscores (not ideal either, `Username 2` and `Username_2` are possible); or using quotes/square brackets when space is involved. `@Username 2` would link `Username`, and `@[Username 2]` would link `Username 2`.

**Comment by ToksT** [comment]
Spaces in usernames are treated as underscores internally. I don't think users will be confused by this as you already need to use underscores in tags, like `user:Username_2`.

> not ideal either, `Username 2` and `Username_2` are possible

`Username 2` is impossible. If a user tries to create an account with whitespace in the name they will be given an error.

**Comment by Type-kun** [comment]
Well, that's easier, then.

>It should also trigger a message when a user is mentioned. 

On creation only, or on edit as well?

**Comment by ToksT** [comment]
> On creation only, or on edit as well?

Ideally I guess it would only trigger the message on edit if the @username was edited in, not if it was already there. Not sure if that's possible though.

**Comment by r888888888** [comment]
I think it'd be fairly easy to check if the message already exists for that context. Still it should probably be rate limited so people can't spam it.

**Comment by Type-kun** [comment]
> Still it should probably be rate limited so people can't spam it.

Dunno if it's worth bothering, any abuse can be prevented with user bans and dmail filtering.

**Comment by r888888888** [comment]
Relevant commits in c9bd6fac5acdecb685f1053caf46a3244667f731 and cad671c533c519ce91e978dece8ebac5b8bf2bae

Currently only enabled on forum posts. Still need to implement dmail notifications.

**Comment by r888888888** [comment]
Deployed on testbooru

**Comment by Type-kun** [comment]
Hyphens in names are missed. Also, I'm fairly sure names like 葉月 won't be caught by `\w+` regexp.
http://testbooru.donmai.us/forum_topics/1

**Comment by Type-kun** [comment]
By the way, how about making a "mention" button somewhere in the users' posts, in addition to "quote"? Autocomplete is neat, but sometimes it will be easier to mention someone above(say, 葉月, again) by clicking one button. Then again, it's always possible to copy/paste the name, so perhaps it isn't worth the work.

**Comment by ToksT** [comment]
`IdolM@ster` currently links the user ster. `@IdolM@ster` links both IdolM and ster. The former should link nothing and the latter should link IdolM@ster.

A way to fix 葉月 and Type-kun is to use `/@[^\s:]+/` instead of `/@\w+/`, which allow the same characters a username can have (everything but whitespace and colons). But then there's a new problem: should the sentence `What do you think, @albert?` alert the user `albert` or `albert?` with the question mark? Both are valid names.

The autocomplete doesn't look so good since the text area for writing forum posts is tall and autocomplete appears under the text area. I don't know if there's any good solution for this: making autocomplete appear higher up could obscure the text you're writing; making the text area shorter would give the user less room to see what they're composing.

**Comment by Type-kun** [comment]
>But then there's a new problem: should the sentence  `What do you think, @albert?`  alert the user  `albert`  or  `albert?`  with the question mark? Both are valid names.

Perhaps mention syntax should be a bit more complicated, `like @[username]`? Or perhaps, since the colon is the only thing that can distinguish username from other text, allow both `@username` and `@:username:`, similar to current dtext link parsing?

Also, perhaps there should be a warning or even an error when referencing a nonexistant user.

**Comment by r888888888** [comment]
Maybe the text area should be made a bit shorter? Checking random sites like Twitter/Jira and they all append the autocomplete to the end of the textarea. I haven't seen any examples of floating the autocomplete near the cursor and I'm not even sure how the position for that could be calculated.

I'm not sure how common it is for usernames to end in punctuation like that. Maybe similar to how link parsing works common delimiters like comma, question mark, colon, semi-colon could be ignored.

**Comment by r888888888** [comment]
Actually nevermind GIthub does it.

**Comment by ToksT** [comment]
> Actually nevermind GIthub does it.

Oh right...

If the popup is small like github's then I think that would be good and not cover up too much.

**Comment by Type-kun** [comment]
It doesn't send dmails upon mentions, does it?

**Comment by r888888888** [comment]
Not yet.

**Comment by Type-kun** [comment]
From the recent commit:

`"You were mentioned in the forum topic \"#{rec.topic.title}\":#{Danbooru.config.hostname}/forum_topics/#{rec.topic_id}?page=#{rec.forum_topic_page}`

How about getting rid of `#{Danbooru.config.hostname}` there? This way, link will be relative to whatever mirror user is currently using.

**Comment by r888888888** [comment]
That means however the link won't work in the email that goes out.

**Comment by Type-kun** [comment]
Hmm, `#{Danbooru.config.hostname}` actually doesn't respect the current mirror at all. See source for http://sonohara.donmai.us/posts.atom for example, it uses `danbooru.donmai.us` everywhere. Relative link wouldn't work in emails, but absolute links in dmails will always lead the user to danbooru, where he could be logged off, for example. I thought about using `<base>`, but it seems that many email clients do not support it. Stackoverflow suggests additional preprocessing for emails; perhaps this is viable, I don't immediately see where replacing `<a href="/...">` with `<a href="http://danbooru.donmai.us/...">` could go wrong.

**Comment by r888888888** [comment]
I'm not sure why anyone would choose a specific mirror at this point. They're both in the same DC, are configured the same, and have approximately similar loads.

**Comment by ToksT** [comment]
The face `@_@` shouldn't create a link

**Comment by ToksT** [comment]
The link doesn't parse right when it's not at the beginning of a line. Like `hello @name` links to the user `@name` instead of `name`.

**Comment by ToksT** [comment]
f8cea306022bb0cd3446544df1783174f65fe620 made it so html is visible in the dmails

**Comment by RaisingK** [comment]
Don't trigger a message if the @ link is inside a [quote] block.

The notifications don't generate the 'you've got mail' notice.

**Comment by ToksT** [comment]
> Also, the notifications don't generate the 'you've got mail' notice.

They do when someone else links your name, but not when you link your own name.
