### ISSUE TITLE
Neutral records to keep track of permissions

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2470]
When a user's level changes a neutral record is created to track this. The same should happen with permissions.

**Comment by ToksT** [comment]
Currently the record is created when "Promote" is clicked on the /janitor_trials page, when the trial is set to inactive. But that's not that useful to keep track of since it doesn't really change anything, it would be better to keep track of when the trial is created since that's when the user gains the ability to approve posts.

**Comment by ToksT** [comment]
These should also work when using the "edit user" page. For example if you give a basic member unrestricted uploads right now it will read: "Updated from Member to Member". Should say "Gave unrestricted upload permission".

**Comment by ToksT** [comment]
I don't understand what the last commit did but the feedback seem to be the same as before, only mentioning changes to level and not to permissions.

**Comment by r888888888** [comment]
That should finally fix it. I don't believe the user/edit path for updating levels/permissions was ever used so I took it out. Editing level/permission should only go through admin/user/edit.

**Comment by ToksT** [comment]
Oh I didn't know user/edit could be used for that that. The records seem to work now for admin/user/edit.
