### ISSUE TITLE
Bookmarklet: always show width/height

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2471]
I noticed an odd behavior while uploading pixiv manga pages through the bookmarklet.  The first time I load the image in the bookmarklet, I only get the "Size" and "Referrer" lines below the preview image, and the image isn't downscaled.  Yet if I hit back to view the image, then load the bookmarklet again, I also get the "Scaled" line.

So there's that inconsistency, but I mainly just want the width/height shown below the image even if it isn't scaled; it's useful for comparing to the dimensions of the 'similar' images.  Move the original width/height to next to the Size?

**Comment by r888888888** [comment]
This is probably a dup of #1375

**Comment by RaisingK** [comment]
The first part, at least.  But I'd like to still see the width/height for images that aren't scaled (i.e. height <= 400).
