### ISSUE TITLE
Limit width of 'Other Names' column on artist versions

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2475]
If an artist listed on an Artist Versions page has a large number of `Other Names`, the `Other Names` columns hogs the horizontal space, squashing the more-deserving `URLs` column.  Add a `max-width` to `Other Names`.

**Comment by r888888888** [comment]
I'm not sure what a good limit will be since everyone has different monitor sizes. I don't think a table is really the best presentation for this kind of data. URLs gets crowded too.
