### ISSUE TITLE
Blacklist indication/display across the site

### ISSUE THREAD

**Issue by Moebius-Strip** [r888888888/danbooru#2486]
Going by [Wypatroszony](http://danbooru.donmai.us/forum_posts/107072), there are some areas on the site where the blacklist being applied without providing a blacklist section to list its activity can cause some problems/confusion. ~~Another problem is the new ability to permanently disable the blacklist could result in blacklisted posts being displayed without providing some kind of hint that this is actually happening~~.

From what I can see, the "blacklist-box" is provided for these areas:
```
Search "inline_blacklist" (5 hits in 5 files)
danbooru-master\danbooru-master\app\views\explore\posts\popular.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\favorite_groups\show.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\pools\show.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\post_appeals\index.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\post_flags\index.html.erb (1 hit)

Search "/partials/index/blacklist" (4 hits in 4 files)
danbooru-master\danbooru-master\app\views\favorites\index.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\posts\index.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\posts\show.html.erb (1 hit)
danbooru-master\danbooru-master\app\views\tag_subscriptions\posts.html.erb (1 hit)
```

Some areas where it might be of interest are the queue (mentioned in the linked forum post), [notes index](http://danbooru.donmai.us/notes?group_by=post), comment areas ([index](http://danbooru.donmai.us/comments?group_by=post), [search](http://danbooru.donmai.us/comments?commit=Search&group_by=comment), [direct/permalink](http://danbooru.donmai.us/comments/543210)),  [pool gallery](http://danbooru.donmai.us/pools/gallery), and pretty much any other thumbnail listing. One place of questionable usefulness might be [user profiles](http://danbooru.donmai.us/users/43210)?

**Comment by r888888888** [comment]
Instead of hiding blacklisted posts maybe they should just have a blank preview? On some pages it's inconvenient to have a dedicated panel just for blacklist management.

**Comment by Moebius-Strip** [comment]
Assuming I'm following you correctly, I think the notes index would be fine with the inline blacklist controls since it's basically just a thumbnail listing. For the comment areas and pool gallery, an alternate blacklist style that only affects the thumbnails and not the related text or elements could most certainly be a good thing.

When you say "blank", it makes me think of completely removing the thumbnail, but maybe you're talking about a placeholder for it? I think it would be rather important to maintain the link that the thumbnail provides. For the comment areas, the thumbnail would seem to provide the only link to the post that the comments are related to. For the pool gallery, the thumbnail provides a quick way to start browsing a pool's posts.

I take it this approach would mean the only way to see which blacklist entries were affecting a page would be navigating to a blacklisted post and then decide whether to reveal its content or not?

**Comment by Moebius-Strip** [comment]
>  Another problem is the new ability to permanently disable the blacklist could result in blacklisted posts being displayed without providing some kind of hint that this is actually happening.

I originally marked this out in an edit since it couldn't actually happen without the "blacklist-list" element existing within the document. Now that individual entries can be toggled on/off across pages, any entry that's disabled by the user's click or the disable all function's "click" will result in the above situation for the browsing session.
