### ISSUE TITLE
Pool gallery has pools missing from the list

### ISSUE THREAD

**Issue by Moebius-Strip** [r888888888/danbooru#2488]
In the pool gallery, if the first post of a pool happens to be one that the user can't normally see (banned, deleted, censored), the whole listing for that pool gets dropped. The [Kantai Collection - Admiral's Winter Vacation](http://danbooru.donmai.us/pools/10226) series is one example of a pool that doesn't show up in the pool gallery.

On a side note, I'm just now noticing the pool gallery seems to exclusively be for series category pools.

**Comment by r888888888** [comment]
This is really only a problem for deleted I think. If it were blacklisted you probably wouldn't want to see it anyway.
