### ISSUE TITLE
Hentai-Foundry image source update for artist finder

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2489]
Old style:
http://pictures.hentai-foundry.com//[letter]/[artistname]
New style:
http://pictures.hentai-foundry.com/[letter]/[artistname]

They removed the double-slash.

**Comment by ToksT** [comment]
Artist finder still needs to be fixed, that only fixed the normalized source redirect when you click the post's source link. Artist urls will need to be normalized to remove the extra /. And existing artist urls will need to be updated with the normalization.

Also the full change seems to be a bit more than just the one /:
Old:
http://pictures.hentai-foundry.com//a/AnimeFlux/219123.jpg
New:
http://pictures.hentai-foundry.com/a/AnimeFlux/219123/Mobile-Suit-Equestria-rainbow-run.jpg

**Comment by r888888888** [comment]
Script has been run.
