### ISSUE TITLE
Add exception to Source Redirect for tumblr GIFs

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2491]
post #2096069 was auto-corrected by Danbooru Upload bookmarklet/source redirect, but came out as static .JPG instead of animated .GIF

**Comment by ToksT** [comment]
Strange. Why would tumblr make the 1280 version a static image when all the smaller versions are animated?

Also this doesn't seem to be true for all gifs on tumblr. Here are some examples of animated 1280 sizes:
http://danbooru.donmai.us/posts/2047925
http://danbooru.donmai.us/posts/2036947
http://danbooru.donmai.us/posts/2023851
Maybe it's a tumblr bug that only occurred for that one image, in which case I don't think we should change anything.

**Comment by Kikimaru** [comment]
I've definitely seen it before.

post 1802044 had the same bug.

**Comment by ToksT** [comment]
I disabled using the 1280 version only for bugged images like these. It should still work for the ones that are actual gifs.
