### ISSUE TITLE
Change upload limit formula

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2492]
It should be based on odds of deletion for the user's upload, capping at 15% but allowing a minimum of 10 uploads a day.

**Comment by r888888888** [comment]
This has been merged into master now.

**Comment by Type-kun** [comment]
Banned posts should probably be excluded from calculations. It's not exactly user's fault that artist wanted them removed.

**Comment by ToksT** [comment]
> Banned posts should probably be excluded from calculations. It's not exactly user's fault that artist wanted them removed.

Banned posts aren't deleted. Albert undeleted all banned posts.
