### ISSUE TITLE
Protect source downloader against server-side request forgery attacks

### ISSUE THREAD

**Issue by kxz** [r888888888/danbooru#2498]
Automatic source downloading for uploads [can be abused to make requests to addresses that aren't publicly accessible](https://docs.google.com/document/d/1v1TkWZtrhzRLy0bYXBcdLUedXGb9njTNIJXa3u9akHM/edit?pli=1), for example other services that listen on `localhost` on the server running Danbooru, or Amazon EC2's metadata URL at `169.254.169.254`. The image downloader should check on each request, including redirect targets, that the hostname is not a loopback, link-local, or private IP address, or something that resolves to one (e.g. `127.0.0.1.xip.io` resolves to `127.0.0.1`), and possibly support an additional custom blacklist in `danbooru_local_settings.rb` for other hostnames and IP addresses.

**Comment by r888888888** [comment]
What would you say to that implementation (assuming the public addresses for the servers are added in the local config)

**Comment by kxz** [comment]
I'd add the RFC 1918 private addresses by default (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) but otherwise this looks good to me.

**Comment by evazion** [comment]
2f17082 fixed this check not being applied to redirects either.
