### ISSUE TITLE
Support uploading mp4 video

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2499]
Should be easy to add since we already support webm, except there seem to be a number of possible file signatures for mp4. I guess this covers them all?:
`[4 bytes of anything] ftypisom`
`[4 bytes of anything] ftyp3gp5`
`[4 bytes of anything] ftypmp42`
`[4 bytes of anything] ftypMSNV`

**Comment by r888888888** [comment]
I imagine MP4 is much more likely to contain audio channels. The question is whether to strip them out or upload it as is.

**Comment by ToksT** [comment]
I added the "videos can't have audio" restriction so people don't upload full anime episodes or something, but since there's also a max duration of 2 minutes it's probably not necessary to have both.

We could get rid of the no audio restriction for videos, but then there should be a warning on the thumbnail that there's sound. For example we could have a new auto-added tag for sound, and put a speaker icon on the thumbnail for posts that have this tag (like the ► for animated posts).

**Comment by r888888888** [comment]
This has been deployed to Testbooru for testing.

**Comment by Type-kun** [comment]
You might want to also add that icon to {{flash_with_sound}} tag. Also, it's probably OK, but 2 minute limit is just enough to upload the entire opening/ending, like http://testbooru.donmai.us/posts/8 , so I'd expect that to happen often from now on.

**Comment by r888888888** [comment]
I wonder if video_with_sound is a better tag to use then.

**Comment by Type-kun** [comment]
Should mp4 videos get `mp4` tag for consistency, as it is already done for webm format?

**Comment by ToksT** [comment]
That was implemented in 92c68db37a587fa048793e54c37939e1fc957640
