### ISSUE TITLE
Pixiv api client not working

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2505]
```
PixivApiClient::Error exception raised
Pixiv API call failed (status=400 body={"status":"failure","has_error":true,"errors":{"system":{"message":"The access token provided is invalid."}}})
```

**Comment by r888888888** [comment]
I cleared the papi cache. I also fixed a bug with the JSON presenter which may be related.

**Comment by ToksT** [comment]
Happening again now for some reason, it was working for a little while though.

**Comment by r888888888** [comment]
I must be going crazy. Upgrading the gem seems to have reverted the TTL expiry behavior for the memcached gem. Reading the current docs for Dalli they seem to expect the expiry in seconds now.

**Comment by r888888888** [comment]
Seems to be fixed now.
