### ISSUE TITLE
Installing on Fresh Debian 8.2 error.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2515]
I seem to be having trouble running the installer, I've copied the whole output here;

This is the installer its output, this was on a freshly installed Debian 8.2 (Jessie) server.
http://pastebin.com/zfwqDySY

And here is the output for the deploy:setup command,
http://pastebin.com/Lt1Fz1pc

I've made an edit to the "/home/danbooru/danbooru/config/deploy/development.rb" file to include :user => "danbooru" to see if I could get it to actually log me in since it seemed to deny me access at "@localhost" and using the correct password for the danbooru account, also have tried using the root user password.

After making the edit the "@localhost" seemed to have changed to "danbooru@localhost" and it did accept my password but giving me the error that "deploy:setup" couldn't be found.

if needed I could give access to the server (It has no data yet and can be re-installed within 5 minutes if needed) so you can test what might cause this issue.

**Comment by Iratu** [comment]
After messing around I found out that I had to do "bundle exec cap development deploy" at least that is what the Cap3 guide tells me.
but this still leaves me with an installing issue; 
http://pastebin.com/XNTNnQSd

It seems to fail to find the Gemfile in the target directory, which is correct because there is none in there and creating one manually there does not resolve the problem.

**Comment by Iratu** [comment]
I've gotten it to work by going back a few revisions when you were still using cap2 and using the cap2 installation to upgrade to the latest revision.

**Comment by r888888888** [comment]
I assume you're using the danbooru user account on the server.

Deploying from the server is a bit strange and not something I'd really recommend, mainly because editing the files means you'll have to use a command line editor. I typically deploy from my Macbook.

If you insist on deploying from the server, you have to realize that Capistrano uses SSH to execute all its commands, so the machine has to SSH into itself. This is why setting up the SSH keys in that way is necessary.

It may be necessary to run cap deploy:setup for the initial deployment to set up the directories.

**Comment by r888888888** [comment]
The failing command is:

```
Command: cd /var/www/danbooru2/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.5 RAILS_ENV=production ~/.rbenv/bin/rbenv exec bundle exec script/delayed_job stop )
Could not locate Gemfile or .bundle/ directory
```

This means you should look in that directory and check to see the Gemfile is there.

**Comment by Iratu** [comment]
I've done some looking around and found out its not checking out the git repository in the /var/www/danbooru2/releases/ folder causing it to be unable to create the /current folder making it not finding the Gemfile.

**Comment by Iratu** [comment]
So it is a file somewhere thats causing the error, I run the first deploy:setup and deploy:update with Cap2, upgrade to the latest danbooru setup which uses cap3 and can use it just fine to update with "bundle exec cap staging deploy"

**Comment by r888888888** [comment]
It might be a permissions issue. Make sure the danbooru account can write to /var/www/danbooru2.

**Comment by taichibana** [comment]
Hi Iratu and r888888888!

I am having an issue during the set up of danbooru, the same problem that Iratu explained at the beginning.

Could you explain how did you get it running??

Thanks!

**Comment by Iratu** [comment]
@r888888888 It's not a permission issue, even setting the /var/www folder to 777 permission set I can't write to it, strangely after downgrading to version 2.88.0 the installer worked because it used cap2 got it installed and running and after that I could upgrade it to the latest revision.

Also a quick question, when going to: /user_upgrade/new I have a redirect loop, is this a small configuration error or something caused because you run a safebooru and I do not?

**Comment by r888888888** [comment]
@taichibana tell me what the contents of /var/www/danbooru2 are

@Iratu It's probably because SSL is enforced. You can disable it on line 4 of UserUpgradesController.

**Comment by Iratu** [comment]
@r888888888 odd error since I was already forcing SSL, it seemed to have worked, thanks for the quick response

**Comment by taichibana** [comment]
Due to some problems with the hosting I had have to change the OS to debian-7.0-standard, but the problem seems to be the same.

I dont have a folder called /var/www/

This is the installer its output on fresh installed and updated  debian 7.0 standard:
http://pastebin.com/MMMP0wXH

And the output for deploy:
http://pastebin.com/8uwe4hyh

thanks!

**Comment by r888888888** [comment]
Go ahead and make /var/www/danbooru2 and make sure it's writable by the danbooru account. Then try runinng the cap depploy.

**Comment by r888888888** [comment]
It also looks like you somehow set the user to "@localhost"? That's incorrect. It should be "danbooru".

**Comment by Iratu** [comment]
>I've made an edit to the "/home/danbooru/danbooru/config/deploy/development.rb" file to include :user => "danbooru" to see if I could get it to actually log me in since it seemed to deny me access at "@localhost" and using the correct password for the danbooru account.

same problem as I had in the Opening Post

**Comment by Iratu** [comment]
Okay I've set up an old server of mine for helping to test this.

After editing the development.rb file to include , :user => "danbooru" I run into this error:
http://pastebin.com/Fv6KZzHL

And this is the content of /var/www/
http://pastebin.com/qy4J3m6C

It can't find "current" which is correct because there is no revision installed yet and this is a fresh install.

**Comment by r888888888** [comment]
I updated the source code. Try pulling the updates and trying again.

**Comment by Iratu** [comment]
development.rb needs this line to be modified, 
server "localhost", :roles => %w(web app db), :primary => true, :user => "danbooru"

Almost seemed to work but it runs into: 
EBUG [dabbfc4c]        Cannot load `Rails.application.database_configuration`:
DEBUG [dabbfc4c]        Could not load database configuration. No such file - ["config/database.yml"]
I snipped the rest.

**Comment by r888888888** [comment]
Run these commands:

```bash
mkdir -p /var/www/danbooru2/shared/config
mkdir -p /var/www/danbooru2/shared/data
sudo -u danbooru bash -l -c 'cp ~/danbooru/script/install/database.yml.templ /var/www/danbooru2/shared/config/database.yml'
sudo -u danbooru bash -l -c 'cp ~/danbooru/script/install/danbooru_local_config.rb.templ /var/www/danbooru2/shared/config/danbooru_local_config.rb'
```

**Comment by r888888888** [comment]
Just create one for development. You can probably copy the one for staging.

**Comment by Iratu** [comment]
Seem to be working OK now, just a small tip;

sudo -u danbooru cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

Might be nice to add that into the INSTALL.debian file at line 86, this would remove the need to enter a password when you SSH from the danbooru user into the danbooru@localhost

**Comment by taichibana** [comment]
I´ve installed danbooru again and now I get this error during the deploy:
http://pastebin.com/9W0H5WV1

**Comment by Iratu** [comment]
as the danbooru user run: "chown danbooru:danbooru ~/.danbooru"
Without the quotes

**Comment by taichibana** [comment]
I had reinstalled the OS and Danbooru again.
1.
danbooru@changemyhostname: sudo -u danbooru bash -l -c 'cp ~/danbooru/script/install/database.yml.templ /var/www/danbooru2/shared/config/database.yml'
danbooru@changemyhostname: sudo -u danbooru bash -l -c 'cp ~/danbooru/script/install/danbooru_local_config.rb.templ /var/www/danbooru2/shared/config/danbooru_local_config.rb'

2.
root@changemyhostname:~# cd /home/danbooru/                                     root@changemyhostname:/home/danbooru# chown -R danbooru:danbooru .danbooru

3. At  development.rb :
set :user, "danbooru"
set :rails_env, "development"
server "localhost", :roles => %w(web app db), :user => "danbooru", :primary => true

4.Then whit danbooru user 
 bundle exec cap development deploy --> The output http://pastebin.com/UWRJ3Q7U

5. Enter the page and the response is 
Something broke
Return to index

I did something wrong??

Thanks

**Comment by r888888888** [comment]
The deployment looks fine.

Check log/development.log to see if there's error messages there.

**Comment by taichibana** [comment]
There are 4 development logs at /var/www/danbooru2/shared/log/

development.log (empty) the newest 
development.log.1 (empty)
development.log.2 (empty)
development.log.3 (150Kb) the oldest one---> http://pastebin.com/gTXM5N0Y

**Comment by taichibana** [comment]
Hi!
I have changed the OS to Debian 8.0-x86_64-minimal.
I have made the same as the message #22

Now the problem I is that after the deploy the website shows the default message of ngix:

"Welcome to nginx on Debian!

If you see this page, the nginx web server is successfully installed and working on Debian. Further configuration is required.

For online documentation and support please refer to nginx.org

Please use the reportbug tool to report bugs in the nginx package with Debian. However, check existing bug reports before reporting a new bug.

Thank you for using debian and nginx."

thanks!

**Comment by taichibana** [comment]
Hi again, 
I have tried everything I know from two months up to now, I really need to set up  the website.
I have a server and the best image board but I cant get it working.
I will give you all the access to the server you want or install the OS that you prefer, but please, help me!
Here you have my mail haroldc.ferguson[ a ]mail.ru
thanks
PS: May be @Iratu cloud help me

**Comment by Iratu** [comment]
Okay so it seems that on a fresh install it errors out with: http://pastebin.com/ayF9aTEb giving you the Failbooru page. It seems that it can't find "gctools"

Upon inspecting the "GemFile" it seems that only "production" has access to this.

group :production do
  gem 'newrelic_rpm'
  # gem 'unicorn-worker-killer'
  gem 'gctools', :platforms => :ruby
end

Taichibana, a quick fix is making a fork out of this and editing the Production files.

**Comment by taichibana** [comment]
Hi Iratu!
I really appreciate your answer but I don't know how to do it :( 
I mean, I don't know which are those files or text that must be edited.
Thanks!

**Comment by Iratu** [comment]
@r888888888 I've tried doing the way I said it but it seems to still run into that error a couple posts ago; http://pastebin.com/ayF9aTEb I seem to be unable to work around this.

**Comment by r888888888** [comment]
Are you deploying in the production environment? That library is included in the gctools gem.

**Comment by Iratu** [comment]
I have tried to Deploy in Production, seems to also fail with that error for some reason as well

**Comment by r888888888** [comment]
You probably have inconsistencies in what environment unicorn is running in.

If the OOBGC stuff is giving you problems just remove references to it. It's in config.ru.

**Comment by Connor22** [comment]
I'm having a similar problem where the "bundle exec cap development deploy" command is asking me for the password to @localhost, which I don't have.

This is a fresh Debian 8.2 > Ruby > PostgreSQL > INSTALL.debian install.

The danbooru2 folder only has a "shared" subfolder with an empty "data" subfolder and a "config" subfolder.

I've tried adding :user => "danbooru" to development.rb

Are there any links you could provide about deploying from another computer if that solves the "SSH'ing into itself" issue?

**Comment by r888888888** [comment]
Run ssh danbooru@localhost

If you don't want to enter the password constantly add your ssh public key to the authorized_keys file

If you don't have a password for danbooru then set it using the root account

**Comment by Connor22** [comment]
danbooru@DebianBooruTest:~/danbooru$ bundle exec cap development deploy
DEBUG [3a05b314] Running /usr/bin/env [ -d ~/.rbenv/versions/2.1.5 ] on localhost
DEBUG [3a05b314] Command: [ -d ~/.rbenv/versions/2.1.5 ]
@localhost's password:

This is where I can't advance any further. No password I have previously used is working.

**Comment by r888888888** [comment]
You have root access. You can set the password to whatever you want. Look up the passwd command.

**Comment by Connor22** [comment]
passwd for which username though? The root password doesn't work for this prompt, and neither does the one set for the danbooru user.

**Comment by Airman8** [comment]
Hi guys,

I'm stuck on deployment as well. development.log gives this error:

    E, [2015-12-09T21:53:22.692646 #22292] ERROR -- : PG::UndefinedFile: ERROR: could not access file
    "$libdir/test_parser": No such file or directory
    : CREATE OR REPLACE FUNCTION testprs_start(internal, int4)
    RETURNS internal
    AS '$libdir/test_parser'
    LANGUAGE C STRICT

I think the file in question is danbooru/db/migrate/20100204214746_create_posts.rb

I don't know what path it's looking for. Earlier I went through the commands in the installation script manually so I could resolve some permissions problems along the way. I think I got it all worked out. Not sure is this is relevant too, but the /var/www/danbooru2/current folder is missing. Any help would be appreciated!

**Comment by utterbull** [comment]
Seconding Connor22's issue. I ambeing prompted for the password of "@localhost". How do I change the password of a username that has 0 characters in it?

**Comment by Iratu** [comment]
`set :user, "danbooru"
set :rails_env, "development"
server "localhost", :roles => %w(web app db), :primary => true, user => "danbooru"`

change it to that in:  ./config/deploy/production.rb

**Comment by Chirishman** [comment]
@Iratu

Did you mean in development.rb? Anyway I did the same steps as @utterbull and @connor22 and, after editing development.rb i get failbooru with this log:

http://pastebin.com/vLSDFd92

**Comment by Iratu** [comment]
@Chirishman it should work. are you seeing the unicorn 'master' process and the two delayed_job processes running?

**Comment by cglmrfreeman** [comment]
I am having problems with a similar setup.
`[4552542e] Running /usr/bin/env [ -d ~/.rbenv/versions/2.3.1 ] as danbooru@localhost`
My rbenv is not installed there. This should be the correct path:
```
export RBENV_ROOT=/usr/local/rbenv
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init -)"
```

**Comment by wakabala** [comment]
I saw r8888888 mentioned previously that it's not recommended to set this all up on the server itself, and instead set it up on a local machine then deploy to a server. I'm not entirely sure which step of the process that should be done. I have a Linode server with Debian 7.x, and I have a local machine with Debian 7.x. I set up. I cloned the git and ran the installer on my local machine, but when it asks for the hostname should I give it my server's hostname? I just installed it on my local machine and got the same @localhost password error that a few others have been getting. Any help would be much appreciated.

**Comment by r888888888** [comment]
You should run the installer on the Linode server, and then clone the repository to your local machine and deploy from your local machine. You will need to install Ruby and the associated gems but it's a vastly simpler operation than the full install script.

The only reason I recommend doing this is because editing the code is easier to do locally. Obviously you will need to fork the project so you can push your own commits.

**Comment by Iratu** [comment]
Closing this since it's not relevant anymore.
