### ISSUE TITLE
Dividing Danbooru on comic and regular posts

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#2516]
Given the deployment of the current day cap on uploads, I think it is time to seriously consider developing a division between danbooru the art site and danbooru the comic site (Albert, you yourself asked if that should be a thing in the past).  While there is overlap between the two, the requirements of each category are different enough that to emphasize and encourage one category can be to the detriment of the other.  A division needs to be established between the two that allows for the catering of the needs of each category, without trying to throw a universal one-size-fits-all standard for the two. Especially when the sizing of the rules are being tailored to fit toward the benefit of the art side ((non-comic post side)  of the site.

I don't know how far to take the division, but for instance upload requirements for comics need to be somewhat different from the regular art post requirements, particularly on the degree of allowable "artistic" quality.  If the division keeps them together on the same site, then comics need to be divided out of the post viewing and placed under their own post section (this for one removes the necessity of a -comic search for those who come here specifically for art and vice-versa), and those comic posts should apply to their own separate upload cap value for users (if keeping them capped, then ideally one with a higher value, around 70-100 posts, as a single large comic can easily take up to 50 posts).  (A different approach with the current cap could be simply halving the count value of comic posts, that would give users a 10-50 pure regular post cap or 20-100 pure comic post cap).

Comics posts and non-comic posts should also be separated apart in a user's stats.  It'd be necessary anyway for a separate cap between the two (or shared cap), but the information is also valuable when determining whether a user should or shouldn't receive a promotion.  In general we reward for art side (or non-comic) post uploads when determining promotions, so being able to see at a glance a user's non-comic post count versus their comic posts count is rather useful.

@r888888888: Any of this is of course if you wish to cater to comics at all. I had asked before if the goal has been to de-emphasize and/or discourage comic uploads with recent changes. Your response (or lack thereof) would suggest that perhaps that is your intent.  If that is so, it would be nice if you made it clear to me then, so that I may know to back off and stop bringing the comic issue up.

**Comment by Type-kun** [comment]
Like you suggested, I think it would be easier to count comic uploads differently towards limit, as half of post or quarter of post, so that the user is allowed to upload more comic posts. It creates some possibility for abuse (tagging every upload as comic, removing the tag later), but any other option might be subject to the same abuse.

**Comment by ToksT** [comment]
> It creates some possibility for abuse (tagging every upload as comic, removing the tag later),

I thought upload limit was calculated on the fly? So as soon as you remove the comic tag from all the posts your upload limit would go back down instantly.

**Comment by Type-kun** [comment]
>I thought upload limit was calculated on the fly? So as soon as you remove the comic tag from all the posts your upload limit would go back down instantly.

Yes, but it will still allow you to upload more images at once, before the comic tag is removed. Such actions are visible, though, so it shouldn't be a problem

**Comment by r888888888** [comment]
I have always considered splintering off an unmoderated Mangabooru but there were a lot of changes that I had intended on implementing, like the gallery view, tagging pools, etc. I'm not sure if people would migrate anyway.

Allowing comics is a hard question. In general they won't have as good art. They might have value in other ways, like humor or drama, but that's dependent on translation which won't necessarily happen with every upload. Does an untranslated mediocre comic belong on the site?

I'm open to the increased count for comics idea. It is open to abuse but that's easy enough to detect.
