### ISSUE TITLE
Rework disabled blacklist cookies

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2518]
It turns out that having one cookie per blacklist entry can lead to exceeding the maximum limit of cookies per domain, effectively logging the user off; see http://danbooru.donmai.us/forum_topics/12086 for details. Perhaps it would be better to move those to local storage or try to compress them into single cookie somehow?

**Comment by r888888888** [comment]
Local storage is already used for autocomplete caching and can easily reach max capacity from that.

**Comment by Type-kun** [comment]
Hm. Then how about compacting the hashes of disabled blacklists into a few space-delimited strings instead of creating a cookie for each one? It'll take a bit longer to process, but at least wouldn't make too many cookies. That still bears the risk of consuming the entire cookie space which is often limited to 4kb, though. 

I assume it would be impossible to simply enumerate blacklists? If that's possible, then a single N-chars long string could be used to keep track of N blacklist entries with 0/1 at the corresponding positions. I understand that the most complicated part would be when user changes their blacklist and the enumeration is messed up, but maybe there's some way around it, since we would have the cookie from before the blacklist was changed and can rebuild it with new entries?

**Comment by ToksT** [comment]
> Local storage is already used for autocomplete caching and can easily reach max capacity from that.

For autocomplete cache each value is like 1000 characters long, and users usually have hundreds or thousands of them. For blacklists the value is only 1 character long and users probably won't have more than a couple hundred tops so it won't be as easy to exceed the cap.

**Comment by Type-kun** [comment]
> For autocomplete cache each value is like 1000 characters long, and users usually have hundreds or thousands of them. For blacklists the value is only 1 character long and users probably won't have more than a couple hundred tops so it won't be as easy to exceed the cap.

I think Albert is talking about the total capacity of local storage. Though, if the storage works like FIFO queue once over its capacity, and if disabled blacklists entries are meant to be disabled as session ends, it shouldn't be a big problem; though, there will still be a chance of blacklists re-enabling by themselves.

**Comment by ToksT** [comment]
Since it's supposed to be limited to the session we should use sessionStorage instead of localStorage. And I believe the two have separate limits so there shouldn't be a problem of the autocomplete cache filling up the same space as blacklists.

**Comment by Moebius-Strip** [comment]
Session cookies and sessionStorage do differ in the fact that sessionStorage isn't shared across tabs/windows unless the new tab/window is opened via page methods such as the target attribute on a link or JavaScript's window.open() method. Manually opening a new tab/window via middle click, shift, control, clicking the tab bar, etc. will not carry over any disable blacklist information.

**Comment by ToksT** [comment]
I made it so "disable all blacklists" only creates one cookie instead of one for each blacklist, that should make it harder to reach the cookie cap. Though it could still happen if a user disabled 100+ blacklists by clicking on each of them manually as opposed to using the "disable all blacklists" button.
