### ISSUE TITLE
Consolidate saved searches+tag subscriptions to off-site service

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2523]
I'm not sure what the best data structure for this might be but I envision something like tag changes feeding into a message queue that's consumed by off-site workers. These workers will then push the post into per-user queues stored in Redis. The whole advantage of this system would be that tag subscriptions effectively become updated with every change instead of running queries every time. The load on the database server would be minimal since the processing would be done in the workers.

**Comment by r888888888** [comment]
Thinking long term, I don't think supporting tag subscriptions is sustainable. Very few sites have a concept of categorizing saved searches and in practice it makes the UI clumsier and the data model more complicated. If we can assume saved searches are all grouped under one category, then the listbooru implementation is much simpler, which in turn makes processing faster.

The end result is this: tag subcriptions will be deprecated. A process will be offered to migrate tag subscriptions to saved searches. Saved search processing will be offloaded to listbooru, which will allow for an aggregate view.

**Comment by Type-kun** [comment]
I don't see how saved searches are a replacement for tag subscriptions. One subscription allows to keep track of 20 separate artists, for example; without using `~` in tag search, it's at least 20 searches that I should perform manually to see if anything new is uploaded. The whole point is that user can see at a glance that something new was uploaded to the tag group they're interested in; if you want to reshape subscriptions, this aspect at least should remain intact. 

Additionally, if said subscription is broken down into 20 searches, even if these searches are somehow ordered by id of last post that matched it and thumbnails are listed the same way as subscriptions, it will be clumsier than current implementation because most of those thumbnails will be old posts anyway.

**Comment by ToksT** [comment]
Also, is removing the ability to categorize saved searches necessary? I don't understand how this helps performance, the category only affects the order they're displayed on /saved_searches. And why not let saved searches be edited?

**Comment by r888888888** [comment]
I think converting the existing tag subscriptions to saved searches will let me keep the categorization.

**Comment by ToksT** [comment]
Maybe "Enable categorized saved searches" should be on by default? Otherwise, it could be mentioned at the top of the /saved_searches page so more people know about the setting.

**Comment by Type-kun** [comment]
@r888888888, do you still intend to drop subscriptions altogether? If you do, I think it should be brought to forums for discussion beforehand. In addition to general storm and rage-quits it's going to cause, I'm fairly certain that some translators use subscriptions to track seldom-updated works, so removing theme completely would impede their work.

Also, can you clarify would listbooru's going to do, exactly? Simply store saved searches?

**Comment by r888888888** [comment]
The plan is to convert subscriptions to saved searches, but saved searches would gain the aggregation feature. So they will be functionally equivalent.

**Comment by r888888888** [comment]
This is all probably several weeks off. I want to track how well an offsite service can keep up with updates and its effect on the database. In the meantime subscription and saved search behavior will be left alone.

**Comment by ToksT** [comment]
Saved searches are still missing the edit page.

**Comment by r888888888** [comment]
Deployed on testbooru

**Comment by evazion** [comment]
Tag subscriptions have been fully replaced by saved searches so I think it's safe to consider this fixed.
