### ISSUE TITLE
Duplicate image copy tag to existing.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2525]
Would it be possible to have the tags entered on a duplicate post to be transfered to the existing one if it wasn't on the existing post.

Example:
Existing post has: small_breasts cute
and the New one has: smiling cum_on_body etc.
Copy the tags the new one has to the existing image. making it: small_breasts cute smiling cum_on_body

**Comment by r888888888** [comment]
If you're talking about uploads this already happens (or at least is supposed to happen).

If you're talking about parent/child relationships that sort of tag duplication wouldn't always be correct.

**Comment by Iratu** [comment]
I'm talking about uploads, but I haven't seen it happen yet

**Comment by ToksT** [comment]
This feature used to exist but I removed it. See http://danbooru.donmai.us/forum_topics/9999

**Comment by Iratu** [comment]
I see, is there a way I can re-add it?

**Comment by ToksT** [comment]
> I see, is there a way I can re-add it?

You can see the removed code here: 14f2e473196a9439253774a4f6e6f70ada3641b6

**Comment by Iratu** [comment]
@ToksT Thanks, I seem to have gotten it to work.
