### ISSUE TITLE
Add ui for accessing search post counts

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2528]
Currently the easiest way to find out the post count of a search is to replace "posts" with "counts/posts.json" in the url manually. There should be a link. Also an html version of the page.

**Comment by Type-kun** [comment]
For a record, tag combination mentioned in topic - http://danbooru.donmai.us/counts/posts.xml?tags=mochiki+touhou - consistently yielded 1000000 for me until today; that is, timed out. The page won't be of much use if even the simple tag combo with small result set times out.

**Comment by ToksT** [comment]
mochiki+touhou doesn't always fail. Two days ago I tried it multiple times, half the time it timed out but half the time it worked fine. Today it seems to be working without any time outs.

I wonder if there's any way to make it more consistent. I don't know why it occasionally times out even for simple searches considering we have a 9 second timeout.

**Comment by Type-kun** [comment]
> I don't know why it occasionally times out even for simple searches considering we have a 9 second timeout.

It uses fast_count module of posts, which currently times out in 500 ms

**Comment by ToksT** [comment]
> It uses fast_count module of posts, which currently times out in 500 ms

That's only the default used by fast_count. /counts/posts.json overrides the default so it uses your timeout.

**Comment by ToksT** [comment]
Wait, fast_count uses the same cache regardless of timeout length, so maybe 1000000 is getting put in the cache when the timeout is 500ms. Then even when someone with a 9 second timeout tries to use /counts/posts.json it would just look in the cache and see 1000000.

**Comment by Type-kun** [comment]
Does it work properly, though? I'm fairly sure I got the timed-out response in way less than 9 seconds.

**Comment by Type-kun** [comment]
>Wait, fast_count uses the same cache regardless of timeout length, so maybe 1000000 is getting put in the cache when the timeout is 500ms. Then even when someone with a 9 second timeout tries to use /counts/posts.json it would just look in the cache and see 1000000.

Yeah, that seems viable. Timed-out counts shouldn't be stored in cache, probably?

**Comment by r888888888** [comment]
I'm gonna change the timeout count to -1 so it's more obvious when something is amiss.
