### ISSUE TITLE
i am the owner of some art, legal action will be taken

### ISSUE THREAD

**Issue by grumpypuppy** [r888888888/danbooru#2529]
i am the god damn owner. I have the right to have my ART removed when I want it REMOVED not in a fucking week. so that i can FUCKING flag it for removal. I will take legal action. 
ID: 11836265

**Comment by kxz** [comment]
If you believe an upload infringes on your copyright, please follow the instructions on [the Danbooru terms of service](https://danbooru.donmai.us/static/terms_of_service). GitHub issues are not an appropriate venue for takedown requests.
