### ISSUE TITLE
Better ip address search for finding sockpuppets

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2530]
Currently you can use the ip search to find sockpuppets but it's very inconvenient. First do a search on a user's id number to get a list of all their ips (this list usually has more than a dozen entries). Then go through the list one by one and do a search on each ip to get a list of users associated with the ip. If there's more than 1 user listed then it might be a sockpuppet.

It should be possible to put in the user's name and get a list of other users that share ips. Example:

Search for [User X](#):
[User Y](#) shares 19/43 ip addresses
[User Z](#) shares 1/43 ip addresses

**Comment by Type-kun** [comment]
Hm, I think the way to do that would be to select a list of user IPs with existing `search_by_user_id(user_ids)`, then something along the lines of

```sql
select q.k, count(distinct q.ip_addr)
from 
(
select distinct creator_id as k, ip_addr  from comments where ip_addr in (?)
union all
select distinct updater_id as k, updater_ip_addr as ip_addr from post_versions where updater_ip_addr in (?)
union all
select distinct updater_id as k, updater_ip_addr as ip_addr from note_versions where updater_ip_addr in (?)
union all
select distinct updater_id as k,  updater_ip_addr as ip_addr from pool_versions where updater_ip_addr in (?)
union all
select distinct updater_id as k,  updater_ip_addr as ip_addr from wiki_page_versions where updater_ip_addr in (?)
union all
select distinct from_id as k,  creator_ip_addr as ip_addr from dmails where creator_ip_addr in (?)
) q
group by k;
```

But I'm not sure how well that would perform. There are indexes on some ip_addr fields, though, so it should be fairly reasonable.

**Comment by r888888888** [comment]
This would have to be made into an asynchronous report. I don't think it's plausible to generate it on demand.

**Comment by ToksT** [comment]
Apparently it already supports searching by multiple ip addresses at the same time if you separate them with commas. So I added quick search links so the user can just click that instead of needing to copy paste all the ips. Also I made it more clear that searching by multiple ips or by user name is possible.

**Comment by r888888888** [comment]
Oh didn't realize you had written something. Not sure which version is more useful. The counts on my commit are a bit confusing and perhaps misleading.

**Comment by ToksT** [comment]
Yeah "count" is undescriptive so I changed it in my implementation, but admittedly "number of occurrences" is barely better.

I think it would be more useful if instead of displaying the number of versions it showed the number of unique ip addresses shared between the pairs of accounts, but I haven't implemented that yet.

Is the 3 months ago limit necessary for performance? Seems counterproductive if there are records of ip addresses from over 3 months ago that are necessary to find certain sockpuppets. I don't know how common that is though, maybe make the max age configurable by the user instead of hard coded?

Also there are some new bugs from our implementations conflicting. If you put in an ip address it treats it like a username and causes an error. There's no way to get a list of the individual ip addresses like there used to be. It does two queries but only displays the results of one which isn't good for performance.

**Comment by ToksT** [comment]
If I do a search for myself on the live site it lists 300 people as sharing ips with me. I think this is a bug since I only have one static ip address.
