### ISSUE TITLE
post_flags: search[creator_name] parameter on user profiles broken

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2535]
The `search[creator_name]` parameter used by the Flags link on user profiles no longer works; `search[creator_id]` still works, though.

**Comment by ToksT** [comment]
I don't understand. It works fine for me?

http://danbooru.donmai.us/post_flags?search[creator_name]=RaisingK

**Comment by RaisingK** [comment]
But for me, that link shows *all* flags, not just mine.  Maybe being a Mod changes things for you?

**Comment by ToksT** [comment]
Oh I get it, neither of these work for users below mod, but creator_id has an exception for your own id, creator_name doesn't.
