### ISSUE TITLE
Demoting fails.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2539]
undefined local variable or method `approval_text' for #<UserPromotion:0x007f23f7e7c620>

After checking in the coding it seems that "Approval_text" and "upload_text" variables aren't set when running the "create_demotion_demail" proc, I copy and pasted line 68 to 78 and added that to the demotion proc.

https://github.com/Iratu/atfbooru/commit/7d82b8a05c9b206c92501a8c49e8d1d2e8c424c8

**Comment by r888888888** [comment]
This is probably fixed in #2470

**Comment by ToksT** [comment]
fixed
