### ISSUE TITLE
Request: Add Inkbunny to the Bookmarklet

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2544]
I was wondering if it was possible to add Inkbunny to the bookmarklets "Post to" and "Batch to" there are a few users that requested this to me in person for my Booru Fork.

InkBunny has an API which could be used for this; https://wiki.inkbunny.net/wiki/API

**Comment by r888888888** [comment]
I don't think this has much utility for Danbooru but you're welcome to implement a code path for it. It's fairly modular. Add a new strategy under app/logical/sources/strategies, and possibly app/logical/downloads/rewrite_strategies. They all follow the same general pattern so you can copy paste an existing strategy.
