### ISSUE TITLE
Error page on add to pool

### ISSUE THREAD

**Issue by mrvacbob** [r888888888/danbooru#2546]
1. Go to image.
2. Open Add to Pool popup.
3. Type text but do not accept an autocomplete.
4. Submit.

Shows error page with backtrace.

**Comment by r888888888** [comment]
I have to assume you're not entering the complete name.

If you are can you provide repro steps on a real post and real pool?

**Comment by mrvacbob** [comment]
Yes, this is if you enter an invalid name.
