### ISSUE TITLE
Error during the Upload of Images

### ISSUE THREAD

**Issue by taichibana** [r888888888/danbooru#2547]
Hi again!

After getting a lot of help from Iratu, he got it running at "production".
i register at danbooru and decided to upload an image.
During the upload of a picture, it i got an error ( direct from a computer or through hotlink). 

Here you have all 3 logs located at “/var/www/danbooru2/shared/log”:
newrelic_agent.log ---> http://pastebin.com/MPMimDgR
production.log----> http://pastebin.com/mb6mKnH6
unicorn.log----> http://pastebin.com/y3NFAxzV

**Comment by ToksT** [comment]
7c7f92d1b21b5d5c4197def3bf5a016aace743aa should fix it just showing an unhelpful `DoubleRenderError`. Try it again and it should show what the real error is.

**Comment by taichibana** [comment]
Hi!
I reinstalled everything again with that change, and i got this two errors during the upload
-uploading from the computer: 
"undefined method `gsub' for nil:NilClass"
-Uploading from pixiv:
"error: PixivApiClient::Error - Pixiv API call failed (status=400 body={"status":"failure","has_error":true,"errors":{"system":{"message":"The request is missing a required parameter, includes an unsupported parameter or parameter value, repeats the same parameter, uses more than one method for including an access token, or is otherwise malformed."}}})"

Here you have all 3 logs located at “/var/www/danbooru2/shared/log”:
newrelic_agent.log ---> http://pastebin.com/8yiGYWgr
production.log----> empty
unicorn.log---->  http://pastebin.com/3MQFrYDJ

**Comment by r888888888** [comment]
You need to create a Pixiv account and fill in the appropriate values in danbooru_local_config.rb.

**Comment by taichibana** [comment]
Thanks, I wil do it! :)
But i don't get the direct upload from a computer work, I continue getting the same error:

"undefined method `gsub' for nil:NilClass"

If concrete log is needed, only tell me and i will give you.
Thanks.

**Comment by ToksT** [comment]
The user account you're using to upload needs to be builder level or higher to see the backtrace. If you're using a basic account it will only show the error without the backtrace.

**Comment by taichibana** [comment]
I changed to builder level and I got this backtrace: 
http://pastebin.com/7SZttzeX

**Comment by ToksT** [comment]
That means there's a nil in the recent tags. Dunno how you did that but 8473cfa109b43f314a4419b75dc6de44cc5f1975 should prevent it from throwing an error.

**Comment by taichibana** [comment]
I have reinstalled everything, and I continue having the same problem.
If you want, here you have the fork I use, which has simple modifications to run Production mode:
https://github.com/taichibana/DanbooruProduction
Thanks.

**Comment by taichibana** [comment]
problem solved by @Iratu
