### ISSUE TITLE
Implication error doesn't fail bulk update request

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2550]
http://danbooru.donmai.us/tag_implications?search[id]=6298,6297

Those two implications failed but the bulk request they're a part of didn't:
http://danbooru.donmai.us/bulk_update_requests?search[id]=401

The bulk request should have an error too.

**Comment by r888888888** [comment]
Hmm strange, those are errors on tags so probably just an unusual race condition that happened during processing. I guess alias/implication errors in general should bubble up to the request.

**Comment by r888888888** [comment]
I've added a retry loop to make this less likely to happen, as well as updating the forum topic.
