### ISSUE TITLE
Record IP address on user creation

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2557]
Currently only recorded when making edits.

Could be helpful if someone creates sockpuppets but has to wait to use them or if they use a different ip for editing than for creating accounts.

**Comment by ToksT** [comment]
It seems like anyone can view it in the api, should be limited to mod+

**Comment by r888888888** [comment]
fixed in 3221ff08f82b46f9eb0b6568fe24605ebad7a691
