### ISSUE TITLE
Similar users

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2560]
This is now feasible because of the various services for async queues and the replicated database.

Relevant commits in f3071e66ec0a1ab3b4b765a176e9549bf9d2ffbd and 18c84e4b0fcc69fb4ad81c03bc152315f36de937 although most of the work is in [reportbooru](https://github.com/r888888888/reportbooru)

It's live on production at the moment and can be seen [here](https://danbooru.donmai.us/reports/similar_users).

Some potential tweaks:

* Presently only favorites of posts uploaded in the past 2 years are looked at. This is to prefer more active users, but a better weighting scheme could be devised.
* A minimum of 500 favorites is required. I think this is the minimum number to get accurate results but it could be lowered.
* Need to show ranking scores
* Presently only the user's favorites are displayed but some more data mining could be done. Favorite artists, tags, uploads, etc. This is all done async so these can be potentially heavy queries.
* MapReduce. With the amount of data involved I don't think it's worth it but the algorithms are amenable to parallelization.

**Comment by ToksT** [comment]
Currently it only looks at people that have 200 total favorites or more, but if most of those 200 are older than 2 years the sample size can still be too small. It should ignore posts more than 2 years old when checking if someone has 200 favorites.
