### ISSUE TITLE
Fetch artist commentary for existing post

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2561]
Is it possible to have some way to automatically fetch an artist commentary, like #2327, but for posts that are already uploaded? It'd be faster and more reliable than copying it by hand.
- The best place for that feature is probably additional "fetch" button in "Add artist commentary" dialogue box.
- It should fail if Original Title or Original Commentary fields are non-empty already.
- It probably would be great if that fetcher worked through API, too, with post ID or source link as a parameter. The latter is open to abuse, though.

**Comment by evazion** [comment]
PR #2793 is an attempt at this. Running on http://devbooru.evazion.ml:3000 for testing. Does several things:

* Adds `/posts/1/artist_commentary.json` and `/artist_commentaries/1.json` API endpoints.
* Includes artist commentary in `/sources.json?url=<url>` to address point 3.
* Adds fetch controls to the "Add artist commentary" dialog box.
* Allows fetching from a source or from another post (to address #2238).
** For convenience, the post ID defaults to either the parent post or the first child.
* Copying commentary is handled clientside via Javascript, not serverside like the copy notes function is. I did it this way so it can just populate the form for you, that way you can review it before saving.
* When fields conflict they are ignored and an error notice is raised, *except* for the original description field. If the descriptions conflict then the fetched one is appended to the current one. 

There was some forum discussion of taking commentaries from multiple sources, that's what the point about appending descriptions is intended to support. If you want the commentary from both Pixiv and Twitter, you can fetch the Pixiv commentary first, then the Twitter commentary second, which will append it to the Pixiv commentary so you have both. It's kind of fiddly though, not sure how well it works.

**Comment by Type-kun** [comment]
Pretty much implemented by now.
