### ISSUE TITLE
"Random post" for anonymous

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2571]
On the post index the "random post" link appears for anonymous, but on the post show page it doesn't show up for anonymous.

**Comment by ToksT** [comment]
Actually i guess the whole options thing doesn't show up for anonymous, with download, find similar, etc

**Comment by Type-kun** [comment]
@r888888888 is this intended? Should we show at least some options to anonymous?

**Comment by r888888888** [comment]
Yeah one danger of that is exposing it to bots and crawlers. You can set rel=nofollow but a lot of crawlers ignore that.
