### ISSUE TITLE
Blacklist CSS doesn't work properly for viewing posts

### ISSUE THREAD

**Issue by Moebius-Strip** [r888888888/danbooru#2573]
Notes on actively blacklisted content are still visible and the "Blacklisted" text is present in the wrong place (hard to see). Blacklisted thumbnails in the parent/child notices are also displaying improperly.

I've made the "Blacklisted" text red in [this screencap](https://imgur.com/c4iTjRL) from [this post](http://danbooru.donmai.us/posts/2245834?tags=parent%3Aany+translated) to make it more visible.

**Comment by r888888888** [comment]
fixed
