### ISSUE TITLE
Wrap embedded notes text into additional div to allow styling.

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2575]
Currently, the text of the embedded note is inserted directly inside `note-box-inner-border`. If there was another `<div>` element around the text, it'd be possible to apply custom CSS to the contents of embedded notes, e.g. hide it altogether using `.embedded .note-box-inner-border div {display:none}`.

**Comment by r888888888** [comment]
The only reason I don't want to do this is it'd have to be resized by javascript. The behavior also collides with how background divs work.

If hiding the displayed content is all you need you can accomplish it with the following rule:

```css
.embedded .note-box-inner-border {text-intent: -1000em;}
```
You could also hide div.bg in case anyone is using that to strip all formatting.
