### ISSUE TITLE
Asynchronous JS is causing errors for embedded scripts

### ISSUE THREAD

**Issue by Moebius-Strip** [r888888888/danbooru#2578]
It appears anywhere with embedded scripts that require jQuery or the Danbooru object are running into problems. Sometimes the problem only shows up when the script isn't loaded from the cache and sometimes it just doesn't seem to matter.

A notable example is any ugoira viewed in its original format. When Danbooru's JS is loaded from the cache, the ugoira runs properly. When it isn't loaded from the cache, a reference error about "Danbooru" not being defined is thrown. In other problem areas, it's a reference error about "$" from jQuery not being defined.

**Comment by r888888888** [comment]
I'll revert it for now.

**Comment by SD-DAken** [comment]
Other problems I noticed while async js was active:
- Usually danbooru loads more or less instantaneous for me, but with async js it sometimes (not always) took several seconds to finish loading. I'm not sure if the js in it's current form does not perform optimally if run async or if it's a browser bug.
- Translation notes appear only after everything else finished loading, this is especially annoying when the page takes a long time to load, see above.
- It breaks[1] userscripts that expect the Danbooru object is defined when DOMContentLoaded fires (default time for userscripts to run when using Firefox + Greasemonkey at least). No way to really avoid this, the script authors have to change their userscripts to run when the load event fires.

[1] It's actually a race condition, depending how fast the page is loading, if it's cached or not, it sometimes works and sometimes does not.
