### ISSUE TITLE
Deploy Danbooru on Debian 7 (netinstall base) - how to move to production?

### ISSUE THREAD

**Issue by riox-zz** [r888888888/danbooru#2579]
I have spend quite some time getting danbooru to run but now I am stuck. 
What I did so far:
####
Install Debian 7 wheezy netinstall with
Default System Tools, SSH Server
User account: rootuser
FQHN: blue.local

Get Danboorou source on the system as root:
# install curl
aptitude -y install curl
# run the install script
curl -s https://raw.githubusercontent.com/r888888888/danbooru/master/INSTALL.debian > install.sh ; chmod +x install.sh ; ./install.sh
> Hostname: blue.local
...
#reboot for good mesure
#login as danbooru
mkdir /var/www/danbooru2/shared/data/preview
mkdir /var/www/danbooru2/shared/data/sample
cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
# test if ssh works and accept host key
ssh localhost
#add ", :user => "danbooru"" to the end of line 3 ~/danbooru/config/deploy/development.rb
vi ~/danbooru/config/deploy/development.rb
# su - into root and fix ownership of keyfiles
chown -R danbooru:danbooru /home/danbooru/.danbooru/
#back to the danbooru user with exit
bundle exec cap development deploy
# wait and reboot
#login as danbooru
cd /var/www/danbooru2/current
#switch memcached from localhost to 127.0.0.1 in config/danbooru_default_config.rb
#start danbooru using WEBrick on port 9000 bound to 127.0.0.1
rails s -p 9000 -b 127.0.0.1

... everything work. What now? 
If I kick out the oobgc stuff from config.ru I can run
unicorn_rails -c config/unicorn/development.rb -D

but now I am beat... help!

**Comment by r888888888** [comment]
If all you care about is running it locally then you can just connect to localhost:9000.

The README has a section on troubleshooting. Read that to isolate where your problems are.

**Comment by riox-zz** [comment]
Ok, now I deployed it on my public server. 
rails_env, "production"
$ unicorn_rails -c config/unicorn/production.rb -D
worker=0 spawned (and all the other workers too)
rack.rb:14: warning: already initialized constant Rack::VERSION
rack.rb:14: warning: previous definition of VERSION was her
dependencies.rb:457:in `load': No such file to load -- gctools/oobgc (LoadError)
reaped #<Process::Status: pid 1034 exit 1> worker=0

Without oobgc in the config.ru file it works fine.

Looks like the workers consume more and more memory over time. I fear sooner or later it will start to swap and kill the system
