### ISSUE TITLE
test_parser is no longer packaged in PostgreSQL 9.5 contrib

### ISSUE THREAD

**Issue by kxz** [r888888888/danbooru#2580]
See the [PostgreSQL 9.5 release notes](http://www.postgresql.org/docs/9.5/static/release-9-5.html#AEN127130). This makes `test_parser` a pain to install since you basically have to do it from PostgreSQL source. It'd be nice to migrate over to [the built-in parsers and dictionaries](http://www.postgresql.org/docs/current/static/textsearch.html).

**Comment by r888888888** [comment]
Looks like none of the default parsers will interpret underscores correctly.

However it is possible to write a plpgsql function that manually parses a string and casts it into a tsvector. This is probably easier than trying to devise a custom parser.

**Comment by Type-kun** [comment]
Unfortunately, new default parser identifies underscores (and other punctuation, except hyphens) as a word boundary. That said, I have strong suspicions that pl/pgsql function will be much slower - it can be tested on 9.4, though.

Test parser code is quite trivial, just over a hundred of lines in C: see http://doxygen.postgresql.org/test__parser_8c_source.html. perhaps it's possible to simply compile it and include as a module into install script? Or just grab the previous test parser module from former contrib packages - it should be a single small .so file, and I doubt it had a single change in years.

That said, I couldn't find how to actually include the module once it's built/obtained. It would probably be considered an extension - http://www.postgresql.org/docs/9.5/static/extend.html - but I have zero experience with these.

**Comment by r888888888** [comment]
I've tried extracting the extension to its own project: https://github.com/r888888888/test_parser

**Comment by r888888888** [comment]
Ideally the next step would be a dpkg package...
