### ISSUE TITLE
Pressing a & d does not go to the next page instead it goes to an undefined page.

### ISSUE THREAD

**Issue by dragons4life** [r888888888/danbooru#2581]

**Comment by ToksT** [comment]
Fixed in 009f020896f744af7a938baec22b751840689b33

**Comment by dragons4life** [comment]
Don't know if the update is live but I am still having the same problem. for example I go to the Naruto tag choose a photo, (apparently A/going back does not work) but when you choose to use D/Forward it works but it takes you to an undefined page.

**Comment by r888888888** [comment]
It's not live.

**Comment by Moebius-Strip** [comment]
I get the feeling this update is live now and fixed a problem with the "rel" attribute (?), but it looks like the JavaScript still needed a [slight tweak](https://github.com/r888888888/danbooru/commit/74872c3cb614a234800b468afe7dce426325e201) to fully resolve the issue. Revert if I'm mistaken.
