### ISSUE TITLE
DText fields is broken when you type not in English

### ISSUE THREAD

**Issue by yurijmi** [r888888888/danbooru#2588]
If you type something in eg. Russian into any DText field (comments or wiki pages for example) the page where parser is being called completely brakes. This is due to ruby's notorious bug with encodings. It thinks that English text and punctuation is in ASCII-8bit and everything else is in UTF-8.

Fixed it by adding force_encoding("utf-8") to parser calls in format_text and strip_dtext in application_helper.rb. Works for me, tested with English, Russian and punctuation. Should work for Japanese too.

**Comment by yurijmi** [comment]
Btw, I can pull request my application_helper here, if you think it'll work for you.

**Comment by Type-kun** [comment]
That's rather strange since we already have a lot of Japanese in wiki pages, and it works just fine. Editing http://danbooru.donmai.us/wiki_pages/48691 with both Japanese and Russian in the body doesn't result in any error. On testbooru, though, yes, there's an issue, very similar to #2586.  @r888888888 switched to custom precompiled DText parser just recently to make things faster; I presume it's still buggy.

**Comment by yurijmi** [comment]
@Type-kun maybe it's due to different server configuration or DText version difference. And I agree, forcing encoding is a bad solution, but it works for me fine currently.

**Comment by yurijmi** [comment]
#2586 has exactly the same error message, just as here.

**Comment by yurijmi** [comment]
Oh, and this also occurs in flags. Though, it's not affected by parse_dtext and was fixed by forcing encoding in other place.

Screenshot of a friend of mine:
![img_2016-03-30 19 48 50](https://cloud.githubusercontent.com/assets/785492/14150216/09b19be4-f6b9-11e5-963c-4349d9143c9b.jpg)

**Comment by r888888888** [comment]
You can lock your deployment to tag 2.101.0 until these issues are fixed.

**Comment by yurijmi** [comment]
@r888888888 not really need to. Fixed it by using force_encode. But you should probably fix that issue with a better solution. Thanks anyway.

**Comment by r888888888** [comment]
should be fixed in master
