### ISSUE TITLE
Bulk update missed some posts

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2591]
After the execution of http://danbooru.donmai.us/bulk_update_requests?search[id]=630 there were some posts left with un-updated tags:

http://danbooru.donmai.us/posts/1691087
http://danbooru.donmai.us/posts/1704439
http://danbooru.donmai.us/posts/2103620
http://danbooru.donmai.us/posts/2116678
http://danbooru.donmai.us/posts/1960909

There's a similarity between those posts: they have fallen under multiple update requests from that batch. It looks like a concurrency issue, similar to #2171 - since post update is non-blocking, and update is done based on initial state of the row, if multiple workers updated a post at the same time then there's a chance for some changes to be lost.

**Comment by Type-kun** [comment]
Perhaps it would be better to create a separate queue for mass updates, aliases and implications, and have a single worker for that queue? It's not a task that needs concurrent execution anyway, but it still would be delayed.

**Comment by r888888888** [comment]
Has thsi happened recently?

**Comment by Type-kun** [comment]
Didn't really have a chance to test, updates are rare, overlapping updates are even more so. Will probably need an artificial test case on testbooru. It had bunch of posts before wipeout, can you batch-upload 100 or 200 random posts from danbooru or from some other source like those random gray rectangles?

**Comment by r888888888** [comment]
Well my impression is it only happens on massive sized databases with a lot of concurrent traffic, so uploading that many to Testbooru wouldn't be an accurate simulation.

**Comment by Type-kun** [comment]
I guess we can close it for now and reopen if that happens again.
