### ISSUE TITLE
IQDB index stays the same after expunge

### ISSUE THREAD

**Issue by yurijmi** [r888888888/danbooru#2594]
When you expunge a post it's not being removed from IQDB index despite that this functional is written in code.

The problem is in ```remove_iqdb_async```:
```ruby
File.exists?(preview_file_path)
```
This is being called after the file was deleted, so the code after this line never runs.

Fixed by #2595

**Comment by r888888888** [comment]
fixed in 27f53fa5db015ca47680e1dda26ad1ef04b27e73
