### ISSUE TITLE
Request: Upload URL correction (Wordpress)

### ISSUE THREAD

**Issue by SciFiz** [r888888888/danbooru#2596]
[Re: Danbooru post 2350300]
Image urls with _wordpress.com_ or _/wp-content/_ in them should be stripped of php data. 
I don't know if the default state of WP actually has any use of the data, as it usually uses a different resize method, but in the case of sites using the jetpack/photon plugin, the data will cause a resized image to be retrieved.
If a site does use the plugin(s) then _jetpack_css-css_ appears in the stylesheet list, and _photon.js_ in the scripts near the end of the source.

Example: http://i0.wp.com/www.SITE.DOMAIN/ifwp/wp-content/uploads/YYYY/MM/ImageFile.png?resize=420%2C300 
I've not encountered any other than i0, but users of the plugin have seen other values.

The default resize method for the WP platform is the good old tried and tested, _../ImageFile-123x456.png_

**Comment by r888888888** [comment]
I'm a l little confused by what you want me to do.

In the post you reference the original source seems to be https://i0.wp.com/sinnergate.com/wp-content/uploads/2016/04/1.png

What should this be transformed to to get the correct (large sized) image?
