### ISSUE TITLE
API sometimes returns empty (json: [ ]) (xml: <posts type="array"/>) 

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2597]
API returns empty a lot for no reason I could find; example api search:

http://atfbooru.ninja/posts.xml?limit=1&tags=order:random+yakumo_chen+yakumo_ran+yuri

it returns `<posts type="array">` and nothing else.and with json it returns `[ ]`

**Comment by r888888888** [comment]
You probably need to authenticate it the call.

**Comment by Iratu** [comment]
Even with full api authentication it still has empty returns.

**Comment by Iratu** [comment]
So after pressing random for a while on a search I got this error: http://pastebin.com/sJD3bPWJ
I did the search with only one tag `yakumo_chen`.

For some reason it thinks there are more images with those tags then there actually are? (not sure)

**Comment by Type-kun** [comment]
>For some reason it thinks there are more images with those tags then there actually are? (not sure)

"Count" queries might time out in your environment. When that happens, a default value is supplied, which is 1000000 currently, IIRC. Perhaps your DB is slow, or cache isn't working for some reason.

**Comment by Iratu** [comment]
How can I check if my cache is working and can I wipe it in case it has had errors caching stuff?

most files in the */shared/tmp/cache/... folder have the following text in the (with some small changes of course)

```
o: ActiveSupport::Cache::Entry:
@valueI"          
:ET:@created_atf1459509789.85272:@expires_in0
```
and nothing else.
