### ISSUE TITLE
[DText] Allow headers to have ID attributes

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2598]
When dealing with large wiki/help pages, there are some cases when it's necessary to make a link to a specific part of it. This can be done using fragment identifiers in an URL - `http://our.wiki/page#fragment`, but we'll need to specify fragments, either with attribute ` id="fragment" ` or `<a name="fragment">...</a>`. 

Since it's usually only necessary to give links to certain sections of documents, it would suffice to allow users to specify `id` attributes for headers, for example using `h4[section_id]. header text` to create `<h4 id="section_id">header text</h4>`

This will come handy in case we decide to put a reminder on the upload page for users not to upload their own art. See http://danbooru.donmai.us/forum_topics/12829 for ongoing discussion.

**Comment by r888888888** [comment]
This has been added to the dtext gem. The syntax is:

```
h1#id-name. header
```

**Comment by Type-kun** [comment]
I presume it wasn't deployed yet?

http://testbooru.donmai.us/wiki_pages/7

**Comment by Type-kun** [comment]
Oh, wikis don't use ragel yet. I'll add the fix to old parser.
