### ISSUE TITLE
Nginx Error: unknown "invalid_referer" variable

### ISSUE THREAD

**Issue by cglmrfreeman** [r888888888/danbooru#2603]
After banging my head for many hours just to get `bundle exec cap development deploy` working without any errors, nginx refuses to start due to this unknown variable.

The variable is defined in, as I should have guessed, `nginx.danbooru.conf`, but it _should_ be a valid variable?

**Comment by Type-kun** [comment]
A string containing `valid_referers` was commented out in https://github.com/r888888888/danbooru/commit/ba65ec3e18c342d17791201b8fd42446deef5ff2 but `$invalid_referer` is still used. It probably wouldn't work without specifying what's a "valid" referrer. 

For a quickfix, either uncomment the `valid_referers` or comment out the `if` block next to it.

**Comment by cglmrfreeman** [comment]
Thank you Type-kun, that did the trick. I'm at least getting a Failbooru page now, which I believe I can investigate from here. If I get stuck again, however, is there any place I should go besides the Issues here on github? I wouldn't want to clutter it with my questions/concerns if the answers are staring at me in the face.

**Comment by r888888888** [comment]
If you restarted the server you need to restart the unicorns unless you've set them up in an init script.

**Comment by cglmrfreeman** [comment]
Thank you for your reply, however my server has now been rendered inoperable due to disk space? I've pinpointed the cause. The server has not been running for more than a day.
```
$ sudo du -hs /var/www/danbooru2/shared/*
237M    /var/www/danbooru2/shared/bundle
12K     /var/www/danbooru2/shared/config
4.0K    /var/www/danbooru2/shared/data
13G     /var/www/danbooru2/shared/log
740K    /var/www/danbooru2/shared/public
8.0K    /var/www/danbooru2/shared/system
3.2M    /var/www/danbooru2/shared/tmp
8.0K    /var/www/danbooru2/shared/vendor
```

**Comment by cglmrfreeman** [comment]
Been a few days, and in other issues, it seems the problem only occurs in higher versions of Ruby. The resolution seems to be just to disable gctools, however after several tries, I am just getting the same error. Any help or am I on my own because I choose to use a higher version of Ruby than the recommended version?
