### ISSUE TITLE
research implications with antecedent tags with no posts

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2604]
It's a bit of a tangent to issue #2593. If you have free time, could you datamine the implications where antecedent tag has zero posts? Those are harmless themselves, but it's possible that they were forgotten when mass updating tags or, less likely, when aliasing - so the implication on target tag is lost.

**Comment by Type-kun** [comment]
I DMailed you instead of creating the issue because it's pretty much impossible to do without querying the database directly or traversing the entire implication list manually.

**Comment by r888888888** [comment]
It's easier for me to remember to do these sorts of things when it's on Github, as long as there's no privacy concerns.

**Comment by r888888888** [comment]
`
gits:sac -> ghost_in_the_shell
negima!? -> mahou_sensei_negima!
ribbon_held_in_mouth -> mouth_hold
artistic_gymnastics -> gymnastics
open_zipper -> zipper
mouth_gag -> gag
genya_arikado -> alucard
theodore_harvey -> golbeza
adrian_fahrenheit_tepes -> alucard
langrisser_i -> langrisser
heroes_of_mana -> seiken_densetsu
gundam_seed_c.e._73_stargazer -> gundam_seed
see-through_dress -> see-through
sheer -> see-through
valkyrie_profile_lenneth -> valkyrie_profile
valkyrie_profile_2_silmeria -> valkyrie_profile
castlevania_the_arcade -> castlevania
gensou_suikoden_vi -> gensou_suikoden
mini_demon_wings -> wings
billiard_ball -> ball
tales_of_phantasia_x -> tales_of_(series)
panther_paws -> paws
onimusha_3:_demon_siege -> onimusha
dead_space_1 -> dead_space
hand_gag -> gagged
tar_21 -> assault_rifle
ar_10 -> battle_rifle
m1_garand-> -> battle_rifle
beretta_model_70 -> handgun
pm_makarov -> handgun
browning_high-power -> handgun
springfield_xd -> handgun
usp_tactical -> handgun
l96 -> sniper_rifle
barret -> anti-materiel_rifle
magpul_fmg-9 -> submachine_gun
l96 -> bolt_action
tar_21 -> bullpup
full_ashtray -> ashtray
robbery -> theft
ichigodaifuku -> ichigo_daifuku
manacles -> cuffs
claymore_mine -> mine_(weapon)
rance_i -> rance_(series)
rance_iii -> rance_(series)
rance_iv -> rance_(series)
gyao -> banned_artist
rabbit_hat -> animal_hat
candy_shop -> shop
mutual_yuri -> yuri
mutual_orgasm -> orgasm
blood-stained_card -> blood_stain
glowing_head -> glowing
glowing_feet -> glowing
striped_underwear -> striped
bioshock_1 -> bioshock
necktie_pull -> necktie
valkyrie_profile_1 -> valkyrie_profile
pirate_flag -> jolly_roger
pia_carrot_e_youkoso! -> pia_carrot_(series)
grabbing_another's_ass -> ass_grab
grabbing_another's_ass -> groping
computer_screw -> screw
tapered_screw -> screw
secretary_bird -> bird
zokuowarimonogatari -> monogatari_(series)
jigzaw_puzzle -> puzzle
adjusting_tie -> adjusting_clothes
lunar:_the_silver_story -> lunar
dog_on_shoulder -> animal_on_shoulder
stg45 -> assault_rifle
type_92_heavy_machine_gun -> heavy_machine_gun
gau-8_avenger -> gatling_gun
qsz_92 -> handgun
mosin-nagat -> rifle
mini-uzi -> submachine_gun
gewehr_41 -> rifle
ruger_mini-14 -> rifle
police_tape -> caution_tape
ak101 -> assault_rifle
yena_xeno -> banned_artist
yakin_jantou -> yakin_byoutou
henry_jekyll_(fate/grand_order) -> berserker_(fate/prototype_fragments)
ipod_mini -> ipod
ipod_classic -> ipod
kabashiromi -> shirakaba
assassin's_creed_syndicate -> assassin's_creed_(series)
natsuki_kazuki_(iceinjure) -> banned_artist
ruffled_dress -> dress
lavender_bowtie -> bowtie
lavender_bowtie -> lavender_bow
mushroom_earrings -> food_themed_earrings
`

**Comment by Type-kun** [comment]
Thanks, created http://danbooru.donmai.us/forum_topics/12870
