### ISSUE TITLE
Searching for tag in post versions

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2606]
Can we get the ability to search for a tag through post versions? It can be necessary sometimes to find out what happened to the nuked tag, for example, and can be handy in general. 

Even more useful would be the ability to actually search for *changes*, as they appear in diffs. That is, search for "+1girl" to find versions that added a `1girl` tag.

I do understand that versions table is huge and unindexed, though. I also understand that searching for changes is impossible currently directly and would require something like a separate column listing these changes, calculated from the previous version. It's might be too costly to include it in the main site, but maybe reportbooru could handle this?

Granted, if this is implemented, it should be only available to builder+ if not mod+.

**Comment by r888888888** [comment]
We don't store the diff.

What could be done is return a list of all posts that have that tag at some point in their history, and possibly for each post show the history of that tag.

This would have to be done on the reporting server so it'd likely be sent to you in a separate message or email.

**Comment by Type-kun** [comment]
Geh, it's actually a duplicate of #1335.
