### ISSUE TITLE
Batch upload strategy for "book mode" pixiv manga

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2608]
Pixiv seems to have a new mode for displaying manga pages, with a reader much like one on comic.pixiv.net, but thankfully with less obsessive protection. It's possible to grab the links to the individual pages, they're embedded into `<script>` elements inside `<head>`, regexp for those should be pretty simple. 

The bad thing is URL is exactly the same for regular manga mode and "book" mode, so it'll be necessary to find some kind of marker inside the page itself.

----

Example:

http://www.pixiv.net/member_illust.php?mode=manga&illust_id=57045668
In the html code, there'll be multiple elements like this (linebreaks added for clarity):

```
<script>
pixiv.context.images[0] = "http:\/\/i1.pixiv.net\/c\/1200x1200\/img-master\/img\/2016\/05\/24\/20\/50\/19\/57045668_p0_master1200.jpg";
pixiv.context.thumbnailImages[0] = "http:\/\/i1.pixiv.net\/c\/128x128\/img-master\/img\/2016\/05\/24\/20\/50\/19\/57045668_p0_square1200.jpg";
pixiv.context.originalImages[0] = "http:\/\/i1.pixiv.net\/img-original\/img\/2016\/05\/24\/20\/50\/19\/57045668_p0.jpg";
</script>
```

We need to find code starting with `pixiv.context.originalImages[NN] = `, then get the text unil next semicolon and remove the unnecessary escaping.

**Comment by r888888888** [comment]
Maybe it's better to just use the Pixiv web api to get this data.

**Comment by Type-kun** [comment]
Perhaps, I'm not familiar with web api. How does one access it?

**Comment by r888888888** [comment]
There's a dedicated wrapper for it here: https://github.com/r888888888/danbooru/blob/master/app/logical/pixiv_api_client.rb

Using it is kinda iffy because it's not officially documented or supported. But it returns a lot of useful data without having to scrape any HTML.

**Comment by r888888888** [comment]
deployed the change to testbooru

**Comment by Type-kun** [comment]
Seems to work just fine for both old and new styles.
