### ISSUE TITLE
BUR is impossible to approve

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2609]
Approving a bulk update request with aliases or implications currently results in the following:
* BUR goes to "queued"
* "BUR Approved" message goes through to the forum and as a notification
* BUR actually remains "Pending"
* All aliases and implications from BUR are created as separate entries and remain "pending"
* Further attempts to approve BUR fail silently without even going to "queued" because aliases/implications already exist as separate pending entries.

Last silent fail is because json approve request fails when trying to message approver:
```
NoMethodError exception raised
undefined method `id' for nil:NilClass
/var/www/danbooru2/releases/20160614192111/app/models/bulk_update_request.rb:62:in `message_approver_on_failure
```

Why it stops midway without actually approving aliases/implications is a mystery to me, though.

**Comment by Type-kun** [comment]
Assuming the changes are deployed to testbooru, it still doesn't work properly. BUR gets approved, but the implications/aliases from it remain in "pending" state. What you tested on production site in topic 7713 was mass update.

**Comment by r888888888** [comment]
I've deployed another fix to testbooru. Can you check if it works now?

**Comment by r888888888** [comment]
I believe this issue is finally fixed now.

**Comment by Type-kun** [comment]
Yes, seems to work fine now.
