### ISSUE TITLE
Question about tag-hiding.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2614]
How can I hide certain tags from unregistered users or for "normal" users, I've looked into the config file but was unable to find it, I probably over-looked it, but after looking at it for a few times I'm just not able to find it.

**Comment by Type-kun** [comment]
You mean, hide posts with certain tags? There's `is_post_restricted?` function in config, I think it should be modified according to your needs. Like `!post.has_tag?("banned_tag|other_banned_tag")` instead of simply returning `false`.
