### ISSUE TITLE
Cookie hardening

### ISSUE THREAD

**Issue by reiyasona** [r888888888/danbooru#2621]
- [ ] **Flag the `_danbooru_session` cookie as `secure` for users who logged in securely.**
Is this related to the following lines in the [**application_controller**](https://github.com/r888888888/danbooru/blob/c400a20b64d941013139b36267014ef4261285e3/app/controllers/application_controller.rb#L160)?

 ```ruby
# before_filter :secure_cookies_check

...

def secure_cookies_check
  if request.ssl?
    Rails.application.config.session_store :cookie_store, :key => '_danbooru_session', :secure => true
  else
    Rails.application.config.session_store :cookie_store, :key => '_danbooru_session', :secure => false
end
```
Reference: issue #1851 

---

- [x] **Flag the `user_name` cookie as `httponly` ([link to source code](https://github.com/r888888888/danbooru/blob/c400a20b64d941013139b36267014ef4261285e3/app/logical/session_creator.rb#L21)).**

 ```ruby
cookies.permanent.signed[:user_name] = {
  :value => user.name,
  :secure => secure
```

**Comment by r888888888** [comment]
I think the issue is if your cookie is signed as secure it wont be valid outside of HTTPS. Which maybe isn't a big deal. Serving binary image data over HTTPS sucks though and adds a burden to the web servers.

**Comment by r888888888** [comment]
Oh this is also an app-level config options so I'm not even sure if it's thread safe.

**Comment by reiyasona** [comment]
As long as the server’s processor supports AES-NI, HTTPS shouldn't cause a huge amount of CPU overhead. The initial handshake is the most stressful part for the server. Therefore you should enable TLS Session Resumption (see #2611). However, once the handshake is done, a very fast symmetric encryption (AES) is used, so the overhead there is minimal in comparison.

For further reading: https://www.keycdn.com/blog/https-performance-overhead/
Fun non scientific comparison (HTTPS + H2 versus HTTP): https://www.httpvshttps.com/

**Comment by r888888888** [comment]
I believe passing in the secure flag when the cookies are created is sufficient so I consider this ticket done for now.
