### ISSUE TITLE
Make commentary editing more intuitive

### ISSUE THREAD

**Issue by reiyasona** [r888888888/danbooru#2623]
Feature request by [BrokenEagle98](https://danbooru.donmai.us/users/23799) ([topic #12990](https://danbooru.donmai.us/forum_topics/12990)):

> 
> Anytime I fully translate a commentary, I also have to edit the tags to remove [commentary request](https://danbooru.donmai.us/wiki_pages/show_or_new?title=commentary_request) and add in [commentary](https://danbooru.donmai.us/wiki_pages/show_or_new?title=commentary). Also, whenever I add a commentary, I have to then go in and manually edit the tags to add either/both commentary request or/and commentary.
> 
> In contrast, when using the translation mode, it gives you a couple of checkboxes and a submit button that does all of the tagging for you.
> 
> When pulling up the "Add artist commentary" dialogue box, it'd be nice to have a couple of checkboxes to select either commentary and/or commentary request (since if it's only partially translated, you still want to have the commentary request tag on it).

**Comment by Type-kun** [comment]
I'm still a bit puzzled - if we're going with checkboxes, why change them to "add"/"remove"? Why not have them checked if the tag is present, and unchecked if it's absent? I'm just not sure how well current solution will work, UI-wise.

**Comment by r888888888** [comment]
That's a good idea but I'm not sure how to make the labels intuitive. "Include the following tags"?

**Comment by Type-kun** [comment]
I'm not the best person around to suggest natural-sounding phrases...

"Tag the post with"? "Set/unset tags"? "Post tags"? Simply "tags"? "Mark as", like in translation mode? Or maybe no label at all, it seems intuitive enough to me, as-is.

**Comment by r888888888** [comment]
Thinking about it I think I prefer the current way. If enough people complain I can revisit this.

**Comment by Type-kun** [comment]
Checkboxes don't work properly (tags are not actually added/removed), and commentary changes are not reflected immediately, nor is page reloaded upon submit.

**Comment by reiyasona** [comment]
[BrokenEagle98 said](https://danbooru.donmai.us/forum_posts/117645):

> Confirmed the behavior of the commentary checkboxes as noted by Moonspeaker above...
> 
> * Similar behavior on different browsers (Firefox 47.0 & Chrome 51.0, on Windows 7)
> 
> * The add tag checkboxes work with any and all other add tag checkboxes combinations. Ex:
>  * Add commentary & Add commentary_check
>  * Add commentary & Add commentary_request
>  * Add commentary & Add commentary_check & Add commentary_request
> 
> * The inclusion of any remove tag checkbox causes the behavior Moonspeaker noted to happen. Ex:
>  * Add commentary & Remove commentary_request
>  * Add commentary & Remove commentary_request & Add commentary_check
>  * Remove commentary & Add commentary_check
> 
> So it appears as if there is something going on with the remove checkboxes that prevents the changes from going through.

**Comment by Type-kun** [comment]
@r888888888 the code used `commentary_check` instead of `check_commentary`. I've made relevant commits, can you deploy it to production?

**Comment by r888888888** [comment]
Done.
