### ISSUE TITLE
NoMethodError Exception after uploading image

### ISSUE THREAD

**Issue by hennign** [r888888888/danbooru#2625]
I created a new Danbooru server, created the first user, then uploaded a jpg (2815x1119, 319KB). I was transferred to 'test.org/posts/1':
```
NoMethodError exception raised
undefined method `+' for nil:NilClass
/var/www/danbooru2/releases/20160716105506/app/views/posts/partials/show/_options.html.erb:6:in `_app_views_posts_partials_show__options_html_erb___973088241388959322_69906982368700'
```
([full error message](http://pastebin.com/MmAPMvfm))

In what I assume is a related error, when I try to go to my account I get a slightly different NoMethodError (test.org/users/1):
```
NoMethodError exception raised
undefined method `tr' for nil:NilClass
/var/www/danbooru2/releases/20160716105506/app/models/post.rb:923:in `uploader_name'
/var/www/danbooru2/releases/20160716105506/app/presenters/post_presenter.rb:74:in `data_attributes'
/var/www/danbooru2/releases/20160716105506/app/presenters/post_presenter.rb:24:in `preview'
```
([full error message](http://pastebin.com/rzjD4Rps))

I really have no clue what's going on here. Any help is appreciated.

If it matters, I installed on a Vagrant box, debian/jessie64, using the INSTALL.debian script. Everything seemed to work normally until I uploaded an image. The jpg was uploaded from my computer, but here is an imgur [link](https://imgur.com/czxSGJ2) to it. I marked it as safe, and gave it a single tag: 'LiS'.

**Comment by hennign** [comment]
OK. Finally tracked this down at least partially. Basically the connection to the memcache server was failing. Not sure why, but I assume there were some changes made between debian/jessie64 (version 8) and debian/wheezy64 (version 7). I also might have needed the ports 9000 and/or 11211 forwarded. I assume not (I forwarded them as part of a different debugging step), but I haven't tried with them disabled.

**Comment by hennign** [comment]
Confirmed, it seems that replacing 'localhost' with '127.0.0.1' in config/danbooru_default_config.rb:93
```
    # List of memcached servers
    def memcached_servers
      %w(127.0.0.1:11211)
    end
```
was the correct solution. debian/jessie64 also works fine with this change.

**Comment by Shadoukun** [comment]
I followed your solution of changing the address of the memcached server in config/danbooru_default_config.rb:93, but the problem still persists for me.

**Comment by hennign** [comment]
Did you try changing it in '/var/www/danbooru2/current/config/danbooru_default_config.rb' and then restarting the server? I'm still unclear on when the server needs to be restarted versus when it will pull changes live. I think the command to restart is 'bundle exec cap unicorn:restart'.

One of the things I noticed pretty quickly when I started working with this project is that changes made in the install repo (~/danbooru) aren't propagated since the deployment pulls from the github repo. I ended up forking the repo and then doing a find replace to change '/r888888888/danbooru/' to '/hennign/danbooru/', so I could commit to my repo and be sure my changes went live.

**Comment by Shadoukun** [comment]
No luck. tried 'bundle exec cap development unicorn:restart' too.  Same issue in the OP. :( 

Tried setting it up several times this way, same result. running Debian Jessie. (It is in a docker container, I don't know if that has any bearing on the problem)

**Comment by hennign** [comment]
Hmm. Is your error exactly the same as mine?
Can you post your step by step installation process and the exact errors (if different at all from mine).
Have you checked with systemctl status memcache(d?) that memcache daemon is running and used telnet 127.0.0.1 11211 to check that you can connect to it. I'm not sure how to do that with a docker container.

As far as possible problems with using docker, my only concern would be that there is a Dockerfile in the root of the repo. I think this is just used by the installation script, but if it is part of the deployment stack, then sometimes issues arise with nested virtual machines. I'm new to rails and not super familiar with Docker. I'm fairly sure this isn't a problem, just what pops to mind.

If you can, try vagrant. It's fairly easy to use and if it works then you'll know the problem is with Docker.
1. Go to www.vagrantup.com. download and install vagrant.
2. Go to desired install folder. Type vagrant box add debian/jessie64. This will take 20-50 minutes usually.
3. Type vagrant init debian/jessie64.
4. Edit Vagrantfile to forward port 80 on guest to 80 on host. Vagrantfile explains how inside with comments and example. You may want to forward ports 9000 and 11211 as well. I'm fairly certain they aren't needed, but I haven't tested with out them forwarded.
5. Type vagrant up.
6. Once booted you can ssh in using vagrant@127.0.0.1:2222 password 'vagrant'. Vagrant account has sudoer access without password.
7. Install and deploy Danbooru.
8. ????
9. Profit. 😁

I apologize for any typos. Posting from tablet.

**Comment by Shadoukun** [comment]
Nevermind. It was actually my mistake. I had made sure postgres was set up correctly and had run in to this error. After that, in trying to figure out memcached with your suggestions, I forgot to do that again. Apparently if pg_hba.conf is missing/unreadable, it throws the same exact error. 

So, ensuring that pg_hba.conf is in the _proper_ directory for my postgresql installation, along with your suggestions made it work now.

Thanks!

**Comment by hennign** [comment]
No problem. Glad you could get it working.
