### ISSUE TITLE
Revert support for -- tag boundary in nginx config

### ISSUE THREAD

**Issue by Iwasawafag** [r888888888/danbooru#2627]
Around May 25-31 changes from ba65ec3e18c342d1779 went live on the main website and since then links to "sample" thumbnail and original image both was printed to the pages with tag string prepended to it, wrapped in pair of dashes. 

Nearly a month later, on July 22 this delimiter was changed to `__` (commit 681fc62f0667707) and allthough there was no changes to `nginx.danbooru.conf` introduced with this commit, old urls with `--` in it suddenly stopped working. I assume it was only changed on production server somehow.

Now why I think this is a big deal. 

Some services, like Discord, do link embedding. Links from Danbooru also getting embedded there better than links from any other image board alike, featuring both - image tags and image itself. Because of this some people in some communities were just posting links to the pages from Danbooru, letting messenger handle the rest. And while Discord does serve images from their CDN for some reason they also check if  image is still present by original url. Or maybe copies on their CDN expired and once I scrolled to old posts it went to original url in attempt to re-download it. 

But since now all those links return 404 - *any links to danbooru that were posted during that month now getting embedded without an image*. Essentially what used to look like this

![](https://cdn.discordapp.com/attachments/182350194401214465/205010404085202944/unknown.png)

started looking like this

![](https://cdn.discordapp.com/attachments/182350194401214465/205010136790466565/unknown.png)

Could `--` tag boundary still be supported as well as `__` by whatever does file resolving (probably nginx)?

Thanks

**Comment by r888888888** [comment]
wont fix
