### ISSUE TITLE
Search for status:active at tag_aliases and tag_implications

### ISSUE THREAD

**Issue by ProximaNova** [r888888888/danbooru#2633]
I can't search for status:active or status:pending at both of the following URLs:
- http://danbooru.donmai.us/tag_aliases
- http://danbooru.donmai.us/tag_implications

Edit 1:
That ability may not be necessary because pending is listed before active at the above URLs.\
Can you add a link to search for the uniqueness of an image? In Options under the link "Find similar" make a link to search all tags on the image you are viewing to see if it is unique relative to other images. I polyfilled the "uniqueness" link at my Gelbooru improver userscript: https://github.com/ProximaNova/Booru-mass-editor/blob/0121259c508b8ff87fb0713bbd37ad80cf2bd5a3/Booru-mass-editor.user.js#L97 @ lines 97 to 99.

Edit 2:
These are duplicate implications:
http://danbooru.donmai.us/tag_implications/368
http://danbooru.donmai.us/tag_implications/1483

**Comment by evazion** [comment]
> Can you add a link to search for the uniqueness of an image? In Options under the link "Find similar" make a link to search all tags on the image you are viewing to see if it is unique relative to other images.

I don't understand what the purpose of this is, but anyway, this is a separate issue.

> These are duplicate implications:
> http://danbooru.donmai.us/tag_implications/368
> http://danbooru.donmai.us/tag_implications/1483

Separate issue. A full list is at https://danbooru.donmai.us/forum_topics/12870?page=2#forum_post_131375.
