### ISSUE TITLE
undefined method `scan' for nil:NilClass on popular search

### ISSUE THREAD

**Issue by kdoshere** [r888888888/danbooru#2635]
Hi

well, as the title says
after enabling report_server for  popular search..etc
I get the next error

`NoMethodError exception raised

    undefined method `scan' for nil:NilClass
    /var/www/danbooru2/releases/20160810230635/app/logical/popular_search_service.rb:11:in `each_search'
    /var/www/danbooru2/releases/20160810230635/app/views/explore/posts/searches.html.erb:13:in `_app_views_explore_posts_searches_html_erb__264851394230965638_70123110143340'`

[full log](http://pastebin.com/F7vYAiC2)

ty for your time~

**Comment by r888888888** [comment]
You need to setup Reportbooru in order for this to work. Setting that up is somewhat complicated so I can't offer any help.
