### ISSUE TITLE
API Date Format Bug

### ISSUE THREAD

**Issue by tjg1** [r888888888/danbooru#2636]
I'm the lead developer of [Nori](https://github.com/tjg1/nori) and [Norilib](https://github.com/tjg1/norilib), the free and open source *booru client and API library for Android.

One of my users has reported a very strange bug with the way dates are formatted by your API.

The dates in your API are usually formatted like this: `2015-05-20T23:09:09-04:00`. Norilib uses Java's [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) to parse them with the following pattern: `yyyy-MM-dd'T'HH:mm:ssZ`.

What the user reported is that while he is logged into his Platinum account, the dates returned by your API look like this: `2005-05-24T03:35:31Z`. There is a literal `Z` character instead of the timezone offset, causing a DateParseException in Norilib. This happens in Nori and in his web browsers (firefox/chromium), but only while he is logged into his account. He reported that it doesn't happen with a newly created basic account.

I have no way of testing this, as I do not have a premium account, but it does seem like a problem on your side. I doubt the user's ISP is doing something funny, as Nori defaults to TLS for Danbooru.

**Comment by r888888888** [comment]
I'm not seeing this. Can you confirm what time zone the user you're testing with is using? It's an option in their user settings.

**Comment by tjg1** [comment]
I just reproduced this by setting my timezone to UTC.

**Comment by reiyasona** [comment]
Yes, I have set (GMT+00:00) UTC.

"00:00" seems to be converted to "Z". : /

**Comment by r888888888** [comment]
Yeah unfortunately that's just the default behavior of the Ruby library. I'm looking for ways to override it.

**Comment by r888888888** [comment]
Is there any way you can parse it as ISO8601? The Z component is defined in the spec so the output is technically sound.

**Comment by tjg1** [comment]
Android uses Java 6 version of the SimpleDateFormat class, which has no support for ISO8601. I will probably end up using String.replace("Z", "+0000").

**Comment by r888888888** [comment]
This has some ideas: http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date

Not all of it is applicable to Android but at the least there are code samples you could adapt.

**Comment by tjg1** [comment]
Fixed https://github.com/tjg1/norilib/commit/c804249f8b2c1f577ceb8185f4edde70171ef453.

Now how about that free premium account to use for testing I emailed you about? 😜

**Comment by tjg1** [comment]
I guess no response means no. Oh well, @reiyasona promised to buy me one.

**Comment by reiyasona** [comment]
@tjg1 [done](https://safebooru.donmai.us/users/491223)
