### ISSUE TITLE
Change some API representations

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2640]
There are some inconsistencies between HTML and API representations.

Remove:
- [ ] `creator_id` from post flags for users below moderator
- [ ] `bit_prefs` from user

Add:

- [ ]  `can_upload_free` and `can_approve_posts` to user

**Comment by BrokenEagle** [comment]
I see that the "bit_prefs" field has been removed from the API representation, but there is nothing yet that informs on user permissions like Type-kun mentioned, i.e. "can_upload_free" and "can_approve_posts".
