### ISSUE TITLE
Displaying supervoter privilege

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2641]
There's currently no way to see if user is a supervoter aside from performing API request and decoding bit prefs. Once these prefs are not displayed anymore (issue #2640), I'm pretty sure it would be completely impossible to see whether the user is supervoter or not.

Is that intended? If not, the supervoter pref should be displayed in the profile, API and as a CSS class, like approval and free upload privileges are.

**Comment by r888888888** [comment]
I'm not sure how useful this is without search capabilities. If what's needed is a centralized listing of all super voters then reopen this and I can add that.
