### ISSUE TITLE
Add privileges to user search

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2644]
After thinking about last part of #2641, I realized there's no way to list all users with any permission, not just supervoters. It makes sense to include permissions in [user search](https://danbooru.donmai.us/users/search) form. Postgres can handle bitwise operations if permission integer is [cast to bit string](https://www.postgresql.org/docs/9.5/static/functions-bitstring.html), though it looks like built-in indexes don't help with them. Knowing the bit count (or at least the upper bound) is required for that, but it's as simple as getting size of `BOOLEAN_ATTRIBUTES` in user model. Perhaps it's even possible to pack this into ActiveRecord extension along with `has_bit_flags`, but I'm not well versed in Ruby enough to know how to do that.

As far as UI goes, I see two options. 
1. Create a checkbox for every permission. Checking it would search only for users having the permission, un-checking would ignore the permission.
2. Create a select element for every permission, each with three options - blank, set, not set. This would allow to explicitly search for users not having the permission, also would be a bit more intuitive, but requires a bit more work, checking both for set and unset bits.

Also, since I (to my shame) had to google how to perform bit checks, here's a reminder:
Checking if bits B are set in bitstring A: `A & B == B`
Checking if bits B are unset in bitstring A: `A & B == 0`

**Comment by r888888888** [comment]
The users table is small enough and this type of query infrequent enough that the sequential scan is acceptable. Worst case, the query can be offloaded to the replica database.

**Comment by Type-kun** [comment]
I expanded `search` method in user model to support `can_approve_posts`, `can_upload_free` , `is_super_voter` parameters as `true` or `false`.  It's easy to add other binary options when necessary, too. Seems to work fine, but I'm concerned about performance, so maybe deploy it without changing search form first?

**Comment by Type-kun** [comment]
Hmm. First search with new parameters executed about 15 seconds but didn't fail I guess that's about 8+8 seconds on count and search itself - lucky considering the timeout is 9. Subsequent searches executed within 3 seconds because if disc cache. Looks like it's impossible to easily speed this up (aside from writing GiST index in C from scratch - I'm certainly not up to that now; or creating a FBI for every interesting bit and checking them separately, which seems plain awful). It should do well serving as additional search parameter, at least, so I guess it's safe to add parameters to the form. I'll go with `<select>` elements, since I added possibility to exclude permissions too.

**Comment by r888888888** [comment]
Yeah no good way to index that.

I would suggest instead of making these search parameters, just create separate pages that list them and offload the query to the replica.

**Comment by Type-kun** [comment]
Can we keep both? They might time-out on their own, but are still useful for searching approvers of certain level, for example. I'd want to add `is_banned` to the mix, too.

Also, looking it up further, it IS possible to do indexable version, but not with bit string. Instead, number array containing set bit positions should be used. If bit positions will be counted right-to-left, it wouldn't even require any re-indexing when new options are added. GIN index [works with integer arrays](https://www.postgresql.org/docs/9.4/static/gin-builtin-opclasses.html), and both use cases are covered by [array operators](https://www.postgresql.org/docs/current/static/functions-array.html): checking for set bits is `db_array @> search_array`, and checking for unset bits is `not db_array && search_array`. Required steps are:

* Create a function that takes `bigint` and produces `integer[]` containing bits set in said bigint, counting from rigthmost - that is, `41` which is `101001` in binary, would result in `[0, 3, 5]`. 
* Create an expression-based GIN index on said function. Don't forget to include [_int4_ops](https://www.postgresql.org/docs/9.4/static/gin-builtin-opclasses.html) - I'm not sure how this is done yet, but it's probably the same as other ops.
* Amend ruby code to use said function, `@>` and `not ... &&` as described above. The part of code where the string to check is built should be changed to build arrays instead, with `bits_included << attr_idx`. Passing array to where is done [like this](http://edgeguides.rubyonrails.org/active_record_postgresql.html#array): `where('... @> ARRAY[?]::integer[]`', bits_included)`.

It's actually pretty simple and should work well. Perhaps use `smallint[]` instead of `integer[]`. Hardest part is postgresql function but it should not be too hard to write, I'll look into it once I get home.

**Comment by Type-kun** [comment]
Well, it turned out to be pretty easy indeed. Here's the function: 
```postgresql
CREATE OR REPLACE FUNCTION bit_pos_array(x bigint)
  RETURNS integer[] AS
$BODY$
    select array_agg(i) from
	generate_series(0, floor(log(2, x))::integer) i
	where (x & (1::bigint << i)) > 0;
$BODY$
  LANGUAGE sql
  IMMUTABLE
  COST 100;
```
and index 
```
CREATE INDEX index_users_on_bit_prefs_array
  ON users
  USING gin
  (bit_pos_array(bit_prefs) _int4_ops);
```
Index is used and should work fine when only a handful of users have the bit set - our use case matches this perfectly. I don't know how to properly create rails DB migrations yet, though.
