### ISSUE TITLE
Create google bigquery table for posts

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2645]
To be used for reporting. Should rely on the pubsub for updates. Probably hosted on reportbooru.

**Comment by evazion** [comment]
Found someone who already set this up on the forum: http://danbooru.donmai.us/forum_topics/12774.

Post versions would be incredibly useful too. It'd finally give us a way to search post changes by tag.

**Comment by Type-kun** [comment]
>It'd finally give us a way to search post changes by tag.

We already have it in https://danbooru.donmai.us/reports/post_versions - though I think it's only available to mod+ as of now. See also #1335

**Comment by evazion** [comment]
Well, that was an example, that's not the only thing I want it for. A public BigQuery table would basically let anyone do realtime SQL queries on a live copy of the database. That's invaluable, it'd allow people to do all kinds of reporting/searching without having to build it in to the site.

The other reason I want it is so I can get a full database dump without scraping the API and without having to bug albert. BigQuery would let anyone get a full, up-to-date database dump at any time.

**Comment by r888888888** [comment]
I'm realizing BigQuery isn't the best service for this because it doesn't support updates or deletes and posts is a table that is constantly in flux. Cloud SQL is an option but I have no doubt the queries are probably slower. BigTable is single key and probably not great for searching. Both are more expensive.

**Comment by evazion** [comment]
Allynay on the forum just does nightly updates with his table. I guess he does a full wipe/reimport instead of trying to update it continuously? Not how BigQuery is intended to be used, I don't think, but it's working well enough for me. For reporting it doesn't matter if the data is a day old.
