### ISSUE TITLE
Make Artist ID and Wiki ID usable in queries

### ISSUE THREAD

**Issue by reiyasona** [r888888888/danbooru#2646]
Artist ID: `artid:<id>`
Wiki ID: `wikiid:<id>`

Example:
`artid:8683 wikiid:4817` = [redjuice skirt](https://danbooru.donmai.us/posts?tags=redjuice+skirt) (redjuice also has Wiki ID [6092](https://danbooru.donmai.us/wiki_pages/6092))

**Comment by Type-kun** [comment]
Out of curiosity, where would that be useful?

**Comment by reiyasona** [comment]
It would be useful in combination with tag subscriptions and saved searches to guarantee consistent results. A tag's notation (e.g. an artist's name) can change over time. If the creation of an alias is left out or forgotten, old queries won't hit their target anymore.

**Comment by BrokenEagle** [comment]
In most cases that would hold true.  However sometimes artist entries and wiki entries get merged because of duplicates, and there's no guarantee of which one will get deleted in the merging, so the ID numbers could also get changed. 

 I'm not sure there's a way to guarantee that an artist or wiki would always be tied to a certain ID...?

**Comment by reiyasona** [comment]
**Merge scenario:**

Artist IDs and Wiki IDs don't get reused, right? If two tags are getting merged, we can simply set a pointer.

`ID 00001 and ID 00002 -> merge -> set pointer to superior ID`

**Purge scenario:**

If a tag was completely deleted without the creation of an alias, there should be some kind of warning for everyone who is using this tag in a subscription or saved search.

**Note:**
-  All artist tags have an Artist ID.
-  All tags (also artist tags) will only have a Wiki ID if a wiki entry is created.

**Comment by evazion** [comment]
I think the real problem people is moving artists without requesting aliases. People shouldn't be forced to use `artid:1234` in their subscriptions/saved searches to protect themselves from tag moves. Instead we should encourage people to move tags the right way: request aliases to move large tags and mass updates for small or ambiguous tags. This would require fixing #2251 first though.

**Comment by reiyasona** [comment]
Okay, I understand. It's better to fix the real problem than to keep working around it.
