### ISSUE TITLE
@mentions shouldn't link to Danbooru users in artist commentaries

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2654]
http://danbooru.donmai.us/posts/2474586
http://danbooru.donmai.us/artist_commentaries?commit=Search&search%5Btext_matches%5D=%40&utf8=%E2%9C%93

Commentaries from Twitter often use @mentions but they're referring to Twitter users, not Danbooru people.

I think comments and forum posts are the only places where @mention syntax really makes sense. @mentions anywhere else - commentaries, notes, wiki entries, wherever else - probably aren't Danbooru users.

**Comment by Type-kun** [comment]
Hmm. Selectively enabling mentions would require another parameter to `dtext.parse`. Though maybe it can be tied to `Mentionable` class somehow? I can make the changes to the old parser, but ragel is moonspeak for me as of now, so it's up to @r888888888 .

Anyway, are there any other places where @ syntax would make sense? Comments and forum, yes, but I also can see dmails and user feedback at least.

**Comment by evazion** [comment]
> Hmm. Selectively enabling mentions would require another parameter to dtext.parse.

Yeah, that's what I was thinking. I don't fully understand the ragel parser either, but it handles options for `dtext.parse` [here](https://github.com/r888888888/dtext_rb/blob/master/ext/dtext/dtext.rl#L1405-L1416), a flag could probably be added there and checked in the mention action [here](https://github.com/r888888888/dtext_rb/blob/master/ext/dtext/dtext.rl#L368-L387), similar to how `f_inline` is handled for headers.

> Anyway, are there any other places where @ syntax would make sense? Comments and forum, yes, but I also can see dmails and user feedback at least.

Hmm, thinking about it more, commentaries, notes and perhaps the wiki are probably the only places where it doesn't make sense. Everywhere else is probably fine.
