### ISSUE TITLE
Email addresses misparsed as @mentions

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2655]
`foo@gmail.com` is interpreted as a @mention for `@gmail.com`.

Examples in the wild:

http://danbooru.donmai.us/artist_commentaries?commit=Search&search%5Btext_matches%5D=%40gmail.com&utf8=%E2%9C%93

**Comment by Type-kun** [comment]
Just a reference. According to RFC, the following symbols can be used as the "name" part in the email: ```A-z0-9!#$%&'*+-/=?^_`{|}~```. The name part itself is `([:class:].)*[:class:]` where `[:class:]` are the symbols specified. 

For our purposes it'll be enough to check whether the symbol before `@` is within `[:class:]`. I can code the part for javascript, but it's pointless without fixing dtext gem first, so calling @r888888888 here.

**Comment by r888888888** [comment]
fixed in the dtext gem

**Comment by Type-kun** [comment]
Wait, if I read this correctly, @ will only be parsed as mention when there's either a space or a newline before it? Will that be enough? Also, reopening this as a reminder to myself to fix old parser, too.

**Comment by Type-kun** [comment]
Welp, disregard that, old parser already follows the same rule with `MENTION_REGEXP = /(?<=^| )@\S+/`. Did a quickfix to make JS autocomplete follow that rule, too.
