### ISSUE TITLE
Make navbar and subnavbars extended and configurable via css

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2656]
I sometimes see requests in the forums to add or remove items from menu or subnavbar. Obviously, simply pushing everything available in there is impossible, especially for small screen resolution. However, since users have control over CSS, navbars can be make configurable without much hassle.

Steps to do that:
1. push everything available into navbar and subnavbars
2. assign unique css class or id to every `<li>` item and `<menu>` item
3. add site-wide css rules with `display:none` to newly added items

This way, the UI remains visually unchanged, but users gain complete control over what they see in the menu.

**Comment by evazion** [comment]
+1, more CSS classes always help.

re: fitting it all on small screens, the menu is already collapsed at <660px width (commit: a6233f297eca8c17322158b3e788587b365e7980). Something similar could be done to hide these new entries only if the screen is too small, and not hide them if the screen is big enough.
