### ISSUE TITLE
Support approver:any and approver:none metatags

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2660]
Requested by users to keep track of unrestricted uploads. Basically, `approver_id is not null` and `approver_id is null`, respectively. It's unindexed, but it wouldn't perform any worse than `approver:type-kun`, for instance.

**Comment by BrokenEagle** [comment]
For this, does anything need to be done about users [None](http://danbooru.donmai.us/users/11539) and [Any](http://danbooru.donmai.us/users/292333)...?

**Comment by evazion** [comment]
`status:approved` and `-status:approved` might be an alternative. But they're inactive users, I don't think it's a problem. I suggested `approver:any` / `approver:none` for symmetry with `parent:any` / `child:any` / `pool:any`.

**Comment by Type-kun** [comment]
Well, we could either simply ignore those two users, or allow searching by user ID as well. Latter approach begets more problems: for example, if we support `approver:337059` to search for my approvals, then it will clash with potential user literally named 337059 - number-only usernames aren't prohibited. Switching to `approver:#337059` or `approver:[337059]` suffers from the same problem.

**Comment by r888888888** [comment]
no reason to support this on -approver, the double negative just makes it confusing
