### ISSUE TITLE
Testbooru doesn't display full-size files

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2661]
http://testbooru.donmai.us/data/__danboo__27bc7d4bdf2b9cb84d84b367a2fee9fd.jpg is unavailable

http://testbooru.donmai.us/data/27bc7d4bdf2b9cb84d84b367a2fee9fd.jpg opens fine.

I guess testbooru nginx config wasn't fixed after #2612

**Comment by r888888888** [comment]
fixed
