### ISSUE TITLE
Handle source: metatag when editing posts

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2664]
Currently every metatag except `source:` is supported when editing a post. This is needed for adding sources via tag scripting as described here: http://danbooru.donmai.us/forum_topics/9127?page=131#forum_post_118649.

(Note to self: apply fixes [here](https://github.com/r888888888/danbooru/blob/master/app/models/post.rb#L676) and [here](https://github.com/r888888888/danbooru/blob/master/app/models/post.rb#L741))

**Comment by Type-kun** [comment]
It wouldn't handle spaces properly, though. It's possible to make special exception in Tag.scan_tags, for example extracting `source:"text with spaces here"` first before breaking the rest on whitespace, but then it wouldn't handle double quotes.

**Comment by evazion** [comment]
`source:` doesn't handle spaces properly when searching either. So we already can't handle things like `source:Image board` or `source:*Kantai Collection*`. The best you can do is abuse wildcards: `source:Image*board`, `source:*Kantai*Collection*`.

Also there's no way to search for a literal source of `none` or literal `*` characters. Such posts do exist, although only a small number.

I think the options are:

* Fix Tags.parse_query to allow `source:"*Kantai Collection*"`. But that doesn't look easy.
* URL decode the source string. So to search `*Kantai Collection*` you'd say `source:*Kantai%20Collection*`. But that's not easy to use.
* Only allow URLs in the source. If the source is a doujin or something then put it in a pool instead of putting the title in the source.
* Don't worry about all this, just leave it as is.

**Comment by Type-kun** [comment]
Fixed with the merged PR
