### ISSUE TITLE
nil exception in /artist_versions

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2665]
http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=22356
http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=42677

Nil exception thrown [here](https://github.com/r888888888/danbooru/blob/master/app/models/artist_version.rb#L101). Introduced by 23f4232bd2872aabdb38dcfd913fc8863feb36f1?

**Comment by Type-kun** [comment]
Yes, didn't expect `other_names_array` to return nil instead of empty array. Will fix later today.

Also, somehow, re-submitting artist 42677 caused other names to convert from `nil` to an empty string. I wonder what's going on here.
