### ISSUE TITLE
Test fails because of rails/performance_test_help

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2666]
Attempting to run `bundle exec rake test` to complete full test suite fails with
```
LoadError: cannot load such file -- rails/performance_test_help
```
This is due to test/performance/dtext_test.rb which requires `rails/performance_test_help`. Since rails 4, that helper was moved to rails-perftest gem. Either the gem should be included in the gemfile, or performance test should be dropped since dtext parser is moved to ragel.

**Comment by r888888888** [comment]
Oh the performance tests were not intended to be run.

Just run test:units and test:functionals.

**Comment by Type-kun** [comment]
Oh, seems to run fine now. That aside, running test:functionals gives me a couple of failures. Did I misconfigure something, or is that an actual uncaught regression?

```
  1) Failure:
PoolsControllerTest#test_: The pools controller revert action should revert to a previous version.  [/home/artem/vboxmount/danbooru/test/functional/pools_controller_test.rb:105]:
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: US-ASCII
-"725"
+"725 726"
```

**Comment by r888888888** [comment]
fixed
