### ISSUE TITLE
cap production deploy uses username 'albert' when configured otherwise

### ISSUE THREAD

**Issue by hachi** [r888888888/danbooru#2670]
When I execute:

`bundle exec cap production deploy`

The end error I reach is:

```
SSHKit::Runner::ExecuteError: Exception while executing as danbooru@localhost: bundle exit status: 1
bundle stdout: bundler: failed to load command: unicorn (/home/danbooru/.rbenv/versions/2.1.5/bin/unicorn)
bundle stderr: ArgumentError: can't find user for albert
```

I have removed every reference to the string 'albert' from my working tree, develop branch, master branch, and the equivalent remote branches in all places I can find.

I keep hunting with `grep -r albert .` and it finds nothing in my tree. Where is this config coming from?

**Comment by r888888888** [comment]
well the most likely problem is config/unicorn/production.rb

it may be trying to run something on the remote server (localhost in your case i assume). is the code deployed on a different directory? check there.
