### ISSUE TITLE
secure way of sharing dmails

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2677]

**Comment by Type-kun** [comment]
I've made the initial changes. All that's left is a way to give user the button to share their dmail. Not sure what's the best way for that, perhaps a pop-up input box? Also I'm not sure what's the best way to construct a link in RoR. I'm positive there's something built-in for that.

Hash is displayed in the API if it's necessary to share before the button is implemented.

**Comment by r888888888** [comment]
I believe naked SHA-1 is susceptible to a length extension attack (as unlikely as that is) so I switched it to use an HMAC.
