### ISSUE TITLE
Using bookmarklet on valid non-images shows blank preview

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2680]
This includes example, mp4, ugoira, webm or swf files. Regardless of file type, upload page sends them to `<img>` tag resulting in blank preview. It's pretty misleading for users to see blank image on valid upload. Perhaps preview tag should be chosen based on file extension? 

As for ugoira, I'm not sure whether it's possible to actually embed our player there, since we'd have to get frame data somewhere, too. But maybe displaying a placeholder saying "ugoira" would be better than a blank image?

**Comment by SD-DAken** [comment]
> As for ugoira, I'm not sure whether it's possible to actually embed our player there, since we'd have to get frame data somewhere, too. But maybe displaying a placeholder saying "ugoira" would be better than a blank image?

Maybe simply displaying the first frame together with a note that it was recognized as ugoira is a good trade off between usefulness and complexity. If I'm not missing something this only requires extracting the first frame - no additional data required.
