### ISSUE TITLE
Support pixiv whitecube redesign

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2681]
Pixiv is gradually switching users to new design called "whitecube" - see https://danbooru.donmai.us/forum_topics/13205. It changed both URLs and HTML layout, making our bookmarklet fail when using it. It's only selectively enabled for now, and it doesn't look like you can switch to it or opt out - redirects kick in if you attempt to visit urls from other design. Easiest way to see the whitecube design seems to be creating a new pixiv account; if it doesn't work for some reason, I can provide account credentials for testing.

Artist urls are now `http://www.pixiv.net/whitecube/user/<id>`
Image urls are now `http://www.pixiv.net/whitecube/user/<id>/illust/<illust_id>`

Intermediate pages are removed, there's no more `mode=`. Links are the same for manga and standalone images. Direct image links didn't change, thankfully. 

When opening  `http://www.pixiv.net/whitecube/user/<id>/illust/<illust_id>`, artist page  `http://www.pixiv.net/whitecube/user/<id>` is loaded first, and the image itself is later loaded with Javascript. That renders html parsing of the image page useless.

**Comment by r888888888** [comment]
I set up a new account but dont seem to get the whitecube design. Can you send your credentials? You can email it to r888888888@gmail.com. If you're concerned about security you can encrypt it with GPG. My pub key id is A95269F3.

**Comment by Type-kun** [comment]
Sent the credentials. Now, maybe I should create a new account if whitecube isn't set automatically for all accounts...

**Comment by r888888888** [comment]
Parsing most of this data from the pixiv api is way easier than trying to scrape the HTML page so I will tentatively go that route.

**Comment by r888888888** [comment]
The api returns frame data for ugoira uploads but curiously leaves out the content type. I wonder if this field is actually used when calling the ugoira player.

**Comment by evazion** [comment]
Grepping ugoira_player.js for `mime_type` shows where it's used. AFAICT it's only used for encoding images as `data:image/<png|jpg|gif>;base64` URLs as some kind of backwards compatibility hack for <iOS 6? That is, it probably doesn't matter.

**Comment by evazion** [comment]
PR #2735 addresses a bug where the bookmarklet fails for whitecube URLs.

**Comment by Type-kun** [comment]
I guess this can be closed now.

**Comment by evazion** [comment]
Reopening because whitecube appears to be dead now. None of the URLs work any more. This code may as well be removed.
