### ISSUE TITLE
Artists are uneditable

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2688]
It's a regression introduced by c8c99e9, there's no `editable_by?` in model.

**Comment by BrokenEagle** [comment]
Might it be easier to replace the code in the "edit.html.erb" file with the following code instead for now...?
`<% if !@artist.is_active? %>`
    `<p>This artist entry is inactive and cannot be edited.</p>`
`<% elsif @artist.is_banned? %>`
`    <p>The artist requested removal of this page.</p>`
`<% else %>`
`    <%= render "form" %>`
`<% end %>`

**Comment by Type-kun** [comment]
I think changing `editable_by?` back to `visible?` would suffice.

**Comment by Type-kun** [comment]
Fixed by 026a64c I guess?

**Comment by Type-kun** [comment]
...nope. It made banned artists uneditable by any means, even for admins.
https://danbooru.donmai.us/artists/12242/edit

**Comment by BrokenEagle** [comment]
Probably changing it like you suggested would work then...

`<% if !@artist.is_active? %>`
    `<p>This artist entry is inactive and cannot be edited.</p>`
`<% elsif @artist.visible? %>`
`    <%= render "form" %>`
`<% else %>`
`    <p>The artist requested removal of this page.</p>`
`<% end %>`

**Comment by r888888888** [comment]
What's the use case for editing a banned artist?

**Comment by Type-kun** [comment]
Adding more source links, for example. If banned artist suddenly opens a twitter account, he wouldn't want pictures from there uploaded, either. 

I'm not sure about inactive entries though, since I don't completely understand what "deleted" status implies.

**Comment by BrokenEagle** [comment]
For myself, I delete artist entries whenever I find duplicates. Another case could be someone creating bogus artist entries, similar to bogus wiki creations.  For both of those cases, there should be no reason to edit that entry any further.

**Comment by BrokenEagle** [comment]
Shouldn't this be closed ...?
