### ISSUE TITLE
Mod+ tool to mass-undo versions

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2689]
Currently, mod staff is essentially powerless when a user messes up enough posts, either deliberately or by accident. There's no tag combination to search for, and restoring everything by hand is awful. We should create a tool to allow working with post versions of any given user. It might be a bit tricky to implement, but it's definitely worth the trouble. Such a tool is essential for two tasks:

1) Instantly undo any damage done by vandals and sockpuppets. They are going rogue lately.
2) Fix incorrect aliases, implications and mass updates. This was always a huge pain, and everyone makes mistakes sometimes. We had two cases in the past couple of months.

What I have in mind is a form which allows enough versatility to pick only the offending versions and either undo them or apply a tag script to the post.

Here's the fields I would like to see. 
1) `User id` - required. Queries will use index and therefore should be very fast, putting as little strain on DB as viewing user's post changes.
2) Radio button group. Values: `All versions` (default) | `Only specified range`
2.1) If "Only specified range" is selected above, `Start version ID` and `End version ID` input boxes must be filled out.
3) Checkbox - `Only with the following changes:`
3.1) Input box, `changes` - required if the above checkbox is selected. Format would be `+added_tag -removed_tag`. This should select versions **containing** the specified changes, not only those that match exactly.
4) Radio button group - `Action`. Values: `Undo` (default) | `Apply tag script`
4.1) Input box `tag script` if "Apply tag script" is selected above.
5) Preview button - find and display first 50 versions that match the criteria, to verify whatever you're trying to do.
6) Submit button - start the processing, either synchronously or as a delayed job.

Searching for changes in versions requires loading up every matched `PostVersion`, which could be a memory hog. Luckily, ActiveRecord has [Batch Processing](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html) which was created exactly for that case. Setting batch size to 100 should reduce the load to nothing.

Usually, `undo` will suffice, but having a possibility to apply a tag script would enable this tool to fix virtually anything I can think of.

**Comment by BrokenEagle** [comment]
This should be expanded to include all versioned types once the above gets implemented, i.e. notes, commentaries, pools, artists, and wiki pages.

Additionally, it could also offer the option to apply the various types of locks in mass... this would be for the more persistent user. This last one's a little more iffy though, as it could be mistakenly used as well, so if it does get implemented, add the ability to unlock en masse as well.

**Comment by SD-DAken** [comment]
> 2) Radio button group. Values: `All versions` (default) | `Only specified range`

Isn't that a dangerous default value? If you want to undo an incorrect mass update etc. and accidentally submit the form to soon you will undo all of the user's changes not only the ones that should be undone. Maybe chose `Only specified range` as default or no default at all?
Implement a confirmation (`This will undo n changes. Are you sure?`)?

Let's hope this doesn't become necessary, but if, for whatever reason, too many changes have been undone, will it be possible to easily redo them?

**Comment by BrokenEagle** [comment]
**Undo**  actions create a new _post version_, which can be reverted as well.  So let's say one of the moderators makes a mistake with reversions... they can then go back in with their own UserID and revert the changes they just made.

**Comment by evazion** [comment]
I've been thinking this over some. Here's what I propose:

1) Add metatags for searching for posts by post versions. Think something like: `updater:foo,bar,baz removed:rating:q added:rating:s updated:>1w verid:1000..2000` to find posts 1) updated by users foo, bar baz 2) where they changed the rating from questionable to safe 3) older than 1 week ago 4) and in a specified post version range.

I think it would be possible to have `PostQueryBuilder#build` farm this search out to BigQuery in a manner something like this:

```
query = %Q{
  SELECT post_id
  FROM [danbooru.post_versions]
  WHERE
    id IN (SELECT id FROM [danbooru.post_versions] WHERE added_tags.name = "rating:s")
    AND id IN (SELECT id FROM [danbooru.post_versions] WHERE removed_tags.name = "rating:q")
  ORDER BY updated_at 
  LIMIT 1000
}
post_ids = search_big_query(query)
relation = relation.where(["posts.id IN (?)", post_ids])
```

This is similar to how things like tag subscriptions / saved searches are handled, but just calling out to BigQuery instead.

2) Add a new bulk update request type for mass undo. The syntax would be something like `mass undo -> updater:foo,bar,baz removed:rating:q added:rating:s updated:>1w verid:1000..2000`, i.e. the same as a tag search. It would do the search and run undo on all the matching post versions.

The point of all the above is that:

1) Don't need to build a special single-purpose tool, instead can generalize existing tools.
2) The requirements to filter by updater, post version ids, added/removed tags are met, they'd just be normal metatags.
3) The preview requirement is met, it'd just be a normal tag search.
4 The tag script requirement is met, it could be done with normal tag scripting or with a mass update.
5) Doing it as a bulk update gets you all the bulk request infrastructure for free. Each mass undo would be tracked in the bulk update list, normal users could submit requests to fix vandalism, bulk updates are already handled asynchronously via delayed jobs, etc.

The form you describe could then be something that generates the preview search and bulk request for you, so this process is faster and easier.

Account pages could also have an "undo all edits by this user" link that would open the form with it already filled out, that way undoing a vandal's edits would just be a couple clicks.

**Comment by BrokenEagle** [comment]
Maybe make the versions metatags _**verid**_, _**verage**_, and _**verdate**_ for searching. That way it'd be symmetrical with the post search terms.  Not sure there's a need for comma delimitted **_updater_** metatag though, since there's no similar mnemonic with any other metatag search term. 

Since a new version gets created every hour (even moreso if another user modifies it in the meantime), then should each version that matches the search criteria from the same post be displayed, or only the latest?  If more than one version does get displayed, should this fact be illustrated in some way so that the user doesn't think he's looking at duplicates?

**Comment by Type-kun** [comment]
>Additionally, it could also offer the option to apply the various types of locks in mass... this would be for the more persistent user. This last one's a little more iffy though, as it could be mistakenly used as well, so if it does get implemented, add the ability to unlock en masse as well.

Fixing #1716 and #1303 will handle this.

>Let's hope this doesn't become necessary, but if, for whatever reason, too many changes have been undone, will it be possible to easily redo them?

Yes, like BrokenEagle mentioned, you can later undo an undo. Can do with no default option, I just suspect that default usage for the form would be reverting tag vandalism.

>Implement a confirmation ( This will undo n changes. Are you sure? )?

Hm. Certainly, it will allow to double-check yourself, but it will double the processing time. Counting changes requires the same looping over versions as undoing them. Then again, this confirmation could contain info about the actual changes you're about to undo, since we'd be looping anyway.

@evazion there's three things I don't like about this: 
* BigQuery is synchronized an hour after version is recorded, for the purpose of version merging, since BQ is not updateable. You'd be looking at the outdated values.
* It's open to DoS. Imagine searching for `verid:1..10000000000`, or even `updated:>1w` without other tags. Even if BigQuery doesn't fail, it'll consume horrible amounts of memory on return and hopefully will silently fail, not crash the app. If you enforce a limit on BigQuery query, it becomes useless as mass-update tool. What's worse, it will happen often by accident, you have to specify all constraints for it to be fast enough.
* Compared to building a form and an undo loop, this is much more complex.

Mixing in BigQuery in tag searches sounds cool, but it should enforce limits and it's not fit for undoing IMO.

>Account pages could also have an "undo all edits by this user" link that would open the form with it already filled out, that way undoing a vandal's edits would just be a couple clicks.

Intended to do this either way :3 This link might as well auto-fill the form fields.

>Add a new bulk update request type for mass undo.

I agree that recording mass undos is a good thing. Though, well, it's possible to have this syntax for mass undo requests without actually allowing it in searches. Handling everything through BUR is interesting, though it requires more work to implement, too.

**Comment by r888888888** [comment]
Querying the versions table in Postgres is not viable. The tags aren't indexed. So BigQuery is necessary.

The one hour gap isn't a huge problem. If the vandal put in changes in that gap time you can just rerun the revert for that gap period.

The potentially massive scale of a revert is a good reason why this can't necessarily be pigeon-holed into the existing post search framework. I'm not convinced that's even the best presentation format; you're more interested in the actual tag changes than what the post looks like.

**Comment by r888888888** [comment]
I would also propose breaking this into two distinct problems:

* Dealing with vandals. This is a much simpler case. It's usually a user just mass changing the rating or removing tags or sources. There's no need to constrain by date or version id. It should be a one button operation to revert all of their changes because there's no valuable information that's being lost.
* Dealing with moderation mistakes. This is trickier and requires the afore mentioned constraints and reporting tools to limit the revert precisely.

**Comment by r888888888** [comment]
I've added the vandalism revert in 5b48d272f2eb2df21a14b09aa22d590a4e568236

**Comment by BrokenEagle** [comment]
I thought Janitor was an obsolete level...?  Why set the permission level for this at that...?

**Comment by r888888888** [comment]
You're right. I've changed it to moderator+.
