### ISSUE TITLE
Report to see new/dormant user activity

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2690]
If a new user immediately starts editing posts left and right, or a user that didn't do a thing for months suddenly goes active, it's often a vandal. Can a report, visible to builder+, be made to list such users? Will work great in conjunction with #2689 to nullify sockpuppet damage.

I don't think it's possible to create dynamically with sql, though, we don't store "last activity" field and it would get overwritten anyway. Maybe editing posts despite being new or dormant should trigger a write of user ID to some table, upon which a report should be built.

**Comment by evazion** [comment]
In the moderator dashboard there's a tag updates table that shows which members have made a lot of edits recently. If it had an option to filter by account age then we could use that to detect mass edits coming from new accounts.

**Comment by Type-kun** [comment]
It wouldn't allow to see "sleepers", though. There might be people dedicated enough to wait a week or two before they start vandalizing from the account.

**Comment by r888888888** [comment]
I figured a better place for this kind of report is on reportbooru and here's a rough attempt at one:

http://isshiki.donmai.us/reports/tag_vandalism/

I can create a similar one for notes although it's not as clear what might constitute note vandalism. I guess clearing the bodies?
