### ISSUE TITLE
Nil dereference on top and missed searches pages

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2698]
Reported in http://danbooru.donmai.us/forum_topics/9127?page=135#forum_post_120843:

> ghostrigger said:
> got on top amd missed searches

>> NoMethodError exception raised 
>> undefined method `scan' for nil:NilClass

http://danbooru.donmai.us/explore/posts/searches
http://danbooru.donmai.us/explore/posts/missed_searches

It seems that reportbooru is timing out:

http://isshiki.donmai.us/hits/day?dates=2016-10-02
http://isshiki.donmai.us/missed_searches

I'm guessing this leads to a read timeout exception in [PopularSearchService#fetch_data](https://github.com/r888888888/danbooru/blob/master/app/logical/popular_search_service.rb#L14), which the `Cache.get` swallows and returns nil instead, leading to a nil deref in `each_search`.

**Comment by evazion** [comment]
#2501 mentioned OOM killer issues with reportbooru. So I guess this and #2697 are just caused by reportbooru being down?

**Comment by r888888888** [comment]
fixed
