### ISSUE TITLE
Unvote Missing Template Exception

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2700]
I've been updating the help:api wiki by going through the code and then testing the different functions. When I got to the **_unvote_** function for both the _posts_ and _comments_ controllers, I got the following **500 Internal Server Error** responses:

`{"success": false, "message": "Missing template posts/unvote, application/unvote with {:locale=\u003e[:en], :formats=\u003e[:json], :variants=\u003e[], :handlers=\u003e[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:\n  * \"/var/www/danbooru2/releases/20161003030034/app/views\"\n"}`

`{"success": false, "message": "Missing template comments/unvote, application/unvote with {:locale=\u003e[:en], :formats=\u003e[:json], :variants=\u003e[], :handlers=\u003e[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:\n  * \"/var/www/danbooru2/releases/20161003030034/app/views\"\n"}`

However, the unvote action does go through and the vote is decremented, however this isn't very optimal as I'd have to ignore all HTTP 500 errors from Danbooru in order to use the function as it is.  

Also, there are no issues with the **_votes_** function, however once a post has been voted on, the only way to remove it is with the unvote function. Voting the opposite way does not work since it detects you have already voted and blocks that action.

The following are the URLs and methods used for both functions:

```
POST /posts/$id/votes.json?score=up
POST /comments/$id/votes.json?score=up
PUT /posts/$id/unvote.json
PUT /comments/$id/unvote.json
```

I'm not sure if this has something to do with the vestigial references to the votes destroy function [here ](https://github.com/r888888888/danbooru/blob/master/config/routes.rb#L99) and [here](https://github.com/r888888888/danbooru/blob/master/config/routes.rb#L193).  If I remember correctly, unvotes used to be accomplished with the DELETE HTTP method...

**Comment by r888888888** [comment]
I'll create delete templates on /posts/id/votes.json and /comments/id/votes.json.

**Comment by r888888888** [comment]
I realize the app uses the unvote action but really it shouldn't and I'm too lazy to change the references to use the DELETE endpoint.
