### ISSUE TITLE
Deploy Issues

### ISSUE THREAD

**Issue by VeryCrushed** [r888888888/danbooru#2705]
So i managed to use the install script, and have everything working up to deploy. It starts going, grabbing the code from github on my fork until it stops at this:

`INFO [73b23f86] Running ~/.rbenv/bin/rbenv exec bundle exec script/delayed_job --queues=default,debian -n 2 start as danbooru@localhost
DEBUG [73b23f86] Command: cd /var/www/danbooru2/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.5 RAILS_ENV=production ~/.rbenv/bin/rbenv exec bundle exec script/delayed_job --queues=default,debian -n 2 start )
^C(Backtrace restricted to imported tasks)
cap aborted!
Interrupt:
/home/danbooru/danbooru/lib/capistrano/tasks/delayed_job.cap:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => delayed_job:start
(See full trace by running task with --trace)
The deploy has failed with an error:
`

Here is a full log: http://pastebin.com/qhBrL5m2

**Comment by VeryCrushed** [comment]
Managed to get past it with a development deploy, im on the site but am unable to upload images

![tw](https://cloud.githubusercontent.com/assets/2308261/19149494/4a51770e-8b7f-11e6-9396-cde1f4b2f186.png)

**Comment by evazion** [comment]
Make sure the `public/data/preview` and `public/data/sample` directories exist. I think you have to create them manually on a fresh install.

**Comment by VeryCrushed** [comment]
That worked, kinda. I created the directories and now im getting this
![tw](https://cloud.githubusercontent.com/assets/2308261/19149877/4b5c694a-8b81-11e6-83f5-131cccb955ee.png)

**Comment by VeryCrushed** [comment]
Also, visiting My Account results in this 
![tw](https://cloud.githubusercontent.com/assets/2308261/19149963/b044e24c-8b81-11e6-8f13-12387bb95141.png)

**Comment by VeryCrushed** [comment]
Rebooted server, now getting failbooru without having done anything else. Ill leave it there for now, but i cant seem to get this to run right at all.

**Comment by Type-kun** [comment]
it's weird that you had to create the directories manually; this should have been handled either by install script or by capistrano deploy:setup task. Errors you are getting are likely because your first upload was corrupted and now post record is stored in the DB without uploader name, causing every listing to fail. Regarding failboorus, check log directory, hard to say what's wrong without further info. Maybe unicorn isn't even running, check for that first.

That aside, I guess setup/deploy process looks pretty weird for people unfamiliar with Rails. It took me about a week of development and RTFM before it became somewhat clear. Maybe a detailed readme or wiki is necessary to explain what's going on. Also, there should be a separate install/run description for getting an instance running for development/testing purposes - it can be done without involving capistrano at all if one doesn't need remote deployment.

**Comment by VeryCrushed** [comment]
Did fresh clean install, still get the exact same result. If the directories were supposed to be created im going to say immediately that there is an install issue, which probably explains the failbooru as well.

What version of Debian has the most success at getting an install working? The guide on the wiki is also out of date, and at the bare minimum the script needs chown danbooru:danbooru ~danbooru/.danbooru/* added to it to even work properly when it comes to deploying. Like I'll send a pull request with some install script changes if I can just get it to work.

**Comment by r888888888** [comment]
I would suggest you open up a Rails console (**bundle exec rails console** is the command) and try some of these things:

```ruby
post = Post.find(1)
post.file_url
post.presenter.humanized_essential_tag_string
user = User.find(1)
user.level
user.name
User.id_to_name(1)
```

**Comment by VeryCrushed** [comment]
@r888888888 

Here is the result:

`danbooru@danbooru:/var/www/danbooru2/releases/20161006185909$ bundle exec rails console
Loading development environment (Rails 4.2.5.1)
irb(main):001:0> post = Post.find(1)
  Post Load (1.4ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT 1  [["id", 1]]
=> #<Post id: 1, created_at: "2016-10-06 19:09:51", updated_at: "2016-10-06 19:09:51", up_score: 0, down_score: 0, score: 0, source: "", md5: "d84a64717de8bb2d78924389309f2e37", rating: "q", is_note_locked: false, is_rating_locked: false, is_status_locked: false, is_pending: false, is_flagged: false, is_deleted: false, uploader_id: 1, uploader_ip_addr: #<IPAddr: IPv4:11.0.0.1/255.255.255.255>, approver_id: nil, fav_string: "", pool_string: "", last_noted_at: nil, last_comment_bumped_at: nil, fav_count: 0, tag_string: "", tag_count: 0, tag_count_general: 0, tag_count_artist: 0, tag_count_character: 0, tag_count_copyright: 0, file_ext: "jpg", file_size: 224009, image_width: 900, image_height: 662, parent_id: nil, has_children: false, is_banned: false, pixiv_id: nil, last_commented_at: nil, has_active_children: false, bit_flags: 0>
irb(main):002:0> post.file_url
=> "/data/d84a64717de8bb2d78924389309f2e37.jpg"
irb(main):003:0> post.presenter.humanized_essential_tag_string
Dalli::Server#connect localhost:11211
localhost:11211 failed (count: 0) Errno::ECONNREFUSED: Connection refused - send
MemCache Error: No server available
=> nil
irb(main):004:0> user = User.find(1)
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
=> #<User id: 1, created_at: "2016-10-06 19:07:06", updated_at: "2016-10-06 19:09:52", name: "verycrushed", password_hash: "", email: "Andrew.Babbitt@outlook.com", email_verification_key: nil, inviter_id: nil, level: 50, base_upload_limit: 10, last_logged_in_at: "2016-10-06 19:07:06", last_forum_read_at: nil, recent_tags: nil, post_upload_count: 1, post_update_count: 1, note_update_count: 0, favorite_count: 0, comment_threshold: -1, default_image_size: "large", favorite_tags: nil, blacklisted_tags: "spoilers\nguro\nscat\nfurry -rating:s", time_zone: "Eastern Time (US & Canada)", bcrypt_password_hash: "", per_page: 20, custom_style: nil, bit_prefs: 91312, last_ip_addr: #<IPAddr: IPv4:11.0.0.1/255.255.255.255>>
irb(main):005:0> user.level
=> 50
irb(main):006:0> user.name
=> "verycrushed"
irb(main):007:0> User.id_to_name(1)
Dalli::Server#connect localhost:11211
localhost:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - send
localhost:11211 is down
MemCache Error: No server available
=> nil
`

**Comment by evazion** [comment]
You need to start memcached. I remember getting those same NoMethodErrors, it was because memcached wasn't running.

**Comment by VeryCrushed** [comment]
@evazion 

sudo /etc/init.d/memcached restart
[ ok ] Restarting memcached (via systemctl): memcached.service.

retried, and get the same result

**Comment by kdoshere** [comment]
danbooru_default_config.rb > List of memcached servers > %w(localhost:11211) to %w(127.0.0.1:11211)

**Comment by Type-kun** [comment]
Yep, very similar to issue #2625. I vaguely remember that this can be fixed by modifying /etc/hosts file, but can't find the info right away. Something IPv6-related IIRC.

**Comment by VeryCrushed** [comment]
Thanks @kdoshere @Type-kun that worked, leaves me with just a few questions.

I have a i7-6700HQ and a Samsung 950 Pro that im running it on, and allocated 4 cores to the VM. Its pretty speedy, however the site can stall so much. CPU and disk usage go way up when just trying to view a page. Any way to speed this up?

Also, does Unicorn just not start up with the OS by default?

**Comment by r888888888** [comment]
Well for starters you seem to be running in development mode. That reloads the entire application on every request. You need to launch it in production mode.

**Comment by VeryCrushed** [comment]
@r888888888 Since my post saying i used development deploy, i set up a new vm and deployed it using bundle exec cap production deploy. The reason i couldn't before appeared to be because of a hostname issue. Also, things have picked up and seem to be running well now. Only thing left is Unicorn
