### ISSUE TITLE
Incorrect score update bug

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2709]
Voting up and then unvoting works fine.
Voting down and then unvoting does not.  Doing both actions in a row decrements the score twice. However, this is not permanent and the correct score get shown upon page refresh.

This is due to the [update_post_on_destroy](unvote-post-link) function in the post_vote model, where....
`Post.where(:id => post_id).update_all("score = score - #{score}, down_score = down_score - #{score}")`
...should be changed to...
`Post.where(:id => post_id).update_all("score = score + #{score}, down_score = down_score - #{score}")`

**Comment by Type-kun** [comment]
No, that's wrong. If the correct score gets shown after refresh, then sql code is correct, and indeed it is. The line you posted is executed only on negative score, so when supervoter undoes his `-3` vote, for example, it means `score - (-3), downscore - (-3)` - in other words, `score + 3, down_score + 3`. 

Getting incorrect results until refreshing the page usually means something is wrong in the javascript. Looks like in this case, though, the data is pulled from model after a request went though. https://github.com/r888888888/danbooru/blob/master/app/models/post.rb#L1038-L1039 looks like the actual culprit.

**Comment by evazion** [comment]
PR #2710.
