### ISSUE TITLE
No Revert Function Protections

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2711]
The revert function allows any existing version to be used for the `version_id=%d` field of the URL, instead of only restricting it to the instances those versions are attached to.

This doesn't pose such a problem for regular web users as the web page will render all of the correct information for them.

However, those using the API don't have those same protections, and could possibly unknowingly screw up any of the possible versioned entities (artist commentaries, artists, notes, pools, posts, wiki pages).

**Comment by evazion** [comment]
evazion/danbooru@385d3eb is a fix but it's not fully tested.

Other issues:

* Reverting an artist reverts `is_active` even when user doesn't have permission to do so. Could be used by members to undelete artists.
* Reverting an artist doesn't do anything with `is_banned`. If an admin reverts a banned artist, should that unban it if the old version was unbanned?
* Reverting a post bypasses rating locks. `PUT /posts/1.json?post[rating]=Z` bypasses ratings locks too for that matter.

**Comment by evazion** [comment]
PR #2713. I didn't address the other things above, those are separate issues.
