### ISSUE TITLE
Upgrade to Ruby 2.3

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2712]
Ruby 2.1 is reaching EOL so may as well upgrade.

**Comment by evazion** [comment]
Only issue I've noticed is a warning from gctools-0.2.3. 0.2.4 fixes it but [according to this](https://github.com/tmm1/gctools/issues/11) oobgc is not necessary any more.

**Comment by Type-kun** [comment]
Does rbenv actually respect `.rbenv-version`? Their documentation doesn't seem to mention it at all, relying on `.ruby-version` instead.

**Comment by r888888888** [comment]
Huh, you might be right. I guess I was always relying on the global version being set correctly.

**Comment by r888888888** [comment]
this is complete now
