### ISSUE TITLE
Improve tag alias/implication forum approval message

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2715]
- [x] When an alias is approved, but it has a conflicting wiki page, a warning is posted in the forum thread. This warning is posted under albert's account. Instead it should be posted by the approver as part of the `The tag alias foo -> bar has been approved` message. Reference: [topic #13297](http://danbooru.donmai.us/forum_topics/13297)
- [x] The `tag alias foo -> bar has been approved` message should link to the new tag alias itself, for convenience in long threads so you don't have to go back to the link in the OP.
- [x] The forum post requesting the alias should be updated when it is approved/rejected, so you don't have to read the whole thread to see the outcome.
- [ ] Maybe the forum title should be updated to mark the thread as resolved? It's difficult to see in the forum listing which threads are resolved vs unresolved.

**Comment by Type-kun** [comment]
>The forum post requesting the alias should be updated when it is approved/rejected, so you don't have to read the whole thread to see the outcome.

Currently impossible, we don't store post number, only the thread number.

> Maybe the forum title should be updated to mark the thread as resolved? It's difficult to see in the forum listing which threads are resolved vs unresolved.

Same. Think about the topics where multiple requests are being made in different posts.

**Comment by evazion** [comment]
evazion@187200dc27eb84030ab8e3dc4a794dd86cf58dd3 - wip on the first two, works but not tested on the error path.

**Comment by r888888888** [comment]
@evazion can you convert to a PR?

**Comment by evazion** [comment]
Will do, there were some broken tests I need to fix first though.

**Comment by evazion** [comment]
PR #2715 addresses this. But in doing this I realized a couple things:

1. The wiki conflict warning is only triggered for individual alias requests, not bulk updates.
2. We have four different ways to make aliases/implications:

* /tag_alias_request/new
* /tag_implication_request/new
* /admin/alias_and_implication_import/new
* /bulk_update_requests/new

That's three more than we need. It would simplify things if BURs were the only way.

**Comment by evazion** [comment]
> The `tag alias foo -> bar has been approved` message should link to the new tag alias itself

I changed the message to `tag alias foo -> bar (alias #123) has been approved`, so the DText parser just needs to be updated to recognize `alias #123` syntax.

The other things about updating the forum post on approval I will leave alone, switching things from storing the topic number to the post number is too much work.

**Comment by r888888888** [comment]
The only issue with standardizing on BURs is it requires learning a special syntax. I guess the existing requests can just serve as a wrapper around that, however.

**Comment by evazion** [comment]
I was thinking BURs could have a form that helps build the script, something like this: https://i.imgur.com/aJIN5x2.png
