### ISSUE TITLE
Wiki pages should be undeletable

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2716]
* Deleting a wiki page should not purge it from the database. It should set an `is_deleted` flag like everything else does.
* Builders should be able to delete/undelete wiki pages. Having to ask mods to delete trivial things in the Pointless Wikis thread is a waste of everyone's time.

**Comment by BrokenEagle** [comment]
+1 to this. As it stands, it's possible the same wiki page name could be created and purged over and over with no way of knowing.

Also, if the records no longer get purged and it just sets a flag, then Builders could be given delete authority without too much worry of them accidentally deleting and purging a valid entry.  Plus there are more Builders than moderators, which would facilitate better responsiveness to Wiki gardening needs.
