### ISSUE TITLE
Saved searches categories don't show posts of all contained searches

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2723]
... while viewing the gallery of all saved searches does indeed show the posts of all saved searches.

Let's say I saved a search for `tag_1` in `category_a` and then save the search for `tag_2` in the same category. Searching for `search:category_a` will then show only the posts with `tag_1`. The problem applies to the preview in my profile too, which will only show `tag_1` posts. It’s not a matter of waiting a bit for the saved search to be updated because the problem still exists after over two weeks.

However, searching for `search:all` will show all posts with `tag_1` and  `tag_2`, as expected.

**Comment by r888888888** [comment]
the listbooru server was bugged due to faulty configuration. i've fixed it but will continue to do some testing.

**Comment by kittey** [comment]
Now `search:all` is broken too since about two days ago. It only displays posts matching the very first search I saved, nothing from other searches from the same category or from other categories.

Attempting to show the posts in saved search categories (`search:category_a`) is still as broken as it was, only showing results from the first search saved under that category.

**Comment by r888888888** [comment]
Saved searches have been operating fine for me for the past few weeks. Please reopen if you continue to see issues.

**Comment by kittey** [comment]
I created a new category with two saved searches in it and it and it has results from both searches in it, as expected.

However, the category that was bugged before is still bugged and has only results from the first saved search in it. Should I simply recreate it or do you want to investigate? It’s called `extra_artists` under my account `kittey`.

**Comment by r888888888** [comment]
@kittey i've reset your saved searches. in case it still appears to be broken for you, can you clarify which category you think is bugged?
