### ISSUE TITLE
Aliases/Implications are set to active on creation.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2724]
From http://danbooru.donmai.us/forum_topics/13320:

> NWF Renim said:
>
> All aliases and implications proposed from around 4 days to now seem to automatically be active: topic #13307, topic #13308, topic #13309, topic #13315

Probably introduced by my patch in eaa0426c36015ab2bcc0242e7f6c1545f5749d7f, although I'm not seeing how. I can't reproduce this on my test instance either.

**Comment by r888888888** [comment]
Fixed and deployed.

**Comment by evazion** [comment]
Is the production schema different from the schema in db/structure.sql? I ask because 1) some aliases/implications have a reason field but it isn't in the schema and 2) even with the mass assignment being blocked in `TagAlias.new(:status => "pending")`, that still defaults to pending for me anyway.

Also there are a couple more places to fix: AliasAndImplicationImporter and Artist#ban!.

**Comment by r888888888** [comment]
It may be because the default is set to active (likely a prior migration issue).

**Comment by r888888888** [comment]
I've change the default to pending now on both aliases and implications.
