### ISSUE TITLE
Add Static Link To Recent Danbooru Commits

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2742]
The commit # next to the release version on the bottom of the page would be a perfect place to add a hyperlink to the commits page (https://github.com/r888888888/danbooru/commits/master).  I find myself multiple times having to navigate there indirectly through the release hyperlink whenever I want to see what the commit # means as far as recent fixes/features.

**Comment by evazion** [comment]
I snuck that in a few days ago in fd4eb8fa08eaac9cc60d0c6adb249d5b5fb4980a, unless you mean something else? Check it out on testbooru.

**Comment by BrokenEagle** [comment]
Wouldn't it make more sense to link it to https://github.com/r888888888/danbooru/commits/master though...? Danbooru doesn't get updated with every commit, so there could potentially be several to a dozen new commits since the last push.  At least for myself, I'm just gonna navigate to the above URL anyways to see ALL of the recent changes...  Maybe I should just bookmark it... :/

**Comment by evazion** [comment]
How about like this: "Running [Danbooru](https://github.com/r888888888/danbooru/commits/master) v2.105.0 ([af49c9c](https://github.com/r888888888/danbooru/commits/af49c9c))." That is, Danbooru links to master while the hash links to the running commit.

**Comment by BrokenEagle** [comment]
*SHRUGS*... like I mentioned, seeing one commit out of a possible of several to more than a dozen since the last push isn't necessarily that helpful.  If GitHub had a way of combining multiple commits on one page, and all of the commits since the last push to the Danbooru/Testbooru server's was tracked so that therefore all of the commits could be shown on a single page, that'd definitely be useful, but I'm not sure that's possible though ...?
