### ISSUE TITLE
Remove post status locking and note locking

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2743]
Actually looking at `locked:status` and `locked:notes` just now I realize a couple things:
- There are no status-locked posts.
- Note locking is hardly used: only 100 uploads in the past 6 years. Most don't have notes or text to begin with. The majority of locked posts date from 2008 or earlier, presumably when anonymous editing was still a thing?

Since these features are unused or virtually unused, I propose they be removed to simplify the code.

**Comment by kittey** [comment]
Locking notes and ratings are used to combat abuse, often just temporarily. From my experience, most misbehaving users have a beef with only a few posts, so I’m not surprised by the low amount of actually locked posts. I don’t think that those features should be removed.

Didn’t know that status locking was a thing, but maybe it’s just not for builders.

**Comment by BrokenEagle** [comment]
Agree with kittey... locks are more useful in the moment to combat vandalism, and the locks should be removed after a certain time period once the vandals have moved on.  I don't know whether this should have to be done manually though, or whether this should happen automatically after a certain time period...?

**Comment by evazion** [comment]
Let me put it this way: if we unlocked everything more than 2 years old we'd be left with only [16 note locked posts](http://danbooru.donmai.us/posts?tags=locked:notes+age:<2y). I see only two vandals among those, both of whom were banned right away and didn't come back. So I think vandalism is a non-issue, it's rare and note-locking doesn't stop it, at best it just shifts vandalism to other posts.

It would make sense to auto-unlock notes after a certain time, but knowing how old a lock is would require tracking locks in the post version history. Which they should be, except after seeing how unused they are I don't think it's worth the effort or worthwhile having them to begin with.

**Comment by BrokenEagle** [comment]
Hmm, before anything is decided, I'd like to see this presented and debated in the forums at least, instead of only being talked about by the few users that actually come to this site.
