### ISSUE TITLE
Dtext Regular Link Misparsing

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2744]
The DText renderer is misparsing regular URLs with surrounding punctuation, and sometimes if the URL itself ends in punctuation.

These issues are demonstrated at http://testbooru.donmai.us/posts/11, more specifically http://testbooru.donmai.us/comments/5

1 and 2 are the same as far as misparsing seen with trailing ')' or trailing '}'.  The issue is triggered when there is something beyond just the trailing character, such as the comma used for both of the 'a' cases, and is not seen when that character is taken away as seen with the 'b' cases.  It causes the trailing character to be consumed by both the link text as well as the link itself.

3 misparses regardless if there is an extra trailing character or not, except for some reason when there is no trailing character it adds in a ';' that wasn't in the original text.

4 doesn't mess the link up, although it does consume the final '"' as part of the link text.

5 shows that URLs that end in closing parentheses, as is often the case on Wikipedia,  get misparsed when the URL is surrounded by whitespace.  When it has a trailing character, such as the comma, it parses things correctly.  In this case, it isn't including the closing parentheses as either part of the link text or the link itself.

**Comment by r888888888** [comment]
Yeah I see what's happening. The parser thinks the comma is the end of the string, and since it's not a special terminal it's included in the link.

I'm honestly not sure what the correct behavior should be since there are cases where a closing parenthesis in a URL is desired, and cases where it isn't. I guess really it should look for a matching bracket as the first character, but that complicates the parser grammar a lot.

**Comment by BrokenEagle** [comment]
Would it be better to do something similar to the textile links, i.e. links that are surrounded with singular square brackets would display just the link. That would facilitate those outlier cases and also allow the user to precisely specify the boundaries of the hyperlink.
