### ISSUE TITLE
Editing Notes Creates New Notes Stacked On Top Of Each Other

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2747]
Shounen_Fake noticed this issue on [post #2527315](http://danbooru.donmai.us/posts/2527315), a post that I had translated.  It had triple stacked notes in the same location.  I thought it must've been an error that I made, but then I came upon [post #2528809](http://danbooru.donmai.us/posts/2528809) with the same issue.  This one had quadruple stacked notes.  I've already deleted the extras, but you can still see them in it's history.

http://danbooru.donmai.us/note_versions?search%5Bpost_id%5D=2527315
http://danbooru.donmai.us/note_versions?search%5Bpost_id%5D=2528809

I did remember when translating post #2527315 that after I had hit the Save button, the outline of the text box remained red instead of going black.  So I then retested this on testbooru, first creating a note, then opening it up for editing without reloading and modifying it before resaving it again.  The end effect is that it ended up creating 2 notes in the same location stacked on top of each other.  You can see this demonstrated at the following link.

http://testbooru.donmai.us/posts/4

**Comment by evazion** [comment]
I think PR #2748 fixes this, but I don't use notes so I'm not positive. I have it running on http://devbooru.evazion.ml:3000/, can you test it?

**Comment by BrokenEagle** [comment]
Tested it on http://devbooru.evazion.ml:3000/posts/1 and it works as it should.
