### ISSUE TITLE
Source upload strategy for bcy.net

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2766]
Bookmarklet should be able to handle bcy.net urls. There seems to be no public API in sight, but the image is loaded right away along with the page, without JS. From a quick glance, it works as follows:

For thumbnail URLs:
Pattern is `http://img[0-9]+.bcyimg.com/drawer/[0-9]+/[0-9]+/post/[a-z0-9]+/[a-z0-9.]+/w650`

* remove the `/w650` part to get full-size image.

For work URLs:
Pattern is `http://bcy.net/illust/detail/[0-9]+/[0-9]+`.

* Parse the source code to get the thumbnail url. CSS selector `img.detail_std` will do to get the element, url is in `src` attribute; then repeat the step above.

I'm not sure how PNG images are handled, and registration seems too difficult to check it myself.
Full-size images are accessible without a referrer, so it's just a matter of parse and rewrite.

**Comment by Type-kun** [comment]
looks like there's no force-conversion to JPG, so thumbnail rewrite rule will work for PNG images as well (see http://danbooru.donmai.us/forum_posts/122884)

**Comment by Type-kun** [comment]
Turns out it's not so simple. 

First of all, http://bcy.net/illust/detail/33032/829971 shows that there could be more than one image, and all of them have `img.detail_std` as their class. So batch upload can be done as well

Also, http://bcy.net/illust/detail/75549/910712 shows there are locked posts that require login and/or follow. It's possible to manually extract a single image from any thumbnail where it's displayed (navigation, previews, artist pages), but I don't think it can be easily automated, unless there's a way to create image URLs from work page.

**Comment by Type-kun** [comment]
There are also other thumbnails hat should be rewritten. If full-size image URL is:

`http://img9.bcyimg.com/drawer/1491/post/c04ey/7a85f760aa7e11e688552967e7522d45.jpg`

Then there are thumbnails like this:
`http://img9.bcyimg.com/drawer/1491/cover/c04ey/7a85f760aa7e11e688552967e7522d45.jpg`
`http://img9.bcyimg.com/drawer/1491/post/c04ey/7a85f760aa7e11e688552967e7522d45.jpg/2X2`
`http://img9.bcyimg.com/drawer/1491/post/c04ey/7a85f760aa7e11e688552967e7522d45.jpg/tl640`

Maybe it would make sense to write a general rewrite rules: one to remove everything after `7a85f760aa7e11e688552967e7522d45.jpg`, and one to transform `cover` to `post`.

**Comment by evazion** [comment]
`w230` is another thumbnail size:

* `http://img9.bcyimg.com/drawer/1491/post/c04ey/7a85f760aa7e11e688552967e7522d45.jpg/w230`

Couple more url types:

* `http://img5.bcyimg.com/article/post/c04f2/fdf11a70ad5911e6a35613b9d16d7204.jpg/w230`
* `http://img9.bcyimg.com/group/intro/c04ce/7f04b4f097f711e68c8d07803ae811d6.jpg/w650`

Date segment (`4bm1`) may be less than five characters: 

* `http://img9.bcyimg.com/drawer/17192/post/4bm1/615ad0b040c711e6b8814383a511d1aa.jpg` 

When you click a post to view full size, there's some trailing junk in the url that generates a watermark:

* `http://img5.bcyimg.com/drawer/17192/post/4bm1/615ad0b040c711e6b8814383a511d1aa.jpg?imageMogr2/auto-orient/strip|watermark/2/text/wqlFY2xvc2lvbgpiY3kubmV0L3UvOTkyNDYy/fontsize/432/fill/I0U1RTVFNQ==/dx/6/dy/10/font/5b6u6L2v6ZuF6buR`

`img5.bcyimg.net` and `img9.bcyimg.net` are the only servers that seem to be used or that work.

**Comment by evazion** [comment]
PR #2770 is a wip on this. So far just did the thumbnail -> full size rewriting. Branch is running on http://devbooru.evazion.ml:3000/.

**Comment by evazion** [comment]
Made some more progress:

- [x] Rewrite sample urls to full size urls
- [x] Rewrite work urls to full size urls for the bookmarklet
- [x] Support batch uploads
- [x] Support logging in for login-only images
- [x] Scrape all the metadata (artist commentary, tags, artist info)

TODO:

- [ ] Add testcases.
- [ ] Figure out what we should do for the artist finder.
- [ ] Figure out if there's any possible way to get the work page url from the image url. If not, then need to change the source from the image url to the work page url after upload like we do with twitter.

**Comment by crs00** [comment]
bcy recently changed to a different URL format for post IDs.
Example: https://bcy.net/illust/detail/1667/1060083 is now https://bcy.net/item/detail/6387858508053765902
I'm assuming this would break what is currently in place, unless somebody already fixed it and I missed it.

**Comment by r888888888** [comment]
The bcy.net domain has never been formally supported. There are only 726 uploads from the domain.
