### ISSUE TITLE
Approving deleted image doesn't create mod action

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2771]
Apparently, going to `status:deleted` and using approve mode doesn't create mod action `<user> undeleted post #...` like "undelete" button on post does, despite doing the same thing.

**Comment by evazion** [comment]
Cause looks to be that undelete goes through `/moderator/post/posts/1/undelete?post_id=1` to `post.undelete!`, while approve goes through `/moderator/post/approval` to `post.approve!`, which doesn't log.

**Comment by evazion** [comment]
PR #2774. Another way to do this was to use the `shift+o` keyboard shortcut to approve the post.
