### ISSUE TITLE
Topics set as mod+ can't be reverted to public ones

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2772]
When attempting to set blank option as min level, I get an error: 
>Error: Min level is not included in the list

Example: https://danbooru.donmai.us/forum_topics/13429

**Comment by BrokenEagle** [comment]
Related conversation...
http://danbooru.donmai.us/forum_topics/13430

Should their be some kind of check so that BUR/Implication/Alias threads can't have a min-level set...?

**Comment by Type-kun** [comment]
Turns out new topic can't be created as public by mod+, either. That's due to 
```
validates_inclusion_of :min_level, :in => [0, User::Levels::MODERATOR, User::Levels::ADMIN]
```
in forum topic model, while in html form, "public" option represented as a blank option in select box, with empty string as value.

**Comment by evazion** [comment]
PR #2773 should fix this.

> Should their be some kind of check so that BUR/Implication/Alias threads can't have a min-level set...?

I think it's sufficient to trust mods not to do silly things like make request threads private. Not worth worrying about unless these mistakes become a common problem.

**Comment by Type-kun** [comment]
Maybe level 0 should be called "None" instead. Could `Min level: public` create misunderstandings?

**Comment by evazion** [comment]
Seems reasonable, changed it to `None`. Wasn't sure what to call it, since technically user level 0 is called `Anonymous` in the code, but that's definitely confusing.
