### ISSUE TITLE
Log more mod actions

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2776]
I think any kind of edit or deletion requiring mod privileges ought to be logged. Currently these things are logged:

* banning/unbanning posts.
* deleting/undeleting/permanently deleting posts .
* deleting/undeleting/permanently deleting pools.
* changing user levels (promoting/demoting users).
* creating/editing/deleting tag aliases/implications.
* changing user names
* banning users

But these things are not:

- [x] editing/deleting comments
- [x] editing/deleting user feedbacks
- [x] editing/deleting forum posts
- [ ] permanently deleting wiki pages
- [x] creating/deleting ip bans
- [x] performing mass edits via `/moderator/tag/edit`
- [x] performing bulk reverts

**Comment by r888888888** [comment]
fixed
