### ISSUE TITLE
Weekly report of unused tags

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2778]
This is doable now. Danbooru could send heavy uploaders a weekly report of common tags that were added to their uploads by other users. It's a good way of increasing discovery. Could potentially integrate with wiki and related tags.

**Comment by Type-kun** [comment]
This sounds like a very nice idea. I would also consider doing same thing monthly for less active uploaders.

**Comment by BrokenEagle** [comment]
Would it be possible/worthwhile to track whether an unused tag suggestion becomes incorporated into a user's tagging habits, or if they keep getting dinged for not using the same tags over and over...?

**Comment by r888888888** [comment]
It's possible but would need to store some state to track that data. And there's a question of how useful that would be. Assuming you have that data, what would you do with it?

**Comment by BrokenEagle** [comment]
It'd be an interest item more than anything else, to gauge the effectiveness of the weekly/monthly reports.

However, if common tags were constantly being missed (ex. hair color, hair length, etc), that might warrant an intervention in the form of a DMail first, followed by feedback if necessary...

However, I don't know if the effort required to implement would be worth it...?

**Comment by Type-kun** [comment]
There is some discussion on the first usage: https://danbooru.donmai.us/forum_topics/13166?page=2#forum_post_124936 - people want a way to opt-out.

What are the criteria, exactly? 10+ uploads a week, and tag was added at least 5 times to the weekly uploads, if I'm reading it correctly?

**Comment by r888888888** [comment]
This is handled in reportbooru
