### ISSUE TITLE
Erroneous pixiv_id parsed for novel/background/profile images

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2779]
I've found a few posts with sources that are incorrectly parsed as having pixiv illustration IDs: [id:2551782,2551779,2529316,1477553,608683 pixiv:>0](http://danbooru.donmai.us/posts?tags=id%3A2551782%2C2551779%2C2529316%2C1477553%2C608683+pixiv%3A%3E0)

post #2551782: http://i1.pixiv.net/novel-cover-original/img/2016/11/03/20/10/58/7436075_f75af69f3eacd1656d3733c72aa959cf.jpg
post #2551779: http://i1.pixiv.net/novel-cover-original/img/2016/11/11/20/11/46/7463785_0e2446dc1671dd3a4937dfaee39c227f.jpg
post #2529316: http://i2.pixiv.net/background/img/2016/10/30/12/27/30/7059005_da9946b806c10d391a81ed1117cd33d6.jpg
post #1477553: http://i1.pixiv.net/img15/img/omega777/novel/2612734.jpg
post #608683: http://img08.pixiv.net/profile/nice/1408837.jpg

**Comment by evazion** [comment]
PR #2782.

Some of these posts will have to be resaved to update their pixiv IDs: https://bigquery.cloud.google.com:443/savedquery/446593546541:923320dfed1c475b94b25fc3deb861bd
