### ISSUE TITLE
IQDB(S) not adding new images to the db.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2786]
I've updated the booru to the latest commit but I cannot get the IQDBS system to submit new posts to the IQDB database, I've set it up to use the new IQDBS system and can read from it with images added before the update.

I've set the configs; 

```
   def iqdbs_auth_key
    end

    def iqdbs_server
    end
```

This is my .env file

```
IQDB_HOSTNAME=localhost
IQDB_PORT=4000
IQDB_DATABASE_FILE=/var/www/iqdbs/shared/iqdb.db
AUTH_KEY=-SNIP-
SINATRA_PORT=4567
```

Since I don't want to use the Amazon stuff I've left that out.

P.S.

Would it be possible to update the https://github.com/r888888888/danbooru/blob/master/script/fixes/029_iqdb_import.rb script to work with the new iqdbs system?

**Comment by evazion** [comment]
> Since I don't want to use the Amazon stuff I've left that out.

There's your problem. Amazon SQS is what's used to update IQDBS with new posts, so you either have to set that up or revert commit 7aab50f7264665d8fdbe69debb300c483edc7a06.

**Comment by Iratu** [comment]
So basically you're forcing people to register to a 3rd party service to use the IQDBS?

Personally I'd prefer if there was a way around that build into it, but I guess for now I'll use "Amazon SQS"
