### ISSUE TITLE
User similarity report broken.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2798]
http://danbooru.donmai.us/reports/similar_users is broken. Backtrace:

    HTTP error code: 404 Not Found
    app/logical/reports/user_similarity.rb:41:in `block in fetch_similar_user_ids'
    app/logical/reports/user_similarity.rb:36:in `fetch_similar_user_ids'
    app/presenters/user_similarity_presenter.rb:18:in `fetch'
    app/presenters/user_similarity_presenter.rb:6:in `initialize'
    app/controllers/reports_controller.rb:24:in `new'
    app/controllers/reports_controller.rb:24:in `similar_users'

Caused by https://isshiki.donmai.us/reports/user_similarity returning a 404. 

http://danbooru.donmai.us/reports/uploads is also broken by https://isshiki.donmai.us/reports/uploads 404'ing.

**Comment by r888888888** [comment]
This is probably because the autogenerated reports shared the same directory. I've moved it to user-reports for now the user similarity report is working again.
