### ISSUE TITLE
Improve nico seiga support.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2805]
Currently the artist finder doesn't work for NicoSeiga. This is because artist entry URLs look like `http://seiga.nicovideo.jp/user/illust/15954798` but post URLs look like `http://seiga.nicovideo.jp/seiga/im6355583` so there's no match. But this could be made to work by implementing `Sources::Strategies::NicoSeiga#normalize_for_artist_finder!`, similar to how Pixiv artist finding works.

Fetching the artist commentary should also be supported.

**Comment by r888888888** [comment]
I've retroactively fixed the existing nicovideo urls so they should work with the artist finder now.
