### ISSUE TITLE
Comment Bug With Platinum Accounts

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2810]
On [Danbooru 2 Issues](http://danbooru.donmai.us/forum_topics/9127), starting on [page 147](http://danbooru.donmai.us/forum_topics/9127?page=14#forum_post_124736).

> Claverhouse said:
> Since last night, and restarts of the browser, plus yes, I am logged in, commenting doesn't work.
> It goes to a new page that says:
> No route matches {:action=>"show", :controller=>"posts", :id=>nil} missing required keys: [:id]

After g3gen reported the same issue on [page 148](http://danbooru.donmai.us/forum_topics/9127?page=148#forum_post_124769), it was postulated and then confirmed that this bug only affects Platinum-level accounts.

**Comment by evazion** [comment]
Already fixed in #2809! Deployed just a minute ago.

**Comment by BrokenEagle** [comment]
Yeah, saw it right after I posted this...
