### ISSUE TITLE
/posts/random.json does not redirect nicely

### ISSUE THREAD

**Issue by hyperco** [r888888888/danbooru#2813]
When GETing `/posts/random.json`, a `Location` header is returned that redirects to the post page, not the post JSON. This is unexpected and not very useful if attempting to get a random post on the command line, such as when using the `-L/--location` option for `curl`.

**Comment by BrokenEagle** [comment]
In the meantime, you can always disallow redirects, then pull the "Random" post location from the response header and append ".json" to the end before making another GET request.  So still not a single command-line argument, but it could be functionized via a script or batch file to make it a single command-line argument.

**Comment by evazion** [comment]
PR #2813 fixes it, but note that you can do `curl -H "Accept: application/json" -L danbooru.donmai.us/posts/random` to make it work. The `Accept` header is an alternate way to request a JSON response.

**Comment by BrokenEagle** [comment]
> PR #2814 fixes it, but note that you can also do curl -H "Accept: application/json" -L http://danbooru.donmai.us/posts/random to make it work. The Accept header is an alternate way to request a JSON response.

Ah, that's pretty cool.... Did not know that... (ツ)
