### ISSUE TITLE
Bugs for mod actions on post/comment update/delete

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2824]
Attempting to edit another user's forum post results in the following message:

> undefined local variable or method `rec' for #<ForumPost:0x007f25e5c59290>
> app/models/forum_post.rb:23:in `block in <class:ForumPost>'
> app/controllers/forum_posts_controller.rb:50:in `update'

It's due to `rec` being undefined outside of lambda expression.

**Comment by Type-kun** [comment]
Mostly fixed, but deleting a comment causes a following message to be written:

> comment #... updated by ...

instead of "deleted by". Not sure why.

**Comment by evazion** [comment]
I think the `after_destroy` callbacks never actually run, since deleting a comment just sets the `is_deleted` flag instead of destroying the object.

**Comment by Type-kun** [comment]
Hm, true. Same happens to forum posts now that I have checked.

**Comment by r888888888** [comment]
fixed
