### ISSUE TITLE
Restore search within pool versions IP in mod tools

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2825]
After pool versions table got offloaded to amazon sqs, search in pool versions was broken. It was "fixed" by commenting out queries to pool versions table in 3d2b81d , but that actually left mod tools without ability to search for IP addresses in pool versions. The functionality should be restored, otherwise pools could be freely vandalized.

On the off-note, @r888888888, how can this be tested? Would I need to set up Amazon SQS account like the name implies, or just the Archive service? How do I run the initial table setup? This probably should get documented better for other users, too.

**Comment by r888888888** [comment]
The data is there, I just wasn't sure how to integrate it at a glance.

For testing purposes, the simplest way is probably to just write a script to generate some random pools and version data. You can create a local archive_development database that the PoolArchive model can connect to and you can just create versions directly on that database.

You could also set up your own AWS account and enable SQS. It is basically free at low volume so there's no real cost. This means you'd also have to run the archive service independently somewhere.
