### ISSUE TITLE
Saved search categories retain non-matching posts

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2827]
I have a subscription with some frequently misused tags, such as `cap`. Whenever a posts shows up there, I go and correct it. Once my subscriptions get updated, the post disappears from the subscription because it doesn’t match anymore.

Now that subscriptions are being phased out, I made saved searches for those tags and put them all into one category. Matching posts are added to the category, as expected, but when I fix the tags and they don’t match any of the the saved searches anymore, the posts are never removed and clutter the results.

For example, I removed the `cap` tag from [post #2582751](https://danbooru.donmai.us/posts/2582751) 13 days ago but it’s still showing up in the category’s results as well as in `search:all`, even though it shows up in none of my saved searches when I manually go through them one by one.

**Comment by r888888888** [comment]
I will have the updater reset the stored posts which should solve this problem. This does mean eliminating the date constraint, but given that the searches are being performed on the read only replica and queries are being deduplicated anyway it shouldn't be a huge deal.

**Comment by kittey** [comment]
It's working as expected now.
