### ISSUE TITLE
Lower Permission to See Previous Usernames to Builder+

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2830]
See [topic #13516](http://danbooru.donmai.us/forum_topics/13516) on the Danbooru forums for the discussion on this.

Currently, the ability to see previous usernames is restricted to Moderator+.  There was a desire expressed on the Danbooru forum for this to be lowered to Builder+.

**Comment by evazion** [comment]
PR #2830 would lower it to Member+ but that can be changed if desired. Also it allows admins or the name  change requester to view all past name change requests, including rejected ones in case there are any.
