### ISSUE TITLE
Replace Subscriptions Link With Search:All Link

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2831]
In response to subscriptions being deprecated, the Subscriptions link from the Posts page should be replaced with a link to Search:All.

From Danbooru [topic #13612](http://danbooru.donmai.us/forum_topics/13612#forum_post_125413):
> Gollgagh said:
> Could we get a quick link to search:all in the navigator to replace the subscriptions button when this all happens?

**Comment by evazion** [comment]
`/posts` already has a link to `Saved searches` in the navbar, and from there `Gallery` takes you to `search:all`. If we added this to `/posts` it would mean having three links in the navbar: `Searches`, `Saved searches`, and `search:all`. I think that'd be confusing.

I think what is really desired is an easy way to view your saved searches. The `/saved_searches` page isn't very good at that, so people want to use `search:all` instead. I think ultimately it would be better to improve the `/saved_searches` page, have some type of gallery overview, that way don't have to resort to `search:all`.
