### ISSUE TITLE
Post unvote API returns status 500 on success

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2838]
Successfully unvoting a post through the JSON API yields status 500 and `{"success": false, "message": "Missing template posts/unvote, application/unvote with {:locale=\u003e[:en], :formats=\u003e[:json], :variants=\u003e[], :handlers=\u003e[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:\n  * \"/var/www/danbooru2/releases/20170111220719/app/views\"\n"}`.

Using the JavaScript URL instead gives me status 200 for both success and failure.

**Comment by r888888888** [comment]
I've eliminated the unvote actions and standardized on the vote resources.
