### ISSUE TITLE
"Original" tag shows up twice in Pixiv source data

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2839]
When fetching a post’s source from Pixiv, the `オリジナル` tag shows up twice when it should be there only once.

For example, [post #2599024](https://danbooru.donmai.us/posts/2599024) has these tags on Pixiv:
`漫画   4コマ   オリジナル   おっぱいのついたイケメン`

Clicking “Fetch source data” on Danbooru yields these tags:
`漫画   4コマ   オリジナル   おっぱいのついたイケメン   オリジナル`

So far, I’ve only seen it happen with the オリジナル tag and the extra tag was always last.

**Comment by evazion** [comment]
See PR #2840.
