### ISSUE TITLE
Pool Versions no longer recording changes correctly

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2844]
After adding several posts to a pool over the last couple of days, it still only lists one new version.  Additionally, it lists no new added posts, even though the post count is different (59 vs 46).

http://danbooru.donmai.us/pool_versions?search%5Bpool_id%5D=10823

**Comment by r888888888** [comment]
I believe what's going on is the version merge logic is writing incorrect values for added_post_ids and removed_post_ids.

**Comment by r888888888** [comment]
I've run a fix to correct all the versions made this year.
