### ISSUE TITLE
Track last read page in pools

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2845]
You can technically do this with bookmarks but it would be nice if there was a site feature to read the last read page of a pool.

**Comment by BrokenEagle** [comment]
Should this only work for series-type pools...? I myself have never had a reason to browse through collection-type pools with the pool navigation since they are more like tags, so there would be no reason to track the last read page IMO...

**Comment by r888888888** [comment]
Yes, I think so.
