### ISSUE TITLE
Pools Still Not Recording Versions Correctly

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2848]
Referring to issue #2844.

Just tested this and it is still not recording pool versions correctly.

http://danbooru.donmai.us/pool_versions?search%5Bpool_id%5D=5205

That is a pool where the last several edits have not been recorded, including edits by myself.  I attempted to remove and then readd those same posts to try to trigger a new version without any success.

I also checked the raw JSON and discovered that pool 5205 had 359 posts, whereas the latest pool version only had 356 posts.

http://danbooru.donmai.us/pools/5205.json
http://danbooru.donmai.us/pool_versions.json?search%5Bpool_id%5D=5205&limit=1

**Comment by r888888888** [comment]
Sorry. The postgres instance was saturated on open connections (since every web server connects to it) and so the sqs queue was backlogged. I've increased the connection limit and the queue has cleared up now.

**Comment by BrokenEagle** [comment]
Got it... just checked the above and everything seems to be corrected.  Thanks for the quick response.
