### ISSUE TITLE
IP address search is broken (again)

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2849]
> PG::UndefinedColumn exception raised
> 
>  ERROR: column pool_versions.updater does not exist LINE 1: ...rsions_updater_ip_addr FROM "pool_versions" WHERE "pool_vers... ^
>  app/logical/moderator/ip_addr_search.rb:53:in `search_by_user_id'
>  app/logical/moderator/ip_addr_search.rb:43:in `search_by_user_name'
>  app/logical/moderator/ip_addr_search.rb:13:in `execute'
>  app/controllers/moderator/ip_addrs_controller.rb:7:in `index'

I strongly suspect the reason for this is missing `belongs_to :updater, :class_name => "User"` in Pool Archive model, since line 53  mentioned above says `PoolArchive.where(updater: users)`

**Comment by Type-kun** [comment]
With this, `PoolArchive.where(updater: users).to_sql` returns something sensible in rails console. Tests needed though. @r888888888 deploy on testbooru please? Also probably need to enable pool history on testbooru.

**Comment by evazion** [comment]
My fault, didn't have archives set up so didn't actually test that line. Finally got it set up now though and yeah, the fix works.

http://devbooru.evazion.ml/moderator/ip_addrs?search[user_name]=albert

**Comment by r888888888** [comment]
I have it fixed in my post-archive branch, I will probably cherry-pick it in tomorrow.
