### ISSUE TITLE
NoMethodError exception when sending DMail

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2850]
From [Danbooru 2 Issues](http://danbooru.donmai.us/forum_topics/9127?page=154#forum_post_125844) topic.

> Vezral said:
> First time posting in the forum, not sure if I'm supposed to post my issue here or create a new thread for it.  Anyway, I wanted to message (dmail?) Moonspeaker regarding some translation stuff and the following error occurred:
```
NoMethodError exception raised
undefined method `include?' for nil:NilClass
app/models/dmail.rb:196:in `send_dmail'
app/models/dmail.rb:49:in `block in create_split'
app/models/dmail.rb:45:in `create_split'
app/controllers/dmails_controller.rb:42:in `create'
```

**Comment by evazion** [comment]
```ruby
def send_dmail
  if to.receive_email_notifications? && to.email.include?("@") && owner_id == to.id
    UserMailer.dmail_notice(self).deliver_now
  end
end
```

It looks like he turned on email notifications but has a blank email. I think it'd be best to validate the email before that setting can be turned on, not later.
