### ISSUE TITLE
search:uncategorized should search for uncategorized saved searches

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2859]
There's no way to search for uncategorized saved searches. You can do `search:all` but that includes all saved searches, which you may not want.

`search:Uncategorized` doesn't work because uncategorized searches actually have a category of NULL, not `Uncategorized`, which seems a little weird. Also there's an issue with [this](https://github.com/r888888888/danbooru/blob/c7b5a4e2292cea67d926e88546101c56c47e18b1/app/views/users/_statistics.html.erb#L146-L156) rendering the link to uncategorized searches as [/posts?tags=search%3A](http://danbooru.donmai.us/posts?tags=search%3A) in your profile.

**Comment by r888888888** [comment]
in hindsight i should not have allowed null names at all, and instead always default to uncategorized if one isnt given. its possible to still fix this by renaming all the keys in redis and i will probably do this at some point but for now a workaround is implemented in 634b94e

**Comment by HaxtonFale** [comment]
User profile still shows all searches under uncategorized. Should this be filed as a separate bug?
