### ISSUE TITLE
Upload tag change report

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2863]
There was a discussion in [mod chat](https://safebooru.donmai.us/forum_topics/13341?page=3#forum_post_126076) about a tool for monitoring given user's tagging habits, to see what they added to their uploads and what they haven't. I proposed the following:

1) Take user's uploads, order by ID descending; show ID and maybe thumbnail in the first column
2) For each upload, traverse versions, see what tags were added by user, merge them in a single record, and show it as a second column
3) Take current version, diff against the second column we just calculated, and show the result (tags added and removed by other users) as a third column.

In addition to being useful to moderators, it might make for a great tag discovery tool, and also allow users to relatively easily identify posts reported by danboorubot.

**Comment by r888888888** [comment]
Are there still any outstanding issues with this?

**Comment by Type-kun** [comment]
It's not linked anywhere yet. The link should either go near profile upload count (`Uploads 7669 (Tag Change Report)`) or in profile subnavbar. 

Other than that, it seems to be loading a tad bit slowly, probably because of usual N+1 issue, but it's not that much of the problem so far.

**Comment by evazion** [comment]
#2947 fixes a couple N+1 queries problems. There's one left in that each time `changes` is called, it loads the previous version to calculate the rating/source/parent changes. Archives would need `rating` / `previous_rating` fields instead of `rating` / `rating_changed` to fix this.

**Comment by Type-kun** [comment]
>There's one left in that each time  changes  is called, it loads the previous version to calculate the rating/source/parent changes.

Hm. Can't rails make use of versions preloaded with `includes(versions: [:post])`? It re-loads already loaded rows after all. Or, it would be uglier, but we can expose a method in `version` model to calculate changes to another version given as parameter, then call that method both from `changes` and from report.

**Comment by evazion** [comment]
> Hm. Can't rails make use of versions preloaded with includes(versions: [:post])?

Well, it hadn't been because the way `PostArchive#previous` was defined, it didn't use associations so preloading didn't help it. #2948 fixes it, but it's pretty hacky and subtle.

PSA: I'm using the RailsPanel chrome extension for finding N+1 problems. It makes seeing what's happening on the SQL level much easier. I have it running on http://devbooru.evazion.ml:3000/, so if you have the extension installed you can use it there.
