### ISSUE TITLE
Undeleting a post doesn't resolve flags

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2865]
`Post.undelete!` doesn't call to `flag.resolve!` like `post.approve!` does. It works fine until an undeleted post is flagged again. Since previous flags, including automatic "Unapproved in 3 days", are not resolved, post pruner finds the post with `post.flags.unresolved.old.any?` and deletes it on the first run instead of after three days.

That aside, why are `undelete!` and `approve!` different at all? You'd think one should call another instead, to avoid code duplication.

**Comment by evazion** [comment]
I don't see a need to even have one call the other. I think `undelete!` could be removed completely and `approve!` used for both. Could possibly get rid of `controllers/moderator/post/approvals_controller.rb` too and merge it into `controllers/moderator/post/posts_controller.rb`. Doesn't seem necessary that approving lives in its own controller, separate from all the other mod actions.
