### ISSUE TITLE
"*_(cosplay)" should not create tags

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2868]
Issue I noticed when trying to remove the tag "shantae", which has been split into shantae_(character) & shantae_(series)

The empty tag "shantae" is being created for posts with "shantae_(cosplay)" - this should be considered a bug, and removed.

**Comment by BrokenEagle** [comment]
Issue being debated on [topic #13679](http://danbooru.donmai.us/forum_topics/13679).
