### ISSUE TITLE
Add option "import" for Pools *suggestion*

### ISSUE THREAD

**Issue by kdoshere** [r888888888/danbooru#2883]
Well, the other day I saw something interesting regarding the pools, one of the issues that I find when using pools is that when we need to create or update one this process is not as good as it should.

Because when doing so at the moment we only have two options, you can either go to each image and then add them to the pool manually or you could also enter their ids (and by doing that you will need to remember each id) and either of those options are slow, not optimal and time consuming.

In order to fix this I'd propose to create a new option like an import that would work like this:

As user you could create a new pool of the type of collection with name as "pantsu" for example, then you'd select the new option that is next to the edit option (this would be our new option), then you'll get redirected to a page similar to the edit pool one but this new page would offer you to search for posts by tags and would give you the results.

To prevent issues of having to load too much result pages and avoing to use any kind of auto paging that could be slow we could limit the number of post displayed by using the per_page value and also that on the page's foot we could have two options: "Add the selected images and finish" and "Add the selected images and load next page". 

That would be my suggestion.

Pros: It would ease the pool collection creation and edition process by speeding up the addition of new images in an easy way.

Cons: It could be difficult to implement.

**Comment by kittey** [comment]
How is that better than creating a pool, searching for some tags, then switching over to “tag script” mode and adding `pool:123456` to posts by clicking on the thumbnails, which is what we have now?

**Comment by evazion** [comment]
Yes, you can achieve this with tag scripts or with mass updates. If those aren't usable enough, I think it would be better to improve them than to make a tool that's specific to pools only. This problem isn't unique to pools, you have the same difficulty when populating new tags or new favgroups.

**Comment by kdoshere** [comment]
Well yes, the tag script of the mode menu is an option, but sadly the mode menu is just for premium users and my option aims to be of use to all users. We could also do it using external script but I'm not really used to use them so I don't really know about that.

@evazion: You're right, its not just a pools issue and maybe there's a better way of doing that without having to create a new option.

**Comment by BrokenEagle** [comment]
If I remember correctly, this used to be an option on Danbooru, and still is an option on Gelbooru.

One option that could simulate the above import function would be to do a tag search as normal, making sure to append .json to the URL.

Example with Girls und Panzer:
http://danbooru.donmai.us/posts.json?tags=girls_und_panzer

Copy and paste all of the resulting text into the JSON window on https://jqplay.org/.  Then paste `map(.id)` into the Filter window. Grab the resulting text from the Result window, replacing the brackets "[ ]" and commas "," with spaces, leaving nothing but the post IDs. Copy and paste the remaining text into the Posts window on the Pool edit page.

For more than one page of results, just append "&page=2", and so on and so forth, until no more results are returned.

Granted the above is not the most straightforward process, but it is available to all users regardless of level.

**Comment by r888888888** [comment]
I don't think you need an intermediate stage, really.

Just have an option to export a search into a pool. Then you can edit the pool manually and remove the posts that don't belong.
