### ISSUE TITLE
Unread DMail Checking Bug

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2886]
Mentioned by [Moonspeaker on Danbooru](http://danbooru.donmai.us/forum_topics/9127?page=157#forum_post_126958):

> I didn't see these problems mentioned within the last two pages, so...
> 
> For the past week, at least once a day, an attempt to go to or refresh a Danbooru page returns the following error:
> 
> ActiveRecord::StatementInvalid exception raised
> 
>` PG::QueryCanceled: ERROR: canceling statement due to statement timeout : SELECT "dmails".* FROM "dmails" WHERE "dmails"."owner_id" = $1 AND (is_read = false and is_deleted = false) ORDER BY dmails.id desc LIMIT 1`
> `app/views/layouts/default.html.erb:88:in ``_app_views_layouts_default_html_erb___4319382528528581785_69888694139880'
> `app/controllers/pools_controller.rb:18:in `index'`
> 
> Refreshing again fixes things, but I'm wondering if this may just be a symptom of something else.

There should be a graceful fail for the DMail checking mechanism so that if it does fail like with the above, that it doesn't disrupt the page load.

**Comment by evazion** [comment]
Wrapping this in a `Dmail.with_timeout` would let it fail gracefully, but I think it would be better to put indexes on these columns. This is happening because `is_read` and `is_deleted` aren't indexed.

**Comment by evazion** [comment]
PR #2889 would add these indexes, but after thinking about it I'm not sure postgres will use them. There's already an `owner_id` index it could be using, but I suspect the `ORDER BY dmails.id desc LIMIT 1` makes it prefer the `id` index instead, which would cause the "start at the highest id and scan down until finding a match or timing out" behavior.
