### ISSUE TITLE
Incorrect Relative Links for User Feedbacks

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2887]
As reported by [KyteM on Danbooru](http://danbooru.donmai.us/forum_topics/9127?page=157#forum_post_127030):

> This is a tiny issue but email notifications forget to add the domain name to links, so for example a mail about getting a user record will point to http://user_feedbacks/?search[user_id]=186589
> 
> I assume it's because it simply mirrors the dmail, which has the domain name implicit.

Just as a point of reference, I received a User Feedback DMail with a correct relative linking on 5 Feb 2017, and KyteM received his incorrectly linked DMail on 17 Feb 2017, so something changed in the last two weeks is affecting things.

**Comment by evazion** [comment]
Are you sure? He's talking about the email notifications you get when you're sent a dmail. On Danbooru the dmail is fine, but inside an email the relative links are broken.

Anyway PR #2888 should fix this. Emails are slightly broken still in that some dtext stuff needs CSS that's not present in the email (think: spoilers tags). Fixing that would probably require something like [premailer](https://github.com/premailer/premailer).

**Comment by BrokenEagle** [comment]
Ah sorry, I misread KyteM's post since I had completely forgotten about e-mails as I had disabled that option years ago... :/
