### ISSUE TITLE
`after_destroy` callbacks should be fired upon comment deletion

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2892]
Since `is_deleted` flag has been introduced to comments along with `delete!` procedure, `after_destroy` callbacks are not fired anymore, so posts' `last_commented_at` and `last_comment_bumped_at` are not recalculated properly, and "updated" mod action is logged instead of "deleted". The same problem applies to all models that aren't actually destroyed but marked as deleted.

**Comment by evazion** [comment]
I think changing it to `before_save <callback>, if: :is_deleted_changed?` should work, so that it works on undeletion too.
