### ISSUE TITLE
Post Versions JSON API no longer includes the source in the added/removed/unchanged fields

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2901]
The Post Versions JSON API no longer includes the source in the added/removed/unchanged fields.  Without the source specified in removed_tags, I can't tell what the source used to be without querying all of the edits for that post.  Please add back in.

**Comment by r888888888** [comment]
I believe this is fixed now although admittedly the API returns the changes as arrays instead of strings.

**Comment by RaisingK** [comment]
Confirmed. Thanks.
