### ISSUE TITLE
Post Versions JSON API: unicode escapes

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2902]
There are unicode escapes in the Post Versions JSON API results that don't seem necessary embedded in tag strings, like "\u003e" for ">" and "\u0026" for "&"...

**Comment by evazion** [comment]
It's valid JSON, conforming JSON parsers ought to be able to handle it. This comes from `to_json`, which escapes HTML entities when is `config.active_support.escape_html_entities_in_json` is enabled. Disabling that would probably introduce XSS vulnerabilities in other areas.

See also: http://api.rubyonrails.org/classes/ERB/Util.html#method-c-json_escape
