### ISSUE TITLE
DMail Error Reported When There is an Issue With Sending an Email Notice

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2904]
From user Provence on the Danbooru forum:

> 
> 454 Temporary service failure
> app/models/dmail.rb:181:in `send_dmail'
> app/models/dmail.rb:51:in `block in create_split'
> app/models/dmail.rb:47:in `create_split'
> app/controllers/dmails_controller.rb:42:in `create'
>
> and that after trying to mention said user via the @ mention:
>
>454 Temporary service failure
>app/models/dmail.rb:181:in `send_dmail'
>app/logical/mentionable.rb:63:in `block in queue_mention_messages'
>app/logical/mentionable.rb:52:in `each'
>app/logical/mentionable.rb:52:in `queue_mention_messages'
> app/controllers/forum_posts_controller.rb:48:in `create'
> 
> Don't know, but is it really possible to block users completely? Couldn't find that option anywhere and it only happens to one user.

At the current version of the code (a90a1bd), the error is occuring at the [following line](https://github.com/r888888888/danbooru/blob/a90a1bd8954358373268b780b86fc8213481edba/app/models/dmail.rb#L181):

`UserMailer.dmail_notice(self).deliver_now`

I'm guessing that it's somehow failing to send an e-mail notification to the user when a DMail is being generated, and there is not graceful failing mechanism so it just completely errors out.

**Comment by evazion** [comment]
Email is failing because Amazon SES is down at the moment: https://status.aws.amazon.com/.

Should probably use `deliver_later` for this, so that the mail is queued in a background job and can be retried on failure.

**Comment by OOZ662** [comment]
Is that also the reason all the DMails I've sent and received today claim the user's IP address is 127.0.0.1, or should I make a separate issue on that?

**Comment by evazion** [comment]
Make a separate issue, sounds like a different bug.
