### ISSUE TITLE
Post versions not being recorded

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2907]
Since 2017-03-01 00:05 UTC, post versions aren’t being recorded. From [post #2645087](https://danbooru.donmai.us/posts/2645087) onwards, posts have no tag history at all.

Edit: Nvm. Just noticed that it’s an artifact of the post versions being moved offsite. I guess the issues can stay until it’s working properly.

**Comment by r888888888** [comment]
I believe the archive database server was running out of disk space. I've upgraded it and things seem to be normal again.

**Comment by kittey** [comment]
Well, post versions are being logged again and it seems that the entries from the outage period are there too.

There's no merging of post versions, though.

**Comment by BrokenEagle** [comment]
It's been noted [on the forum](http://danbooru.donmai.us/forum_topics/9127?page=161#forum_post_127823), but post versioning appears to either have stopped or is lagging. The first time I checked, it was about ~30 minutes behind, so I assumed it had stopped as before, but when I refreshed the post_versions page again, it had processed a few more but was still ~30 minutes behind.

**Comment by OOZ662** [comment]
It's been over an hour since I last made some changes and they haven't appeared in my or the post's history yet.

**Comment by r888888888** [comment]
It was a typo with the queue processor. The fix was deployed and the queue is being processed again.
