### ISSUE TITLE
Re-enable post version merging

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2910]
I don't really understand why this was disabled, anyway. Is it too hard to replace a record in offloaded database? Either way, it seems to be an universal agreement in issues topic that versions without merging create too much clutter and put unnecessary pressure on taggers.

**Comment by evazion** [comment]
I think they could be stored unmerged in the db but merged on-the-fly for display purposes. Just before they're rendered in the view, do a pass over the array and merge consecutive edits by the same person into a single (unsaved) record.

Not merging them in the db does make the API easier to consume. As it was, if you were reading /post_versions.json you had to wait 2 hours after seeing an edit to be 100% sure the post version was finalized.

**Comment by Type-kun** [comment]
>I think they could be stored unmerged in the db but merged on-the-fly for display purposes. Just before they're rendered in the view, do a pass over the array and merge consecutive edits by the same person into a single (unsaved) record.

This doesn't work well with normal numbered pagination, unfortunately.

**Comment by r888888888** [comment]
The logic for it was kind of tricky because the diffs are stored now. I will re-enable it for pools first to see if it works correctly. The changes will have to be made in the Archives app.
