### ISSUE TITLE
Upload tags report lists extraneous parent: and source: metatags

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2911]
Example: http://safebooru.donmai.us/reports/upload_tags?page=1&user_id=337059
Notice how there's always a "parent:" in tags added by uploader, even if post has no parent.

I can't reproduce it on my development version, partly because I still have no idea how to set up archives without SQS - there really should be either a manual or a proper install script to set up archives locally.

**Comment by Type-kun** [comment]
The cause is likely https://github.com/r888888888/danbooru/blob/master/app/models/post_archive.rb#L152-L158 and two similar functions which doesn't check whether parent_id, rating or source is present. I don't want to change it blindly though.

**Comment by evazion** [comment]
IMO blank fields shouldn't be excluded, they should be listed as `parent:none` or `source:none` if not present.

**Comment by Type-kun** [comment]
I wouldn't agree with that as I like the old (current) way better, but either way it should be consistent.
