### ISSUE TITLE
Post Versions: extra changes attributed to me

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2918]
Some of my edits are showing up in Post Versions as including changes from the previous edit (which isn't even mine).  I was only adding `commentary_request` in the below posts:

* http://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2648178
* http://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2648186
* http://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2648149
* http://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2648161
* http://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2648150

**Comment by r888888888** [comment]
The current processing logic looks fine so I'm assuming something got messed up during the export (which had to stop and start a few times). Since the tags themselves look fine I'm going to regenerate the diffs for all changes in the past 30 days, which should be enough to fix this for reporting.

**Comment by RaisingK** [comment]
Okay then.
