### ISSUE TITLE
Post changes report doesn't work properly

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2919]
Searching for versions that added `a.i._channel` tag produces no results despite there being over 40 posts tagged with it, each having a version with said tag in "added tags". I highly suspect post archive to be the cause, but I can't know for sure.

**Comment by evazion** [comment]
The changes report uses big query instead of the archives. Looking at the table in big query, it appears it hasn't updated since 2017-02-27.

**Comment by r888888888** [comment]
The BQ export was stalled. I've started it up again.

**Comment by Type-kun** [comment]
Search for `a.i._channel` still doesn't produce any results though. Has it stopped again, or missing versions since 02-27 have not been repopulated?

**Comment by r888888888** [comment]
fixed in 79c0dc3
