### ISSUE TITLE
NoMethodError Exception for Uploads/Tag Changes

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2925]
Seems like the latest update broke some of the posts functions as [reported on Danbooru](http://danbooru.donmai.us/forum_topics/9127?page=165#forum_post_128465).

> Unbreakable said:
> 
> Trying to tag posts only gives me:
> 
> NoMethodError exception raised
> 
>     undefined method `each_value' for #<Array:0x007f6e215cab48> Did you mean? each_slice
>     app/models/post.rb:573:in `set_tag_counts'
>     app/controllers/posts_controller.rb:49:in `update'

> andalus said:
> 
> Need help, i can't upload, its error
> 
> Upload #1354642
> Date: 2017-03-18 08:52:26 +0700
> Source: http://i4.pixiv.net/img-original/img/2017/02/20/10/09/17/61549451_p11.png
> Tags: fate/grand_order fate_(series) fujimaru_ritsuka_(female) king_hassan_(fate/grand_order) eiri_(eirri) 1boy 1girl armor cloak comic greyscale highres horns hug long_sleeves monochrome skull speech_bubble translation_request weapon younger from_behind
> An error occurred: error: NoMethodError - undefined method `each_value' for [0, 0, 0, 0, 0, 1, 3, 3, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]:Array Did you mean? each_slice

**Comment by r888888888** [comment]
This has been fixed
