### ISSUE TITLE
No implicit conversion of nil into String

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#2940]
For some reason after updating today I get this error, I've tried finding what causes it but its so random that I have difficulty finding it.

The link that I'm certain that gives the error: http://atfbooru.ninja/posts?ms=1&page=4&tags=tagme&utf8=%E2%9C%93 Warning: NSFW.

```
TypeError exception raised

    no implicit conversion of nil into String
    app/presenters/presenter.rb:3:in `escapeHTML'
    app/presenters/presenter.rb:3:in `h'
    app/presenters/post_presenter.rb:91:in `data_attributes'
    app/presenters/post_presenter.rb:24:in `preview'
    app/presenters/post_set_presenters/base.rb:15:in `block in post_previews_html'
    app/presenters/post_set_presenters/base.rb:14:in `post_previews_html'
    app/views/posts/partials/index/_posts.html.erb:3:in `_app_views_posts_partials_index__posts_html_erb___4105440364023184004_69840399403520'
    app/views/posts/index.html.erb:39:in `_app_views_posts_index_html_erb__4550986712557394749_69840376209340'
    app/controllers/posts_controller.rb:16:in `index'

```

I've tried reverting back to before I updated and I'm still getting the error after that.

**Comment by evazion** [comment]
This is a bug I accidentally introduced in d1debecd0bb8b7ad1837be342923be587209bcc6. It's triggered by posts that have source that is NULL instead of the empty string. #2941 is the fix.

**Comment by Iratu** [comment]
Thanks, that seems to have resolved that issue.
