### ISSUE TITLE
/post_versions is extremely slow.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2951]
https://danbooru.donmai.us/post_versions has been really slow ever since switching to archives. This is a known problem but it should probably have an issue.

I had thought it was caused by N+1 issues, but `/post_versions` is still slow even after those were fixed. Yet `/post_versions?search[post_id]=1` and the upload tags report are not slow, it's just `/post_versions`.

Looking at the query log, I think it's because `/post_versions` is doing a sequential scan:

```sql

danbooru2_archive=# set enable_seqscan = off;
danbooru2_archive=# EXPLAIN SELECT "post_versions".* FROM "post_versions" WHERE (true) ORDER BY updated_at desc, id desc LIMIT 20 OFFSET 0;
                                           QUERY PLAN                                            
-------------------------------------------------------------------------------------------------
 Limit  (cost=10000000022.81..10000000022.86 rows=20 width=199)
   ->  Sort  (cost=10000000022.81..10000000023.69 rows=350 width=199)
         Sort Key: updated_at, id
         ->  Seq Scan on post_versions  (cost=10000000000.00..10000000013.50 rows=350 width=199)
(4 rows)
```

I think the `ORDER BY updated_at desc, id desc` clause is preventing it from using the `updated_at` index. I think it should either use only one of `id desc` or `update_at desc`, or it needs a multicolumn index on `(updated_at, id)`.

**Comment by Type-kun** [comment]
If postgres is anything like oracle in index handling, then multicolumn index will also be used with `ORDER BY updated_at desc` queries if there's any, so it might be better to switch to multicolumn index.

**Comment by evazion** [comment]
Should note that a similar problem affects `/pool_versions`. It does an `ORDER BY updated_at desc` but it doesn't have an `updated_at` index.

**Comment by r888888888** [comment]
I think the simplest solution here is to get rid of the id order clause. It shouldn't be needed with recent data anyway.

**Comment by evazion** [comment]
It looks like `updated_at` only has one second precision. So there are a lot of updates with the same timestamp that are listed in an undefined order.

**Comment by r888888888** [comment]
Actually maybe sorting by id only is good enough.
