### ISSUE TITLE
Prevent renaming wikis with non-empty tags.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2964]
From https://danbooru.donmai.us/forum_topics/13868?page=1#forum_post_129247:

If someone renames a wiki that has a non-empty tag, then that tag will still need to be moved and any wikis linking to the old wiki will need to be updated to the new wiki. Therefore there should be a validation that prevents renaming wikis with non-empty tags, to ensure that people fix the tag first. Possibly make it optional like secondary validations on BURs are optional.

**Comment by BrokenEagle** [comment]
It goes without saying, but the above should not prevent renames if the tag for the current wiki name is empty, i.e. they have already moved all of the tags to the new name.
