### ISSUE TITLE
Post versions not recorded when using pool:<name> metatag

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2972]
From https://danbooru.donmai.us/forum_topics/9127?page=173#forum_post_129631:

> I have noticed that sometimes after Moonspeaker has translated a post, the tag history bugs out.
If you check posts like post #2691343, post #2689658, post #2686074 you'll see that the original tagger has completely vanished. At least on my end.

> I think I noticed something like this on post #2687933 a few days ago; I found some erroneous character tags and was curious who had added them, but the Tag history didn't include the original tagger. Now it's fixed. Doing a quick check...okay, that's not right. The Tag histories of #2691343 and post #2689658 show me as the original tagger, which isn't true; I just translated them. I have no idea why this is happening.

Basically, sometimes the initial post version isn't created after upload. This happens when an upload is tagged with a `pool:<name>` metatag. Actually, any edit containing the `pool:` metatag doesn't save a post version.

This is a bug introduced by #2952. There I changed `create_version` to run inside an `after_commit` hook so that versions are sent only after the post has been successfully saved. But inside `after_commit` you can't use the `changes` hash to check for changes, because the post has already been saved. Instead you have to use `previous_changes`.

The problem is that `previous_changes` records only the set of changes performed by the most recent `save`. If a post is saved twice things go wrong. This is what happens:

\* post is tagged and sets `post.tag_string = "pool:1234 touhou"`
** `changes` now contains the changed tag string.
\* `post.save` is called. post is updated in the database.
** `changes` is now blank. `previous_changes` now contains the changed tag string.
\* `after_save` callbacks run
** `apply_post_metatags` runs
*** `add_pool!` runs
**** `pool_string` is set to `pool:1234`.
**** `update_column` updates the post's `pool_string`. `previous_changes` now contains the only the changed `pool_string`.
\* `after_commit` callbacks run
** `create_version` runs
*** `previous_changes` is checked and only the `pool_string` has changed, so a version isn't saved.

**Comment by evazion** [comment]
I guess #2952 should be reverted until this can be fixed. The problem is that `create_version` really ought to run only after all the other callbacks are successful, but if it runs after `apply_post_metatags` then the `changes` / `previous_changes` hashes will be clobbered and `create_version` won't work.

**Comment by r888888888** [comment]
If the ultimate goal is to fix the missing post error on the version listing, then it may be simpler to just assume the post linking may not exist.

One possible fix for this is to create a delayed job to send the message to SQS. That way if the transaction is rolled back the delayed job is reverted also.

**Comment by r888888888** [comment]
I've reverted #2952 for now.

**Comment by evazion** [comment]
> If the ultimate goal is to fix the missing post error on the version listing, then it may be simpler to just assume the post linking may not exist.

#2950 was discovered because of a failed upload but I think that's not the only time it can happen. If `apply_post_metatags` times out for whatever reason, then `create_version` shouldn't run or else it'll create a spurious post version.

> One possible fix for this is to create a delayed job to send the message to SQS. That way if the transaction is rolled back the delayed job is reverted also.

If that is done, then is even SQS necessary? Delayed job is a work queue, SQS is a work queue, so this would be two levels of queuing. I'm not sure why SQS is needed at all, a delayed job could insert the post version just as well.

**Comment by evazion** [comment]
In short: changing `after_save :create_version` to `after_commit :create_version` to fix #2950 broke other things. Not using `after_commit` here means #2950 is still broken.
