### ISSUE TITLE
Recover subscriptions lost due to migration bug

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2987]
Multiple users have already reported losing their subscriptions due to bug that's fixed in #2986. It should be possible to recover those from database backups prior to migration notice, if we have any. Opening the issue here so it doesn't get lost in the forums.

**Comment by r888888888** [comment]
I won't be able to do this until Monday but I will disable the backup pruner until then.

**Comment by Type-kun** [comment]
In that case, migration should also be disabled until then, to prevent more people losing their data. Or fixed, but then it will require smart recover instead of just replacing the subscription table contents with old version.

**Comment by r888888888** [comment]
They've been recovered now and AFAICT subscriptions were found for every user who sent me a message.
