### ISSUE TITLE
Wiki Autocomplete Misses On Certain Meta-wikis

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2990]
I noticed this the other day when trying to go to the "List of Meta-Wikis" wiki.  Autocomplete couldn't find it, so I ended up typing out the whole thing.

After looking into it a bit further, it seems that the URL addon "search[order]=post_list" reduces the amount of wikis that are returned by a query. I did a comparison using the search string "list_of_*" with and without the above addon, and the following are the list of wiki ID's that aren't included when "search[order]=post_count" is used.

{[wiki #85505](http://danbooru.donmai.us/wiki_pages/85505), [wiki #36875](http://danbooru.donmai.us/wiki_pages/36875), [wiki #54807](http://danbooru.donmai.us/wiki_pages/54807), [wiki #85275](http://danbooru.donmai.us/wiki_pages/85275), [wiki #77099](http://danbooru.donmai.us/wiki_pages/77099), [wiki #78380](http://danbooru.donmai.us/wiki_pages/78380), [wiki #64820](http://danbooru.donmai.us/wiki_pages/64820), [wiki #65845](http://danbooru.donmai.us/wiki_pages/65845), [wiki #74044](http://danbooru.donmai.us/wiki_pages/74044), [wiki #85849](http://danbooru.donmai.us/wiki_pages/85849), [wiki #70245](http://danbooru.donmai.us/wiki_pages/70245), [wiki #78438](http://danbooru.donmai.us/wiki_pages/78438), [wiki #76647](http://danbooru.donmai.us/wiki_pages/76647), [wiki #60526](http://danbooru.donmai.us/wiki_pages/60526), [wiki #65906](http://danbooru.donmai.us/wiki_pages/65906), [wiki #68214](http://danbooru.donmai.us/wiki_pages/68214), [wiki #82807](http://danbooru.donmai.us/wiki_pages/82807), [wiki #74111](http://danbooru.donmai.us/wiki_pages/74111), [wiki #71571](http://danbooru.donmai.us/wiki_pages/71571), [wiki #60564](http://danbooru.donmai.us/wiki_pages/60564), [wiki #60565](http://danbooru.donmai.us/wiki_pages/60565), [wiki #62620](http://danbooru.donmai.us/wiki_pages/62620), [wiki #60583](http://danbooru.donmai.us/wiki_pages/60583), [wiki #76972](http://danbooru.donmai.us/wiki_pages/76972), [wiki #52142](http://danbooru.donmai.us/wiki_pages/52142), [wiki #68017](http://danbooru.donmai.us/wiki_pages/68017), [wiki #75746](http://danbooru.donmai.us/wiki_pages/75746), [wiki #58596](http://danbooru.donmai.us/wiki_pages/58596), [wiki #80359](http://danbooru.donmai.us/wiki_pages/80359), [wiki #74221](http://danbooru.donmai.us/wiki_pages/74221), [wiki #81138](http://danbooru.donmai.us/wiki_pages/81138), [wiki #82679](http://danbooru.donmai.us/wiki_pages/82679), [wiki #84987](http://danbooru.donmai.us/wiki_pages/84987)}

I didn't test, but I imagine similar results with the other types of meta-wikis.

**Comment by evazion** [comment]
Right, I see the problem. What's happening is that `search[order]=post_count` causes an inner join with the tags table to get the post count, but an inner join excludes wikis and don't have a tag. It should be a left outer join instead.
