### ISSUE TITLE
Artist URL breakdown

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2993]
It would be useful to have a domain breakdown of all uploads for a specific artist.

**Comment by evazion** [comment]
Something like this could work for the query:

```ruby
Post.tag_match("hammer_(sunset_beach)").reorder(nil).pluck("distinct substring(source from 'https?://([^/]*)')")
```

That includes subdomains though, which adds some noise.

**Comment by r888888888** [comment]
I think aggregating artist urls would be faster and provide good enough results.
