### ISSUE TITLE
Nginx throttle still causing trouble

### ISSUE THREAD

**Issue by ROMaster2** [r888888888/danbooru#2996]
I mentioned in the Danbooru 2 Issues Topic several times the Nginx throttle has been causing problems for me. Images don't want to load, load halfway and stop, take way longer than they should, etc.

**Comment by kittey** [comment]
Images not loading at all on the first try happened to me only once or twice, but I’ve been having several images load only halfway as well. The larger the image, the more likely it is to break.

**Comment by r888888888** [comment]
I've tried increasing the rate limit.

**Comment by ROMaster2** [comment]
Still running into the same problems. I think it has more to do with the one per second throttle.

**Comment by r888888888** [comment]
I'm curious how you open images. Do you open multiple posts at once? There is a 1 req/sec limit but the burst factor is at 5.

**Comment by ROMaster2** [comment]
I usually tab them while going through the posts. I have a basic script that loads changes the tab to the image with a back option:
`location.assign($("#image").eq(0).attr("src"))`

**Comment by Tsubasaza** [comment]
https://puu.sh/vUpCA/15877228fa.jpg

Encountering the same issues too
