### ISSUE TITLE
Post moved to S3 but has old image urls

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3020]
The above affects the following post.

http://danbooru.donmai.us/posts/100000.json

As can be seen, the above post currently uses the following image URLs.

/data/3109d63ee7b968897e8a2c74a3e39f00.jpg
/data/sample/sample-3109d63ee7b968897e8a2c74a3e39f00.jpg

They should be migrated to the S3 version.

/cached/data/3109d63ee7b968897e8a2c74a3e39f00.jpg
/cached/data/sample/sample-3109d63ee7b968897e8a2c74a3e39f00.jpg

Also, what's the preferred method for reporting this in the future. I imagine this could potentially happen again as more images get moved to S3.

**Comment by r888888888** [comment]
You can just update this ticket.

**Comment by r888888888** [comment]
fixed

**Comment by BrokenEagle** [comment]
[Post #13303](https://danbooru.donmai.us/posts/13303).
[Fullsize image](https://danbooru.donmai.us/cached/data/ba6f4d3cd1f3829aa445690f06d0b96e.jpg) works fine.
[Sample image](https://danbooru.donmai.us/cached/data/sample/sample-ba6f4d3cd1f3829aa445690f06d0b96e.jpg) produces the following error output:
```
<Error>
<Code>InvalidObjectState</Code>
<Message>
The operation is not valid for the object's storage class
</Message>
<RequestId>82008A759D3AB80B</RequestId>
<HostId>
faLfTGpIxoIgsOMdtozeJ2G4QqbAz6U9LAQ18hK1KMMwv3Ur1v2MqRZcTAd4O8T0UsMldXMaBS4=
</HostId>
</Error>
```

**Comment by evazion** [comment]
https://danbooru.donmai.us/posts/36112
https://danbooru.donmai.us/cached/data/sample/sample-ba7849eb50e9ec5d683de3a19e2c3961.jpg

**Comment by r888888888** [comment]
I've regenerated these two.

**Comment by evazion** [comment]
https://danbooru.donmai.us/posts/39871
https://danbooru.donmai.us/cached/data/sample/sample-930e419cc73a089cee74ba2640bd548e.jpg
