### ISSUE TITLE
XML representation of own user produces invalide results after merging #3011

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3024]
After #3011, XML version of your own account no longer produces valid XML, due to `can-comment-vote?` and other similar methods ending in question mark being exposed. XML doesn't allow question marks in element names, and multiple parsers I've tried give the error.

**Comment by evazion** [comment]
I'm surprised that `to_xml` allows you to generate broken XML at all instead of producing an error. I couldn't figure out any way to make `to_xml` do the right thing, so #3024 just overrides `serializable_hash` to strip these characters out.
