### ISSUE TITLE
Test failures under ruby 2.4

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3039]
Many source tests fail when running under ruby 2.4:

```ruby
  1) Error:
Sources::ArtStationTest#test_: The source site for an art station artwork page should get the artist name. :
NoMethodError: undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
Did you mean?  <
    app/logical/sources/strategies/art_station.rb:32:in `block in get'
    app/logical/sources/strategies/art_station.rb:31:in `get'
    app/logical/sources/site.rb:6:in `get'
    test/unit/sources/art_station_test.rb:8:in `block (2 levels) in <class:ArtStationTest>'
    test/unit/sources/art_station_test.rb:30:in `block in create_test_from_should_hash'
```

This seems to be caused by an incompatibility between fakeweb and ruby 2.4. Fakeweb hasn't had any commits for 4 years and is apparently unmaintained, so perhaps it would be better to use another gem.

https://github.com/chrisk/fakeweb/issues/57
https://github.com/chrisk/fakeweb/pull/60

**Comment by r888888888** [comment]
I've replaced Fakeweb with Webmock.

**Comment by evazion** [comment]
f8ed7d4 fixed a bug with the source tests failing caused by Webmock disabling non-stubbed HTTP requests by default.
