### ISSUE TITLE
Bad Linebreak in Install Script File (and other installation issues)

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3041]
1. Been going through the install process on Ubuntu, and line [52-53](https://github.com/r888888888/danbooru/blob/master/script/install/nginx.danbooru.conf#L52) was causing issues due to the "\" line continuation right in the middle of a variable.  Basically, it was causing Nginx to fail to restart.  After removing the above and rejoining the line, then running init.d, I was successfully able to get it to restart.

**Comment by BrokenEagle** [comment]
On Ubuntu, when running `bundle exec rake db:create db:migrate"`, I was running into the issue where it said that it couldn't find `config/database.yml`, and then later on `danbooru_local_config.rb`, even though I double checked and they were both in `/var/www/danbooru2/shared/config/`.  I ended up having to move both config files into the config directory in my local danbooru repository, which is where I ran the bundle command from.

After moving it, I was able the bundle command successfully.

**Comment by Type-kun** [comment]
>When running  bundle exec rake db:create db:migrate" , I was running into the issue where it said that it couldn't find  config/database.yml , and then later on  danbooru_local_config.rb , even though I double checked and they were both in  /var/www/danbooru2/shared/config/ . I ended up having to move both config files into the config directory in my local danbooru repository, which is where I ran the bundle command from. After moving it, I was able to use the above bundle command successfully.

IIRC you're supposed to migrate using capistrano if you go the install script way. Either way, the script is unfit for development purposes, as it is created with "deploying to external server" in mind and therefore creates a lot of entities unnecessary if you want to run your dev copy on the local machine. Capistrano isn't required to get your instance up and running, you can easily avoid creating "danbooru" system user, etc. I've actually thought about creating a separate script or manual for developers, for a long time: a lot of install script directives can be ignored, but there's just a few extra steps.

**Comment by BrokenEagle** [comment]
That would be a great help, as there are probably others that also want to do development as well.

Also, after looking over some of the previous issues, I was running into many of the exact same issues as tmannen in issue #3012, including needing to install ruby-dev to get bcrypt to install.  

Overall, the install script(s) could probably use a refresh...
