### ISSUE TITLE
Artist Lookup Failing on Creating/Editing a Post for Pixiv Users Due to Changing Usernames

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3048]
It's been noted on the [Danbooru Forum](http://danbooru.donmai.us/forum_posts/131246) that artist lookups for Pixiv are starting to fail.  The main reason for this is that users can change their usernames on Pixiv, and the artist finder currently uses the username I believe...?  It should instead use the user ID, which is unchangeable.

The user ID can be found in the follow type of link:

https://www.pixiv.net/member.php?id=20021325

But due to the large variability to the Pixiv user link, the following is an example of what I've been using to grab the user ID.
```
^https?://(?:(?:www|touch)\.)?pixiv\.net/(?:member|mypage)\.php[?#]id=(\d+)
^https?://www\.pixiv\.net/whitecube/user/(\d+)
```
Though the above could probably be combined...

**Comment by AraHaan** [comment]
I agree with using the id's instead.

**Comment by evazion** [comment]
#3060 changes the finder to matching against the member ID. The artist entry must have a URL of the form `http://www.pixiv.net/member.php?id=339253`. It must have one for each Pixiv account the artist has. It must be that form exactly; other forms like `https://www.pixiv.net/member_illust.php?id=339253` won't work. 

Artist entry URLs of the form `http://i1.pixiv.net/img01/img/bkubb/` are no longer used by the artist finder, with one exception. If an older post has a source of that form, and the post is bad_id, then we can't look up the Pixiv member ID, so we fall back to matching the username as we currently do.

For example: [post #2468645](https://danbooru.donmai.us/posts/2468645) has source `http://i1.pixiv.net/img27/img/s832241/11880659.jpg`, which is deleted and so can't be resolved to a Pixiv member ID. The finder falls back to matching `http://i1.pixiv.net/img27/img/s832241/`, which matches [binzoko megane (san-inch)](https://danbooru.donmai.us/artists/14427).
