### ISSUE TITLE
Pictures not loading properly

### ISSUE THREAD

**Issue by FunkyGamer** [r888888888/danbooru#3051]
Hello there!
I've just managed to setup my own Danbooru on my server.
Afterwards I've upload a picture to test it out.
However I'm now encountering a strange problem.

If I look at it via the posts homepage, everything is fine. Meaning a thumbnail is shown.
However if I now click on it, the picture just won't load.
Downloading the picture doesn't work either.
Inspecting the page with the browser, it seems like Danbooru is trying to load the pictures from **/cached/data/...** instead of **/data/...**
If I change that url to the said /data/... using the browser manipulation, the picture loads just fine.

So, where is that /cached inserted into the url and why?
Is there any way to disable that behaviour, because it seemingly doesn't work that way?
What am I missing?

**Comment by evazion** [comment]
`use_s3_proxy?` inside `danbooru_default_config.rb` is what's causing this behavior. Change that to return `false`. See #2500 for the issue discussing this feature.

**Comment by FunkyGamer** [comment]
@evazion Thanks, that fixed my problem!
I already figured it would be something like the S3 thing, but only did find the S3 entries further down the file and those were all set to false already. The s3 proxy thing was the one I had to disable, thanks
