### ISSUE TITLE
Add "General" button for related tags on new/edit posts

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3061]
There should be a button for general tags.  The vanilla option for many tags is overwhelmed by copyright/character tags, yielding a minimal number of general tags to choose from.  One current workaround is to use the related tags page, however that approach is a bit unwieldy.

**Comment by evazion** [comment]
#3093 adds this and #3092 fixes an issue with related tags being slow to calculate.

Note that the `General`/`Artist`/`Character`/`Copyright` buttons and the `Related tags` button use different algorithms for calculating related tags. The `General` button gives you the most frequently occurring tags, while the `Related tags` button gives you the most similar tags as determined by [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity). Frequent tags tend to include universal tags like `1girl`, `solo`, `bad_id`, whereas cosine similarity tends to filter these things out.

**Comment by BrokenEagle** [comment]
> Frequent tags tend to include universal tags like 1girl, solo, bad_id, whereas cosine similarity tends to filter these things out.

True, but like I mentioned, many times the number of character/copyright tags returned by Related tags tend to overwhelm many if not most of the general tags.  Often, simple things you would expect like hair color and eye color, not to mention clothing items, don't even make it to the list.

Would it be beneficial though to do a cosine similarity for the different tag categories in addition to what's being done now...?  It's true that it wouldn't work for searches that aren't tag instances, but I imagine that >95% of the `related_tags` usage are for single tags queried from the post edit box.

**Comment by evazion** [comment]
> True, but like I mentioned, many times the number of character/copyright tags returned by Related tags tend to overwhelm many if not most of the general tags. Often, simple things you would expect like hair color and eye color, not to mention clothing items, don't even make it to the list.

Well, I just wanted to make it explicit that the `General` button and the `Related tags` button do different things. It isn't very clear from using these buttons that `General` is not just `Related tags` minus character/copyright tags.

> Would it be beneficial though to do a cosine similarity for the different tag categories in addition to what's being done now...? It's true that it wouldn't work for searches that aren't tag instances, but I imagine that >95% of the related_tags usage are for single tags queried from the post edit box.

This should probably be it's own issue. The simplest thing to do would be to raise the cutoff from 25 related tags to something higher, so that more general tags can be included. This would make the tags table bigger though, and hence make other things that use that table slower.
