### ISSUE TITLE
Images wont load at all

### ISSUE THREAD

**Issue by Tsubasaza** [r888888888/danbooru#3064]
Images wont load at all, tried it with different browsers and it's giving me the exact same error. This is what it looks like.

https://puu.sh/vUpCA/15877228fa.jpg

**Comment by Tsubasaza** [comment]
Sometimes it loads, sometimes it says "picture doesn't exist".

**Comment by r888888888** [comment]
Can you paste the URL of the image?

**Comment by Tsubasaza** [comment]
https://danbooru.donmai.us/posts/178794
https://danbooru.donmai.us/posts/147410
https://danbooru.donmai.us/posts/68794

It's not just these few images, it's over thousand images.

**Comment by Tsubasaza** [comment]
Any news on solving this? it's pretty annoying and it wasn't a problem until a month ago or so.

**Comment by r888888888** [comment]
Those pages work for me. Can you link the image URL, not just the page?

**Comment by Tsubasaza** [comment]
https://danbooru.donmai.us/posts/68794 
https://danbooru.donmai.us/data/70cd9036fa50466c3147b10ade76af68.jpg
https://puu.sh/vZZym/1ccfe779b0.jpg

=/

**Comment by Type-kun** [comment]
Yeah, the direct link is wrong. It should be https://danbooru.donmai.us/cached/data/70cd9036fa50466c3147b10ade76af68.jpg instead, since the image is offloaded to S3 already.

Are you using any kind of userscripts? Those might affect the links.

**Comment by evazion** [comment]
Pretty sure this is a bug in [Better Better Booru](https://github.com/pseudonymous/better-better-booru). See https://github.com/pseudonymous/better-better-booru/issues/78.

**Comment by evazion** [comment]
Closing as this is a bug in Better Better Booru.
