### ISSUE TITLE
<div> id incorrect for certain controllers

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3065]
I was trying to develop some CSS for various controllers, and I noticed that some were using the incorrect <div> id.  The ones I could find like this were **wiki_page_versions** and **pool_versions**, which used **c-wiki-pages** and **c-pools** instead of **c-wiki-page-versions** and **c-pool-versions**.

Changing the above might also require updating the CSS since the current version pages might be relying on `#c-pools` or `#c-wiki-pages`.

**Comment by evazion** [comment]
There was some CSS that had to be moved for `#c-wiki-page-versions`, but `#c-pool-versions` looked okay.

**Comment by BrokenEagle** [comment]
Found another page that needs updating... the Flags & Appeals from the posts controller.

Example:
http://danbooru.donmai.us/posts/2726434/events

It currently is **c-post-flags**, but should be **c-post-events** instead.

Another possibility could be **c-posts** with **a-events**...

**Comment by BrokenEagle** [comment]
And found another one... The Upload tag changes report.

Example:
https://danbooru.donmai.us/reports/upload_tags?user_id=23799

It currently is **c-post-versions**, but could be **c-reports-upload-tags**.

Another possibility could be **c-reports** with **a-upload-tags**.

**Comment by evazion** [comment]
I'm standardizing on using the same name as the controller class, so I went with `c-post-events` and `c-upload-tags-report`.

**Comment by BrokenEagle** [comment]
Found a few more....

- https://danbooru.donmai.us/explore/posts/popular
- https://danbooru.donmai.us/explore/posts/searches
- https://danbooru.donmai.us/explore/posts/missed_searches

They all use #c-explore-posts #a-index.  Instead, they could probably use...

- #c-explore-posts #a-popular
- #c-explore-posts #a-searches
- #c-explore-posts #a-missed-searches

**Comment by evazion** [comment]
Fixed those.

**Comment by BrokenEagle** [comment]
Found a few more...

**/bans/new** uses `#bans #new` instead of `#c-bans #a-new`
**/user_revert/new** uses `#c-users #a-new` instead of `#c-user-reverts #a-new`
**/user_upgrade/new** uses `#c-users #a-upgrade-information` instead of `#c-user-upgrades #a-new`
**/static/terms_of_service** uses `#terms-of-service #section` instead of `#c-static #a-terms-of-service`

Not sure how to handle the following...

**/moderator/ip_addrs?search[user_name]=
/moderator/ip_addrs?search[ip_addr]=**

Both use `#c-moderator-ip-addrs #a-index`, even though both present different tables.

Speaking of which **/wiki_page_versions** tables change depending on whether **search[wiki_page_id]** is added or not.  I was able to get around it in the mobile CSS layout I posted to the forums by using "nth-last-of-type()", but I can't imagine it will always be that easy a workaround.

**Comment by evazion** [comment]
Fixed `/bans/new`, `/user_revert/new`, `/user_upgrade/new`, and `/static/terms_of_service`.

> Not sure how to handle the following...

> /moderator/ip_addrs?search[user_name]=
/moderator/ip_addrs?search[ip_addr]=

I added `#p-ip-listing` and `#p-user-listing` ids to distinguish between these pages. The mnemonic is P for [partial](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials), in keeping with C for controller and A for action.

For wiki page versions I added `#p-page-listing` (when showing a single page's history) and `#p-global-listing` (when showing the global history).
