### ISSUE TITLE
Add wildcard * support for other names on wiki search.

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3070]
Often, an artist commentary will only have a first or last name, or even just part of a first name in in the case of nicknames.  Currently, there is no way to search on Danbooru for anything other than exact matches.  This most often affects Twitter commentaries, as there are usually no tags available to pull, so the user is entirely reliant on the commentary to try to find a character if unknown.  For those cases, I currently have to go to Pixiv and other sources to find the character.

**Comment by evazion** [comment]
Other names can contain asterisks themselves. An example is [Amairo Islenauts](https://danbooru.donmai.us/wiki_pages/47885) (Other name: `天色*アイルノーツ`). So searches would need to have syntax for escaping literal asterisks, and for consistency this should apply for all wildcard searches.

**Comment by BrokenEagle** [comment]
What about the Regex dot-star combination, i.e....

#  .*

Before the above gets implemented, we can search for and fix any existing instances, then just forbid any future entries from having that particular combination.

Thoughts?

**Comment by evazion** [comment]
I realized there are only ~15 or so wiki pages that have an other name containing a `*`, so #3070 goes ahead and adds the wildcard search. Escaping wildcards is really an issue in itself, so I'll leave that to another issue.
