### ISSUE TITLE
Remove superfluous image links on new artist from Pixiv

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3078]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=186#forum_post_131642):

> Provence said:
> Regarding artists and Pixiv: We used to include a direct URL to an image.
> Since a direct URL is added automatically when creating a new artist, is it ok that a direct URL is not added (since it seems superfluous and doesn't help anymore)?

> BrokenEagle98 said:
> Well, there used to be a reason, when the image URL was normalized (under the hood) to be of the format "http://img.pixiv.net/img/USERNAME/". However, it's now normalized as "http://www.pixiv.net/member.php?id=ID_NUMBER" which is already being added anyways. So yeah, there's no longer any reason to keep it around.

**Comment by r888888888** [comment]
Is it safe to just delete these from the database?

**Comment by evazion** [comment]
https://danbooru.donmai.us/artist_versions?search%5Bupdater_id%5D=13506

@RaisingK's bot still adds these `http://img.pixiv.net/img/$username/` URLs. If they were removed it would likely try to add them all back.

IMO the bot should either add the Pixiv username to the Other Names field, or maybe add it as an `http://www.pixiv.me/$username` URL. Either way, adding `http://img.pixiv.net/img/$username/` URLs is no longer necessary.

**Comment by RaisingK** [comment]
I've taken that part out now.
