### ISSUE TITLE
Counts not updating properly

### ISSUE THREAD

**Issue by FunkyGamer** [r888888888/danbooru#3079]
Hello there!
I've encountered a problem with the several counters on my own Danbooru.

The tag counters don't seem to work at all, meaning every single tag I used is saying it does contain 0 posts. I mean I can search for a tag, that works, but the number next to it just says 0 all the time.

Also the posts counter seems to update reaaaaally slow. I've uploaded some pictures yesterday and it took the counter until today evening to actually show the new number of posts.

Is this behaviour normal?
How do I fix the tag counter?
It's not really a function breaking bug, but it certainly is kind of annoying, not being able to see the amount of pictures with a certain tag.

**Comment by r888888888** [comment]
You need to run the DelayedJob background worker. Typically this is done during the Capistrano deployment but if you are running locally you can find an example command in Procfile.

**Comment by FunkyGamer** [comment]
Alright, so if I have this running in the background, everything should be updated accordingly if new posts are made?

How often does the overall post counter update though? immediately?

**Comment by FunkyGamer** [comment]
@r888888888 Thank you very much!
This solved my problem.
I'm deploying it locally, so I had to use the according command.
Maybe you should add that to the install instructions, in case other people experience the same issue.
