### ISSUE TITLE
ATOM discovery link issues

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3081]
After adding a few posts as sources for comments, I realize that the current method is somewhat inconvenient.  Right now, if I have a post whose comments I want to track, I have to go over to an alternate tab and type in "http://danbooru.donmai.us/comments?group_by=comment&search[post_id]=POSTID", let the page load, and then add the auto-discovered link to my list of feeds. Or alternatively, just type the ATOM link directly into the feed application (or URL bar) and add it that way.

Instead, it would be nice if there was an auto discovery link on the post page itself.  So basically, add the line in the [Index by Comment view](https://github.com/r888888888/danbooru/blob/master/app/views/comments/index_by_comment.html.erb#L33) into the the [Posts Show view](https://github.com/r888888888/danbooru/blob/master/app/views/posts/show.html.erb) somewhere.

Also, would it be useful to add a submenu to the Post Show menu giving the option to Subscribe to the conversation.  Or it could also be added to the Options menu.

**Comment by BrokenEagle** [comment]
Found an issue with the forum topic ATOM discovery link.  Currently the link is visible to feed detectors, but they are unable to add it since the link provided is invalid.

`<link rel="alternate" type="application/atom+xml" title="Artist tagging help" href="http://danbooru.donmai.us/forum_topics.8199" />`

As can be seen above, the href is wrong.  It should instead be http://danbooru.donmai.us/forum_topics/8199.atom.

**Comment by evazion** [comment]
> Also, would it be useful to add a submenu to the Post Show menu giving the option to Subscribe to the conversation. Or it could also be added to the Options menu.

Eh, these menus are already a little crowded IMO, so I'm not too keen on further crowding them with a niche option that I think few people would use.
