### ISSUE TITLE
Inconsistency between pool_string and pool.post_ids.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3091]
https://danbooru.donmai.us/forum_topics/9127?page=187#forum_post_131773:

> For some reason, this page shows less posts than the pool actually has:
http://danbooru.donmai.us/pools/12394
E: It works now. Had to remove all posts from the pool first, though.

> I ran into the same/similar thing at [pool #11990](https://danbooru.donmai.us/pools/11990) yesterday with some posts having the pool at the bottom but with both "<prev" and "next>" grayed out but « and » still works, the pool only appears to have 5 posts when you view it too. I don't know what order the posts should be in so I haven't touched it.

5 posts: https://danbooru.donmai.us/pools/11990
15 posts: https://danbooru.donmai.us/posts?tags=pool:11990

The posts in this pool have the pool in their `pool_string`, but the pool doesn't have these posts in its `post_ids` list.

**Comment by evazion** [comment]
The pool add/remove code has two issues:

* Adding a post to a pool isn't transactional, since updating the pool and updating the post are separate actions. If there is a timeout in the middle of adding a post, then hypothetically the post would be half-added to the pool.

* Adding a new id to the pool's `post_ids` isn't atomic, so if two posts are added to a pool at the same time, one update could clobber the other. This could happen if the user uses a `pool:1234` tag script to batch add posts to a pool.

#3095 wraps everything in  `with_lock do ... end` blocks, which I believe solves these concurrency issues.

**Comment by BrokenEagle** [comment]
What would be the best way to handle post/pool discrepencies after this gets fixed...?  Unfortunately, I don't think the above can  be handled automatically, especially if order matters.  Maybe find every instance of the above situation and post it to a thread on Danbooru...?  That way, others could help out.
