### ISSUE TITLE
Post flags using LOCALHOST IP address for all users

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3096]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=187):

> Log said:
> Every flagger ip in the queue is listed as 127.0.0.1, I don't think this is intentional?

> BrokenEagle98 said:
> Is this for every creator of a flag, or is it only for DanbooruBot...?

> Log said:
> Every flag currently in the queue.
>
>http://imgur.com/D8UnGJk

**Comment by r888888888** [comment]
For some reason that field is defaulted to 127.0.0.1 in the schema.
