### ISSUE TITLE
Some additional ATOM fixes

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3098]
Just a few minor touch-ups needed.  The following were tested with both RSS Feed Reader for Chrome and feedly.com.

1. Fix for the alternate link
Currently, clicking on the ATOM link title takes the user to the Danbooru main page instead of the relevant comments search or forum topic, however, this is not the case for the already established posts ATOM feed.  Comparing the different versions, it seems like it's the alternate link that is causing the issue.
**Posts:**
`<link href="http://danbooru.donmai.us/posts?tags=girls_und_panzer" rel="alternate"/>`
**Comments/Forum topic:**
`<link rel="alternate" type="text/html" href="http://danbooru.donmai.us"/>`

2. `<id>` link format
I don't know if this is causing or will cause issues, but these are some additional discrepancies to the above.
a. Main `<id>` value
**Posts:**
`<id>http://danbooru.donmai.us/posts.atom?tags=girls_und_panzer</id>`
**Forum topic (show):**
`<id>tag:danbooru.donmai.us,2005:/forum_topics/9127</id>`
**Comments:**
`<id>tag:danbooru.donmai.us,2005:/comments</id>`
b. Each `<entry> <id>` value
**Posts:**
`<id>http://danbooru.donmai.us/posts/2739452</id>`
**Forum topic (show):**
`<id>tag:danbooru.donmai.us,2005:ForumPost/85923</id>`
**Comments:**
`<id>tag:danbooru.donmai.us,2005:Comment/1698812</id>`

3. Forum topic (index):
Not sure how useful this feed is.  It always shows the stickied topics first, plus it only shows the first forum post of each topic in the feed.

**Comment by r888888888** [comment]
I don't think issue 2 causes problems since AFAIK it's only used to track which entries have been read or not. As long as it's unique it shouldn't cause problems.

**Comment by BrokenEagle** [comment]
Does the comments fix in the above commit account for search terms appended to the URL, such as `search[creator_id]`, `search[post_id]` or `search[post_tags_match]`...?
