### ISSUE TITLE
Add support for NicoSeiga API

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3100]
Brought up [on the Danbooru forum](https://danbooru.donmai.us/forum_topics/9127?page=188#forum_post_131989):

> Provence said:
> Is there a reason why Danboorru can't fetch the artist on post #2740760?
> Artist has a Seiga link.

> BrokenEagle98 said:
> AFAIK the artist finder has never been implemented for NicoSeiga. From what I was able to uncover online, little is known about the NicoSeiga API as opposed to its better known [implementation on NicoNico](http://dic.nicovideo.jp/a/%E3%83%8B%E3%82%B3%E3%83%8B%E3%82%B3%E5%8B%95%E7%94%BBapi). However, I was able to discover the following NicoSeiga API endpoint.
> 
> http://seiga.nicovideo.jp/api/illust/info?id=6357840
> 
> It returns XML though instead of JSON, but you still get the artist ID which should allow an artist finder to work. Additionally, it would allow the artist commentary to be pulled, which currently doesn't work either.

So basically....

- [ ] 1. Add support for NicoSeiga API
- [ ] 2. Implement artist finder for NicoSeiga
- [ ] 3. Implement artist commentary for NicoSeiga

**Comment by r888888888** [comment]
Wow, it doesn't even require authentication. I wonder how long they'll keep it up.

**Comment by BrokenEagle** [comment]
It's been there fore the last several months from when I first found it.
