### ISSUE TITLE
Fetch source data: syntax error in tsquery

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3102]
* https://danbooru.donmai.us/source.json?url=https%3A%2F%2Fi.pximg.net%2Fimg-original%2Fimg%2F2017%2F05%2F31%2F14%2F46%2F30%2F63154991_p0.png

```
ERROR: syntax error in tsquery: "'클로저스' | 'closers' | 'クローザーズ' | '티나' | 'tina' | 'ティナ' | 'https://www.pixiv.net/' | '銃' | 'CLIP STUDIO PAINT' | 'https:' | '' | 'www.pixiv.net'"
```

**Comment by BrokenEagle** [comment]
I wonder if it's the URL in the tag list that is causing the issue...?  It also seems like it's trying to break it apart according to the fix in #2915.
