### ISSUE TITLE
Saved Searches with -comic not populating

### ISSUE THREAD

**Issue by OOZ662** [r888888888/danbooru#3106]
I have a couple sets of saved searches which include "character -comic" searches. These results will never show up in the whole of the saved search's results. This is most notable in my Kantai Collection set, which has 14 "character -comic" entries and 2 "character" entries; only the two without the negated tag appear in the results.

**Comment by r888888888** [comment]
Important to note that listbooru is searching for 1000 posts at a time. I'll add some extra logging to help debug this.

**Comment by BrokenEagle** [comment]
@evazion brought up the fact on Discord that he was able to get results to show up by having a single saved search in its own category.

- tenryuu_(kantai_collection) -comic

Going back to the **Kantai_Collection** category I have set up with OOZ662's saved searches, I now saw that the character **Tenryuu** was now being populated.  Additionally, **Yura** was also being populated, so I'm guessing that either evazion or someone else added `yura_(kantai_collection) -comic` to its own category as well.  As a test, I added `nagato_(kantai_collection) -comic` to its own category ***kantai_collection_1C*** while still keeping it in the ***kantai_collection*** category, and within several minutes, **Nagato** started being populated in both ***kantai_collection_1c*** and ***kantai_collection***.

As a final test, I added my own modified version `tenryuu_(kantai_collection) -comic -zilch` to its own category ***kantai_collection_2a*** while also keeping it in ***kantai_collection_2***, and within several minutes it was now being populated in both saved searches as well.

As a thought, is it possible that the combination of all of those high post count Kantai Collection characters are returning too many results causing something to choke somewhere, and only when it is handing those characters individually for those individual categories is it able to return things properly...?

**Comment by r888888888** [comment]
I see from the logs that sometimes there's a 502 error from Cloudflare. Occasionally there's a statement timeout. I will add a retry mechanic and see if that helps.
