### ISSUE TITLE
Fix Artstation URL issues

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3108]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/13057?page=3#forum_post_132143):
> chinatsu said:
> 
> For anyone using the artist subdomain (IE https://dantewontdie.artstation.com/projects/YZK5q as opposed to https://www.artstation.com/artwork/YZK5q), the artist commentary will not be fetched using the Danbooru bookmarklet or the tool for fetching commentary from the post page.
> 
> Additionally, a user in ArtStation can fairly easily change their subdomain. When an artist changes that domain it will result in all the source links to the old one becoming bad artstation ids.

So, fix URLs of the format `https://*.artstation.com/projects/YZK5q` so that...

1. They instead show `https://www.artstation.com/artwork/YZK5q` in the sidebar.
2. The artist commentary can be fetched.

**Comment by evazion** [comment]
> They instead show https://www.artstation.com/artwork/YZK5q in the sidebar.

This remains to be done.
