### ISSUE TITLE
Access denied for replaced images hosted on S3

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3115]
These images are broken:

https://danbooru.donmai.us/posts/880067
https://danbooru.donmai.us/posts/898031

https://danbooru.donmai.us/cached/data/4247ae247f96e980b9143da1528ca8dd.png
https://danbooru.donmai.us/cached/data/5920b4bfb85dda7bfe175ba43cd9d10f.png

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>F7E62421D2E78149</RequestId>
  <HostId>
    zFpcQFh4ucjIc2FEqpM+R8jmnANMZfPHkTlDWJpYc8xuTV+yI5FoGAUFcQKUL9tSKz1B6fSpSow=
  </HostId>
</Error>
```

Bad permissions on S3?

**Comment by evazion** [comment]
This seems to affect any replaced post below id 1000000:

* https://danbooru.donmai.us/comments?group_by=comment&search%5Bcreator_name%5D=DanbooruBot&search%5Bpost_tags_match%5D=id%3A..1000000

**Comment by r888888888** [comment]
A combination of factors i think. The refactored s3 uploader wasnt setting the ACL to public-read, AND it was uploading to the wrong directory for samples. This can all be fixed but it'll take some time to update/move the files over.

**Comment by r888888888** [comment]
The samples under large/ have been moved to sample/, and the ACL has been reset.

**Comment by r888888888** [comment]
These should be fixed now.

**Comment by BrokenEagle** [comment]
The following image is broken:

https://danbooru.donmai.us/posts/831064
http://danbooru.donmai.us/cached/data/sample/sample-d00bf4dc2f87ae1cd6f1853c0533e715.jpg

It gives the same error message as noted by evazion.

**Comment by r888888888** [comment]
That one is fixed now.
