### ISSUE TITLE
No Blacklist Box on the various controllers

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3121]
Basically, there are no "#blacklist-box" or "#blacklist-list" entries when searching comments, that is, the `group_by=comment` field is set.  The Javascript still runs and the blacklisted posts still get hidden, however, there is no way for users to modify their settings.

**Comment by BrokenEagle** [comment]
Found a couple more in addition to the above.

/users/$ID
/artist_commentaries
/moderator/dashboard

**Comment by BrokenEagle** [comment]
@evazion 

In reference to your suggestion on issue #3183, I'm posting this here, although I don't have permissions to reopen this issue myself.

Anyways, from Unbreakables response on the [Danbooru forums](http://danbooru.donmai.us/forum_posts/133668), I realized that the Artist Show page doesn't have blacklist controls.  

I thought it wasn't working because I wasn't seeing anything, but it was the same issue with my CSS as on #3183.

**Comment by evazion** [comment]
Fixed in 9d9ac53e4dd568da7c90c8a75f23490c58a89651.

**Comment by BrokenEagle** [comment]
Found another one.  The comments/show doesn't have any blacklist settings.
