### ISSUE TITLE
Out-of-order tag edits in version history

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3131]
https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2730692
https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2730572

If two people edit the same post at the same time, the edits can appear out of order in the version history. Sometimes it appears as if the second edit came before the uploader's initial edit.

This is because 1) post versions are ordered by `updated_at` only, so if two versions have the same timestamp their ordering is undefined 2) `updated_at` only has one second precision, making collisions more likely to happen.

Related to #2951.

**Comment by r888888888** [comment]
I assume this is fixed now with the FIFO queues?

**Comment by Type-kun** [comment]
It would be great if logs of queue processing for that post are present, so that we can see what actually happened there instead of just assuming it's fixed now. Same goes for #3132, which looks more complicated

**Comment by evazion** [comment]
I think archives will process versions in the right order now, but edits can still be displayed out of order if two edits share the same timestamp.
