### ISSUE TITLE
Allow danbooru to work from behind a proxy

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3135]
There should be a way to make Danbooru use proxy when fetching files from the outside. Admittedly, this is a niche use-case, but it might be useful for development purposes - for example, I have to develop from behind a proxy on one of my boxes. Currently Danbooru both disregards system proxy settings and doesn't have any settings of its own to override those.

Here's what is happening. `Net::HTTP.new` has default parameter `p_addr = :ENV`, which is a special value which means proxy address and port are derived from `http_proxy`. To turn off the proxy, you have to explicitly pass `nil` in that parameter. However, Danbooru uses `Net::HTTP.start` pretty much everywhere when it's fetching resources from the outside, and for whatever reason `start` has `p_addr = nil` as default parameter, which it internally passes to `new`, making it bypass proxy by default. 

I'm not sure what would be a better way to solve it. We can add explicit `p_addr = :ENV` everywhere `start` is used. We can also wrap `start` in a separate utility class/method and use it instead. The second way would also allow for a clean way to create proper configuration variables in danbooru config to override proxy settings if need be. For my local instance, I solved it radically by overriding `Net::HTTP.start` in the initializers, but it's probably not the proper solution (and it's getting cumbersome to constantly alter `.gitignore`).

**Comment by evazion** [comment]
I would also find this useful, in my case for logging and firewalling purposes.

If every callsite needs to be updated anyway, how about switching everything over to `HTTParty`? It has a simpler API than `Net::HTTP` and I think it allows one to set proxy settings globally.

**Comment by evazion** [comment]
Just realized, some places use `Mechanize` instead of using `Net::HTTP` directly. Those places would need to set the proxy separately in any case.

**Comment by r888888888** [comment]
AFAICT HTTParty doesn't have any configuration options for setting the proxy globally.

**Comment by evazion** [comment]
Yeah, I misread the docs. You have to make a class that configures things and use that class instead of using HTTParty directly:

```ruby
class HTTP
  include HTTParty

  http_proxy 'http://example.com', 80, 'user', 'pass'
  headers 'User-Agent' => 'Danbooru'
  default_timeout 30
end
```

**Comment by r888888888** [comment]
Fixed in aa7d514efca65d6c1ab94257da99c86877a5bf39

**Comment by evazion** [comment]
Fixed an error that caused uploads to fail in 5066f75. The file downloader started throwing an `Net::HTTPOK#read_body called twice` exception after switching to HTTParty, not sure why.

**Comment by Type-kun** [comment]
Just a note that this doesn't affect calls to mechanize that evazion mentioned earlier, but mechanize itself seems to respect system-wide proxy settings.
