### ISSUE TITLE
Implement `flag:` and `appeal:` metatags

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3142]
This would allow to quickly search for post that were flagged or appealed by users, combined with other tags. Looks doable, this shouldn't be much harder than `noteupdater` for example.

Syntax: 
* `flag:<username>`, `flag:any`, `flag:none`
* `appeal:<username>`, `appeal:any`, `appeal:none`

First, searching for the specific usernames. For appeals, it's the same `posts.id IN (?)` with simple `PostAppeal.unscoped.where(creator_id = ...)` would work.  For flags, only non-automatic flags should be selected, so it's probably better to use `PostFlag.unscoped.search({:creator_id => ..., :category = "normal"}).reorder("")` to make use of already coded-in restrictions.

As for `any` and `none`, it's a bit tricky. It can be done with the same `IN` and `NOT IN` queries without specifying `creator_id`, but it should be checked to see if postgres optimizes it properly. Otherwise, it should be possible to do using `where (' EXISTS (' + PostFlag.unscoped.search({category = "normal"}).where('post_id = posts.id').select('1').to_sql + ')')` or something.

**Comment by r888888888** [comment]
Those NOT IN/NOT EXISTS queries are going to explode.

Flags don't get deleted so that subquery is going to worsen over time. At a minimum you'd have to exclude albert/DanbooruBot. A way around this (assuming you just wanted to spot check the most recent flags by a user) is to scope the flag query to the most recent N days.

Also flagger info is supposed to be hidden to non-mods.

I would argue a better interface for this (given the distribution of how flags work (very top heavy)) is to create some sort of listing for flags that display the post preview.

**Comment by evazion** [comment]
I'm running it on http://devbooru.ml:10000 and they do okay.

* http://devbooru.ml:10000/posts?tags=-flagger:md_anonymous
* http://devbooru.ml:10000/posts?tags=touhou+-flagger:md_anonymous
* http://devbooru.ml:10000/posts?tags=-flagger:none
* http://devbooru.ml:10000/posts?tags=touhou+-flagger:none
* http://devbooru.ml:10000/posts?tags=touhou+flagger:any

The slowest I've found is `touhou flagger:any`, which is ~700ms (https://explain.depesz.com/s/KFFU).

**Comment by evazion** [comment]
It should be noted that `appealer:any` would also fix issue #1221 ("Support status:appealed").

**Comment by Type-kun** [comment]
>Also flagger info is supposed to be hidden to non-mods.

It is; that's why I went with `PostFlag.search` instead of `where`. In addition to filtering out automated flags, search methods already check whether current user is moderator or flagger themselves:

`if params[:creator_id].present? && (CurrentUser.is_moderator? || params[:creator_id].to_i == CurrentUser.user.id) `

...Though there's an unintended side effect I didn't think of: when searching for user's flags without proper rights, it simply doesn't place additional `where` clause instead of making the search result empty; so instead of searching for user's flags, it searches for ALL flags. I guess it can be filtered out in query builder, but there should be a method like `can_see_creator(id)` in flag model, and the rest of code should use it instead of duplicating the logic everywhere.

>Those NOT IN/NOT EXISTS queries are going to explode.

`NOT EXISTS` in particular should always be fast, since most posts don't have flags and it should selectively pick rows by `post_id` instead of running a full scan. I'm more worried about `flagger:any` since it's ether a lot of subqueries for `EXISTS` or a `post_flags` fullscan for `IN` - it's one of those cases where the speed should be checked on a real dataset, because it's a typical usecase and optimizer should be smart enough to do something .  At any rate, `flagger:<user>` should be fast because it should use index on `creator_id`.

>I would argue a better interface for this (given the distribution of how flags work (very top heavy)) is to create some sort of listing for flags that display the post preview.

The reason I want this metatag is to combine it with other tag queries; for example `user:uploader status:active flagger:flagger` to see resolved flags by specific flagger for specific uploader.

Also @evazion `-flagger:none` is not supported, just as with other metatags. You were excluding flags by user "none" (http://devbooru.ml:10000/users/11539) with that query.

**Comment by r888888888** [comment]
Hmm, it's not as bad as I thought. If we just add the permission checks I can merge this.
