### ISSUE TITLE
Nijie: fetch source data doesn't work with https://nijie.info/view_popup.php

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3153]
* Open https://nijie.info/view_popup.php?id=213043.
* Right click -> open https://pic03.nijie.info/nijie_picture/728995_20170505014820_0.jpg.
* Upload image with bookmarklet.
* Observe that fetching source data fails.

Problem is the regexes don't handle `view_popup.php` urls.

**Comment by r888888888** [comment]
AFAICT the artist profile isn't linked on the popup page. Probably need to go back to the canonical url at http://nijie.info/view.php?id=213043 which is available from the twitter meta tags.
