### ISSUE TITLE
Networks problems on hijiribe

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3161]
@r888888888: https://hijiribe.donmai.us seems to be either down or having network connectivity problems. It's timing out and uploads are failing because sonohara can't sftp the files over to it. Looks like it experienced some DNS resolution problems prior to this too.

Errors:

* https://danbooru.donmai.us/uploads
* https://danbooru.donmai.us/uploads/1456240
* https://danbooru.donmai.us/uploads/1456198
* https://danbooru.donmai.us/uploads/1456158

**Comment by r888888888** [comment]
Rebooting it doesn't seem to have helped.

I've taken it out of DNS for danbooru.donmai.us and removed it from the config for sonohara.

**Comment by r888888888** [comment]
Hijiribe is back up.

**Comment by evazion** [comment]
Reopening because hijiribe is down again.

**Comment by deusexcalamus** [comment]
Can confirm, its dead, Jim. Also @r888888888 can you please use your twitter/the danbooru hashtag when the site is down for maintenance/etc? Else remove it from the page, because it hasn't been used in ages.

**Comment by r888888888** [comment]
I've taken hijiribe out.

**Comment by r888888888** [comment]
Something weird going on with the networking stack. Periodically it loses connectivity beyond the gateway, but just now it fixed itself.

**Comment by evazion** [comment]
https://danbooru.donmai.us/forum_topics/9127?page=190#forum_post_132602
http://sonohara.donmai.us/forum_topics/14145
http://sonohara.donmai.us/delayed_jobs

There are reports of images for new uploads on hijiribe being broken. It seems the files aren't being transferred to hijiribe?

Also there are some failed `Post.backup_file` jobs in the jobs listing. I'm guessing this is because the backup job is sent to the default queue, meaning it can run on either sonohara or hijiribe, but if it runs on hijiribe it fails due to missing files.

**Comment by r888888888** [comment]
Correct but I've taken hijiribe out of the DNS for danbooru.donmai.us so users shouldn't be using it. Once I figure out what the problem is I will sync all the missing images over.
