### ISSUE TITLE
Uploading fails

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3166]
Uploading an image gives the following error on the latest commit: https://pastebin.com/CZ8MY7iZ

**Comment by evazion** [comment]
You'll need to convert the queue (the one configured in `aws_sqs_archives_url`) to a FIFO queue on Amazon.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html

**Comment by Iratu** [comment]
Alright, it seems to work now, thanks.
