### ISSUE TITLE
Tag translations for direct wiki names

### ISSUE THREAD

**Issue by chinatsu-chan** [r888888888/danbooru#3174]
When a post uses tags such as "twintails" or "kantai collection" that match directly to the name of a wiki, there are no translated tag suggestions. Would it be possible for such translations to be made? As it stands such translations are possible, but only if the name of a wiki page is repeated in the other name category.

Sure a user may see the tags in the meta data region but they may also not and it would certainly aid in tagging if the tags were "translated."

**Comment by chinatsu-chan** [comment]
This should probably be made into an opt-in only setting with an explanation to actually read wiki pages before tagging an image and that translated tags are merely suggestions and still need to be contextually relevant.

For instance, if painttool_sai is tagged on an image because the artist used that, it is suggested as a translated tag. Obviously however, the tag is to be used for actual representations of PaintTool SAI, not just if an image was made with it.

So uh, a lot of unintended consequences from this. The suggestions in #3208 would probably help a lot.

**Comment by evazion** [comment]
> This should probably be made into an opt-in only setting with an explanation to actually read wiki pages before tagging an image and that translated tags are merely suggestions and still need to be contextually relevant.

I don't like making it an option because then few people would use it, and having it is important for sites like dA/ArtStation/Tumblr where most tags are in English and wouldn't be suggested without this.

I would rather improve the UI for related tags to a) remind people to only use tags when they actually apply and b) add `?` links to make it easier to check wikis.

**Comment by evazion** [comment]
I noticed some artist tags being suggested by this in https://danbooru.donmai.us/posts/2808885. Artist tags should be excluded from being suggested as translated tags.
