### ISSUE TITLE
Allow replacement of S3-hosted posts

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3180]
Currently posts hosted on S3 are not allowed to be replaced. This is because the old files need to be deleted, but the code has no provision for deleting things from S3.

The problem is that S3 was (and still is?) the backup system for images, but now it's being used to host images in production, so deleting files from it isn't very safe if there are no other backups.

**Comment by r888888888** [comment]
I assume these actions are sufficient:

- Queue a delete on S3 after the grace period
- Upload the replacement file to S3
- Delete the cached file locally

**Comment by evazion** [comment]
Pushed a couple fixes for missing declarations in 0390039.
