### ISSUE TITLE
Find Similar By Post is not working

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3182]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=190#forum_post_132954):

> kittey said:
> 
> Is "Find similar" broken? It doesn’t return anything on any of the posts I tried.

> BrokenEagle98 said:
> 
> Yeah, I see what you mean...
> 
> I checked [post #2765559](http://danbooru.donmai.us/posts/2765559) and nothing showed up, however searching by the image URL still works...
> 
> http://danbooru.donmai.us/iqdb_queries.xml?url=http://danbooru.donmai.us/data/sample/sample-075c9a805d29fb5edf7df2c1fd097d74.jpg

**Comment by BrokenEagle** [comment]
Just wanted to add that I tested the XML/JSON for the IQDB query where post_id is used as a parameter and it does work.
http://danbooru.donmai.us/iqdb_queries.xml?post_id=2765559

I went back and tested the above using HTML and discovered the most likely cause of the error.

http://danbooru.donmai.us/iqdb_queries?post_id=2765559

```
ActionView::MissingTemplate exception raised
Missing template iqdb_queries/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in: * "/var/www/danbooru2/releases/20170623210441/app/views"
app/controllers/iqdb_queries_controller.rb:38:in `create_by_post'
app/controllers/iqdb_queries_controller.rb:14:in `index'
```

**Comment by r888888888** [comment]
That is supposed to be a JavaScript XHR POST request. So simply pasting it into your browser won't work.

**Comment by BrokenEagle** [comment]
Discovered that this issue was actually being caused by the custom CSS in [forum #132142](http://danbooru.donmai.us/forum_posts/132142).  Since the blacklist controls don't run on the dynamically loaded Javascript content nor on the uploads page, the posts are never unhidden by the "blacklisted" class being added.

After exceptions were added for those uses of IQDB, the thumbnails now appear as expected.
