### ISSUE TITLE
Dmail Show View incorrectly using class instead of ID

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3185]
As can be seen in the file linked below, the `<div>`'s are incorrectly using _class_ instead of _id_.

https://github.com/r888888888/danbooru/blob/master/app/views/dmails/show.html.erb#L1-L3

**Comment by evazion** [comment]
Note that this changes the layout for dmails, as it triggers a `max-width: 50em;` rule that did not trigger before.

**Comment by Type-kun** [comment]
>Note that this changes the layout for dmails, as it triggers a  max-width: 50em;  rule that did not trigger before.

Maybe we should remove that rule? I think it looks pretty dumb on wide screen right now: http://puu.sh/wMtYJ/93acc89b50.png

**Comment by BrokenEagle** [comment]
Agree with Type-kun here... there is no other place on the site that I know of that restricts the width as such.  Not comments, nor forum posts.

**Comment by evazion** [comment]
> Maybe we should remove that rule? I think it looks pretty dumb on wide screen right now: http://puu.sh/wMtYJ/93acc89b50.png

IMO quote blocks having this much dead space looks worse: https://i.imgur.com/qYwcNji.png.

> Agree with Type-kun here... there is no other place on the site that I know of that restricts the width as such. Not comments, nor forum posts.

It's not unprecedented, there are a few other pages with fixed width layouts:

https://danbooru.donmai.us/moderator/post/queue
https://danbooru.donmai.us/tags
https://danbooru.donmai.us/users/new
https://danbooru.donmai.us/user_upgrade/new
https://danbooru.donmai.us/static/site_map
https://danbooru.donmai.us/static/terms_of_service
https://danbooru.donmai.us/explore/posts/intro

Nonetheless, I removed it to maintain consistency with comments and the forum. Although IMO all text heavy pages should have limited width. Excessively wide text is widely regarded to be worse for readability.

**Comment by r888888888** [comment]
Maybe the quote blocks should be restyled to only have the leftmost border.

**Comment by r888888888** [comment]
As a comparison, Gmail doesn't seem to set a max-width.

**Comment by BrokenEagle** [comment]
> Reddit is a counterexample: they limit comments to 60em.

The 60em limit on Reddit seems to help maintain a block style for comments in their tiered hierarchical comment structure.  If there was no limit, then you would be limited to only the left margin to gauge how deep in the comments you are.  However, since our comment/forum system is purely sequential-based, there's no need to block off the comments as such to achieve better visibility.

Besides, IMHO the common case should be to use as much of the screen as possible, especially since users can always customize the layout themselves via custom CSS.
