### ISSUE TITLE
Post Replacement comment: use Replacement URL instead of Final Source

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3197]
For the automatic comment generated by post replacements, listing the Replacement URL for the NEW line seems more useful than having both OLD and NEW list the same URL (in the case of a Final URL being unchanged)...

**Comment by evazion** [comment]
This was done in #3192, but it's still not quite right. What should be listed is the actual image URL downloaded during the upload process. If someone enters `https://twitter.com/username/status/1234` as the replacement URL, for example, we should record the image URL, not the html URL given by the user.
