### ISSUE TITLE
Internet Explorer cannot open secure Danbooru (HTTPS)

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3202]
First reported on the [Danbooru forum](http://danbooru.donmai.us/forum_topics/14193), and then later confirmed by myself and others.  I tested it out using 3 different computers: all with IE11, two computers with Windows 7 and one with Windows 8.

**Comment by evazion** [comment]
I'm pretty sure this is the same bug as #3656. Closing as duplicate.
