### ISSUE TITLE
Dead code elimination

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3206]
Danbooru has accumulated a fair amount of dead code over time. I'm going to open this as a tracking issue for dead code removals to reference.

**Comment by SD-DAken** [comment]
I guess the references to view_count are dead code since the post view counts are long gone:
https://github.com/r888888888/danbooru/blob/master/app/presenters/post_presenter.rb#L83
https://github.com/r888888888/danbooru/blob/master/app/models/post.rb#L62

**Comment by r888888888** [comment]
I think view counts are something I will eventually bring back although I'm not sure if I'd persist them in Postgres still. 

[Reddit has an interesting system](https://redditblog.com/2017/05/24/view-counting-at-reddit/) that maybe overkill for Danbooru's purposes, but updating the posts table in Postgres on every view isn't something I think is tenable.
