### ISSUE TITLE
Fix translated tag suggestions for Pixiv

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3208]
The combination of #3174, #3033, and #2915 has led to bad translated tags being suggested for Pixiv. Namely, `photoshop` and `sai` are suggested because of #3033 and #3174, but our `photoshop` tag has a very different meaning from Pixiv's. Another example is `Fate/GrandOrder` suggesting `fate`.

Translated tags should work like this:

* First, search undeleted wikis by other names.
* If a match is found but the tag is empty, stop. This way ambiguous tags can be blackholed.
* If no match, search for the tag with the same name.
* If no match, split tag on delimiters and repeat above.

**Comment by chinatsu-chan** [comment]
Not just Pixiv but all sources. I think the verbose tag suggestions should be changed to opt-in in addition to these changes.
