### ISSUE TITLE
Add graceful failure mechanism for issues with other servers

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3212]
Connection issues with other servers causes exceptions in Danbooru as talked about in the [Danbooru forum](http://danbooru.donmai.us/forum_topics/9127?page=192).

>  Unbreakable said:
> 
> Trying to visit a profile pages only gives me:
> 
> PG::ConnectionBad exception raised
> 
>     could not connect to server: Connection refused Is the server running on host "yukinoshita.donmai.us" (104.237.154.176) and accepting TCP/IP connections on port 5432?
>     config/initializers/active_record_extensions.rb:23:in `ensure in with_timeout'
>     config/initializers/active_record_extensions.rb:23:in `with_timeout'
>     app/models/post.rb:1215:in `fast_count_search'
>     app/models/post.rb:1206:in `fast_count'
>     app/presenters/user_presenter.rb:146:in `block in noted_posts_count'
>     app/logical/current_user.rb:70:in `without_safe_mode'
>     app/presenters/user_presenter.rb:146:in `noted_posts_count'
>     app/views/users/_statistics.html.erb:88:in `_app_views_users__statistics_html_erb___2200515886989858214_70249715724140'
>     app/views/users/show.html.erb:5:in `_app_views_users_show_html_erb__2358049794660773414_70249715675440'
>     app/controllers/users_controller.rb:41:in `show'

> BrokenEagle98 said:
> 
> Getting the same error as above but with {{search:all}} instead...

There should instead be a graceful failure mechanism, so that user experience isn't impacted even if another server is having issues.

**Edit:**

Changed to be generalized for all other servers.

**Comment by Type-kun** [comment]
This might be possible for load-balancing servers like hijiribe and sonohara, which can be automaticaly handled by, well, front-end load balancers - I'm pretty sure it's already done and redirects everything to one server when other is down. But yukinoshita is read-only database copy, there's likely no mirroring server for it, and it's hardcoded as read-only database URL. It might be technically possible to rescue a particular "database offline" exception in `PostReadOnly` model and retry on the main DB if that happens. However, that would impact the main database performance, and there should be a mechanism for notifying @r888888888 that ro server is offline.

**Comment by r888888888** [comment]
The keyword for this is failover and there seem to be some gems already for ActiveRecord that can handle this. I guess it can just offload the work to the main database server, but these queries were being delegated to the replica for a reason. There may need to be some sort of QoS standards. I can see multi-tag searches being delegated, but things like reporting should just fail until the replica is restored.

**Comment by evazion** [comment]
There are middlewares for Postgres that do load balancing and failover. See [Pgpool-II](http://www.pgpool.net/mediawiki/index.php/Main_Page), among others. IMO doing it at the database level would be easier to manage than at the app level.

**Comment by BrokenEagle** [comment]
This issue is causing errors again.
http://danbooru.donmai.us/forum_posts?search[id]=142717..142719
```
could not connect to server: Connection refused Is the server running on host "yukinoshita.donmai.us" (104.237.154.176) and accepting TCP/IP connections on port 5433?
app/models/application_record.rb:114:in `ensure in with_timeout'
app/models/application_record.rb:114:in `with_timeout'
app/models/post.rb:1213:in `fast_count_search'
app/models/post.rb:1204:in `fast_count'
app/presenters/user_presenter.rb:116:in `block in noted_posts_count'
app/logical/current_user.rb:84:in `without_safe_mode'
app/presenters/user_presenter.rb:116:in `noted_posts_count'
app/views/users/_statistics.html.erb:88:in `_app_views_users__statistics_html_erb__4581566849145541254_46963653810340'
app/views/users/show.html.erb:5:in `_app_views_users_show_html_erb__2499693831730215114_46963653966020'
app/controllers/users_controller.rb:40:in `show'
```

**Comment by nonamethanks** [comment]
As of today it's breaking user pages again.

```
HTTP error code: 502 Bad Gateway
app/models/saved_search.rb:37:in `block in post_ids'
app/logical/cache.rb:18:in `get'
app/models/saved_search.rb:22:in `post_ids'
app/logical/post_query_builder.rb:76:in `block in add_saved_search_relation'
app/logical/post_query_builder.rb:72:in `each'
app/logical/post_query_builder.rb:72:in `add_saved_search_relation'
app/logical/post_query_builder.rb:201:in `build'
app/models/post.rb:1634:in `tag_match'
app/presenters/user_presenter.rb:47:in `posts_for_saved_search_category'
app/views/users/_post_summary.html.erb:36:in `block in _app_views_users__post_summary_html_erb___2568463808609239324_47347305297880'
app/views/users/_post_summary.html.erb:28:in `each'
app/views/users/_post_summary.html.erb:28:in `_app_views_users__post_summary_html_erb___2568463808609239324_47347305297880'
app/views/users/show.html.erb:9:in `_app_views_users_show_html_erb__2618623042193355887_47347307088260'
app/controllers/users_controller.rb:40:in `show'
```

**Comment by r888888888** [comment]
The listbooru init scripts weren't installed correctly. I've started up the service and the web processes.
