### ISSUE TITLE
Bookmarklet doesn't work with Twitter in Firefox

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3218]
In Firefox, using the bookmarklet on a Twitter status silently fails. The problem is that Twitter has a Content Security Policy that blocks third party scripts, and apparently Firefox strictly enforces this policy even for bookmarklets.

I'm not sure if there's anything we can do about this. A userscript or browser extension might work, but I'm not positive about that.

https://bugzilla.mozilla.org/show_bug.cgi?id=866522
https://medium.com/making-instapaper/bookmarklets-are-dead-d470d4bbb626
https://github.com/blog/1477-content-security-policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by BrokenEagle** [comment]
As I made a note on the [Danbooru wiki](http://danbooru.donmai.us/wiki_pages/56209), there is a new Firefox addon that allows for users to use Bookmarklets on sites even with Content Security Policy.  I tested it out myself and verified that it works with Danbooru's bookmarklets.

https://addons.mozilla.org/en-US/firefox/addon/bookmarklets-context-menu/

**Comment by BrokenEagle** [comment]
I mentioned the above Firefox addon on the [Danbooru forum](https://danbooru.donmai.us/forum_topics/14429) for this same issue, and @kittey made the suggestion to add that information to the [Bookmarklet page](https://danbooru.donmai.us/static/bookmarklet).
