### ISSUE TITLE
Size/overflow issues with detachable edit dialog

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3219]
This was first brought up by Unbreakable on Discord.

Basically, there are three different error conditions caused by the detachable edit dialog on posts (Shift+E).

Normal behavior: [Image 1](https://cdn.discordapp.com/attachments/310846683376517121/336209630122475520/Danbooru.png), [Image 2](https://cdn.discordapp.com/attachments/310846683376517121/336209653702852610/Danbooru2.png)

1. Moving the detachable window before then expanding the related tags, the related tags overflows outside the box. [Image 3](https://cdn.discordapp.com/attachments/310846683376517121/336209767322353664/Danbooru4.png)
2. Moving the detachable window after expanding the related tags before then collapsing the tags, the box does not resize back to its minimized size. [Image 4](https://cdn.discordapp.com/attachments/310846683376517121/336209739518050314/Danbooru3.png)
3. Resizing the window at any point and then expanding the related tags, the expanded window will be contained within the collapsed window with scroll bars for scrolling. No picture.

`1.` and `2.` are caused by the height attribute on the `<div>` container identified with the attribute `[aria-describedby=edit-dialog]` going from **auto** to whatever the height of the window is at the time it was moved.

`3.` is caused by the height attribute on the `<div>` container identified with the ID `edit-dialog` going from **auto** to whatever the height of the window gets set to by the resize.

I was able to fix both of the above with the following CSS.

```
[aria-describedby=edit-dialog],
#edit-dialog {
    height: auto !important;
}
```

The `!important` is necessary since the height attributes on both `<div>` containers are element attributes.

**Comment by evazion** [comment]
5d48244 fixes 1 and 2 by globally setting `height: auto !important;` on all dialogs. AFAICT that's safe.

As for 3, just setting `#edit-dialog { height: auto !important }` has the side effect of preventing the dialog from being resizeable. b545a5e handles this by only expanding the height when the related tags are shown.
