### ISSUE TITLE
Post expunge leaves users with no way to remove favorites

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3222]
The expunging that happened recently [brought up an issue](http://danbooru.donmai.us/forum_topics/11399?page=6) that occurs with favorites when a post is expunged.  Basically, the expunge function only does something with the favorites if the post has a parent, otherwise it does nothing.  This has left a lot of users with favorites that they can't get rid of even going through the API, since the destroy function on favorites does a post lookup which will fail since the post no longer exists.

- [ ]  Fix the expunge function so that it removes favorites if a parent does not exist
- [ ]  Clear out all users' favorites that no longer have an associated post

**Comment by BrokenEagle** [comment]
It seems like the above didn't run something that clears out all user's favorites, so how do users remove expunged favorites without using the API..?.  Is it possible to do so through the mode menu on the post index...?  Unfortunately, I don't have anything I can try out for myself since I haven't had any expunged favorites.

**Comment by r888888888** [comment]
I added a script to fix favorites in 2947b25d6eb1c5ec8aba2c5d19469c120297dcea

**Comment by r888888888** [comment]
The script has been run.
