### ISSUE TITLE
Exception in NoteSanitizer#relativize_links

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3225]
https://danbooru.donmai.us/forum_topics/9127?page=193#forum_post_133896

> [post #2660179](https://danbooru.donmai.us/posts/2660179) does not work. When I try to open it, the site says "Invalid scheme format: http"
> Don't know what s the problem here...

```
Addressable::URI::InvalidURIError exception raised
Invalid scheme format: http
app/logical/note_sanitizer.rb:85:in `relativize_links'
app/logical/note_sanitizer.rb:58:in `sanitize'
app/views/notes/_note.html.erb:1:in `_app_views_notes__note_html_erb___4296294498752858803_70326643013860'
app/views/posts/show.html.erb:101:in `block in _app_views_posts_show_html_erb___91165748961475063_70326949334840'
app/views/posts/show.html.erb:100:in `_app_views_posts_show_html_erb___91165748961475063_70326949334840'
app/controllers/posts_controller.rb:33:in `show'
```

Caused by malformed URL in https://danbooru.donmai.us/notes/1904133.json.

**Comment by r888888888** [comment]
I think the behavior here should just render the text with everything html escaped.

**Comment by evazion** [comment]
Well, that's what it was trying to do, except in the process it tries to rewrite internal links to Danbooru and invalid links weren't handled correctly.
