### ISSUE TITLE
Post expungement bugs

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3229]
https://danbooru.donmai.us/posts/2787610
https://danbooru.donmai.us/posts/2787609
https://danbooru.donmai.us/posts/2787604
https://danbooru.donmai.us/posts/2363502

https://danbooru.donmai.us/posts/2512784
https://danbooru.donmai.us/posts/2512800

The first set of posts above failed to be fully expunged. The parent in the second set is inconsistent in its has_children flag.

There are at least a few bugs here:

- [x] Expungement isn't wrapped in a transaction, which causes an incomplete expungement when something fails midway through. Failure was possibly related to parent/child posts, given the failures were all for parent posts.

- [x] Child posts are reparented using `update_column`, meaning callbacks aren't triggered and so the `has_children` flag isn't set and new post versions aren't created for these edits.

- [x] Expunged posts aren't removed from deleted pools. Removing a post from a deleted pool is silently ignored.

- [x] Post replacement records aren't destroyed along with the post.

**Comment by r888888888** [comment]
I had some trouble expunging these at first because the destroy callback on the favorites association kept timing out. That may have left some posts in a bad state. After removing the callback the process seemed fast enough.

**Comment by evazion** [comment]
I guess that was why those 4 posts were partially expunged. I can't figure out what else could have failed to cause that. #3229 should fix the other bugs.
