### ISSUE TITLE
Replacements deleting files currently in use.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3235]
https://danbooru.donmai.us/forum_topics/9127?page=193#forum_post_133964

Some posts have missing files due to incorrect deletions triggered by post replacements. By the time a scheduled deletion runs a month later, the files being deleted may be in use again by another post.

#3148 was meant to prevent this, but it didn't work:

```ruby
def delete_files(post_id, file_path, large_file_path, preview_file_path, force: false)
  unless force
    post = Post.find(post_id)

    if post.file_path == file_path || post.large_file_path == large_file_path || post.preview_file_path == preview_file_path
      raise DeletionError.new("Files still in use; skipping deletion.")
    end
  end

  # ...
end
```

Two problems here:

* The check is if the files are still in use by the replaced post, but they could be in use by a different post.
* It compares file paths, but the present file path may be different from when the deletion was first scheduled. File paths contain the `Rails.root`, which contains a timestamp that changes on every Danbooru release.

**Comment by RaisingK** [comment]
How do we fix the posts currently impacted?  If I try to replace via the URL (either the old URL, or the new), I hit a "duplicate md5" error.  If I replace with the md5 itself, I get "file does not exist".  So even if I temporarily replace with something with a new md5, I still won't be able to switch back to the version I want...

**Comment by BrokenEagle** [comment]
I made a list of all posts with the above replacement issue on the Danbooru forums.

http://danbooru.donmai.us/forum_posts/134015

**Comment by evazion** [comment]
> How do we fix the posts currently impacted? If I try to replace via the URL (either the old URL, or the new), I hit a "duplicate md5" error. 

I think I'll fix it so that replacing a post with the same file won't trigger the dupe md5 check.

> If I replace with the md5 itself, I get "file does not exist". So even if I temporarily replace with something with a new md5, I still won't be able to switch back to the version I want...

Screenshot? I'm not seeing this when I try it.

**Comment by RaisingK** [comment]
> I think I'll fix it so that replacing a post with the same file won't trigger the dupe md5 check.

Great, that would allow approvers to fix corrupted images in general.

> Screenshot? I'm not seeing this when I try it.

I was trying to put in the literal MD5 hash in place of the replacement URL, but on further reflection, I'm not sure why I expected that to work.

**Comment by evazion** [comment]
Pushed a fix to not leave comments / mod actions when you're replacing a post with the same file. This is to avoid spamming comments when fixing missing images and the files are otherwise unchanged.
