### ISSUE TITLE
Show unvote link as applicable upon page load

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3250]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=194#forum_post_134176):
> worldenddominator said:
> 
> Make the vote link would say "unvote" from the beginning if I open a post that I've recently voted (i.e. that I can't vote now).

One way to do this would be to add a show function to the favorites controller that would return whether the vote for a post is positive, negative, or does not exist.  Then make the Javascript do a vote query upon loading the post show page.  One benefit to this approach is that it would also expose the vote status to a user through the API.  Additionally, the code for checking if a post has already been voted on could be removed from the post show page since it would no longer be possible to vote on a post that has already been voted on without unvoting it first.

**Comment by Type-kun** [comment]
Post vote link can be changed to "unvote" server-side if the vote already exists; it just takes a single query, and it can be made instant if two-column index on post id + user id is used. The information about user's votes can be exposed through the api separately if necessary.

> It would make sense to promote these two functions as buttons underneath the image.

Other potential place for those place would be below the search bar but above the tag list.

**Comment by evazion** [comment]
This would take an extra query but the cost should be negligible.
