### ISSUE TITLE
Keyboard shortcuts (A,D) for pools not working as intended  

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#3256]
Keyboard shortcuts for [A] (left/previous page) and [D] (right/next page) are not working as intended.

If user clicks an image from inside a Pool, the previous/next shortcut does not work since no search is generated (e.g. [A] goes to next post by post ID).
If user goes
Pool -> Posts -> [click any post]
[A] goes to next post inside pool, by post ID.

Please note that Next/Previous buttons still work as intended.

Tested with: 
pool #12687
Bug reproduced in Firefox & Chrome.

**Comment by evazion** [comment]
Already fixed in 40e006f7cb20e588f9662327b2de802cf408d9e1.
