### ISSUE TITLE
Keyboard shortcuts [Left arrow, Right arrow] do nothing

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#3257]
Might be related to issue #3256

http://danbooru.donmai.us/static/keyboard_shortcuts 
Lists 
[Left arrow] = previous page
[Right arrow] = next page

These keyboard shortcuts are not implemented.

**Comment by Moebius-Strip** [comment]
You're not trying to use the arrow keys to navigate from post to post are you? They're only implemented for listings ([thumbnails](http://danbooru.donmai.us/posts), [comments](http://danbooru.donmai.us/comments?group_by=post), etc). As far as listings go, they work just fine for me.

**Comment by Kikimaru** [comment]
Not 100% sure now if they were broken before on those pages.

**Comment by evazion** [comment]
Working as intended. Left and right arrow keys aren't implemented on post show pages to avoid causing problems with using these keys to horizontally scroll wide images.
