### ISSUE TITLE
Exception when uploading certain DeviantArt posts

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3260]
http://xxnikichenxx.deviantart.com/art/Miss-Fortuna-lingerie-v1-League-of-Legends-694099971

http://danbooru.donmai.us/uploads/new?url=http://xxnikichenxx.deviantart.com/art/Miss-Fortuna-lingerie-v1-League-of-Legends-694099971

Uploading the above post fails. The dA source strategy returns a null image url, which causes an exception later in the url rewriting process.

Are Danbooru's dA credentials configured correctly? This works on my local devbooru.

**Comment by r888888888** [comment]
It may have been because I didnt have mature content filter disabled. It seems to work now.

**Comment by lllusion3469** [comment]
On my personal installation, this issue still persists, despite definitely having the mature content filter disabled.
When logged in through my regular browser, I have a cookie called "auth_secure", which seems to be needed, since I'm logged out when deleting it.

This simple diff seems to be a temporary fix on my end, it simply disables the cache, loggs in every time and just keeps the cookies set by deviantart themselves, as I understand it.
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -141,7 +141,7 @@ module Sources
       end
 
       def session_cookies(mech)
-        Cache.get(DEVIANTART_SESSION_CACHE_KEY, 2.hours) do
+        #Cache.get(DEVIANTART_SESSION_CACHE_KEY, 2.hours) do
           mech.request_headers = Danbooru.config.http_headers
 
           page = mech.get("https://www.deviantart.com/users/login")
@@ -158,10 +158,10 @@ module Sources
 
           auth = mech.cookies.find { |cookie| cookie.name == "auth" }.value
           userinfo = mech.cookies.find { |cookie| cookie.name == "userinfo" }.value
-          mech.cookie_jar.clear
+          #mech.cookie_jar.clear
 
           [auth, userinfo]
-        end
+        #end
       end
     end
   end
```
but i don't know how to properly fix it, especially since this doesn't seem to be necessary everywhere. 

(I don't know why that would matter, but my server is in Germany)

**Comment by r888888888** [comment]
That is pretty strange. Are you sure you weren't just using an old session? What happens if you only comment out the `mech.cookie_jar.clear` line?

**Comment by lllusion3469** [comment]
That seems to make it work once, but only once.

**Comment by lllusion3469** [comment]
I've tried to replicate it, but I can't even get it to work once now, just commenting out that one line.

About sessions/Cache:
* do they persist over restarts of danbooru?
* if so, does `rm -rf tmp/cache` clear it?

**Comment by r888888888** [comment]
`Cache` points to memcached so it's whatever process you started for that. It's persistent between requests and server restarts.

**Comment by lllusion3469** [comment]
I don't know what did it, but i tried
* `rake tmp:cache:clear`
* `systemctl restart memcached`
* `{echo flush_all; echo quit} | nc localhost 11211`
* `rm -rf tmp/cache`
while danbooru was not running

Restarting danbooru with `mech.cookie_jar.clear` was commented out resulted again in it working only a single time.
Afterwards, I followed the same procedure again, with these changes in place, then starting danbooru:
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -118,7 +118,7 @@ module Sources
       def agent
         @agent ||= begin
           mech = Mechanize.new
-          auth, userinfo = session_cookies(mech)
+          auth, userinfo, auth_secure = session_cookies(mech)
 
           # This cookie needs to be set to allow viewing of mature works
           cookie = Mechanize::Cookie.new("agegate_state", "1")
@@ -136,6 +136,11 @@ module Sources
           cookie.path = "/"
           mech.cookie_jar.add(cookie)
 
+          cookie = Mechanize::Cookie.new("auth_secure", auth_secure)
+          cookie.domain = ".deviantart.com"
+          cookie.path = "/"
+          mech.cookie_jar.add(cookie)
+
           mech
         end
       end
@@ -158,9 +163,10 @@ module Sources
 
           auth = mech.cookies.find { |cookie| cookie.name == "auth" }.value
           userinfo = mech.cookies.find { |cookie| cookie.name == "userinfo" }.value
+          auth_secure = mech.cookies.find { |cookie| cookie.name == "auth_secure" }.value
           mech.cookie_jar.clear
 
-          [auth, userinfo]
+          [auth, userinfo, auth_secure]
         end
       end
     end
```
and it seemed to work consistently every single time.
After undoing the change, it stopped working again.

I don't know what would happen with my change in place if deviantart, didn't set a `auth_secure` cookie.

Note that this has been happening for about 3 weeks now, and I even rebootet a few times in that time frame.

**Comment by r888888888** [comment]
Oh I see what's going on.

They sometimes throw up a CAPTCHA to prevent botting.

I'm not sure if there's a great answer for this.

**Comment by lllusion3469** [comment]
After pulling commit `bc69badadd9fafb41b62c67e16182c3ad3e0b482` the error message stayed the same:
```txt
NoMethodError exception raised

    undefined method `sub!' for nil:NilClass
    app/logical/downloads/rewrite_strategies/tumblr.rb:57:in `rewrite_cdn'
    app/logical/downloads/rewrite_strategies/tumblr.rb:11:in `rewrite'
    app/logical/downloads/file.rb:49:in `block in before_download'
    app/logical/downloads/file.rb:48:in `each'
    app/logical/downloads/file.rb:48:in `before_download'
    app/controllers/uploads_controller.rb:10:in `new'
```
As I understand it, this implies that it hasn't been served a CAPTCHA.

The almost same fix, again, fixes it on my end:
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -118,7 +118,7 @@ module Sources
       def agent
         @agent ||= begin
           mech = Mechanize.new
-          auth, userinfo = session_cookies(mech)
+          auth, userinfo, auth_secure = session_cookies(mech)
 
           if auth
             # This cookie needs to be set to allow viewing of mature works
@@ -136,6 +136,11 @@ module Sources
             cookie.domain = ".deviantart.com"
             cookie.path = "/"
             mech.cookie_jar.add(cookie)
+
+            cookie = Mechanize::Cookie.new("auth_secure", auth_secure)
+            cookie.domain = ".deviantart.com"
+            cookie.path = "/"
+            mech.cookie_jar.add(cookie)
           end
 
           mech
@@ -166,9 +171,10 @@ module Sources
 
           auth = mech.cookies.find { |cookie| cookie.name == "auth" }.try(:value)
           userinfo = mech.cookies.find { |cookie| cookie.name == "userinfo" }.try(:value)
+          auth_secure = mech.cookies.find { |cookie| cookie.name == "auth_secure" }.try(:value)
           mech.cookie_jar.clear
 
-          [auth, userinfo]
+          [auth, userinfo, auth_secure]
         end
       end
     end
```

This [commit](https://github.com/4pr0n/ripme/commit/b662b46a44a087af316953b10aee537397f2fa2a#diff-aab4e263d591d1c7f23d015a2e540a32R161) seems to indicate, that this cookie has already existed for at least 4 years, though, so I don't get why it would only be necessary sometimes.

**Comment by lllusion3469** [comment]
I think this would fix it for anyone having this problem without breaking any other system:
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -118,7 +118,7 @@ module Sources
       def agent
         @agent ||= begin
           mech = Mechanize.new
-          auth, userinfo = session_cookies(mech)
+          auth, userinfo, auth_secure = session_cookies(mech)
 
           if auth
             # This cookie needs to be set to allow viewing of mature works
@@ -136,6 +136,13 @@ module Sources
             cookie.domain = ".deviantart.com"
             cookie.path = "/"
             mech.cookie_jar.add(cookie)
+
+            if auth_secure
+              cookie = Mechanize::Cookie.new("auth_secure", auth_secure)
+              cookie.domain = ".deviantart.com"
+              cookie.path = "/"
+              mech.cookie_jar.add(cookie)
+            end
           end
 
           mech
@@ -166,9 +173,10 @@ module Sources
 
           auth = mech.cookies.find { |cookie| cookie.name == "auth" }.try(:value)
           userinfo = mech.cookies.find { |cookie| cookie.name == "userinfo" }.try(:value)
+          auth_secure = mech.cookies.find { |cookie| cookie.name == "auth_secure" }.try(:value)
           mech.cookie_jar.clear
 
-          [auth, userinfo]
+          [auth, userinfo, auth_secure]
         end
       end
     end
```

**Comment by r888888888** [comment]
If you write a pull request I can merge that in.

**Comment by evazion** [comment]
http://danbooru.donmai.us/uploads/new?url=http://xxnikichenxx.deviantart.com/art/Miss-Fortuna-lingerie-v1-League-of-Legends-694099971

Reopening because this is happening again. Uploading the above post still fails.

**Comment by lllusion3469** [comment]
With my change it has been working perfectly for me except when get a captcha.
As far as I can tell, since you're just returning nil in 
https://github.com/r888888888/danbooru/blob/e006380567c0652ea35d4b2b5598e4d025b5d82a/app/logical/sources/strategies/deviant_art.rb#L187
a captcha would, in this case, cause the same error message.
On my machine I put a "raise 'captcha'" there, so I can tell when this happens.
Is that possible, or have you already checked that?
I can't test it right now, since I'm not getting a captcha.
(I'm not sure, but 2 hours of cache time might be too long sometimes, sometimes it might log you out sooner than that)

**Comment by lllusion3469** [comment]
When I modify my session_cookies to return nil unconditionally (which is what happens when you get a captcha)
```ruby
def session_cookies(mech)
  return nil
end
```
I get the same error message as before (no mention of any captcha issue):
```
NoMethodError exception raised

    undefined method `sub!' for nil:NilClass
    app/logical/downloads/rewrite_strategies/tumblr.rb:57:in `rewrite_cdn'
    app/logical/downloads/rewrite_strategies/tumblr.rb:11:in `rewrite'
    app/logical/downloads/file.rb:48:in `block in before_download'
    app/logical/downloads/file.rb:47:in `each'
    app/logical/downloads/file.rb:47:in `before_download'
    app/controllers/uploads_controller.rb:10:in `new'
```

But as I mentioned before, the cache expiry of 2 hours might possibly also be an issue:
I modified it once to be higher, and I think that also resulted in the same message after some time, it might also have happened once after changing it back, but I really don't know.

**Comment by evazion** [comment]
After changing it to raise an error, it turns out that on my dev machine I'm getting captcha'd every single time, even with session caching turned off completely.

We should probably just switch to using their official API: https://www.deviantart.com/developers/
