### ISSUE TITLE
Uploaders should be able to see and edit their own uploads tagged under loli/shota

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3261]
The current system REALLY sucks. 
Not only you cannot see your own uploads if they're tagged as loli/shota when searching for files you uploaded, you can't even edit the tags for said posts in case you made a mistake on upload - or add a translation/commentary. 

This is even more pointless if you consider the fact that, as the uploader, you've already seen those files and presumably know how to get any of them without going through danbooru, which makes the block completely pointless.

Rather than incentivizing buying a gold account, this just curbs down contribution.

Currently the only way to do this is to wait to add the censored tags only when you're 100% sure you've tagged everything correctly, but it's an obtuse way to do it because it's just circling around the problem without addressing it.

Another problem is that member-level uploaders, with an uploading cap, can only tell when they'll be able to upload again by looking at their previous uploads. Censoring your own uploads makes the situation even worse because they completely disappear from self-searches and turn this into a guessing game.

**Comment by r888888888** [comment]
You're welcome to use another site.
