### ISSUE TITLE
failbooru on fresh install

### ISSUE THREAD

**Issue by tbennett6421** [r888888888/danbooru#3269]
I've struggled through getting this installed and finally got the deployment working. When I browse to the site I receive a webpage titled **Failbooru**  with a body of **Something broke**

I've checked the postgres schema and tables and all looks good.
I've checked the rails database connection and it appears to be working.
I then ran into the following error in the nginx error logs for the site.

2017/08/12 22:23:07 [error] 1318#1318: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.51, server: danbooru.redacted.domain, request: "GET /assets/application.css HTTP/1.1", upstream: "http://127.0.0.1:9000/assets/application.css", host: "danbooru.redacted.domain", referrer: "http://danbooru.redacted.domain/"
2017/08/12 22:24:21 [error] 1318#1318: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.51, server: danbooru.redacted.domain, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "danbooru.redacted.domain"
2017/08/12 22:32:03 [error] 1318#1318: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.51, server: danbooru.redacted.domain, request: "GET /assets/application.css HTTP/1.1", upstream: "http://127.0.0.1:9000/assets/application.css", host: "danbooru.redacted.domain", referrer: "http://danbooru.redacted.domain/"

I can confirm through netstat output that port 9000 is not listening on this host.
There are no rules in iptables.

What do I need to do now?

**Comment by r888888888** [comment]
Check the process list and make sure Unicorn is running:

`ps ax | grep unicorn`

If not your first step is to get it running.

**Comment by tbennett6421** [comment]
I have 24 instances on Unicorn running on this machine. The web page is still broken.

![cap](https://user-images.githubusercontent.com/6843296/29297145-84918bd4-8124-11e7-9bdf-71bc5419f0e9.png)

**Comment by tbennett6421** [comment]
I figured out what was going on, I missed a commented option in the unicorn/production.rb file.

Changing a redeploying has the webserver running correctly now

**Comment by evazion** [comment]
Closing since seems to have been resolved.
