### ISSUE TITLE
Image replacement on /cached/ images doesn't create/update sample images

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3274]
> [BrokenEagle98 said:](http://danbooru.donmai.us/forum_posts/134783)
> Most of the sample-size images for [pool #2383](http://danbooru.donmai.us/pools/2383) are missing, the only good one is the first. The full size images are still there, so they probably just need to go through the replacement process again to generate the sample images... hopefully... :/

> [EB said:](http://danbooru.donmai.us/forum_posts/134796)
> I've noticed that same thing has happened with pretty much all of my old uploads that were replaced. Tried replacing one of them with the same image to see if anything happens, but got nothing. It seems like this affects posts with IDs of less than 1000000.

**Comment by r888888888** [comment]
They're not on S3. This may have been some weirdness caused by the files being moved out of Amazon Glacier. I can regenerate them but it will take some time.

**Comment by BrokenEagle** [comment]
Okay... I thought that all images that had `/cached/` in the URL path were on S3...?

**Comment by r888888888** [comment]
They're supposed to be.

**Comment by r888888888** [comment]
this is being covered in #3290
