### ISSUE TITLE
Allow builders to delete pools

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3282]
Currently only mods can mark pools as deleted. This makes cleaning up pools a slow process. Given that pools are only soft deleted and they can be easily undeleted, it should be safe to extend this permission to builders.

**Comment by BrokenEagle** [comment]
+1 agree with this.  There are dozens of pools put up for deletion that still waiting to be deleted.  The fact is, that moderators just aren't as active as builders.  And like Evazion said, pools are only soft deleted, making mistakes much easier to clean up.
