### ISSUE TITLE
Unable to Unfavorite posts

### ISSUE THREAD

**Issue by gcscaglia** [r888888888/danbooru#3285]
In version d124ff8 (live at danbooru), I'm unable to unfavorite posts.

Before favoriting a post, the Favorite link has an format such as: `http://danbooru.donmai.us/favorites?post_id=2812295`. After favoriting, the link becomes `http://danbooru.donmai.us/favorites/2812295`, and clicking it does not unfavorite the post.

Using the browser developer tools, I can see the link issues a `DELETE` request, and the server answers with a `403 Access Denied` with the content bellow:

```html
<HTML>
<HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Access Denied</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: You are not allowed to access the document you requested.
</B></FONT>
<HR>
</BODY>
```

**Comment by BrokenEagle** [comment]
Unbreakable and I are still able to unfavorite a post. http://danbooru.donmai.us/forum_topics/9127?page=198

The issue may be similar to what DeusExCalamus experienced a week ago which was resolved by the user clearing their Danbooru cookies.

**Comment by gcscaglia** [comment]
I can confirm the problem is on my side, cleaning the cookies solved the issue. Thank you.
