### ISSUE TITLE
Pool renaming wrongly checks deleted pools

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3286]
I kept trying to rename [pool #9827](http://danbooru.donmai.us/pools/9827), and kept getting errors saying that the name was already taken.  I performed a pool search trying to find this pool and didn't come up with anything.  It wasn't until I searched with **search[is_deleted]=true** that  I found a hit with [pool #9828](http://danbooru.donmai.us/pools/9828).  I ended up having to rename that pool before I could change the name of the first pool.

**Comment by r888888888** [comment]
Pool names still have to be unique regardless of status (because of the way searches are handled) so it's probably better to improve the search options.
