### ISSUE TITLE
Support cropped thumbnails

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3287]
Assuming a device width of 360px:

* Add support for 150x150 and 640x320 cropped and resized images. 
* This allows 3 thumbnails per row (rescaled to 120x120, the css property object-fit is useful for this)
* Only recent images will be converted.
* Use [Thumbor](https://github.com/thumbor/thumbor) for smart cropping. Should probably set up a new service to read messages off SQS and process asynchronously and upload to S3.

**Comment by r888888888** [comment]
I am currently testing this on posts with id<1000.

**Comment by r888888888** [comment]
It turns out face detection isn't super reliable on cartoon faces.

I think a better algorithm would be to focus on the rule of thirds based on aspect ratio.

**Comment by evazion** [comment]
This was implemented. Smarter cropping could still be explored.
