### ISSUE TITLE
Don't prune the post_approvals table

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3288]
Throwing this in as a suggestion. Certain users are irritated by the fact that post can be approved twice by the same person if the approval period is a month apart; maybe this is something worth considering, given that the resulting table would grow only a couple records more than posts table. 

If accepted, a fix script should also be run, to have the table populated. Not sure about the proper way of devising the approval date, though.

**Comment by r888888888** [comment]
I think this should be fine.
