### ISSUE TITLE
Set "Deleted?" option on comment search page to false and hide

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3291]
The **Deleted?** option on the comment search page is of questionable utility when deleted comments aren't displayed for HTML queries anyway.  Hide the option and have it always set to 'false'?  Or just don't use the parameter at all and make 'false' the default when it isn't used, so that comment search links from profiles exclude deleted comments as well...

**Comment by BrokenEagle** [comment]
Or show deleted comments when the **is_deleted** parameter is set to *True*.  They're visible from the API anyways.
