### ISSUE TITLE
Twitter video uploads sets the source incorrectly

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3293]
Reported on Discord, and verified on Testbooru.  http://testbooru.donmai.us/posts/43

The above post was uploaded using the bookmarklet.  On the upload page, it listed the Tweet link as the source, however once the post was created, it lists the video link as the source.

**Comment by r888888888** [comment]
Do you know what the Tweet page was?

**Comment by BrokenEagle** [comment]
Ah, sorry, should have included that.

https://twitter.com/Al_Grimm/status/905471563226423296
