### ISSUE TITLE
Revise how uploads slots get reset

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3294]
Brought up in Discord and the [Danbooru forum](http://danbooru.donmai.us/forum_topics/11878?page=8).

Basically, the issue comes down to upload slot drift.  For example, if a user uses all of their slots by 10pm, then the following day, they have to wait until that time to finish using all of their slots for the day.  However, due to the imprecise nature of uploading, the upload won't occur until at minimum a minute or two later, so the new time would be 10:02pm.  This drift keeps occurring for all upload slots, until the reset period comes sometime after midnight.  This essentially leads to users having to throw away an entire day every once in a while to start their uploads earlier in the day.

Two ideas for this were proposed on the forum.

1. Make the refresh period for upload slots 23 hours
2. Reset all upload slots for all users at 0000 UTC

1 has the advantage of only having to adjust a few values to use 23 hours instead of 1 day, however it could technically give users more upload slots per day on average.

2 would require more of a rework in the code, but it has the advantage of keeping the refresh period to a day.

For myself, I'd be more in favor of 2.

**Comment by r888888888** [comment]
The disadvantage of 2 is it favors certain time zones where the reset happens around the time where they might get home or before they leave for work/school. It might also cause a stampeding effect around reset time.

**Comment by BrokenEagle** [comment]
Well, 2 only favors those that want to use up two days worth of upload slots in a single day.  If they do that, then that limits when they can upload in the surrounding days.

Let's say that the reset time for an individual works out to be 6pm and their upload limit is 50.  They could technically upload 50 before 6pm and 50 after 6pm for a total of 100 uploads.  However, if they do that, they are effectively limiting themselves to not uploading after 6pm the day before, and not uploading until after 6pm the day after.

It's true though that there could be a stampede effect, though it would only happen for those individuals that are home when the reset occurs.  Not sure whether that's a disadvantage enough to avoid using 2 though...?

**Comment by r888888888** [comment]
I think the forum response favors 1. I'm okay with the slight bump in limit, it's only 1-2 anyway, and it's simpler to implement.
