### ISSUE TITLE
IPv6 addresses are sometimes recorded

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3304]
Somehow, IPv6 addresses are sometimes recorded as the users' addresses. https://danbooru.donmai.us/posts/2856120 has a few examples. I'm not sure on what this will break, but I'm pretty sure danbooru was built with v4 IPs in mind, so it's better to fix this and change those IPs to 127.0.0.1 or something.

**Comment by BrokenEagle** [comment]
There are a couple options for this that I see...

1. Record all IPv6 as 127.0.0.1 or some other static non-routable IP
2. Disallowing IPv6 connections for users
3. Rework code to account for IPv6

**Comment by evazion** [comment]
Does this actually break anything? Postgres can handle both in the same datatype (https://www.postgresql.org/docs/10/static/datatype-net-types.html), and I don't think do anything with subnets (so we don't have to worry about IPv4 subnets vs IPv6 subnets, for example), so as far as I can tell it should be fine.

**Comment by Type-kun** [comment]
well, IP bans will get problematic, for one thing.

**Comment by hakusaro** [comment]
Just putting it out there that [v6 adoption is at about 17%](https://www.google.com/intl/en/ipv6/statistics.html). It's probably better to see what isn't working with v6 and patch in the direction of making v6 support more final than it is to try to stick with v4.

**Comment by evazion** [comment]
I don't think anything is broken with this. I agree that Danbooru should support IPv6.
