### ISSUE TITLE
Upload Limit Tooltip in user profile reports wrong time left for next free slot

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3305]
As the title says. 

For example, right now for me it is 21:52.  [I have an upload limit of 49](http://danbooru.donmai.us/users/508240), and my tooltip says "19 minutes left".
 ![3jnnlhowsuen_tmp 817laxmj6f](https://user-images.githubusercontent.com/12946050/30500804-47424bd8-9a60-11e7-9dd8-a676f159ec50.png)
However as [my actual 49th last upload](http://danbooru.donmai.us/posts/2855500) shows, the next upload slot will become free in ~10 minutes (at 22:00, since the uploaded time for the above was 23:00). 
![hjwgqxehu5mw_tmp 9hkyehl5zx](https://user-images.githubusercontent.com/12946050/30500926-c304c9a8-9a60-11e7-8db3-b9541b23ab8e.png)

This discrepancy started happening when the cooldown for upload slots was reduced to 23 hours.

**Comment by r888888888** [comment]
My concern for making the 23 hour window explicit is then eventually people will assume the window is 23 hours when the intent was for it to be 24 hours, and then the expectation will be to push the window to 22 hours. Maybe I'm being irrational?

**Comment by nonamethanks** [comment]
Well, the only reason to lower it was to make sure the upload slots reset wouldn't keep moving forward until the user had to either abandon uploading for a day every once in a while, or change sleeping schedule. 
Seeing that the amount of users that consistently hit the upload limit over a long amount of time is pretty low relatively speaking, I doubt anyone will ask for it to be lowered even further. Even more so since the only problem with the 24 hours system was preventing us from uploading at the same hours, a problem which was completely solved with the switch to 23 hours.

**Comment by BrokenEagle** [comment]
Yeah, I agree with nonamethanks.  I don't think it will be too much of an issue.  The purpose was to avoid upload drift on what is intended to be a daily refresh rate.  Anything beyond that will just be greed on the part of users and can be shot down accordingly.  I'd even emphatically argue against it if it ever comes up.
