### ISSUE TITLE
Unable to fetch source data during upload. Error: nil

### ISSUE THREAD

**Issue by tbennett6421** [r888888888/danbooru#3309]
Unable to use the fetch source data option.

Adding a source url to either a post image or the direct link to image and clicking fetch source data results in an error message.
```
Error: Sources::Site#get delegated to strategy.get, but strategy is nil: #
```

**Comment by r888888888** [comment]
This is (more or less) expected behavior if none of the sites match. I could fix it to return a more intelligent status code if you think that would be useful. In practice this doesn't happen very often because the majority of the content from URL is from a few sites.

**Comment by tbennett6421** [comment]
Is there a list of supported sites? I just though something was broken with my instance.

**Comment by r888888888** [comment]
You can find a list [here](https://github.com/r888888888/danbooru/tree/master/app/logical/sources/strategies) and you are free to add your own to expand the logic.

**Comment by tbennett6421** [comment]
Okay, thanks for clarifying that
