### ISSUE TITLE
Usability: Search box

### ISSUE THREAD

**Issue by hakusaro** [r888888888/danbooru#3310]
Right now, I have questions about the search box. Is it really this small on everyone's displays?

![screen shot 2017-09-21 at 15 18 19](https://user-images.githubusercontent.com/532647/30719285-1e9a60ce-9ee0-11e7-901b-1a2fd5ca6851.png)

The search box is an okay start at a search box, but I think it actually has several problems. If you want to create long, complex queries, like `1girl black_hair shirt rating:safe solo simple_background` you can do so additively fairly well: start with a general term and just keep adding at the end of the box.

However, if you forget which terms you've included in your query, you have no choice but to scroll back and forth in the box. You can also copy the text outside the box and edit in a different location, but this seems counter intuitive.

If it were a multi-line text field, this would be a lot simpler. It would show all active search parameters as well as let you easily add or remove them. I know you can just click the +/- buttons next to tags, but those buttons don't help if the tag you want to add to the query isn't listed. If you want to change your search in a big way, those buttons don't help either.

So, my suggestion is to either move the search box into an area where it can be larger (thus displaying more of the query at once), or turn it into a textarea so that it can expand in vertical space. Both of those would make searching a far better experience.

**Comment by r888888888** [comment]
Not sure if this is better.

**Comment by evazion** [comment]
IMO the search box should be moved to the header. This is what I do in my userscript (screenshot below).

The search box being in the sidebar causes a number of usability issues (search box is too small, search isn't available on most pages, on mobile the search box is buried way down at the bottom of the page) that can be fixed by moving it to the header. Search-on-top is how most sites work nowadays anyway.

![screenshot](https://i.imgur.com/x2qSC1C.jpg)

**Comment by hakusaro** [comment]
Until the commit goes live (I have no development environment or test environment setup), I can't really comment on the change. I think that @evazion's suggestion is definitely worth considering, however.

**Comment by evazion** [comment]
This change prevents the enter key submitting the search in the search box..

**Comment by r888888888** [comment]
fixed in 3eae2e279a9f92b720d5bb5a8741df1a0a239a1a

still not sure if this is worth doing overall. i guess i'll find out based on how many people complain.

**Comment by BrokenEagle** [comment]
There has been issues of readability raised on the [Danbooru forum](http://danbooru.donmai.us/forum_topics/9127?page=205).

It looks it's because text areas default to monospace, whereas text inputs use Arial.

**Comment by hakusaro** [comment]
@BrokenEagle it's worth noting that's probably a system or browser choice. The box just defaults to system-ui on Mac, which means it ends up rendering in San Francisco on Yosemite+. I obviously can't comment on other platforms, though.

**Comment by Type-kun** [comment]
I can't say I like this implementation choice. Since the default size stays the same, it became even harder to navigate through your own query because of natural textarea word-wrapping. I'd say that moving the search bar to the very top like Evazion suggested would make more sense. Or maybe give it its own full-length div under subnavbar where applicable? Roughly, like this: http://puu.sh/y1evx/94ebeb98e9.png - as an added benefit, "+" menu can potentially be expanded to full buttons. I think search function is important enough to make it that prominent.

**Comment by r888888888** [comment]
I agree. It's janky. I like your idea of moving it below the secondary links though.

**Comment by r888888888** [comment]
I've settled on a compromise since I didn't really like it on its own line afterall. It's not that pretty when it overflows into the images but I think that's an uncommon case and it's more usable than what we had before.

**Comment by r888888888** [comment]
Well, it's not very usable in responsive mode.

**Comment by BrokenEagle** [comment]
I agree that the responsive mode doesn't do as well with the current setup.  One potential idea might be to use two separate inputs for desktop and responsive mode.  Desktop mode would use the current setup with a text input, and responsive mode would use a text area, switching between them with the responsive CSS.

As a reference, the following is what it looked like yesterday with a text area on my phone in responsive mode and with some custom CSS to increase the height of the text area.

![image](https://user-images.githubusercontent.com/21149935/31785018-9e27f2be-b4b8-11e7-8eff-ddd27bbb14fc.png)

IMO the above is close to ideal on a phone as it presents the largest available viewing box to the user taking the onscreen keyboard into account.  When the user is entering tags, it'll be better to have as much screen area as possible.

**Comment by BrokenEagle** [comment]
User [MFZBdude](http://danbooru.donmai.us/users/346322) made a note on Discord about an issue with the search box in responsive mode.

> MFZBdude said:
> 
> Searching long tags in mobile view on mobile does not work very well.
> After a certain length, you lose sight of a portion of the autocomplete.

[Screenshot](https://cdn.discordapp.com/attachments/310846683376517121/370807898420281344/Screenshot_20171019-233756.png)

> BrokenEagle98 said:
> 
> Is it that it's pushing the autocomplete and all of the tags to the left...?

> MFZBdude said:
> 
> Yep.
> Can't scroll to get back to them, either.

I have confirmed this issue myself. Trying to move the window back will trigger the gesture controls which will go to the previous page.

**Comment by hakusaro** [comment]
I had a hunch that the 3D touch keyboard would help on iOS, but it has no real benefit. [This video shows how 3D touch does nothing to help](https://streamable.com/f8mhc).

Even when the search box was still a standard textbox, however, the responsive layout didn't have a great experience trying to search with lots of tags. In fact, it's usually harder to manipulate the text cursor on mobile devices, so it's more of a problem there.

If you try scrolling around Google's website on mobile, you encounter hilariously bad results as well: [Ex A](https://streamable.com/j1yog) and [Ex B](https://streamable.com/0mvde). This might be a surprisingly difficult problem to tackle.
