### ISSUE TITLE
Issues with gestures and hotkeys

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3311]
From the [Danbooru forum](http://danbooru.donmai.us/forum_topics/9127?page=202):

> Zekana said
> 
> On mobile, when a page is done loading that has a picture on it, for some reason it will scroll off to the right with a blank white page. I can move the page to the left to view everything but the moment I scroll 1 or down it instantly does it again. If I switch to "request desktop site" I don't have any issue. I was on earlier today and this stuff wasn't happening so not sure what is up with it.

Have confirmed this for myself, on both the post/show and post/index pages.  It didn't seem to happen on a few of the other pages that have thumbnails, such as comments or artists.  Trying to pan back left is particularly annoying, as if you pan too much it acts as if you used the backspace key and takes you to the previous page.

There is also some additional related behavior as noted below.

> Art stalking said:
> 
> I seem to be having an issue where if I try to press "a" to go to the previous post, it will essentially function as a page back button. For example, if I am looking through an artist's posts, I can still use "d" to look at the next set of images, but "a" will go back a page.
> 
> Edit: It happens only when looking at a post, if looking at a search page or a favorites group, it will function as it should.

"A" seems to have been switched to the backspace key on the post/show page, yet it still works as expected on the post/index or favorite/index pages.

**Comment by r888888888** [comment]
I believe I've deployed a fix for Zekana's problems. Thresholds have been raised all around and there's no more janky partial movements.

As for Art, that happens on posts/show. I think probably I need to write a dedicated handler for gesture.

**Comment by BrokenEagle** [comment]
It was [reported on Danbooru](http://danbooru.donmai.us/forum_posts/136523), and confirmed by myself, that pinch zooming both in and out seems to be mostly disabled on the post/show page.  It's difficult, but somewhere below the image you can pinch zoom in, but once zoomed in I was unable to zoom back out.  Also when zoomed in, I could for the most part only pan up or down.  Panning to the right sometimes worked, but panning to the left would cause the browser to return to the previous page.

Test setup:
- Samsung Galaxy S6
- Chrome

**Comment by BrokenEagle** [comment]
There have been some reports on Danbooru of high sensitivity to the backswipe motion on the post show page that enacts the backpage action ([forum #137014](https://danbooru.donmai.us/forum_posts/137014) [forum #137085](https://danbooru.donmai.us/forum_posts/137085)).  I have been unable to replicate this myself though ([forum #137015](https://danbooru.donmai.us/forum_posts/137015)).

**Comment by r888888888** [comment]
Gestures can now be disabled in settings.
