### ISSUE TITLE
Uploading ugoiras doesn't work with batch bookmarklet

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3317]
Brought up by nonamethanks on Discord.

Basically, uploading an ugoira with the batch bookmarklet will only load the first frame, whereas using the post bookmarklet still works as expected.  I was unable to demonstrate this issue due to #3316, but you can check out the following upload pages that have been loaded using the post and batch bookmarklets and comparing the source.

- Image used: [pixiv #59523577](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=59523577)
- [Upload page using the Batch bookmarklet](http://testbooru.donmai.us/uploads/new?ref=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D59523577&url=https%3A%2F%2Fi.pximg.net%2Fimg-original%2Fimg%2F2016%2F10%2F18%2F03%2F07%2F28%2F59523577_ugoira0.jpg)
- [Upload page using the Post bookmarklet](http://testbooru.donmai.us/uploads/new?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D59523577&ref=)

**Comment by r888888888** [comment]
This is now fixed although getting the previews to load the images would be nice.

**Comment by BrokenEagle** [comment]
Brought up by @nonamethanks.  It seems like Twitter videos aren't loading image previews at all, no matter which bookmarklet is used.

[Original Twitter Link](https://twitter.com/ssukguk/status/891467243485147136)
[Post to Danbooru Upload Page](http://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Ftwitter.com%2Fssukguk%2Fstatus%2F891467243485147136&ref=)
[Upload Page Screenshot](https://puu.sh/xPS8O/a64b6995e4.png)

**Comment by evazion** [comment]
That's a separate issue. The upload page doesn't do any filetype detection when displaying the preview, it just assumes everything is an image and thus can't handle webms/mp4s or ugoiras.
