### ISSUE TITLE
Resolution with Random on Post/Show

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3318]
[From Danbooru](http://danbooru.donmai.us/forum_posts/137005):

> CodeKyuubi said:
> 
> I've noticed I can now only go to a random post from the search page, but not the post itself. This is rather detrimental when I want to go through my favorites randomly.

Didn't realize this was removed myself.  If this is permanent, then certain other items need to be adjusted, to include maybe the Javascript, but definitely the [Hotkey listing](http://danbooru.donmai.us/static/keyboard_shortcuts).

**Comment by evazion** [comment]
It was removed in ffb212c616921536855931b8560d88707f082cf5. I would argue it's extraneous on the `/posts` page, but not on the posts show page.

**Comment by r888888888** [comment]
I'm going to be pedantic. I've always thought it weird to have this link on the sidebar that had nothing to do with the post itself but rather was just some UI for randomly navigating through a search. The fact it does this isn't even obvious from the link text. I can write a bookmarklet or a user script to emulate the old behavior if people are adamant on having it.

**Comment by BrokenEagle** [comment]
> I can write a bookmarklet or a user script to emulate the old behavior if people are adamant on having it.

I was going to do this myself otherwise... the following was the bookmarklet I came up with...
```
javascript:t=new URL(window.location);window.location=t.origin+'/posts/random?tags='+t.searchParams.get('tags');
```
...or using a script to rebind the R key...
```
$(document).off(".random");
Danbooru.keydown("r","random",e=>{
    let t = new URL(window.location);
    window.location=t.origin+'/posts/random?tags='+t.searchParams.get('tags');
});
```

But it'd be better if there was an officially supported workaround.

**Comment by Type-kun** [comment]
For the record, I used to use that feature, too, so I'd like to see it back in one form or another.

**Comment by hakusaro** [comment]
Just figured I should mention that I spent a good 30 minutes trying to figure out why "r" for random didn't work on the post show view. The hotkey listing really needs to be updated, if this isn't coming back at least as a hotkey.
