### ISSUE TITLE
API Limits

### ISSUE THREAD

**Issue by tbennett6421** [r888888888/danbooru#3319]
How do admin go about raising the API limits in local deployments? I have roughly 3000 images to migrate platforms and regularly upload >80 images.

I'm using the root account (Level admin) and the user page shows API Limits 59/60.

**Comment by BrokenEagle** [comment]
https://github.com/r888888888/danbooru/blob/master/app/models/user.rb#L631

You can either change the Platinum limits, or add in limits for the higher levels, with `is_builder`, `is_moderator`, `is_admin`.

**Comment by tbennett6421** [comment]
Thanks for the assistance
