### ISSUE TITLE
Incorporate replacement comment info in the replacement history

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3324]
The automatic comment generated when a post is replaced is more informative than the corresponding entry in the replacement history.

**Comment by BrokenEagle** [comment]
Would it be beneficial to allow approvers to also add a comment, or maybe select a reason from a list of reasons like they do for disapprovals, for replacing a post.  As it is now, I've seen some replacements that were unexplainable, especially those that replace the image source with something from a completely different site.

http://danbooru.donmai.us/post_replacements?page=b9617&limit=1

Some ideas for a list could include...

1. Sample size
2. Non-revision (but MD5 is different)
3. Better version (for instances of extreme artifacts)
4. Other (specify with a comment)

**Comment by evazion** [comment]
#3324 implements this. Existing replacements will need to have their data filled in.

It will be possible to update a replacement's data with `PUT /post_replacements/:id.json?post_replacement[md5]=...`. Someone will need to scrape the data from the comments and update old replacements accordingly, though.

Letting approvers specify a reason is not a bad idea, although perhaps not as useful now that replacing is Mod-only. I'll leave this open for the idea anyway.
