### ISSUE TITLE
Anonymous + Vetted Users

### ISSUE THREAD

**Issue by tbennett6421** [r888888888/danbooru#3326]
Is there an option somewhere to require a user to login before being able to do anything on the website? Additionally how can I tie down registration such that new users need to be approved by a mod?

**Comment by r888888888** [comment]
There's no baked in way to do that. You can add the appropriate `before_filter :member_only` to the controllers you want to protect. Importantly you'd want to keep `UsersController` open for the most part to allow signups.

**Comment by evazion** [comment]
> Additionally how can I tie down registration such that new users need to be approved by a mod?

Probably the simplest way would be to ban new accounts by default then have a mod unban vetted accounts. Adding `user.is_banned = true` to the `customize_new_user` method in your `danbooru_local_config.rb` should do the trick.

**Comment by tbennett6421** [comment]
After adding ```user.is_banned = true``` to the ````customize_new_user``` method in ```danbooru_local_config.rb``` I get broken pages.

When a user registers they get a broken page with the following trace
```
NoMethodError in Users#show
Showing /var/www/danbooru2/releases/20171015155844/app/views/users/_ban_notice.html.erb where line #3 raised:

undefined method `reason' for nil:NilClass
<div class="ui-corner-all ui-state-error" id="ban-notice">
  <h1>Your account has been temporarily banned</h1>
  <p>Reason: <%= format_text CurrentUser.user.recent_ban.reason %></p>
  <p>Your ban will expire in <%= time_ago_in_words(CurrentUser.user.recent_ban.expires_at) %></p>
</div>

Trace of template inclusion: app/views/layouts/default.html.erb
Rails.root: /var/www/danbooru2/releases/20171015155844
```

When I try to edit the user accounts in question I also get a broken page with a trace showing
```
ActionController::UrlGenerationError in Admin::Users#edit
Showing /var/www/danbooru2/releases/20171015155844/app/views/users/_secondary_links.html.erb where line #31 raised:

No route matches {:action=>"show", :controller=>"bans", :id=>nil} missing required keys: [:id]
<div class="ui-corner-all ui-state-error" id="ban-notice">
  <h1>Your account has been temporarily banned</h1>
  <p>Reason: <%= format_text CurrentUser.user.recent_ban.reason %></p>
  <p>Your ban will expire in <%= time_ago_in_words(CurrentUser.user.recent_ban.expires_at) %></p>
</div>
Trace of template inclusion: app/views/layouts/default.html.erb
Rails.root: /var/www/danbooru2/releases/20171015155844
```

**Comment by r888888888** [comment]
Instead of setting `user.is_banned=true` you should create a ban: `Ban.create(user_id: user.id, reason: "whatever", duration: 10000)`.

This is a strange way to use bans though. It'd be better to just add a `before_filter :gold_only` to any controller you want restricted and manually promote users to gold.

**Comment by tbennett6421** [comment]
```before_filter :gold_only ``` does appear to be working better. Can you tell me how to delete the accounts I used for testing? When I try to edit the users from the admin user listing I get a broken page with the above stacktrace.

**Comment by r888888888** [comment]
You can open a Rails console from a shell terminal:

`bundle exec rails console`

Then execute this:

`User.destroy_all`

Adding the `before_filter :gold_only` will redirect anyone who isn't a gold level account or higher to the login page.

**Comment by tbennett6421** [comment]
Thanks both of you for the assistance
