### ISSUE TITLE
Tag post counts not updating

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3329]
Sometime yesterday the post counts stopped updating for some tags, perhaps as part of the BURs being run in [topic #14395](http://danbooru.donmai.us/forum_topics/14395).  The **under-rim_glasses** tag is the biggest offender I can think of right now, with a reported count of 1297, but an actual count of zero.

- Tag: http://danbooru.donmai.us/tags/684071
- Post: http://danbooru.donmai.us/posts?tags=under-rim_glasses&raw=true

I've tried to fix that tag and the other tags, but the tag correction doesn't appear to currently work.

**Comment by r888888888** [comment]
The delayed job worker is timing out reading the jobs. Not sure if it's because the table got so bloated. I'll try running an analyze vacuum to see if it helps.

**Comment by r888888888** [comment]
I've deleted all the update_related jobs which reduced the size to 600k rows.

**Comment by r888888888** [comment]
Adding an index on delayed_jobs.locked_by seems to have dramatically sped it up.

**Comment by r888888888** [comment]
I forgot increment/decrement post count creates extra jobs. I'm going to take the site down and let the workers catch up.

**Comment by r888888888** [comment]
This should be fixed now.
