### ISSUE TITLE
Twitter redirect for Downbooru doesn't work for all users

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3330]
The Twitter redirect only seems to work for a select group of users.

https://twitter.com/search?f=tweets&q=from%3Ateruyo%20%23danbooru&src=typd

It used to work for me in the past, but not anymore.  I thought it might be that a Twitter account is needed, but Chiara confirmed that he has an account yet still couldn't get it to work, whereas in contrast nonamethanks said that it was working for him.

**Comment by hakusaro** [comment]
The default search setting blocks "sexually explicit content" from showing up in results. If you do that query without that setting, you get nothing.

Before:
![screen shot 2017-10-22 at 12 00 15](https://user-images.githubusercontent.com/532647/31864754-9fcc57e4-b720-11e7-9cea-81912d110ab5.png)

Setting panel:
![screen shot 2017-10-22 at 11 59 27](https://user-images.githubusercontent.com/532647/31864756-a463e81c-b720-11e7-8895-1963df427152.png)

After disabling:
![screen shot 2017-10-22 at 12 00 25](https://user-images.githubusercontent.com/532647/31864757-ac863432-b720-11e7-93a9-661ba3798b75.png)

If you're logged out and you see the error message, you can click "search setting" but nothing happens.

![screen shot 2017-10-22 at 12 01 36](https://user-images.githubusercontent.com/532647/31864768-d25360d6-b720-11e7-9d90-17c9495ec6e8.png)

The best solution is probably to just create a separate status account or directly link to the profile.

**Comment by hakusaro** [comment]
I thought a Twitter widget would work, but Twitter doesn't appear to respect their own safe search toggle on the widget.

![screen shot 2017-10-22 at 12 06 22](https://user-images.githubusercontent.com/532647/31864816-81a13b44-b721-11e7-80f3-31c026a01327.png)

**Comment by r888888888** [comment]
I've switched accounts to @danboorubot.
