### ISSUE TITLE
Desktop mode user setting not being saved

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3334]
From [Danbooru](http://danbooru.donmai.us/forum_posts/137542):

> Laethiel said:
> 
> I'm using Chrome on Android, and Firefox on PC. I've enabled the "Desktop mode" option under Advanced Settings 3 separate times now, and after the second and third times I've immediately gone back and checked my Settings again to make sure it's set to Yes, and it is. But when I come back on a later day, it can have just reverted to No. This most recently happened just a few minutes ago: when I checked my settings (on my PC), "Desktop mode" was set to No again, even though I definitely didn't disable it. And after setting it to Yes, I loaded up danbooru on Android, and got the mobile version. Checking Advanced Settings on Android, Desktop mode was set to No, while on the same page on my PC, it was set to Yes. I don't know what's going on with it; it feels like maybe it's being saved locally instead of server-side, and then the local setting is overwriting the server-side setting.
> 
> For now, I've gone into Advanced Settings on both PC and Android and set Desktop mode to yes, and also selected "Request desktop site" on Android. I'll post again if the error continues.

Looking through the code, it looks like **desktop_mode** isn't really being set anywhere, and only being used as a different way to set or unset the **dm** cookie.  Is this supposed to be just a session variable, or a persistent setting that the user can set?

**Comment by r888888888** [comment]
It is indeed a cookie so he'd have to set it on each device.

**Comment by Cirnyan** [comment]
Both on desktop and android firefox, the dm cookie is set to expire at end of session, this requires setting it again practically every new day on mobile. is this intended?

**Comment by r888888888** [comment]
This will be moved to a pref in a95af95eaeaaa82cebed7acc236d5a7f34b6e580
