### ISSUE TITLE
Pageviews not registering in Google Analytics

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3336]
Something is wrong with the Google Analytics setup. On September 7th the site suddenly dropped from ~6 million pageviews per day down to ~600k. On Sept. 22nd it dropped again to ~100k pageviews per day. Something must be wrong here.

![screenshot](https://i.imgur.com/6KO8FTa.png)

**Comment by r888888888** [comment]
Google was complaining about sending too many hits so I had to introduce a sampling rate to cut down on the number of calls. It's currently set to 1 which means only 1% of hits are being sent to Google. So it's probably safe to multiply any number by 100.

**Comment by evazion** [comment]
Alright. Certain stats like average session duration are different (went from ~9:20 to ~6:10), but I guess that can't be helped.
