### ISSUE TITLE
Dmail timing out on unread mail check

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3339]
00Z622 reported this issue on Discord, which is the same issue as #2886.

> 00Z622 said:
> 
> This error's been plaguing me for weeks. Wonder if Danbooru hates me having ancient unread mails.

[Screenshot](https://cdn.discordapp.com/attachments/310846683376517121/370768906459283468/err.png)

It seems like he had some really old unchecked Dmails that were causing the issue, same as last time.

**Comment by Type-kun** [comment]
I'm pretty sure separate indexes on `is_read` and `is_deleted` are useless in this case, postgres will likely just use index owner_id or id instead of merging indexes. Multicolumn index on `owner_id, is_read` would probably work much better, though it's hard to tell without running `Explain` on live data.

**Comment by evazion** [comment]
I'm not sure if it would use a `(owner_id, is_read)` index either. I suspect that postgres is overestimating how many rows the query matches, causing it to choose the `id` index over other indexes because the query planner isn't accurately evaluating the costs. This is the same reason why queries like `solo solo_focus` time out (postgres overestimates how many results `solo solo_focus` returns and chooses the `posts.id` index when it should have used the `tag_string` index).

**Comment by Type-kun** [comment]
Well, there's only one certain way to check this. @r888888888 can you run `explain` on `SELECT "dmails".* FROM "dmails" WHERE "dmails"."owner_id" = 332700 AND (is_read = false and is_deleted = false) ORDER BY dmails.id desc LIMIT 1` please?

**Comment by BrokenEagle** [comment]
I don't know if this makes a difference, but the user with the above-named ID (OOZ662) already fixed his issue by clicking the "Mark all as read" link.  So I don't know if thr above query will show issues anymore...?

**Comment by r888888888** [comment]
``
danbooru2=# \d dmails
                                        Table "public.dmails"
     Column      |            Type             |                      Modifiers                      
-----------------+-----------------------------+-----------------------------------------------------
 id              | integer                     | not null default nextval('dmails_id_seq'::regclass)
 owner_id        | integer                     | not null
 from_id         | integer                     | not null
 to_id           | integer                     | not null
 title           | text                        | not null
 body            | text                        | not null
 message_index   | tsvector                    | not null
 is_read         | boolean                     | not null default false
 is_deleted      | boolean                     | not null default false
 created_at      | timestamp without time zone | 
 updated_at      | timestamp without time zone | 
 creator_ip_addr | inet                        | not null
 is_spam         | boolean                     | default false
Indexes:
    "dmails_pkey" PRIMARY KEY, btree (id)
    "index_dmails_on_creator_ip_addr" btree (creator_ip_addr)
    "index_dmails_on_is_deleted" btree (is_deleted)
    "index_dmails_on_is_read" btree (is_read)
    "index_dmails_on_message_index" gin (message_index)
    "index_dmails_on_owner_id" btree (owner_id)
Triggers:
    trigger_dmails_on_update BEFORE INSERT OR UPDATE ON dmails FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger('message_index', 'pg_catalog.english', 'title', 'body')
``

``sql
explain analyze SELECT "dmails".* FROM "dmails" WHERE "dmails"."owner_id" = 332700 AND (is_read = false and is_deleted = false) ORDER BY dmails.id desc LIMIT 1;

                                                                    QUERY PLAN                                                                     
---------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.42..549.51 rows=1 width=464) (actual time=47726.161..47726.161 rows=0 loops=1)
   ->  Index Scan Backward using dmails_pkey on dmails  (cost=0.42..59851.37 rows=109 width=464) (actual time=47726.159..47726.159 rows=0 loops=1)
         Filter: ((NOT is_read) AND (NOT is_deleted) AND (owner_id = 332700))
         Rows Removed by Filter: 485142
 Planning time: 0.171 ms
 Execution time: 47726.197 ms
``

``sql
analyze dmails;
``

``sql
explain analyze SELECT "dmails".* FROM "dmails" WHERE "dmails"."owner_id" = 332700 AND (is_read = false and is_deleted = false) ORDER BY dmails.id desc LIMIT 1;
                                                                  QUERY PLAN                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.42..551.20 rows=1 width=465) (actual time=439.993..439.993 rows=0 loops=1)
   ->  Index Scan Backward using dmails_pkey on dmails  (cost=0.42..60034.79 rows=109 width=465) (actual time=439.991..439.991 rows=0 loops=1)
         Filter: ((NOT is_read) AND (NOT is_deleted) AND (owner_id = 332700))
         Rows Removed by Filter: 485142
 Planning time: 0.941 ms
 Execution time: 440.017 ms
``

Maybe the analyze is enough?
