### ISSUE TITLE
Incorrect tag category counts

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3365]
https://danbooru.donmai.us/posts/2924654.json

Some (all?) posts after #3353 was merged have incorrect `tag_count_*` fields. See above for an example; it says the post has 167 gentags, 4 artists, 4 characters, 4 copyrights, and 12 meta tags.

**Comment by evazion** [comment]
I *think* 5f39a8b fixes it. There were a few test failures in `test/unit/post_test.rb` that now pass, at least.

Leaving this open because the tag counts on affected posts still need to be fixed. I think just resaving the posts will be sufficient.

**Comment by BrokenEagle** [comment]
Ah, snap... don't know how I missed that. I thought I had rechecked each function individually?

What's the best way to go about resaving all of the posts?

**Comment by evazion** [comment]
Closing, I think the tag counts are correct now.
