### ISSUE TITLE
Delayed jobs not running

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3370]
Sometime yesterday when the new tag category was deployed, the Delayed jobs stopped running.  This is probably similar to #3329.  Right now, I can't even enumerate how many there are since the table has gotten so large.

**Comment by r888888888** [comment]
This probably needs to be moved to SQS or something because when the DJ table gets too big it starts affecting everything else.

**Comment by r888888888** [comment]
I had to vacuum the delayed jobs table.

It turns out `Tag#update_category_post_counts` can be slow and can easily bottleneck the worker. I'll take down the site and try to let it catch up.

**Comment by BrokenEagle** [comment]
@r888888888 

The delayed jobs has choked again.  It was at 3000 pages last night (20 per page, total 60K), and is well over the limit of 5000 right now.

The approximate end seems to be at...

http://danbooru.donmai.us/delayed_jobs?limit=100&page=3843

...so around 384K.

**Comment by evazion** [comment]
@r888888888 

Jobs are choked again. See https://danbooru.donmai.us/delayed_jobs?limit=100; the backlog is at ~285k jobs right now. Preprocessed uploads aren't working because of this.

There should really be some kind of monitoring or autorestarting here.

**Comment by evazion** [comment]
@r888888888 jobs are down once again. This really needs monitoring + autorestart on failure.
