### ISSUE TITLE
Add additional restrictions for changing tag categories

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3372]
Related to #3370, but that issue makes it a bit clear that changing tag categories should be restricted further based upon their tag count.  Admittedly, changing tag categories with high post counts should be a rare event, and adding a new tag category as for #3292 is a rare event.  Still, this demonstrates how easy it might be for an overzealous Builder+ to inadvertently break the site.

The following are just some spit-balled ideas for new restrictions:

1. Post count > 50: Builder+
2. Post count > 10000: Moderator+
3. Post count > 100000: Admin

**Comment by evazion** [comment]
I'd suggest restricting tags larger than 10,000 to admins only (to be honest, I wouldn't be against an even lower limit), and making a new type of bulk update request for requesting category changes. This way category changes would be proposed in the same way that aliases/implications are proposed.

**Comment by r888888888** [comment]
I think 10k + builder is sufficient for now. We can see if we need to further restrict it.
