### ISSUE TITLE
List approver in BUR approval messages

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3374]
Currently the BUR approval message looks like this:

```
The bulk update request #1386 has been approved.
```

But it's not immediately obvious what the request was and who approved it. The approver and the original forum post should also be included, like this:

```
The bulk update request #1386 (forum #139259) has been approved by @HillsideMoose.
```

**Comment by Type-kun** [comment]
Make sure `@mention` would not send a dmail to approver, though

**Comment by evazion** [comment]
Excuse the reference spam above. I force pushed some fixups and Github added a reference each time.

**Comment by r888888888** [comment]
Yeah I noticed this. I wanted to clear out the BUR queue before modifying the function signature.
