### ISSUE TITLE
Don't spawn unnecessary post count cache expiration jobs

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3376]
`Post.expire_cache_for_all` is called each time the tags are changed on a post, which causes a delayed job to be spawned for every edit. The purpose is to expire the `Post.fast_count` cache for the changed tags, but this cache is not actually used. For single tags, `Post.fast_count` gets the count from the `tags` table, not from memcache. There's nothing to expire here because counts for single tags aren't stored in memcache.

This can be verified by doing `Cache.get("pfc:#{Cache.hash("touhou")}")` and seeing that it returns null.

**Comment by r888888888** [comment]
Removing the job to expire the cache locally was removed in dba0117b99e69d368b88e088da866599874c54e7 which at least cuts the number of jobs in half.

I'm not sure if it's safe to remove entirely for single tags. `Post#fast_count` calls `Post#get_count_from_cache` which gets it from Memcache. Getting the count directly from Postgres is a simple call but it's still much faster to get it from the cache.

I do notice a bug with how the expiration interacts with safe mode/hide deleted posts mode.

I wish there was a way of knowing the post count for each tag when expiring the cache. If the count is high then it's probably ok to skip a large percentage of the expiration calls.

**Comment by evazion** [comment]
The count is only stored in Memcache if `get_count_from_cache` returns zero and we enter `fast_count_search`. But for single tags that never happens. `get_count_from_cache` first checks Memcache, which fails, then checks the database, which will always succeed.

Doing `Post.fast_count("touhou"); Cache.get(Post.count_cache_key("touhou"))` should confirm this. The cache is never getting set for single tags, we're always getting the count from the database.

**Comment by r888888888** [comment]
I see now. `get_count_from_cache` never sets the value if it goes to the database.
