### ISSUE TITLE
Batch bookmarklet doesn't fetch artist/tags from twitter

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3377]
The batch bookmarklet currently tries to fetch twitter data from the direct image url rather than the post page, and so it fails.
Example: https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Ftwitter.com%2Flegacy2outback%2Fstatus%2F931158838727733248

![](https://i.imgur.com/hboq0dt.png)

**Comment by r888888888** [comment]
https://twitter.com/legacy2outback/status/931158838727733248 is invalid.

**Comment by nonamethanks** [comment]
Hm, seems that twitter post expired.  https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Ftwitter.com%2Fmochimochiart%2Fstatus%2F930553450072543232 is another example - for me really any twitter post fails in the same way. It works instead on testbooru (http://testbooru.donmai.us/uploads/batch?url=https%3A%2F%2Ftwitter.com%2Fmochimochiart%2Fstatus%2F930553450072543232)
