### ISSUE TITLE
/post_versions pages don't update instantly anymore

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3378]
I replicated this a few times, and another user on the forums had the same problem. It seems a few minutes need to pass currently before the posts versions pages (both the general one and the post specific ones) correctly register tag changes. Until yesterday the update was instant.

The actual tag list from the post page is unaffected.

**Comment by r888888888** [comment]
This is dependent on how long the work queue is. Sometimes it'll be slow. What I can do is add a disclaimer about how large the lag is.

**Comment by nonamethanks** [comment]
That would be helpful! It's a bit confusing sometimes because freshly created posts might even display empty post versions.
![](https://cdn.discordapp.com/attachments/310846683376517121/380775586014167041/Post_Changes_Bug.png)
