### ISSUE TITLE
Error generated from source data when attempting to upload from upload page

### ISSUE THREAD

**Issue by hakusaro** [r888888888/danbooru#3382]
```
Error: Sources::Site#get delegated to strategy.get, but strategy is nil: #
```

Generated by (NSFW): https://i.imgur.com/CBjJItH.jpg

![screen shot 2017-11-17 at 17 07 59](https://user-images.githubusercontent.com/532647/32974277-1f091d96-cbba-11e7-983f-adc4a7dd03de.png)

**Comment by r888888888** [comment]
Imgur isn't supported.

**Comment by hakusaro** [comment]
Well, I expected that. I guess I more thought that it shouldn't scream if that happens?

**Comment by evazion** [comment]
40d0751 fixed a bug with artist URL normalization raising NoStrategyError when it tried to normalize unrecognized URLs in artist entries.
