### ISSUE TITLE
Fetch commentary not creating fully formed textile links

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3384]
Brought up by Chinatsu.  This issue was showing up on [post #2922731](https://danbooru.donmai.us/posts/2922731), though in case its been updated, I've included the Artist Commentary history for that post below.

https://danbooru.donmai.us/artist_commentary_versions?search%5Bpost_id%5D=2922731

**Comment by evazion** [comment]
It looks like the links on Deviant Art are missing the `http://`. They look like this: https://www.deviantart.com/users/outgoing?www.inprnt.com/gallery/teemutaiga/kisu.

**Comment by BrokenEagle** [comment]
Yeah, FWIW, I've seen other sites do similar things.  Besides the above, I've also seen only the `protocol` portion missing, as in `//www.inprnt.com`   But at least this seems to be a valid href, unlike the above.

https://stackoverflow.com/questions/8951423/html-links-without-http-protocol

**Comment by evazion** [comment]
This fixes it for DeviantArt, let me know if it's broken on other sites.
