### ISSUE TITLE
Bookmarklet sets wrong source for Tumblr posts

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3385]
I'm not sure how to replicate this, and I haven't been able to make some examples on testbooru because its upload page seems to be broken for post links, but basically almost all of my tumblr uploads as of the past two days or so have had the direct url to the image set as source, rather than the post. 
Until a few days ago the correct source was picked.

https://danbooru.donmai.us/uploads/1640768.xml for example was uploaded completely through the bookmarklet, but [the source is instead the image url](https://danbooru.donmai.us/posts/2928519), and so were [these other posts](https://danbooru.donmai.us/posts?tags=source%3A*data.tumblr.com*+age%3A%3C3d+user%3Anonamethanks+).
[Others instead](https://danbooru.donmai.us/posts?tags=source%3A*tumblr.com%2Fpost*+age%3A%3C2d+user%3Anonamethanks+) had the source set correctly.

**Edit:** Uploading through the /uploads/new page also uploads the wrong source. As it happens, one of my tries with it failed and https://danbooru.donmai.us/uploads/1640791  was the result - the source's incorrect here too.

**Comment by evazion** [comment]
The bug was caused by missing `||` operators in a conditional. It turns out that Pawoo, Tumblr, and ArtStation were all broken by this bug. Pawoo and Tumblr were broken in eeb41d2ffd555247c2df57239482591ec72013c0 (2 days ago) and ArtStation was broken in 118843b26a8b2015977f7832ba2a3eb2aa13c38b (since June 22nd). Oops.

**Comment by nonamethanks** [comment]
@evazion this should be reopened, because it's happening again. The bookmarklet works fine but using the post url on the upload page sets the image link as source.
https://danbooru.donmai.us/uploads/1832886.xml 
https://danbooru.donmai.us/uploads/1832883.xml

**Comment by evazion** [comment]
This got fixed as part of #3805.
