### ISSUE TITLE
Searching certain metatags results in an empty paginator

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3390]
Discussion: https://danbooru.donmai.us/forum_topics/14710

Searching for [pool:1537](https://danbooru.donmai.us/posts?tags=pool%3A1537) results in a empty paginator. `Post.fast_count("pool:1537")` returns 0.

The problem is that there is an empty tag named `pool:1537`. `get_count_from_cache` looks up `pool:1537` in the tags table, finds this tag, and returns 0. The tags table isn't supposed to contain metatags, but it does anyway because of past bugs. Funnily enough, this also means that for certain metatags the related tags are cached in the tags table.

This worked by sheer accident prior to 73f257e. Previously if `get_count_from_cache` returned 0, we fell back to `fast_count_search` and ran a full count.

The fix would be to either avoid looking up metatags in the tags table, or to purge invalid metatags from the tags table altogether. IMO the latter option would be better.

**Comment by BrokenEagle** [comment]
I'd be for purging them myself, as they don't add any value at this point.  I'd actually like to see a greater tag purge myself, removing all tags that don't meet the current tag name validations.  This would also have the side-benefit of fixing #3272 as well.

**Comment by evazion** [comment]
On second thought, I think it'd be best to do both (purge invalid tags and avoid looking up non-tags in the tags table), so that's what #3391 does.

**Comment by r888888888** [comment]
There are also lots of misspelled metatags like arist and aritst, although I doubt those cause many problems. What I could do is just prune any tag with a colon and zero post count.

**Comment by evazion** [comment]
To be honest, I think pruning all empty gentags would be safe. Pruning artist/copy/character tags, on the other hand, would delete tag type information on old post versions. I don't think this information is used anywhere, but still, it's potentially useful.

**Comment by evazion** [comment]
So the fix in 134958d didn't actually work for [pool:1537](https://danbooru.donmai.us/posts?tags=pool:1537). It still has an empty paginator. `pool:1537` is incorrectly identified as a simple tag, so `fast_count` still gets the count from the empty `pool:1537` tag in the tags table.

Pushed a better fix in b3a9cd6.
