### ISSUE TITLE
Bookmarklet on pixiv url with deleted post page returns failbooru, and trying to upload it returns an error

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3395]
I wasn't sure whether to open two bugs or one for this, so I apologize in advance.

https://i.pximg.net/img-original/img/2017/11/21/20/45/25/65987426_p0.jpg
Pic related is still alive, but https://www.pixiv.net/member_illust.php?mode=medium&illust_id=65987426 has been deleted. 
It used to be possible to upload this, but recent changes broke it and now it returns
```An error occurred: error: PixivApiClient::Error - Pixiv API call failed (status=400 body={"status":"failure","has_error":true,"errors":{"system":{"message":"対象のイラストは見つかりませんでした。(illust_id:65987426)","code":206}}})``` as a fail error (see https://danbooru.donmai.us/uploads/1644340) (which is displayed on the uploads/new page as ```Error: Pixiv API call failed (status=400 body={"status":"failure","has_error":true,"errors":{"system":{"message":"?????????????????????????????????????????????????????????(illust_id:65987426)","code":206}}})``` if one bypasses the bookmarklet)

Furthermore, using the bookmarklet on the picture url returns the failbooru "something broke" page.

**Comment by evazion** [comment]
The failbooru is a mixed encoding issue. The `PixivApiClient::Error` is because the download strategy tries to fetch the source data in the course of rewriting sample images to full size images, which fails if the work is bad ID. To be honest I don't see how this has ever worked.
