### ISSUE TITLE
More automated measures against spammers

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3408]
Today we had another spammer and I and several users got hit with a multitude of spam ([topic #1234/p3](http://danbooru.donmai.us/forum_topics/14440?page=3)).  Speaking for just myself, I got hit with 14 messages before a moderator finally banned the offender.  However, it's possible without a moderator on watch that the situation could have gone on for a lot longer.

Therefore, there should be more automated measures to block such users.  After so many spam messages sent in a certain time period, such users should either be auto-banned or at least blocked from sending DMails, although the former would probably be easier to implement.

**Comment by ghostrigger** [comment]
got some ideas, as of late this is a recurring annoyance. still is. definitely agree on automated process for faster and immediate action for mitigating damages. a mod review, if ever necessary for false positive, could come afterwards.

* forum topics untouched for 2 years should be locked by default. mods can always connect/join (implemented already) threads if needed. this also avoids necrobumps.

* basic members cannot create/post forum topics/threads with external links (beginning http and outside of donmai.us). this is not limited to newly signed accounts as some in the past stayed dormant for months. such posts can go directly to /dev/null or flag as spam and subject for mod review.

* blacklist certain keywords for topic/post creation for basic members like porn, p3rn, p0rn, etc, prefix and postfix with wildcards may apply.

* automatic negative feedback for users with suspicious activity described above.

**Comment by evazion** [comment]
For forum spam, I would suggest running posts through Akismet and requiring a captcha for things that fail the spam check. I think a hard ban of external links would be problematic (think of members linking to sites like Pixiv, for example).
