### ISSUE TITLE
`og:image` meta tags can point to video files

### ISSUE THREAD

**Issue by tsudoko** [r888888888/danbooru#3415]
Examples: [post #2916557][], [post #2941591][]

`preview` URLs always point to image files, but preview images might be too small for `og:image`. A possible soultion might be adding an additional sample URL that's guarenteed to point to a non-tiny image file.

[post #2916557]: https://danbooru.donmai.us/posts/2916557
[post #2941591]: https://danbooru.donmai.us/posts/2941591

**Comment by BrokenEagle** [comment]
For reference, Youtube uses multiple different size thumbnails for their video schema.

https://stackoverflow.com/questions/34763547/youtube-maxresdefault-thumbnails

If we go this route, I don't think we'd need as many.  Just one for the index preview and one for the ``og:image``.  Maybe tie it in with the issue on #3400.

**Comment by evazion** [comment]
131c010 switches to using the preview image for non-image posts. For Facebook shares, the minimum size is 200x200, so this is indeed too small for most uses, but it's at least valid.

**Comment by r888888888** [comment]
Fixed in 4dabbde05d72f6e9ef73c565ea2fb671f7c73542
