### ISSUE TITLE
Add back UI for turning "Embed Notes" on/off

### ISSUE THREAD

**Issue by john1980a** [r888888888/danbooru#3418]
The UI for turning "Embed Notes" on/off should be added back.  
It was removed in [commit b361809](https://github.com/r888888888/danbooru/commit/b361809489a0e8bb139d6c62214e881231135d25) with the following reasoning:
> It honestly isn't used much at all. It's active on 4450 posts, which represents 1.3% of all posts with notes. For existing posts it'll continue to work (and I suppose you can update it via the API) but I don't think that usage rate warrants taking up screen real estate.

Why it should be added back:

- It's a single checkbox. That doesn't take much real estate. It's not a good enough reason to remove a feature used on 1000s of posts. Was the checkbox always showing in the Edit options? If so, then why not only have it show when in Note Editing mode? That would solve any real estate concerns.

- A few users have already asked about this on [topic 14437](http://danbooru.donmai.us/forum_topics/14437).  The current bookmarklet workaround is not discoverable.

**Comment by BrokenEagle** [comment]
> If so, then why not only have it show when in Note Editing mode?

This would need some work.  The submit button for that is **Mark as Translated** after all.  We wouldn't want anyone to mistakenly add the **translated** tag before it actually becomes fully translated. 

One option could be that if no translation tags are detected on page load, then it will automatically select the **translation_request** selector.

**Comment by r888888888** [comment]
This has been re-enabled.
