### ISSUE TITLE
Webmaster email address not working

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3420]
From the [Danbooru forum](http://danbooru.donmai.us/forum_topics/14779):

> SwirlyNyan said:
> 
> I've tried emailing them numerous times in regards to a problem i'm having problems with my account not having gold after purchase. Every time I send an email I get a reply back from google saying that my message was not delivered.
> webmaster@danbooru.donmai.us
> This is the email i've been emailing and i'm not sure if its on my end or theirs.

@evazion commented that he's seen a few others that have said it's not working, and that it might be related to when the domain was transferred to CloudFlare.

**Comment by evazion** [comment]
Previous reports:

https://danbooru.donmai.us/forum_topics/14779
https://danbooru.donmai.us/forum_posts/138349
https://danbooru.donmai.us/forum_posts/136342

Perhaps the MX records got screwed up in the transfer?

**Comment by r888888888** [comment]
Should be fixed now.

**Comment by aslian** [comment]
There is no reply to my emails too. The last one was sent August 27, 2024, 4:11:19 PM UTC+00:00. Sending from the mail address of a `a_flan` user.

**Comment by nonamethanks** [comment]
You'll probably have better luck trying to contact evazion through discord, if it's important enough that it needs a reply from him.

**Comment by aslian** [comment]
@nonamethanks
thank you for response! I'd be happy to have an answer from any site admin. I think I'll just file an issue here.
