### ISSUE TITLE
/iqdb_queries.json fails for certain urls

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3424]
https://lohas.nicoseiga.jp/thumb/6844226i
http://seiga.nicovideo.jp/seiga/im6844226

A reverse search for the thumb for this page fails on https://danbooru.donmai.us/iqdb_queries.json?url=https://lohas.nicoseiga.jp/thumb/6827608i even though the image is fully accessible in browser. Same goes for every other seiga thumb.

**Comment by evazion** [comment]
The bug was that we supported http://lohas.nicoseiga.jp/thumb/6844226, but not https://lohas.nicoseiga.jp/thumb/6844226i. The former type of URL no longer works, and is possibly not used any more.
