### ISSUE TITLE
`unknown attribute 'body' for Artist.` on create action

### ISSUE THREAD

**Issue by Yukariin** [r888888888/danbooru#3425]
Hi!
I'm playing with my local danbooru setup and just get `unknown attribute 'body' for Artist.` on artist creation through API.
But according [api docs](https://danbooru.donmai.us/wiki_pages/43568) `artists` route accepts `body` attribute for `create` action.

**Comment by Yukariin** [comment]
Hrm, I'm not too good in Ruby and Rails but looks like it can be fixed with `attr_accessor :body`...

**Comment by evazion** [comment]
Try it with `notes` instead. The API docs may be out of date.

**Comment by Yukariin** [comment]
Yep, `note` works fine.
