### ISSUE TITLE
Current SSL certificates will be distrusted in upcoming versions of Chrome

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3426]
Saw the following error in the Chrome console recently.
```
The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```
Would updating to the latest version of New Relic fix that...?

I also saw the same issue for [where Isshiki logs the post views](https://github.com/r888888888/danbooru/blob/master/app/views/posts/show.html.erb#L153).
```
The SSL certificate used to load resources from https://isshiki.donmai.us will be distrusted in M66. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```
Therefore, this issue might also exist for the site itself.

On a side note, for those interested, would it be possible to get view access to the Danbooru data on New Relic?

**Comment by evazion** [comment]
Currently we're on version `3.13.0.229` of the `newrelic_rpm` gem, which is pretty outdated. The latest version is `4.6.0`. Changelog here: https://github.com/newrelic/rpm/blob/master/CHANGELOG.md#v3130.

I'd also be interested in having access to the New Relic data, if it's not too troublesome. It'd be useful for getting better insight into performance issues.

**Comment by evazion** [comment]
Found this: https://discuss.newrelic.com/t/bam-nr-data-net-using-symantec-certificate-that-will-be-distrusted-in-chrome-70/52370.

**Comment by r888888888** [comment]
I'm pretty sure isshiki is not covered by NewRelic (I believe they filter by subdomain) so that is not surprising. I will upgrade the gem version though.

**Comment by r888888888** [comment]
If you're interested in accessing NR send me your email and I can add you.
