### ISSUE TITLE
Lower the limit for tag category changes

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3448]
Talked about this with @evazion on Discord, where I asked him how long it takes to do a category tag change with 10K posts.  The following is the results from that, with the tag count of "partially translated" being approximate to 10K.
http://devbooru.tk:3000/tags?search[name]=partially_translated
```
[7] pry(main)> Benchmark.realtime { Tag.find_or_create_by_name("partially_translated").update_category_post_counts }
(621235.3ms) => 621.234996182844
```
So about 10 minutes.  A single one of these wouldn't break the site, but multiple ones could.  Even discounting performance issues, such large changes really should be discussed on the forum, and then validated by an Admin.

Lowering the limit to 1000 instead should be sufficient for most tag gardening cleanup required of Builder+ users.

**Comment by evazion** [comment]
I see there's also a bug with `Tag#editable_by?` not enforcing the same limits as `Tag#find_or_create_by_name`. Consequently builders can still change large tags with `/tags/1234/edit`.
