### ISSUE TITLE
Aliased tags are showing up under translated tags

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3450]
User Unbreakable brought this up on Discord.  Basically, if an aliased tag has an other wiki entry, it'll show up under the list of translated tags.  The example he gave was **俺タワー**, which was bringing up both **ore_tower** and **ole_tower**, the former which was aliased to the latter.

I deleted the **ore_tower** wiki which resolved the above issue, but for completeness, the translated tags displayer should reject all tags that have aliases.

**Comment by evazion** [comment]
Instead of filtering out aliased wiki pages, #3453 applies aliases to the found tags and then removes any duplicates. This should give effectively the same results.
