### ISSUE TITLE
Batch Bookmarklet for Artstation returns wrong results

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3459]
Quick example:
https://mokutan.artstation.com/projects/BwV3D
Using the normal bookmarklet on this fetches the right artist, while the [batch bookmarklet](https://danbooru.donmai.us/uploads/new?ref=https%3A%2F%2Fmokutan.artstation.com%2Fprojects%2FBwV3D&url=https%3A%2F%2Fcdna.artstation.com%2Fp%2Fassets%2Fimages%2Fimages%2F001%2F658%2F068%2Flarge%2Fyang-waterkuma-b402.jpg%3F1450269769) returns a list of artists, all of them having direct URLs to their artworks in their link lists.
![mdzlp66tecwj_tmp nxarfwld2m](https://user-images.githubusercontent.com/12946050/34362726-561f0c7a-ea76-11e7-93c4-0d3eb5d478bc.png) 
(example: https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=149341)
The matcher should ignore these URLs when it's matching the project page to an artist, like it was already done in #3429.

**Comment by r888888888** [comment]
Was there ever any standardization on ArtStation profile urls? It looks like all of the following are valid:

```
https://www.artstation.com/mokutan
https://mokutan.artstation.com
https://www.artstation.com/artist/mokutan
```

The first one seems to be the canonical one, and the third one redirects to it. The second one seems to be an alternative version with larger thumbnails.

**Comment by BrokenEagle** [comment]
Not as far as I'm aware.  For artists with Artstation entries, I've been adding both the first and second entries to the list of URLs in their profile

**Comment by BrokenEagle** [comment]
I confirmed it with @evazion, but it seems like this issue is caused by the regex for the cdn Artstation URLs lacking the network path, therefore it's finding matches before it hits the blacklist entry.

``/cdn[ab]?\.artstation\.com\/p\/assets\/images\/images/i``

The above is what the blacklist entry should be instead.

**Comment by evazion** [comment]
`https://www.artstation.com/artist/mokutan` used to be the primary URL used by ArtStation, but they switched to `https://www.artstation.com/mokutan` recently.

I suggest standardizing on `https://mokutan.artstation.com`. `https://www.artstation.com/mokutan` would be fine too, but either way, we only really need one in artist entries.
