### ISSUE TITLE
Minor mistakes in the mod queue

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3461]
At the [top of the queue](https://github.com/r888888888/danbooru/blob/f44f5d1fdb5d75912080dafbcc56cbe62b967319/app/views/moderator/post/queues/show.html.erb#L17) is the message "As a general rule, you should only approve of posts that you personally like. Posts that are not approved in three days will be automatically deleted. Posts with score -3 or lower are marked red. Posts with score 3 or higher are marked green. Posts with the duplicate tag are marked in yellow."

This is not completely true - image samples are also marked as red, and it's not immediate to realize that it's the case. The above should be updated (also in [here](https://github.com/r888888888/danbooru/blob/f44f5d1fdb5d75912080dafbcc56cbe62b967319/app/views/moderator/post/queues/random.html.erb#L17)). 

Furthermore, the random page says "Here are five random posts that are up for moderation. See if any of them are worth approving. Once you finish processing all of them you will be taken to the previous URL ()."
In my case however the random posts are 12.

**Comment by r888888888** [comment]
Are you maybe seeing the flagged posts as red? I don't see any specific logic for marking samples with a red border.
