### ISSUE TITLE
Rejecting a post from its own page should not hide the pending/flagged notices

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3469]
When a negative action (ie "no interest") is taken on a pending post from its page, the flagged and pending notices disappear until refresh (example: http://testbooru.donmai.us/posts/53). They should instead remain in display.
(I'll admit this caught me off guard the first few times as I thought I had accidentally approved a post.)

**Comment by r888888888** [comment]
There is a message indicating what has happened. I don't know how often you'd approve something you just disapproved.

**Comment by nonamethanks** [comment]
The message just says "The post was hidden", I assume because those buttons are shared with the queue, where it's literally hidden on rejection.
It's a bit confusing, that's all, because on flagged posts the red flag notice also disappears with them on action.

**Comment by evazion** [comment]
8472379 just refreshes the page after approving / disapproving the post. This is simpler than trying to update everything on the page in place.

**Comment by nonamethanks** [comment]
`approver:nonamethanks age:<1d: 118 posts`

Err, I'm not sure forcing hundreds of reloads every day is better.

**Comment by nonamethanks** [comment]
Actually, after two weeks and some 3k posts, it didn't turn out to be as bad as I thought. I guess this can be considered fully closed now.
