### ISSUE TITLE
NoMethodError error when adding artist tag to post

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3480]
For [post #2932132](http://danbooru.donmai.us/posts/2932132), attempting to add the artist tag mizu_kane (which currently has no posts) hits an error:

    undefined method `<' for nil:NilClass
    app/models/post.rb:1748:in `block in added_tags_are_valid'
    app/models/post.rb:1748:in `select'
    app/models/post.rb:1748:in `added_tags_are_valid'
    app/controllers/posts_controller.rb:48:in `update'

**Comment by evazion** [comment]
The `created_at` field for [mizu_kane](http://danbooru.donmai.us/tags/545413.json) is null for some reason, so it fails here:

https://github.com/r888888888/danbooru/blob/c3aff42458f69266f8c4bf578a226fb102e8b74b/app/models/post.rb#L1751

**Comment by r888888888** [comment]
Interesting:

```ruby
irb(main):005:0> Tag.where(created_at: nil).count
=> 103416
irb(main):007:0> Tag.where(created_at: nil).average(:post_count).to_i
=> 5
```

These must be created in a without timestamps block somewhere.
