### ISSUE TITLE
Changing tag category shows "could not be removed" warning

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3483]
This can be quickly verified in http://testbooru.donmai.us/posts/57. Changing the tag category for the test tag will display the warning.

Edit: seems it wasn't just for single-post tags, I added the tag to a few more posts on Testbooru and it still gave me the same warning.

**Comment by evazion** [comment]
Is this a duplicate of #3477?

**Comment by nonamethanks** [comment]
Ah woops yeah, I didn't notice that issue. Closing this one then.
