### ISSUE TITLE
 NoMethodError exception raised when making a comment on a Post

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3487]
```
NoMethodError exception raised

    undefined method `gsub!' for nil:NilClass
    app/logical/d_text.rb:73:in `parse_mentions'
    app/logical/mentionable.rb:32:in `queue_mention_messages'
    app/controllers/comments_controller.rb:31:in `create'
```
I receive this error when I try to post a comment on the Booru I host, I've checked the coding and it looks to be the same as the default so I'm unsure what the cause can be.

**Comment by evazion** [comment]
Are you running the latest version? `parse_mentions` doesn't contain a `gsub!` and it's nowhere near line 73:

https://github.com/r888888888/danbooru/blob/927b2f00a2a4b7862d40b3cfa804f30a38f8d89d/app/logical/d_text.rb#L12-L20

**Comment by Iratu** [comment]
Okay it seems that Merging went wrong, somehow the file was 400 Lines long, I replaced my files with the one here and it fixed it...
