### ISSUE TITLE
Redirect API endpoints with `md5` query param to correct format

### ISSUE THREAD

**Issue by bcc32** [r888888888/danbooru#3500]
Currently, a request for
```
/posts.json?md5=031bd291eab8751214b160a65ad5bd00
```

redirects to (at least on danbooru.donmai.us)
```
/posts/2792983
```

when I'd expect
```
/posts/2792983.json
```

This makes it somewhat more difficult to automatically fetch post data given a a post's MD5.

**Comment by evazion** [comment]
This is a legacy redirect for compatibility with old Danbooru 1 links. It would be better to use `/posts.json?tags=md5:031bd291eab8751214b160a65ad5bd00`.
