### ISSUE TITLE
Only show "deleted" entry in Mod Actions when comment is deleted

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3508]
If a mod deletes another user's comment, two actions are added to Mod Actions: "updated" and "deleted".  In this case, the "updated" entry should be suppressed.

**Comment by BrokenEagle** [comment]
Way ahead of you there.  It was fixed in #3496 but hasn't been deployed yet.

**Comment by evazion** [comment]
Closing as fixed.
