### ISSUE TITLE
Many broken pages on Testbooru

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3510]
Not sure if it has something to do with the latest series of commits, but many of the pages on Testbooru are  broken, and unfortunately it's only giving the generic "Something broke" page.

Every post page but the following is broken:

http://testbooru.donmai.us/posts/58
http://testbooru.donmai.us/posts/49
http://testbooru.donmai.us/posts/42

The following artist pages are broken:

http://testbooru.donmai.us/artists/5
http://testbooru.donmai.us/artists/6
http://testbooru.donmai.us/artists/7

Every single wiki page is broken.

Comments by post is broken:

http://testbooru.donmai.us/comments?group_by=post

Comments by comment works:

http://testbooru.donmai.us/comments?group_by=comment

The moderation queue is broken:

http://testbooru.donmai.us/moderator/post/queue

Every single user page is broken.

**Comment by r888888888** [comment]
I think I just had to recompile the cityhash gem but I upgraded it to 0.9 in any case.
