### ISSUE TITLE
Sample images are broken

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3516]
Discussion: https://danbooru.donmai.us/forum_topics/14922

http://sonohara.donmai.us/posts/2996012 (works)
http://hijiribe.donmai.us/posts/2996012 (sample image is broken)
http://hijiribe.donmai.us/cached/xdata/sample/sample-fdfa76223bf585f50d5fb656a7c4f002.jpg

Sample images are broken for many posts. Apparently hijiribe generates `/xdata/` URLs for samples in some cases, but this URL doesn't work.

**Comment by r888888888** [comment]
Fixed.
