### ISSUE TITLE
Uploaded images appear broken upon initial upload

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3517]
Right after uploading, images appear broken because they haven't yet been uploaded to the image server.  To avoid the confusion this causes, posts should not be shown on the post/index page nor should the user that did the upload be redirected to the post page until this occurs.

**Comment by r888888888** [comment]
This is fixed now.

So just to explain what is going on, I decided that S3 is not a viable long-term solution for image hosting. It's too expensive. It will remain the primary backup but I will be using dedicated image servers like raikou1.donmai.us to host older files, currently set to id<500k but this will go up to 1m shortly and I will probably get another server for 1m-2m.

**Comment by evazion** [comment]
Closing as fixed.
