### ISSUE TITLE
Don't prune mod actions

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3518]
Currently mod actions are pruned after one month. But the volume of mod actions isn't that high, so I don't think pruning them is necessary. Now that mod actions are searchable by category, it would be useful to retain full records.

Going by the IDs, we'd have ~220k mod actions right now if they were never pruned, which really isn't that much.

**Comment by BrokenEagle** [comment]
If the above gets implemented, something would need to be done about all of the mod actions with null categories.  Below are two possible actions.

1. Set the correct category ID with regexes
or
2. Delete the mod action

**Comment by BrokenEagle** [comment]
As it has been 30 days since categories were added, there are no longer any mod actions without categories.  Therefore, the above suggested action would no longer be required.
