### ISSUE TITLE
Enable HSTS

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3522]
Discussed in [topic #14902](https://danbooru.donmai.us/forum_topics/14902) and previously in [topic #12916](https://danbooru.donmai.us/forum_topics/12916). In summary, I propose this:

- [ ] Enable HSTS for danbooru.donmai.us and safebooru.donmai.us (but not for sonohara.donmai.us or hijiribe.donmai.us, unless their SSL certs are fixed).
- [x] Add an http://insecure.donmai.us domain for those who want to continue using HTTP.

A significant consequence of this is that, since nowadays browsers default to HTTP/2 when using SSL if the site supports it (which Danbooru does), this will cause most traffic to switch to HTTP/2. This should be a good thing, but it may be worth monitoring.

**Comment by evazion** [comment]
Another consideration: cookies aren't shared between http://danbooru.donmai.us and https://danbooru.donmai.us, meaning that people will have to login again. It might be a good idea to warn people to set an email in their account settings so that they're able to recover their password, to avoid issues with people not being able to login again due to forgotten passwords.

Other things stored in cookies, mainly tag scripts, won't be transferred either.

**Comment by BrokenEagle** [comment]
Really, because they are shared on Chrome at least.  I just checked by opening an incognito window and logging into the HTTP version, and then opening another tab to the HTTPS version where it showed me as logged in.

**Comment by evazion** [comment]
That's what I get for not actually testing this. Cookies with the secure flag aren't shared with the HTTP site, but it looks like the only such cookies are `username` and `password_hash`, which are set when logging in with the `Remember` box checked.

So you can be logged out if you login to the HTTPS site with `Remember` checked, close the window (deleting the `_danbooru_session` cookie, but not `username` / `password_hash`), then open a new window. You'll be logged out of the HTTP site (if you go there first), but not the HTTPS site. But this only happens when going from HTTPS to HTTP, so it's not a problem.

**Comment by BrokenEagle** [comment]
Well, if it comes to it, there are ways to modify cookies, or even copy and transfer cookies to a different domain or subdomain.  There are several cookie editors out there that let you do this.  If needed, I could write up a guide on the forum if there are any such users out there that are caught unfortunate with this.
