### ISSUE TITLE
Add method to prevent image-hosting CloudFlare sites from altering the image

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3528]
It was recently noted that Artstation will send different images depending on whether an image is a cache hit or miss.  Artstation uses CloudFlare, and @evazion noted that that service uses a function called polish which strips an images metadata and also compresses the image.

https://blog.cloudflare.com/introducing-polish-automatic-image-optimizati/

One solution to this is to add a randomized dummy parameter to the URL to prevent a cache hit.  Another alternative would be to set the outgoing headers using cache control.

``Cache-Control: no-cache, no-store, no-transform``

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

Artstation is pretty bad about the above, and there are a plethora of MD5 mismatches between Danbooru and Artstation because of it.  It's possible that it also affects other sites as well.  Most users would have no means around the above, which is why it should be the server that handles it.

**Comment by evazion** [comment]
I tested the `Cache-Control` approach but I wasn't able to get it to work:

```
curl -v -H "Cache-Control: no-cache, no-store, no-transform" "https://cdnb.artstation.com/p/assets/images/images/007/837/661/large/hui-zou-20171020-1-2.jpg?1508847423" > /dev/null

< content-length: 529833
< cf-bgj: imgq:100
< cf-polished: origSize=566144
< etag: "59ef2ff6-8a380"
< expires: Sun, 30 Jan 2028 22:34:35 GMT
< last-modified: Tue, 24 Oct 2017 12:20:06 GMT
< cf-cache-status: HIT
```

Cloudflare still returned a cache hit for the polished version for every combination of `no-cache` / `no-store` / `no-transform` that I tried. Adding a random URL param does work though. It shouldn't hurt to do this for every site, but it could use testing.

**Comment by r888888888** [comment]
Reverted and deployed.

**Comment by evazion** [comment]
Since doing this globally doesn't work, the alternative is doing it only for CloudFlare. CloudFlare can be detected by sending a HEAD request and looking for the `CF-Ray` header.

Also, this blog has some relevant information about Polish: https://pwmon.org/p/5470/cloudflare-discolors-web/. tl;dr: stripping metadata removes color profiles, which can distort the colors.

**Comment by r888888888** [comment]
Is it viable to cache this on a per-domain basis?

**Comment by evazion** [comment]
Yeah, that should work.

**Comment by BrokenEagle** [comment]
@r888888888 @evazion 

I just discovered that Twitter is using CloudFlare which is also altering the images in the same way as above.  However, with Twitter images, it is not possible to alter the image URL in a randomized way like before that won't result in a 404 response.

Should this issue be reopened in hopes that another solution can be found, or is there no way around this problem besides the URL solution?

The only other possible solution I can think of which is very hackish would be to detect cache hits in the response header, and requeue the upload for a later time for when the cache gets purged, however I don't think that would go over well with users.
