### ISSUE TITLE
Images served from the image server don't allow for tagged filenames

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3542]
From the [Danbooru forum](https://danbooru.donmai.us/forum_topics/9127?page=219#forum_post_142844):

> Laethial said:
> 
> When I download post #821989 (using Windows Firefox, Windows Chrome, or Android Chrome), it always saves as just its md5 hash (efecbf8aeb04c2eba0b89901d106b12c.jpg) instead of including character/copyright/artist info. All other posts I've tried downloading are including that information as they should.
> Laethial said:

The above post is being served from the image server (Raikou).  It seems like those currently don't allow for tagged filenames.

**Comment by evazion** [comment]
Apparently fixed now.
