### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3548]
The latest release is 3.3.1. We're still on 1.11.1, which dates to 2014 (!).

The recommended process is to install the jquery-migrate plugin and upgrade gradually, first to 1.12.4, then to 2.2.4, then finally to 3.3.1.

* https://jquery.com/upgrade-guide/3.0/
* https://github.com/jquery/jquery-migrate/

**Comment by r888888888** [comment]
Upgraded to 3.3.1 in e9dc4a397e0e71aac1f78fd0afdcc2f9b0c098c2
