### ISSUE TITLE
BUR approval bugs

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#3554]
1) Rejecting a BUR doesn't work at all: 

```
undefined method `id' for nil:NilClass
app/models/bulk_update_request.rb:123:in `reject!'
app/controllers/bulk_update_requests_controller.rb:41:in `destroy'
```

2) Approving a BUR doesn't create a forum post, see https://danbooru.donmai.us/bulk_update_requests?search[id]=888

**Comment by Type-kun** [comment]
Approving https://danbooru.donmai.us/bulk_update_requests?search%5Bid%5D=1420 did create a forum post though. Looks like it fails when `forum_post_id` is `nil`, for older requests. Either those should be populated, or approve/reject methods amended to handle missing ids.

**Comment by evazion** [comment]
`approve!` and `reject!` should be wrapped in transactions and `approve!` shouldn't swallow exceptions. Approving only works because it's not in a transaction and because it swallows the exception when it tries to update the forum topic .
