### ISSUE TITLE
Post replacement breaks posts whose images are hosted on raikou2.donmai.us

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3569]
When post replacement is done on an old post whose sample/fullsize are hosted on https://raikou2.donmai.us/, the new image is stored as new posts store images, but the post still tries to use the old https://raikou2.donmai.us/ URLs with the new MD5.

See [post #872149](https://danbooru.donmai.us/posts/872149) for one such casualty.

**Comment by evazion** [comment]
See also #3560. I haven't tested this, but I think replacing ugoiras is also broken. Ugoira thumbnails/samples are generated asynchronously during the upload process, so they may not exist yet when post replacement tries to distribute the files. I don't think replaced files can be deleted from the archive servers either.

I think it would be a good idea to introduce some kind of `AssetManager` abstraction for dealing with file storage. `RemoteFileManager` and `S3BackupService` would become instances of this.

**Comment by evazion** [comment]
Some WIP towards this: https://github.com/r888888888/danbooru/commit/e38673de5df2f5c170a739428ab74defb32b7d11. The uploading process will have to be reworked a little bit, because right now it assumes uploads will be stored on the local filesystem, which is not necessarily the case.

**Comment by evazion** [comment]
More work: https://github.com/evazion/danbooru/compare/master-evazion...evazion:feat-storage-manager. Nearly there, just need to finish some tests.

**Comment by RaisingK** [comment]
post #324768 and post #1045226 (raikou2 images) both broke after replacement.
