### ISSUE TITLE
ImageMagickError: width or height exceeds limit

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3570]
From https://danbooru.donmai.us/forum_topics/15066:

> Fisheye placebo (pool #10558) posted for the first time in 3 years. Only issue is, the hight limits have been changed since it last posted so I can't upload a 800x21916 anymore (it's not quite that tall this time). Is there a way around that, or is two images at 10753px and 9912px the only way?

When uploading, ImageMagick raises an error if the image dimensions exceed some default limit. Not sure what a better limit would be, but it would at least better to set known limits rather than relying on implicit defaults. Uploading should also check the dimensions before resizing and fail gracefully if the image is too big to resize.

The limit can be adjusted by editing ImageMagick's `policy.xml` config file (see also https://www.imagemagick.org/discourse-server/viewtopic.php?t=31438).

**Comment by evazion** [comment]
Certain posts can't be edited because of this. [post #1282126](https://danbooru.donmai.us/posts/1282126) is an example. `is_animated_gif?` raises `Magick::ImageMagickError: width or height exceeds limit` for this file.

**Comment by r888888888** [comment]
I imagine the code for resizing the image would break also, not just `is_animated_gif?`. Here are the current limits:

```xml
  <policy domain="resource" name="memory" value="256MiB"/>
  <policy domain="resource" name="map" value="512MiB"/>
  <policy domain="resource" name="width" value="16KP"/>
  <policy domain="resource" name="height" value="16KP"/>
  <policy domain="resource" name="area" value="128MB"/>
  <policy domain="resource" name="disk" value="1GiB"/>
```
