### ISSUE TITLE
Post appeals limited in length

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3585]
Most likely related to issue #2913. 

Issue was first posted on Danbooru's forum and the latest post is at the following:

https://danbooru.donmai.us/forum_posts/144529

Basically, the user is getting an error message that the character length is too long (more than 255 characters).  After discussing it with @evazion on Discord, he believes it may be the same issue as last time, i.e. the values that define the structure in the actual DB differ from those in the ``structure.sql`` file.

Now limiting flags/appeals in length is fine, but that should be explicit in the code and not the result of a faux limitation in the data structure.  It would also need to be detailed in the flag and appeal notices.

I myself don't think flags and appeals need to be terribly long, especially since the DText is rendered inline, but 255 characters seems a bit short, although maybe that's a bit too long for some.  I don't know.... what do others think?

**Comment by r888888888** [comment]
I'll change them to text fields in e006380567c0652ea35d4b2b5598e4d025b5d82a
