### ISSUE TITLE
Superfluous space added on certain autocompletions

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3590]
From the [Danbooru forum](http://danbooru.donmai.us/forum_posts/144593).

> Fossilnix said:
> 
> There's a bug in wiki searches involving autocomplete. Using "help:blacklists" as an example: if I type "help:bl" in the search bar, and then tab to complete the name, and then press enter to search, the results are blank ...If I delete the space that autocomplete puts at the end of the name, then it will take me to the wiki page as expected.

This seems to only affect wiki pages, as it sends a * with the request instead of letting the user choose to use a * or not.

**Comment by evazion** [comment]
The extra space is unnecessary, but it should be harmless.

What happened here was that when you searched for `help:blacklists `, WikiPage#search` tried to normalize the title by downcasing and converting spaces to underscores, but it didn't strip leading/trailing spaces first. So the title was turned into `help:blacklists_`, which doesn't exist.
