### ISSUE TITLE
Serve thumbnails over HTTPS

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3599]
Currently thumbnails are being served over HTTP, which is causing mixed content warnings on https://danbooru.donmai.us.

**Comment by r888888888** [comment]
I think setting the `base_url` option for storage manager explicitly to `https://danbooru.donmai.us` should fix this?

**Comment by evazion** [comment]
Yeah, it should. I *think* leaving it at the default should work too, since it defaults to `Rails.application.routes.url_helpers.root_url` and that should be `https://danbooru.donmai.us` when on https, but that was hard for me to test.

**Comment by evazion** [comment]
Looks good now.
