### ISSUE TITLE
"wrong number of arguments" on viewing image posts

### ISSUE THREAD

**Issue by linoth** [r888888888/danbooru#3600]
Footer is reporting version 7d745ac9

Loading any image returns "wrong number of arguments (given 3, expected 2)"

Firefox 59.0.2, Free tier user, logged in.
Duplicated on Chrome 65.0.3325.181 64-bit, not logged in.

Sorry, just being thorough.

**Comment by evazion** [comment]
Pushed a fix in a432980f855d491730f7cefd067bb0561aa51512, awaiting deployment.

**Comment by linoth** [comment]
Sorry, just saw that went up while I was registering.

**Comment by r888888888** [comment]
Deployed.
