### ISSUE TITLE
Configure S3 backups

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3604]
Just noticed that it looks like new uploads aren't getting backed up to S3. This returns access denied: https://danbooru.s3.amazonaws.com/3c68b2725c33cbef6aa4244c35612869.jpg.

Backups are disabled in the default config. Should just have to add `StorageManager::S3.new("danbooru")` to `backup_storage_manager` in danbooru_default_config.rb to get it working (plus configure `aws_region` / `aws_credentials` if not already configured).

**Comment by r888888888** [comment]
S3 backup storage manager is already configured.

I think we need some sort of mechanism to easily retry distribution. For new uploads it's using the SFTP manager, but it's not possible to get a local file path without manually constructing the path. This makes calling `Post#distribute_files` tricky.

I think the S3 backup manager might be erroring out from another argument mismatch error but it's hard to tell.

**Comment by evazion** [comment]
For existing posts, fixing #3553 should allow retrying the distribution to S3. Replacing a post has the side effect of redistributing it to the asset servers / S3 / iqdb.

For new uploads, I think the whole file distribution process could be done in a delayed job. Then if any part of it failed it would retry automatically.

**Comment by r888888888** [comment]
seems to work now?

**Comment by r888888888** [comment]
The backup is working now.
