### ISSUE TITLE
Errno::ENETUNREACH error when replacing posts

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3611]
[forum #144922](https://danbooru.donmai.us/forum_topics/15142?page=1#forum_post_144922):

> post #872149 using http://danbooru.s3.amazonaws.com/a904988cd40471d6acb2b8bde8746f7c.png and http://orig08.deviantart.net/d3a0/f/2010/365/1/9/19fb751f3632160df65a2966f0206ffc-d31qmf5.png:
>
>> Errno::ENETUNREACH exception raised
>>
>> Network is unreachable - connect(2) for [2400:cb00:2048:1::6814:872d]:22
app/logical/storage_manager/sftp.rb:71:in `block in each_host'
app/logical/storage_manager/sftp.rb:70:in `each'
app/logical/storage_manager/sftp.rb:70:in `each_host'
app/logical/storage_manager/sftp.rb:24:in `store'
app/logical/storage_manager.rb:40:in `store_file'
app/logical/storage_manager/hybrid.rb:9:in `store_file'
app/models/post.rb:127:in `distribute_files'
app/models/upload.rb:159:in `distribute_files'
app/models/post_replacement.rb:82:in `process!'
app/models/post.rb:1380:in `block in replace!'
app/models/post.rb:1378:in `replace!'
app/controllers/post_replacements_controller.rb:11:in `create'

Replacing post #872149 failed. It looks like it's trying to SFTP to Cloudflare instead of the actual server (`2400:cb00:2048:1::6814:872d` is a Cloudflare IP). Probably need to disable Cloudflare proxying of port 22 for raikou1 / raikou2.

**Comment by BrokenEagle** [comment]
Same issue as above, but this time it was an attempt to upload directly from disk.

> BrokenEagle98 said:
> 
> While maybe not optimal, the broken images should still be able to be replaced by downloading to disk and then replacing the image from disk AFAICT.

> RaisingK said:
> 
> Nope. First attempt got me a "400 Bad Request" page. The second attempt (blanking out the replacement URL, in case that somehow mattered) got me the same ENETUNREACH error as above.

**Comment by r888888888** [comment]
I'm wondering if adding raikou1/raikou2 to the system hosts file would resolve the issue without needing to rewrite the storage manager code.

**Comment by evazion** [comment]
Adding a `ssh.raikou1.donmai.us` subdomain that has Cloudflare proxying disabled should work. See [here](https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-CloudFlare-work-with-) and [here](https://support.cloudflare.com/hc/en-us/articles/200169346-Using-FTP-with-Cloudflare-).

Alternatively, adding raikou1/raikou2's actual ip in `~/.ssh/config` should also work:

```
Host raikou1.donmai.us
    User danbooru
    HostName <raikou1's ip address>
```

**Comment by r888888888** [comment]
This should be fixed now.

**Comment by RaisingK** [comment]
Okay, now it's:

    Net::SSH::AuthenticationFailed exception raised
    Authentication failed for user albert@raikou2.donmai.us
    app/logical/storage_manager/sftp.rb:71:in `block in each_host'

**Comment by r888888888** [comment]
The username should be `danbooru`. Will probably need to implement a fix to specify it.

**Comment by evazion** [comment]
Should be able to specify it in `~/.ssh/config` or in the `ssh_options` param on the storage manager.

**Comment by r888888888** [comment]
It wasn't configured on hijiribe. It is now.
