### ISSUE TITLE
Post replacements: NoMethodError exception raised ("queue_backup")

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3621]
Attempting to replace post #1612128 got me this:

    NoMethodError exception raised
    undefined method `queue_backup' for #<Post:0x0000555ab73d7db0>
    app/models/post_replacement.rb:77:in `block in process!'
    app/models/post_replacement.rb:29:in `process!'
    app/models/post.rb:1378:in `block in replace!'
    app/models/post.rb:1376:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by r888888888** [comment]
I believe this is now handled in `Post#distribute_files` so there's no need to call it explicitly.
