### ISSUE TITLE
Approval links on mod queue have same ID attribute

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3622]
All of the "Approve" links on the mod queue page now have the same ID attribute ("quick-mod-approve"), which seems like bad style.  I don't know why the other disapproval links lost their "disapprove-link" className, but I can workaround that.

**Comment by evazion** [comment]
Broken in 60dbb168d23c71638351ad94358e52da745edf25 (refactored mod queue / post show page to use the same template for quick mod bar).

**Comment by evazion** [comment]
Changed it from `id="quick-mod-approve"` to `class="approve-link"` and added the `disapprove-link` classes back.
