### ISSUE TITLE
Flags are broken

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3624]
Trying to flag any post returns a notice that says "Error: 500 error", and nothing else. I confirmed it myself and Provence found the same problem (as reported here, albeit with a different error message than what I get: https://danbooru.donmai.us/forum_posts/145061)

The network tab shows this:
>ActiveRecord::NotNullViolation exception raised
>
>PG::NotNullViolation: ERROR: null value in column "is_resolved" violates not-null constraintDETAIL: Failing row contains (2018-04-12 20:29:41.129927, 3084916, Test, 508240, null, [edited by nonamethanks :^)], 2018-04-12 20:29:41.129927, 233371).: INSERT INTO "post_flags" ("created_at", "post_id", "reason", "creator_id", "creator_ip_addr", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
app/controllers/post_flags_controller.rb:21:in `create'

**Comment by evazion** [comment]
Looks fixed.
