### ISSUE TITLE
Retry button is displayed for failed uploads that cannot succeed even if retried

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3628]
Example: https://danbooru.donmai.us/uploads/1806870
The retry button here won't do anything, as an user cannot change the tag list from that page, and as such it's misleading to have it.

It also appears on duplicate/"md5 already taken" pages.

**Comment by evazion** [comment]
I went ahead and removed the button entirely. It was broken in several ways:

* Danbooru already retries automatically on network timeouts.
* Most errors outside of network errors probably aren't retriable.
* It was possible to retry uploads you didn't own.
* The button never actually worked. `Upload#process!` returns immediately when the status is `error`, so retrying didn't actually do anything.
