### ISSUE TITLE
Post replacements: ArgumentError exception raised

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3634]
Attempting to replace post #1612128 now gets me:

    ArgumentError exception raised
    invalid option(s): username
    app/logical/storage_manager/sftp.rb:71:in `block in each_host'
    app/logical/storage_manager/sftp.rb:70:in `each'
    app/logical/storage_manager/sftp.rb:70:in `each_host'
    app/logical/storage_manager/sftp.rb:24:in `store'
    app/logical/storage_manager.rb:40:in `store_file'
    app/logical/storage_manager/hybrid.rb:9:in `store_file'
    app/models/post.rb:123:in `distribute_files'
    app/models/upload.rb:161:in `distribute_files'
    app/models/post_replacement.rb:84:in `process!'
    app/models/post.rb:1376:in `block in replace!'
    app/models/post.rb:1374:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by r888888888** [comment]
This will be fixed in the next deployment.
