### ISSUE TITLE
Bookmarklet fails on artstation for some posts

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3637]
https://sa-dui.artstation.com/projects/DVERn
https://sa-dui.artstation.com/projects/ONdWy

In the network console of my browser I see the following error under iqdb_queries:
>{:message=>"Couldn't find Post without an ID", :iqdb_response=>["Exception: image_error: Unknown image format."]}
>app/logical/iqdb/download.rb:46:in `rescue in find_similar'
>app/logical/iqdb/download.rb:20:in `find_similar'
>app/controllers/iqdb_queries_controller.rb:27:in `find_similar'
>app/controllers/iqdb_queries_controller.rb:6:in `show'

And "Unsupported site" in source.json.

I know for sure that these posts used to work some day ago so it's probably due to the Rails update.

It seems that when submitting a post like that I get "An error occurred: error: RuntimeError - invalid content type (only JPEG, PNG, GIF, SWF, MP4, and WebM files are allowed)", and trying to fetch the commentary for such urls return the source.json problem mentioned above.

**Comment by nonamethanks** [comment]
BTW I didn't want to open an issue just for this, but the header for this github repo still says "Danbooru is a taggable image board written in **Rails 4**."

**Comment by evazion** [comment]
I'll leave this open for the repo description issue.
