### ISSUE TITLE
Size link on post show downloads the image instead of opening the image in full screen

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3638]
Brought up by fossilnix on Discord.

Basically, with the **Size** link in the **Information** section on the post show, for posts above 3M it works fine and opens the image full screen.  For posts below 3M it instead downloads the image.  On Hijiribe image links, it returns ``Content-Disposition: attachment`` in the Response header when ``download=1``, whereas none of the other Danbooru domains do that (sonohara, danbooru, insecure). 

This happened as a result of #3594 which added the ``download=1`` URL addon to both the **Size** and **Download** links.  However, it was fine to alter the Download link, but people were using the Size link as a quick way to open the images to full screen in order to compare different images.

**Comment by r888888888** [comment]
Wouldn't removing this cause the cross-origin block again?

**Comment by evazion** [comment]
The `Download` link should be the only one that needs the `?download=1` param. People are used to the `Size` link opening the image in a new tab, rather than trying to download the image.

**Comment by evazion** [comment]
Was fixed in 97dd0680dfe15fb7f439ba45ad9930a72d6869d1.
