### ISSUE TITLE
Can't undo votes

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3640]
After upvoting/downvoting any post, trying to downvote/upvote again after a page refresh to cancel the previous vote will return a 500, along with `Danbooru.notice("You have already voted for this post");` in the network tab.

By the way, the notice's message is not passed either. All I see in the html page is "Error: 500 error".

Also the up/down links won't change to the usual "Undo vote" but will stay like that, effectively blocking any attempt.

**Comment by evazion** [comment]
`> By the way, the notice's message is not passed either. All I see in the html page is "Error: 500 error".`

This came from ad66b8a. It was supposed to be a fallback error handler but instead it overrode the normal error message here.
