### ISSUE TITLE
Post replacements slow/timeout

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3647]
Replacements of older images seem to take a few minutes to take effect and sometimes apparently timeout.  Replacing post #782457 (4 MB) took two attempts (~2 hours between them), and two attempts at post #828048 (9 MB) don't seem to have worked.

**Comment by r888888888** [comment]
Weird. Manually syncing to the archive servers with sftp only takes a few seconds.

**Comment by r888888888** [comment]
I've manually triggered the replacement process for the two posts.
