### ISSUE TITLE
TAGS BUG

### ISSUE THREAD

**Issue by keksnek** [r888888888/danbooru#3650]
i cant access any tags because when i click on them i just get the error

PG::UndefinedObject: ERROR: text search configuration "danbooru" does not exist LINE 1: ..." WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru'... ^ : SELECT "posts".* FROM "posts" WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru', E'(''ishikei'')')) AND (true /* PostSets::Post#posts:2 */) ORDER BY posts.id DESC LIMIT $1 OFFSET $2

any idea when this will be fixed or how to fix it?

**Comment by r888888888** [comment]
Is this on your own copy? Where are you running this?

**Comment by evazion** [comment]
Pretty sure this was this bug in atfbooru: https://github.com/r888888888/danbooru/issues/3645#issuecomment-382072755.
