### ISSUE TITLE
Connection failures with https://hijiribe.donmai.us

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3656]
Several people have reported issues with connecting to https://hijiribe.donmai.us:

* https://danbooru.donmai.us/forum_posts/144021
* https://danbooru.donmai.us/forum_posts/145148
* https://danbooru.donmai.us/forum_posts/145164

My first guess was they were using ancient browsers that didn't support [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). If your browser doesn't support SNI then hijiribe will return safebooru's certificate, which is not valid for hijiribe.

However, judging by these test results they do support SNI, so I'm not sure what's going on:

* https://danbooru.donmai.us/forum_posts/145224
* https://danbooru.donmai.us/forum_posts/145205

**Comment by SD-DAken** [comment]
Since the above comments mentioned Windows 8.1 and IE I did some tests.

Windows 8.1 up-to-date and Firefox 59.0.2
https://danbooru.donmai.us => Works
https://sonohara.donmai.us => Works
https://hijiribe.donmai.us => Works

Windows 8.1 up-to-date and Internet Explorer 11
https://danbooru.donmai.us => Works
https://sonohara.donmai.us => Broken
https://hijiribe.donmai.us => Broken

The IE error page or developer tools are not helpful to diagnose the problem.

Things I noticed:
I didn't check the exact IP-ranges but it seems danbooru.donmai.us goes through cloudflare, but sonohara.donmai.us and hijiribe.donmai.us do not?

sonohara.donmai.us and hijiribe.donmai.us both use http/2 when accessed over https, but IE11 on Windows 8.1 and below does not support http/2.

I therefore have the suspicion that the fallback from https+http/2 to https+http/1.1 might not work correctly for sonohara.donmai.us and hijiribe.donmai.us

**Comment by SD-DAken** [comment]
Looking at this with wireshark I see:

Firefox:
Client Hello
Server Hello
Certificate
Certificate Status, Server Key Exchange, Server Hello Done
Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
Change Cipher Spec, Encrypted Handshake Message
[Encrypted data is transferred]
...

IE:
Client Hello
Server Hello
Certificate
Certificate Status, Server Key Exchange, Server Hello Done
[FIN, ACK] sent by client
[FIN, ACK] sent by server
[connection closed]

I don't spot why IE decides to close the connection, I'm no expert, but the values sent by the server and client seem to be sane on a cursory look.

**Comment by evazion** [comment]
I tried to test the http/2 theory with this:

```
openssl s_client -debug -servername hijiribe.donmai.us -connect hijiribe.donmai.us:443
```

This gives an http/1.1 connection. It's only with `-alpn h2` that you get http/2. IE11 doesn't support [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation), so it shouldn't be possible for it to inadvertently get http/2 (unless something is *really* wrong).

I don't see any obvious reason for IE to close the connection like that either. My other guess would be some issue with the cipher suite, but as far as I can tell IE11 is compatible with the ciphers offered by hijiribe.

Maybe the easiest thing would be to just use Cloudflare for sonohara / hijiribe too.

**Comment by SD-DAken** [comment]
IE11 on Win 8.1 doesn't support http/2 but does support ALPN. It sends this: 
```
Extension: application_layer_protocol_negotiation (len=18)
    Type: application_layer_protocol_negotiation (16)
    Length: 18
    ALPN Extension Length: 16
    ALPN Protocol
        ALPN string length: 6
        ALPN Next Protocol: spdy/3
        ALPN string length: 8
        ALPN Next Protocol: http/1.1
```

hijiribe answers with:
```
Extension: application_layer_protocol_negotiation (len=11)
    Type: application_layer_protocol_negotiation (16)
    Length: 11
    ALPN Extension Length: 9
    ALPN Protocol
        ALPN string length: 8
        ALPN Next Protocol: http/1.1
```
This seems sane because http/1.1 is the only protocol supported by the client and server in this case.

The full client hello looks like this btw.:
```
    Handshake Protocol: Client Hello
        Handshake Type: Client Hello (1)
        Length: 208
        Version: TLS 1.2 (0x0303)
        Random: 5adcb5007dd1bd652dcc1bb79985f92f240842e69a5daa69...
        Session ID Length: 0
        Cipher Suites Length: 52
        Cipher Suites (26 suites)
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
            Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
            Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
            Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
            Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
            Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
            Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
            Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
            Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x006a)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x0038)
            Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
            Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
            Cipher Suite: TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x0013)
        Compression Methods Length: 1
        Compression Methods (1 method)
            Compression Method: null (0)
        Extensions Length: 115
        Extension: server_name (len=23)
            Type: server_name (0)
            Length: 23
            Server Name Indication extension
                Server Name list length: 21
                Server Name Type: host_name (0)
                Server Name length: 18
                Server Name: hijiribe.donmai.us
        Extension: status_request (len=5)
            Type: status_request (5)
            Length: 5
            Certificate Status Type: OCSP (1)
            Responder ID list Length: 0
            Request Extensions Length: 0
        Extension: supported_groups (len=6)
            Type: supported_groups (10)
            Length: 6
            Supported Groups List Length: 4
            Supported Groups (2 groups)
                Supported Group: secp256r1 (0x0017)
                Supported Group: secp384r1 (0x0018)
        Extension: ec_point_formats (len=2)
            Type: ec_point_formats (11)
            Length: 2
            EC point formats Length: 1
            Elliptic curves point formats (1)
                EC point format: uncompressed (0)
        Extension: signature_algorithms (len=20)
            Type: signature_algorithms (13)
            Length: 20
            Signature Hash Algorithms Length: 18
            Signature Hash Algorithms (9 algorithms)
                Signature Algorithm: rsa_pkcs1_sha512 (0x0601)
                Signature Algorithm: ecdsa_secp521r1_sha512 (0x0603)
                Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                Signature Algorithm: rsa_pkcs1_sha384 (0x0501)
                Signature Algorithm: rsa_pkcs1_sha1 (0x0201)
                Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
                Signature Algorithm: ecdsa_secp384r1_sha384 (0x0503)
                Signature Algorithm: ecdsa_sha1 (0x0203)
                Signature Algorithm: SHA1 DSA (0x0202)
        Extension: SessionTicket TLS (len=0)
            Type: SessionTicket TLS (35)
            Length: 0
            Data (0 bytes)
        Extension: application_layer_protocol_negotiation (len=18)
            Type: application_layer_protocol_negotiation (16)
            Length: 18
            ALPN Extension Length: 16
            ALPN Protocol
                ALPN string length: 6
                ALPN Next Protocol: spdy/3
                ALPN string length: 8
                ALPN Next Protocol: http/1.1
        Extension: next_protocol_negotiation (len=0)
            Type: next_protocol_negotiation (13172)
            Length: 0
        Extension: extended_master_secret (len=0)
            Type: extended_master_secret (23)
            Length: 0
        Extension: renegotiation_info (len=1)
            Type: renegotiation_info (65281)
            Length: 1
            Renegotiation Info extension
                Renegotiation info extension length: 0
```
hijiribe picks `Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)`.
The server key exchange uses `Signature Algorithm: rsa_pkcs1_sha512 (0x0601)`.

Both are supported by IE according to the client hello :|
