### ISSUE TITLE
Add improvements to the uploads interface

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3657]
Discussed on discord with @evazion and others, and it was agreed that the uploads interface could use some improvements.

1. Add additional search parameters

Two off the top of my head would include searching by status and searching by source.

Searching by status as it would allow one to quickly identify all problematic records or upload trends without having to search through pages of records.  So the different search status categories would be **pending**, **processing**, **processing**, **duplicate** and **error**.

Searching by source is also important as with it you can quickly identify potential intermittent errors with uploading, such as earlier uploads failing with a source that succeeds upon a later retry.

2. Add improvements to the uploads HTML user interface

The following are just a few ideas that come to mind:

- Add a submenu item **Errors** that would instantly perform a search for all uploads where that status is **error**
- When the status is not completed, add a link that will search uploads by that source
-- This is because some uploads all get stuck as pending, and so it would also help show/debug those cases as well

3. Add a GitHub link on each line of the HTML backtrace (optional)

This would be mostly for the uploads show view, although I could also see it potentially being integrated into all backtraces.  Basically, on each line of the back trace that is applicable to the Danbooru project, i.e. those that are in the Danbooru releases folder and not one of the Ruby gems.

So for example using a [recent upload](https://danbooru.donmai.us/uploads/1815949), it would take the following line...

```
/var/www/danbooru2/releases/20180416234708/app/models/post.rb:790:in `block in apply_post_metatags'
```
...and add the following link on top of it...
```
https://github.com/r888888888/danbooru/blob/9957c4c0e29b3fd519244b03acb3a81e1aaa69cd/app/models/post.rb#L790
```

This would make it easier for technical users to quickly identify issues instead of having to hunt down the right commit, right file, and right line of code.

This last one might be more generalized and might need to go in its own issue, but for now I'm bringing it up here.

**Comment by evazion** [comment]
#3657 should accomplish most of this, except for improving the backtraces. There are several things we could do there - add Github links, hide non-Danbooru lines, strip off irrelevant parent directories. I'll leave that for future work.
