### ISSUE TITLE
JQuery CDN issues

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3663]
There were a couple issues raised regarding loading jQuery from an external site:

* A couple people have reported SSL errors in connecting to https://code.jquery.com. See [forum #145394](https://danbooru.donmai.us/forum_topics/14902?page=2#forum_post_145394), [forum #145494](https://danbooru.donmai.us/forum_topics/9127?page=234#forum_post_145494).

* There were some privacy/security concerns raised in [topic #15181](https://danbooru.donmai.us/forum_topics/15181).

The SSL issues could be fixed by switching to a different CDN (e.g. https://cdnjs.com). The referrer leaks could be addressed by setting a referrer policy (see [here](https://scotthelme.co.uk/a-new-security-header-referrer-policy/)).

That said, I do think onsite hosting may be slightly better. If it's not already in the browser's cache, then it will take an extra HTTPS connection (meaning extra latency) to load it from https://code.jquery.com instead of from Danbooru.

**Comment by r888888888** [comment]
I assume this isn't an issue anymore.

For the referrer leak, this is not something I'm concerned about.
