### ISSUE TITLE
Issue with image resizing on uploads page

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3672]
Brought up by Unbreakable on Discord.  Basically the image resizing doesn't take place sometimes and the resize link fails to work.

I verified the above myself, and after investigating, I discovered it was because part of the **initialize_image** function isn't running.

https://github.com/r888888888/danbooru/blob/master/app/assets/javascripts/uploads.js#L169-L181

On the pages where the link is broken and the image doesn't resize, their are no events bound to the image resize link.  Additionally, the width and height data items on the ``#image`` object aren't being set.  However, I checked, and the **load** event is being set on the ``#image`` object.

```json
{
  "events": {
    "load": [
      {
        "type": "load",
        "origType": "load",
        "guid": 70,
        "namespace": ""
      }
    ]
  }
}
```

So either the **load** event isn't firing, or the ``$("#image")`` doesn't have a length, which doesn't make sense if it's an event called from an existing object.

**Comment by evazion** [comment]
This may be relevant (from http://api.jquery.com/load-event/):

```
Caveats of the load event when used with images

A common challenge developers attempt to solve using the .load() shortcut is to execute a function
when an image (or collection of images) have completely loaded. There are several known caveats with
this that should be noted. These are:

* It doesn't work consistently nor reliably cross-browser
* It doesn't fire correctly in WebKit if the image src is set to the same src as before
* It doesn't correctly bubble up the DOM tree
* Can cease to fire for images that already live in the browser's cache
```

**Comment by evazion** [comment]
984ab98 seems to have fixed this.
