### ISSUE TITLE
Refused to apply style from 'https://danbooru.donmai.us/assets/jquery.qtip.css'

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3675]
Tooltips aren't showing up. I'm getting this error in the devconsole:

> Refused to apply style from 'https://danbooru.donmai.us/assets/jquery.qtip.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

https://danbooru.donmai.us/assets/jquery.qtip.css is returning 404. Not sure what the deal is, since it loads on testbooru.

**Comment by evazion** [comment]
Should this just be offloaded to a CDN too? Wasn't sure what the plan was there.

**Comment by r888888888** [comment]
The CDN is a site I don't control so it will only host popular libraries like jQuery. The qtip stuff would have to be bundled in manually.

**Comment by evazion** [comment]
cdnjs actually does have this one: https://cdnjs.com/libraries/qtip2.

**Comment by r888888888** [comment]
Fixed
