### ISSUE TITLE
Continuous integration testing

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3687]
It'd be nice if we had CI testing, such that every push to the repo automatically ran the test suite.

I have a branch experimenting with this - see https://github.com/evazion/danbooru/commit/807c1abdbd033a1405b56efd43516cfcc1e43152. It's using [Travis CI](https://travis-ci.org/). It works, but it's slow (installing all the prereqs takes a while) and many tests fail unless you configure credentials for every source site (Pixiv / Twitter / etc).

**Comment by r888888888** [comment]
This is now in master, although some of the Pixiv tests still fail intermittently.
