### ISSUE TITLE
Support for off-host database

### ISSUE THREAD

**Issue by meoberto** [r888888888/danbooru#3698]
I'm currently running Danbooru in a LXC container in my home server. Recently, I began the task of migrating all my webapps to use postgresql in a container separate from all the webservers. The nail that sticks out is Danbooru. 
When applying the role ":db" to the database container, capistrano attempts to deploy Danbooru to the databse host as well as the web app host, which I do not want to do. The meaning of the "db" role is confusing, judging by what some googling has returned.

Is there any support at all for databases that are not on the same host Danbooru is running on?

**Comment by r888888888** [comment]
Yes, in fact this is how it works on production with the database running on a separate server.

You will need to update your `database.yml` to point to the correct hostname and port, and you will likely need to add a password.

For deployment it doesn't really matter which server is marked as the db role, as that's only used for migrations and those can be run on any server with a connection with your database server.
