### ISSUE TITLE
Rename "Flags & Appeals" now that it includes approvals

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3705]
Very minor thing, but now that that button also includes approvals, it should be renamed accordingly. Maybe "Post events" since that's the title of the page that it opens.

**Comment by BrokenEagle** [comment]
I'm a little worried though about the lowest common denominators not figuring things out and complaining about how the **Flags & Appeals** page has been taken away.  There also might be others that complain about it anyways not liking the new name.

I created [topic #15242](https://danbooru.donmai.us/forum_topics/15242) on the Danbooru forums as a way to gather community input on this if there is any.

**Comment by evazion** [comment]
Went ahead and renamed it to "Moderation". These are all moderation actions so I think calling it the moderation history is accurate and reasonably intuitive.
