### ISSUE TITLE
Since the latest update some uploads are being submitted twice

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3711]
Compare:
https://danbooru.donmai.us/uploads/1848911
https://danbooru.donmai.us/uploads/1848912

and 
https://danbooru.donmai.us/uploads/1848910
https://danbooru.donmai.us/uploads/1848913

It's happening on and off, but basically some successful uploads get redirected to the duplicate page because they're submitted twice in a row and obviously one of them fails at the duplicate check.

**Comment by r888888888** [comment]
This is probably fixed in f6440ca70dbbacd72509ee9970428d0a72caf81c
