### ISSUE TITLE
Provide any/none modifiers for pixiv: metatag

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3715]
Relevant topic on Danbooru: [topic #15261](https://danbooru.donmai.us/forum_topics/15261)

Basically, the ``source:`` metatag doesn't work as well to get all Pixiv posts by source.  A relatively easy fix for that is to use the ``pixiv:`` metatag and supply it with ``any`` and ``none`` modifiers.

**Comment by evazion** [comment]
`pixiv:none` searches aren't indexed so they may be slow.
