### ISSUE TITLE
Bookmarklet's broken

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3721]
The bookmarklet seems to be broken for all urls. It returns the following error ([example](https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D68818684) with pixiv):
```
NoMethodError exception raised
undefined method `sub!' for nil:NilClass
app/logical/downloads/rewrite_strategies/tumblr.rb:57:in `rewrite_cdn'
app/logical/downloads/rewrite_strategies/tumblr.rb:11:in `rewrite'
app/logical/downloads/file.rb:48:in `block in before_download'
app/logical/downloads/file.rb:47:in `each'
app/logical/downloads/file.rb:47:in `before_download'
app/controllers/uploads_controller.rb:10:in `new'
```

**Comment by evazion** [comment]
Strange, works for me on my devbooru and on testbooru.

**Comment by r888888888** [comment]
They must have change the page. The `Sources::Strategies::Pixiv#get_image_url_from_page` method was returning nil.
