### ISSUE TITLE
Artists are no longer editable

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3727]
Since the latest deployment (production-2018.05.25-164139-utc), artists entries are no longer editable.

Through the HTML, you get the following popup message.
```
Url Url has already been taken.
```

Through the API, you get the following as the return response (422 Unprocessable Entity).
```
{"errors":{"urls":[ ], "url": ["Url has already been taken"]}} 
```

**Comment by r888888888** [comment]
It looks like editing an artist in isolation doesn't trigger this so maybe a URL is already being taken up by another artist? I can try adding a scope to the uniqueness constraint.

**Comment by BrokenEagle** [comment]
Would that work for converting a URL from active to inactive, or vice versa?  Or does order matter, and if its converse isn't removed before the uniqueness test, will it fail?

**Comment by BrokenEagle** [comment]
Since the latest deployment (production-2018.05.25-175502-utc), switching a link from active to inactive removes it entirely.

https://danbooru.donmai.us/artists/43901

However, the history shows that it worked, so the two aren't matching up.

https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=43901

Although I didn't test it, I imagine the opposite (inactive to active) might produce the same results.

**Comment by r888888888** [comment]
I'll get rid of the uniqueness constraint for now. Need to figure out a better way of detecting dupes.
