### ISSUE TITLE
Post bookmarklet is broken on Pixiv

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3728]
As reported first by Unbreakable on Discord.  Since the recent deployment (production-2018.05.25-175502-utc), the **post** bookmarklet no longer works on Pixiv.  I verified it by testing it on all three view modes.

- Medium: [post bookmarklet upload link](https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D68856536&ref=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fid%3D3012291)
- Manga: [post bookmarklet upload link](https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmanga%26illust_id%3D68856536&ref=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D68856536)
- Manga big: [post bookmarklet upload link](https://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmanga_big%26illust_id%3D68856536%26page%3D0&ref=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmanga%26illust_id%3D68856536)

When opening up the image preview link in a new tab, it shows it as an HTML page and not as an image.

https://danbooru.donmai.us/uploads/image_proxy?url=https%3A%2F%2Fwww.pixiv.net%2Fmember_illust.php%3Fmode%3Dmedium%26illust_id%3D68856536

The **batch** bookmarklet still works though.

**Comment by r888888888** [comment]
They must be switching the UI to a different layout for some accounts. It looks like they just embed some JSON on the page and it's possible to extract it this way without going to their API.
