### ISSUE TITLE
The same URL is present more than once in the artist version for certain situations

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3733]
I noticed this when I sent the same URL marked as both alive and dead by accident.  This might be related to #3720. 

A recent example of this with deleting a previously established artist url.

Artist: https://danbooru.donmai.us/artists/93704
Artist history: https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=93704

You can see from the artist history that even though both the url ``https://ask.fm/danekiss/`` was deleted, the active version is not marked as obsolete.  If you check through the API, you'll see that both URLs are showing up in the URL string.

Another example of adding a new dead URL.

Artist: https://danbooru.donmai.us/artists/93642
Artist history: https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=93642

In the history, it shows the URL ``http://odaibako.net/u/bluemomo/`` showing up as both a newly added dead URL and a newly added active URL.  Again, it's most likely because both exist in the URL string.

However, for both of the above, the information still appears correctly in the actual artist entry.  It's just the artist versions that are affected.

**Comment by BrokenEagle** [comment]
The following problem was noticed earlier when converting all of the old Deviantart links to the new Deviantart links, and is probably related to the OP.

![image](https://user-images.githubusercontent.com/21149935/45567203-f5a33680-b80d-11e8-988f-0c34d6c24aab.png)

Whereas before the issue was with both the dead and alive URLs being sent at once, the above issue happened because the same URL was sent both with and without a trailing slash.

**Comment by nonamethanks** [comment]
It seems a specific user added multiple versions of the same link to several artists, with and without trailing slash, for who knows what reason. I adjusted my script (`list(set(urls))` lol) as soon as I noticed it, but this kind of stuff should be probably caught at server level.

**Comment by evazion** [comment]
Sounds like the same issue as #3720. Duplicate urls are considered invalid get stripped from the artist entry, but not before the artist version is saved.

**Comment by evazion** [comment]
Fixed in 03cc3dfa5011aa788e71d41c32fa1a640c1a1098 with #3720.  The bug was that invalid urls were saved in the artist history even though they weren't saved in the artist entry itself.

These duplicate urls will still be in the artist history, since the artist versions were saved like that.
