### ISSUE TITLE
Related tags aren't populating for some tags

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3734]
From the [Danbooru forum](https://danbooru.donmai.us/forum_posts/145182):

> Laethiel said:
> 
> Searching for any of these tags works, but the Tags list on the left side is completely blank:
> narmaya_(granblue_fantasy)
> erune
> draph
> andira_(granblue_fantasy)
> 
> Searching for their aliased versions works, and the Tags list is populated:
> narumeia_(granblue_fantasy)
> erun_(granblue_fantasy)
> doraf
> anchira_(granblue_fantasy)
> 
> These were all part of the same BUR. I checked the rest of that BUR, but didn't see the same problem with any of the others.
> 
> EDIT: Just noticed that vira_lilie has the same problem.
> 
> EDIT 2: Also xenoblade_(series), senran_kagura_shoujo-tachi_no_shin'ei.

I checked the API for some of those tags, and the timestamp for the related tags is recent, even though there is nothing in the related tags string.
Example: 

* **erune**: https://danbooru.donmai.us/tags/1393342.xml

I also searched through the tags with post counts > 10, and found the following tags.

- arthur_pendragon_(fate)
- charlotta_fenia_(granblue_fantasy)
- zooey_(granblue_fantasy)
- you_(pokemon)
- eighth_note
- ass_focus
- tokiani

**Comment by r888888888** [comment]
This was fixed in dd6848912cdcf7a3c2d00397d79bd9c19f7cd317 and deployed. The upgrade to Rails 5 caused `render nothing: true` to be deprecated so the update call was failing.

**Comment by BrokenEagle** [comment]
@r888888888 

Just got the following note from Laethiel on Discord:

>> @BrokenEagle98 Re: issue #3734, erune and draph have related tags now, but the rest don't. I checked the XML files for all of the tags, and they all show related-tags-updated-at today. Some of them have <related-tags nil="true">, while the others just have an empty <related-tags/>.

So it looks like some of those tags still aren't updating.
