### ISSUE TITLE
Ugoiras (zip) aren't playable

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3735]
First brought up by DeusExCalamus on Discord.  I was able to verify this problem myself (Chrome 66 64-bit, Windows 8).

Example post: https://danbooru.donmai.us/posts/3145188?original=1

The following exception is what showed up in the development console:

```
Uncaught Error: ZipImagePlayer error: File undefined not found in ZIP
	at ZipImagePlayer._error
	at ZipImagePlayer._isFileAvailable
	at ZipImagePlayer._loadNextFrame
	at ZipImagePlayer.<anonymous>
	at XMLHttpRequest.<anonymous>
```

**Comment by r888888888** [comment]
Probably because `file` isn't specified anymore in the embedded frame data. `delay_msec` probably has to be mapped to `delay` also. I think this is fixable by mapping the frame data into the old format and generating the filename based on its position in the sequence.
