### ISSUE TITLE
Artist URL search should be case-insensitive for domains

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3738]
I just discovered that URL searches for artists are case sensitive at least with domains, when they should be case-insensitive as there is most likely inconsistency on the caseness of how links are presented.

Example artist:
- https://danbooru.donmai.us/artists/147623

It seems like case sensitivity doesn't affects searches when it only involves the path, as all of the following will find the above artist:

- https://twitter.com/ToasterKiwi
- https://twitter.com/toasterkiwi

However, when the case differes in the domain, then it will no longer find the artist if the case differs:

- https://ToasterKiwi.deviantart.com ([does find the artist](https://danbooru.donmai.us/artists?search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2FToasterKiwi.deviantart.com))
- https://toasterkiwi.deviantart.com ([doesn't find the artist](https://danbooru.donmai.us/artists?search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Ftoasterkiwi.deviantart.com))

The above could affect a large amount of sites, as many include the account name in the domain name instead of as part of the path.  Also, I'm not 100% certain, but I believe that domain specifiers are supposed to be case-insensitive, so it should be fine to do some kind of transformation to that part of the URL where everything is converted to lowercase.  However, that's not the case for the path or query terms, as I have seen case sensitivity sometimes being used there.

### Edit:
Just wanted to note that the above bug can potentially cause duplicate artists to be created.  At least for myself, I heavily use it to check for existing artists before creating a new one.  But if the linkup is never made because the URL isn't found upon searching, then the new artist created will split posts for the same artist depending on where they are uploaded from.

The above example artist is actually the perfect example.  It missed the Deviantart link because of caseness, and the only reason a successful linkup was made was because I also check for name matches and found a match with the name "toasterkiwi", but that saving grace won't always exist.

**Comment by evazion** [comment]
Lowercasing the domain should be safe. Whether the rest of the URL can be treated case-insensitively is going to depend on the site. Notably, Pixiv usernames are case-sensitive:

* https://www.pixiv.net/stacc/evazion (works)
* https://www.pixiv.net/stacc/Evazion (doesn't work)
