### ISSUE TITLE
download-preview.png missing on raikou1 / raikou2

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3743]
Flash files below id 2000000 have broken thumbnails due to the placeholder thumbnail not being present on raikou1 / raikou2:

* https://danbooru.donmai.us/posts?tags=flash
* https://raikou1.donmai.us/images/download-preview.png
* https://raikou2.donmai.us/images/download-preview.png

**Comment by r888888888** [comment]
Fixed
