### ISSUE TITLE
CAN'T SIGN IN AND DON'T HAVE RIGHT MEMBERSHIP 

### ISSUE THREAD

**Issue by PansexualThot** [r888888888/danbooru#3748]
SO I HAVE RESET MY PASSWORD 3 TIMES AND I STILL CAN'T GET LOGGED IN 

I LOGGED OUT DUE TO THE FACT I PAID FOR THE 20$ TIER LAST MONTH 
AND IT WAS SUPPOSED TO BE A 1 TIME PAY, BUT TODAY I NOTICED IT WAS GONE AND I THOUGHT IT WAS A GLITCH SO I SIGNED OUT; BUT THEN I WAS UNABLE TO GET BACK INTO MY ACCOUNT AT ALL 

MY ACCOUNT IS PansexualThot but it used to be Dravina 

I payed for something and I kinda expect to get it; I intended to upgrade in the future since it seemed worth it 

but I ain't paying for anything twice that was supposed to be a 1 time charge

please someone fix my account

**Comment by nonamethanks** [comment]
![](https://cdn.discordapp.com/attachments/310432830138089472/457965722086408222/unknown.png)

Don't want to sound rude here, but did you try writing the login name (in)properly?

**Comment by PansexualThot** [comment]
thanks for the info

whenever I tried to reset the password it came up different in the email 

and when I re-logged it it showed my Gold Membership again
