### ISSUE TITLE
Atom/RSS for mod queue

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3753]
Currently as far as I know there's no effective way for an approver to monitor new posts in the queue without continuously reloading. I've been using https://danbooru.donmai.us/posts.atom?tags=status%3Apending&limit=20 to monitor new posts, but that does not keep track of posts one has marked as not interested. 

It'd be nice to have something like https://danbooru.donmai.us/moderator/post/queue.atom - basically the equivalent of the [already available json](https://danbooru.donmai.us/moderator/post/queue.json).

I checked in https://github.com/r888888888/danbooru/tree/master/app/views/moderator/post/queues to see if it was already there and I just missed it but I couldn't find anything.

**Comment by evazion** [comment]
I think it would be sufficient to add metatags that let you filter out disapproved posts outside of the modqueue.

**Comment by nonamethanks** [comment]
Given that tag searches already have an associated RSS, that should work perfectly. Thank you!
