### ISSUE TITLE
Add ability to recalculate user statistics

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3757]
Related to #3756.  By now, there are probably plenty of user's whose upload counts are off.  Actually, this was probably an issue even before asynchronous uploads, as my own uploads are off, and I haven't had any of those failed uploads stuck in the preprocessed state.

- Profile: 14206
https://danbooru.donmai.us/users/23799
- Post count: 14233
https://danbooru.donmai.us/counts/posts?tags=user%3ABrokenEagle98+status%3Aany

However, it's not just uploads, as other statistics are off as well.

### Note versions:

- Profile: 32307
- Version count: 30270
https://danbooru.donmai.us/note_versions?limit=100&page=303&search%5Bupdater_id%5D=23799

### Post versions:

- Profile: 435178
- Version count: 41822
https://danbooru.donmai.us/post_versions?limit=100&page=4183&search%5Bupdater_id%5D=23799

Most of the other ones were spot on, but some of them were still off by one.

I see a couple possible solutions to this:

### 1. Run a daily, weekly, or monthly task that recalculates all statistics for all users

This would be quite laborious as there are over half a million users.

### 2. Run a recheck everytime a profile page is visited

Not as laborious as 1, although it would still be a bit wasteful unless it was restricted to running once per day, or something like that.

### 3. Have an on demand recheck option for certain levels of users

Kind of like how the tag fix option works.  It could be restricted to just Builder+ to prevent abuse.

**Comment by r888888888** [comment]
I just noticed there's a `counter_cache` on the uploader relation on Post. Is it possible it was double counting all this time? Anyway I don't think a manual increment is necessary.

**Comment by evazion** [comment]
@r888888888  2866335 broke the site map. There's a typo in the route, should be `new_maintenance_user_count_fixes_path`.

**Comment by BrokenEagle** [comment]
As noted by myself and several others, the refresh function doesn't seem to change any of the numbers for uploads, note changes, or post changes.

**Comment by r888888888** [comment]
This is fixed now.
