### ISSUE TITLE
Post replacements: undefined method `is_errored?'

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3761]
Attempting to fix some of the recent broken uploads got me:

    NoMethodError exception raised
    undefined method `is_errored?' for nil:NilClass
    app/logical/upload_service.rb:435:in `process!'
    app/models/post.rb:1400:in `block in replace!'
    app/models/post.rb:1397:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by r888888888** [comment]
Can you give an example of a post and the source/file you were trying to replace it with?

**Comment by RaisingK** [comment]
The ones in https://danbooru.donmai.us/forum_posts/147981 and https://danbooru.donmai.us/forum_posts/148030.  The error isn't occurring right now, though.  The latter are fixed now without me, and the replacement goes through without error (or apparent effect yet, aside from in the history).

**Comment by RaisingK** [comment]
Two more just now:
* post #3168987 with https://pbs.twimg.com/media/DexkwNjUcAALQ8f.jpg:orig
* post #3168988 with https://pbs.twimg.com/media/DexkwnHU0AElUGO.jpg:orig

**Comment by r888888888** [comment]
It looks like the replacement for both posts went through, or the original upload was the correct file. The actual error was buried. I'll make sure these get bubbled up so the cause is clearer.
