### ISSUE TITLE
Related tags don't automatically appear on uploads

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3765]
> dean_exia said ([forum #147987](https://danbooru.donmai.us/forum_posts/147987)):
> Related Tags (recent, frequent, translated and artist) do not automatically appear in Upload page now unless I manually put a word in the tag box and hit any of the five icons under the box.

> tapnek said ([forum #148013](https://danbooru.donmai.us/forum_posts/148013)):
> A big problem for me too as I rely on that section for more efficient tagging. It seems the redesign for the Upload page broke a couple things.

> Benit149 said ([forum #148028](https://danbooru.donmai.us/forum_posts/148028)):
> The Similar function and Artist search don't work for me anymore. I'm using the CSS to revert back to uploading via disk since those functions weren't working with the new layout, but still nothing. The Commentary field comes up fine for me though.

> keonas said ([forum #148301](https://danbooru.donmai.us/forum_posts/148301)):
> Hi, thought this was already reported but doesn't seem like it was.
For a few days now, whenever i try to upload an image (from pixiv) the data box that would auto-load under the tags box doesn't appear anymore.
You can get the "translated tags" and "artist" box if you click "related rags" on something random. 
Clicking Source - artist doesn't bring it up.

> fossilnix said ([forum #148311](https://danbooru.donmai.us/forum_posts/148311)):
> Is this change intentional/permanent? Right now, without the CSS, it won't display for me even when there are translated tags. And wouldn't the artist tag be considered important enough to show the box for? Won't this change make it a lot harder for users (especially newer users) to tag artists?

Commit b0c2ddb changed how related tags are processed so that the related tags only shows up if there are tags in the related tags response, which doesn't happen since the tag box is empty when the initial trigger for the **Related Tags** button goes off.

https://github.com/r888888888/danbooru/blob/b0c2ddba8bf704a4da2869302dd480d360a86b91/app/assets/javascripts/related_tag.js.erb#L95-L97

There is a lot of pushback on this change, whether it was intentional or not, since it also keeps other useful sections from automatically showing up, like **Recent**, **Frequent**, and **Artist**.

**Comment by evazion** [comment]
This works now.
