### ISSUE TITLE
Upload exceptions when both the file and source options are used

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3767]
Seems like there's still a few problems with uploading.

> CodeKyuubi said ([forum #148349](https://danbooru.donmai.us/forum_posts/148349)):
>
> Issue's been closed (I assume this implies that it was thought to be fixed), but I'm still getting exceptions returned when I fill both the file and source boxes

> CodeKyuubi said ([forum #148351](https://danbooru.donmai.us/forum_posts/148351)):
>
> https://i.imgur.com/GLHSzQQ.png
>
> I got this error three times today, once with tumblr (liyart)(downloaded the raw and put it in file box and put the tumblr page link in source) and once with weibo (renatus)(likewise, downloaded full res (large) and put the weibo link in source), and once with sadpanda, where Danbooru tried to pull the sadpanda thumbnail before the pre-loaded file and returned an 'md5 already exists' error.
>
> And I just now tested it with twitter, downloading the :orig and renaming it, then putting the file and source at the same time, returning the same error as above.
>
> Also got this error: https://i.imgur.com/KiADgmx.png
> When I accidentally closed the tab so I restored the tab and tried to re-pre-load the file and got that huge red shenanigen.

**Comment by BrokenEagle** [comment]
>CodeKyuubi said ([forum #1234](https://danbooru.donmai.us/forum_posts/148447)):
>
> A commit was pushed for issue #3767 but Danbooru still fails to upload with both the file and source boxes filled, prioritizing returning an error for md5 mismatching first and foremost before the file box, so any site where the auto-extracted image (or can't auto-extract) does not match the file (Twitter, patreonesque sites, e-h, etc...) fails the upload.

**Comment by lllusion3469** [comment]
Happens for me too when manually uploading a file any specifying any source whatsoever.

Might be more complicated than this, but it seems to fix it for me:
```diff
--- a/app/logical/upload_service/preprocessor.rb
+++ b/app/logical/upload_service/preprocessor.rb
@@ -33,25 +33,25 @@ class UploadService
     memoize :canonical_source
 
     def in_progress?
-      if Utils.is_downloadable?(source)
-        return Upload.where(status: "preprocessing", source: source).exists?
-      end
-
       if md5.present?
         return Upload.where(status: "preprocessing", md5: md5).exists?
       end
 
+      if Utils.is_downloadable?(source)
+        return Upload.where(status: "preprocessing", source: source).exists?
+      end
+
       false
     end
 
     def predecessor
-      if Utils.is_downloadable?(source)
-        return Upload.where(status: ["preprocessed", "preprocessing"], source: source).first
-      end
-
       if md5.present?
         return Upload.where(status: ["preprocessed", "preprocessing"], md5: md5).first
       end
+
+      if Utils.is_downloadable?(source)
+        return Upload.where(status: ["preprocessed", "preprocessing"], source: source).first
+      end
     end
 
     def completed?
```
