### ISSUE TITLE
DeviantArt moving away from subdomains

### ISSUE THREAD

**Issue by lllusion3469** [r888888888/danbooru#3771]
As announced [here](https://www.deviantart.com/danlev/journal/New-Profile-URLs-751783111), deviantart is moving to a new profile url system which breaks automated downloading.

e.g. `https://aeror404.deviantart.com/art/Holiday-Elincia-424551484`
redirects to `https://www.deviantart.com/aeror404/art/Holiday-Elincia-424551484`
i.e. 
```sed
s_https?://([^.]+)\.deviantart.com/(.+)_https://www.deviantart.com/\1/\2_
```
Danbooru obviously doesn't recognize this and says
`Error: bad argument (expected URI object or URI string)`

**Comment by 7nik** [comment]
Also the artist search by new deviantart link always return the same list of unrelated artists if the artist is not presented in the DB and even for some presented:
[https://caidychen.deviantart.com/](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Fcaidychen.deviantart.com%2F&utf8=%E2%9C%93)
[https://www.deviantart.com/caidychen](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Fwww.deviantart.com%2Fcaidychen&utf8=%E2%9C%93)
[https://chris-re5.deviantart.com/](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Fchris-re5.deviantart.com%2F&utf8=%E2%9C%93)
[https://www.deviantart.co/chris-re5](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Fwww.deviantart.com%2Fchris-re5&utf8=%E2%9C%93)
[https://foxiecsc.deviantart.com/](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Ffoxiecsc.deviantart.com%2F&utf8=%E2%9C%93)
[https://www.deviantart.com/foxiecsc](https://danbooru.donmai.us/artists?commit=Search&search%5Border%5D=created_at&search%5Burl_matches%5D=https%3A%2F%2Fwww.deviantart.com%2Ffoxiecsc&utf8=%E2%9C%93)

**Comment by lllusion3469** [comment]
I don't know about your instance, but for me I doesn't work quite yet:

it manages to find all the metadata (artist, tags, image url) but then downloads the (HTML-)page itself instead of the image url.

I think [/app/logical/downloads/rewrite_strategies/deviant_art.rb](https://github.com/r888888888/danbooru/blob/master/app/logical/downloads/rewrite_strategies/deviant_art.rb) also needs to be edited in lines [11](https://github.com/r888888888/danbooru/blob/b2f62482a1eb6bf98d7d9113951a5c8653b1c45c/app/logical/downloads/rewrite_strategies/deviant_art.rb#L11) and [21](https://github.com/r888888888/danbooru/blob/b2f62482a1eb6bf98d7d9113951a5c8653b1c45c/app/logical/downloads/rewrite_strategies/deviant_art.rb#L21).
Something like this:

```diff
--- a/app/logical/downloads/rewrite_strategies/deviant_art.rb
+++ b/app/logical/downloads/rewrite_strategies/deviant_art.rb
@@ -8,7 +8,7 @@ module Downloads
       end
 
       def rewrite(url, headers, data = {})
-        if url =~ %r{deviantart\.com/art/} || url =~ %r{deviantart\.net/.+/[a-z0-9_]+(_by_[a-z0-9_]+)?-d([a-z0-9]+)\.}i
+        if url =~ %r{deviantart\.com/(.+?/)?art/} || url =~ %r{deviantart\.net/.+/[a-z0-9_]+(_by_[a-z0-9_]+)?-d([a-z0-9]+)\.}i
           url, headers = rewrite_html_pages(url, headers)
           url, headers = rewrite_thumbnails(url, headers)
         end
@@ -18,7 +18,7 @@ module Downloads
 
     protected
       def rewrite_html_pages(url, headers)
-        if url =~ %r{^https?://.+?\.deviantart\.com/art/}
+        if url =~ %r{^https?://.+?\.deviantart\.com/art/} || url =~ %r{^https?://www\.deviantart\.com/.+?/art/}
           return [source.image_url, headers]
         else
           return [url, headers]
```

**Comment by evazion** [comment]
Reopening because the artist finder still doesn't work with the new URLs. The artist finder doesn't find [wlop](https://danbooru.donmai.us/artists/87521) as the artist for [post #3200215](https://danbooru.donmai.us/posts/3200215) after changing the artist entry to `https://www.deviantart.com/wlop`.

**Comment by r888888888** [comment]
I've run a script to normalize all the subdomain artist urls to used the path version.

**Comment by BrokenEagle** [comment]
Doesn't ``deviantart.com`` also need to be added to the blacklist, so that when there aren't any matches and it reaches the root path, it doesn't return bogus results?

https://github.com/r888888888/danbooru/blob/95b72f5f5c24f236ff0c13aaf3d8e27f950dfcaf/app/models/artist.rb#L36-L143

**Comment by evazion** [comment]
I think everything's been fixed here.
