### ISSUE TITLE
Uploads fail due to vipsthumbnail being too old

### ISSUE THREAD

**Issue by meoberto** [r888888888/danbooru#3776]
When I attempted to upload a picture to my danbooru instance, I was faced by repeated failures to upload anything, and that is due to the fact that by default danbooru2 tries to run `vipsthumbnail --smartcrop=attention`.
Here are some logs of the issue:
```
    MD5: 3b42ffe5be1cbbfbe0e74e42e3c78ab4
    Size: 101 KB
    (800x1000) 

An error occurred: error: RuntimeError - vipsthumbnail failed (exit status: 1)
```
```
Unknown option --smartcrop=attention
vipsthumbnail: try "vipsthumbnail --help"
127.0.0.1 - - [08/Jul/2018:08:40:02 UTC] "POST /uploads.json HTTP/1.0" 201 12382
- -> /uploads.json
```
Now, researching why would vipsthumbnail fail to recognise smartcrop as an option, I started looking for when was smartcrop introduced to libvips, and it turns out it was version 8.5.0.
There's another problem with that, and that is that debian does not supply any versions later than 8.4.5 in its repositories, not even for unstable.

**Comment by r888888888** [comment]
Correct. I decided to just manually compile and install the latest version of libvips and put it in a directory that didn't overwrite the packaged version.

**Comment by meoberto** [comment]
While #4d4f36c pretty much solves this issue, I think it should be pointed out in the documentation that image cropping requires libvips 8.5.0 or later. I followed [this](https://renchap.com/blog/post/building_recent_libvips_on_debian/) when fixing things up on my server, by the way.
