### ISSUE TITLE
Artist entries with bogus URLs are no longer editable

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3781]
> tapnek said ([forum #148928](https://danbooru.donmai.us/forum_posts/148928)):
>I can't seem to update artist profiles, specifically [artist #129375](https://danbooru.donmai.us/artists/129375). I keep getting the error "Url Url must begin with http:// or https://." even though the following URLs follow that rule.
```
http://blog.jnwiedle.com/
https://twitter.com/jnwiedle
http://pixiedrawings.tumblr.com/
http://helvetica.jnwiedle.com/

Url Url must begin with http:// or https://.
```
I have verified myself, as well as confirming that the revert function doesn't work either.  I tried removing all of the URLS, or changing the name, and nothing works.  I even deleted the artist entry just to see if that would work, which it did, however when trying to revert that change, it redirected goes to a page that looks like the artist edit page, however it has the revert URL in the address bar instead.

https://danbooru.donmai.us/artists/129375/revert?version_id=354760

It also returns the same error message as above, "Url Url must begin with http:// or https://."  Additionally, the sub menu shows the **Delete** link instead of the **Undelete** links as if the revert had been successful, however going back to the artist show page or history shows that it was not successful.

**Comment by r888888888** [comment]
Is this validation even necessary? I was looking into transforming it into a warning but there's no simple way to roll up warnings form the URL level up to artist.

**Comment by BrokenEagle** [comment]
Well does having malformed URL entries affect any of the functions negatively?

**Comment by evazion** [comment]
The purpose is to prevent mistakes like adding `twitter.com/username` instead of `http://twitter.com/username`, which doesn't work with the artist finder.
