### ISSUE TITLE
"MD5 has already been taken" error is displayed instead of duplicate page 

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3784]
Example:
http://seiga.nicovideo.jp/seiga/im8284283 fails to upload with https://danbooru.donmai.us/uploads/1946707 because the post is already up from pixiv (https://danbooru.donmai.us/posts/3179327).

However not only is the post missed by the similar posts result, it also doesn't offer any clue whatsoever in the error page, so it's pretty confusing to tell what's going on.

**Comment by r888888888** [comment]
fixed
