### ISSUE TITLE
Post replacements broken for ugoira images

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3785]
I tried to replace post #3198564 with the original ugoira but ended up with a "No video with supported format and MIME type found" placeholder instead; issue #3133 was supposed to fix this, right?

I tried to re-replace it with https://hijiribe.donmai.us//data/b86cd140b86f548ab520ff56faa941e3.gif, but that didn't work.  The attempt in the replacement history doesn't have MD5 or Size values.

**Comment by r888888888** [comment]
Not sure. I was able to manually convert the file to a webm and distribute it. Then I manually reran the processor and that worked.

**Comment by evazion** [comment]
There's a test for ugoira replacements in the test suite that passes so I'm assuming this is fixed.
