### ISSUE TITLE
Bookmarklet setting wrong source on Pixiv

### ISSUE THREAD

**Issue by Unbreaky** [r888888888/danbooru#3788]
> Unbreakable said [Forum #149037](https://danbooru.donmai.us/forum_posts/149037) 
>
> Anyone else having problems with the bookmarklet setting the source wrong when uploading from Pixiv? For example instead of putting it as https://i.pximg.net/img-original/img/2018/07/24/21/45/27/69842465_p0.jpg it puts it as http://www.pixiv.net/member_illust.php?mode=medium&illust_id=69842465 The batch bookmarklet seems to be working fine though. I've seen it happen to others too.

> fossilnix said [Forum #149037](https://danbooru.donmai.us/forum_posts/149038) 
>
> It happens to me, but only if I use the bookmarklet on the post page instead of the raw image URL

**Comment by BrokenEagle** [comment]
I can also confirm the above.  I can also confirm that the batch bookmarklet still works as it should, even when used on single post entries.

- Post bookmarklet: https://danbooru.donmai.us/uploads?search[id]=1949641
- Batch bookmarklet: https://danbooru.donmai.us/uploads?search[id]=1949641

As can be seen from the above, with the **Post** bookmarklet it sets the source using the post URL, and with the **Batch** bookmarklet it uses the image URL.

**Comment by Unbreaky** [comment]
The bookmarklet has always worked on the post page before and using it there will always grab the best version of an image.

**Comment by r888888888** [comment]
fixed in 7753461f6f13865845a2e325069a1008fe08e21e
