### ISSUE TITLE
[Webpacker] Issues

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3791]
Some outstanding issues with the webpacker build deployed on testbooru:

- [x] Autocomplete styling is broken
- [x] Post preview tooltip is broken
- [x] `Utility not defined` error in post mod queue
- [x] Ugoira player is broken

**Comment by evazion** [comment]
Multiple issues have been reported on the [forum](https://danbooru.donmai.us/forum_topics/9127?page=248#forum_post_149235):

- [ ] Tag colors are broken
- [ ] Related tags / find artist are broken
- [ ] 'E' to edit shortcut is broken (inserts the letter 'e' in the tag box)
- [ ] Approvals are broken? (unconfirmed)
- [ ] Userscripts that relied on internal Danbooru functions (e.g. `Danbooru.notice`, etc) are broken.

**Comment by r888888888** [comment]
'E' seems to be fixed; it may have been a side effect of other javascripts breaking on that page. The checked items have been fixed and deployed.

**Comment by evazion** [comment]
Links in certain places are grey instead of blue:

![image](https://user-images.githubusercontent.com/8430473/43666203-7c232162-9738-11e8-8ce5-24893cb96d1b.png)

![image](https://user-images.githubusercontent.com/8430473/43666229-98933620-9738-11e8-9d40-292e4fa15f49.png)
