### ISSUE TITLE
Batch bookmarklet doesn't set Twitter sources correctly

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3793]
Reported by @nonamethanks on Discord.  Same issue as #3777.

https://danbooru.donmai.us/uploads?search%5Bsource_matches%5D=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2F%2A

As can been seen from the above, there has been a surge of Twitter image source links over the last day (at least) that are for the most part impossible to attribute to an artist unless the uploader happens to do so.

**Comment by r888888888** [comment]
fixed
