### ISSUE TITLE
The Javascript "Danbooru" global variable is no longer accessible

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3795]
Many user scripts (including my own), are dependent on the library of functions and variables that Danbooru provides, and are currently broken or impaired.  When going to the dev console (F12), the Danbooru global variable is completely inaccessible.

**Comment by r888888888** [comment]
This is an unfortunate side effect of Webpack modularizing everything.

Some of the most common methods can be accessed via DOM events:

```javascript
$(window).trigger("danbooru:notice", "Message");
$(window).trigger("danbooru:error", "Message");
$(window).trigger("danbooru:index_for_post", post_id, current_comment_section, include_below_threshold);
$(window).trigger("danbooru:initialize_saved_searches");
```

Additional functions can be exposed with this method. I can probably just create a global Danbooru object that makes that event calls to keep existing scripts functioning.

**Comment by r888888888** [comment]
@BrokenEagle If you give me a list of all the entry points you were using I can add hooks to look for globally defined functions. It would at least get your scripts working again while figuring out what to do going forward.

**Comment by BrokenEagle** [comment]
The following is the list of functions I'm currently overwriting that get called by other Danbooru event handlers.

```
Danbooru.Autocomplete.normal_source
Danbooru.Autocomplete.pool_source
Danbooru.Autocomplete.user_source
Danbooru.Autocomplete.favorite_group_source
Danbooru.Autocomplete.saved_search_source
```

There were several others, but they weren't really necessary to overwrite, so the above list should be all that is required, I believe.

**Comment by BrokenEagle** [comment]
The following are a couple more functions that get utilized, but don't need function hooks:

```
Danbooru.RelatedTag.build_recent_and_frequent
Danbooru.RelatedTag.current_tag
Danbooru.RelatedTag.process_response
Danbooru.RelatedTag.process_artist
```

The above haven't been exported yet, and I saw how several other functions of various usability have already been exported manually, but I wonder at what point it would be easier just to export the whole thing?

**Comment by Moebius-Strip** [comment]
I made a quick list so I can't tell you how each of these ends up being used just yet. Some are modified, some are used as is, and some are just tested for. Knowing that may not even matter...? If it does, I'll have to sift through the ~65 instances to figure it out.

```
Danbooru.Autocomplete
Danbooru.Autocomplete.normal_source
Danbooru.Autocomplete.render_item
Danbooru.Autocomplete.static_metatag_source
Danbooru.Autocomplete.static_metatags
Danbooru.Autocomplete.user_source
Danbooru.Blacklist.initialize_all
Danbooru.Comment.initialize_all
Danbooru.Dtext.click_button
Danbooru.Note.Box.scale_all
Danbooru.Note.Box.toggle_all
Danbooru.Note.Edit.show
Danbooru.Note.TranslationMode.active
Danbooru.Note.TranslationMode.start
Danbooru.Note.TranslationMode.stop
Danbooru.Note.TranslationMode.toggle
Danbooru.Note.embed
Danbooru.Note.load_all
Danbooru.PostModeMenu.click
Danbooru.Ugoira
Danbooru.Ugoira.create_player
Danbooru.Ugoira.player
Danbooru.autocompleting <-- Not sure what this was, but it no longer appears to be needed.
```

**Comment by evazion** [comment]
That might be because autocomplete.js is missing an `export default Autocomplete` statement?

There are a few other modules I was using in my own code: Post, Shortcuts, RelatedTag, and Paginator.

**Comment by kittey** [comment]
Could `Danbooru.TagScript.run` be exposed as well?

**Comment by BrokenEagle** [comment]
In addition to the remaining unexported modules as requested above, there is a userscript on the Danbooru forum ([forum #146849](https://danbooru.donmai.us/forum_posts/146849)) which modifies the post tooltips, so the **PostTooltip** module would also need to be exported.

### Remaining exports:
- [ ]  RelatedTag
- [ ]  Post
- [ ]  Shortcuts
- [ ]  Paginator
- [ ]  PostTooltip
