### ISSUE TITLE
Bookmarklets do not use the preprocessed post on Twitter

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3798]
Similar to #3782.

https://danbooru.donmai.us/uploads?search%5Bsource_matches%5D=https%3A%2F%2Ftwitter.com%2F%2A&search%5Buploader_name%5D=BrokenEagle98

This seemed to happen regardless of using the Post or Batch bookmarklet from the Twitter post page.

**Comment by r888888888** [comment]
I think fixing this once and for all requires an additional field on uploads. For twitter galleries, the status url will always point to the gallery, so another source is required for storing the twimg url.

**Comment by r888888888** [comment]
Fixed in 334d8b7c6f254868de7917542c112573aaf13da1
