### ISSUE TITLE
Drag and drop freezes on large file sizes

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3802]
> Grahf said ([forum #149279](https://danbooru.donmai.us/forum_posts/149279)):
> 
> I'm once again running into the same issue that I described a month ago ([forum #148117](https://danbooru.donmai.us/forum_posts/148117)).
> 
> I am trying to upload images from https://e-hentai.org/g/1265731/6f00bd8106/ (explicit content warning)
> 
> These images are fairly large, most being over 10MB each. When I drag the image from my computer to the upload portion, the loading bar gets about a third of the way done and then just freezes. It doesn't matter how long I wait, it will not progress, and trying to upload the image results in the same error:
> 
> ActiveRecord::RecordInvalid exception raised
> 
> Validation failed: Md5 confirmation doesn't match Md5
> app/logical/upload_service.rb:42:in `start!'
> app/controllers/uploads_controller.rb:54:in `create'
> 
> EDIT: I have uploaded the images now, but only through use of yande.re as a sort of proxy so that I was not uploading them directly from my computer.

I tested and verified the above myself on Testbooru.

- http://testbooru.donmai.us/uploads/215

The file I used for testing was the following.

- https://raikou1.donmai.us/ee/9f/ee9fc87de65def4103e70518cec05b52.png

Unlike Grahf, the upload bar did complete loading and turn green, but when I uploaded I still got the same error message.

```
ActiveRecord::RecordInvalid exception raised
Validation failed: Md5 confirmation doesn't match Md5
app/logical/upload_service.rb:42:in `start!'
app/controllers/uploads_controller.rb:54:in `create'
```

Even though it says the MD5 doesn't match, I checked and the page produced an upload MD5 hash of ``ee9fc87de65def4103e70518cec05b52``, which matches the actual MD5 as can be seen from the image link above.   The upload record also had the same MD5 hash.

### Request payload

```
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="utf8"

✓
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="authenticity_token"

/zJlP6Gv54cbfStV0LfGoKn+hbOS/2WkoQzk5zyevUT+1/HVi1hrWDHDDlAGVU5hxJBcPncfxlfv6BoGzBYrLA==
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="url"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="ref"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="normalized_url"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[md5_confirmation]"

ee9fc87de65def4103e70518cec05b52
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[referer_url]"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[as_pending]"

0
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[file]"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[source]"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[rating]"

s
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[parent_id]"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[artist_commentary_title]"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[artist_commentary_desc]"


------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[include_artist_commentary]"

0
------WebKitFormBoundaryjPhC0jAIPTcjDECX
Content-Disposition: form-data; name="upload[tag_string]"

drag_and_drop upload_from_disk very_large_file_size md5_validation_test forum_post_149279
------WebKitFormBoundaryjPhC0jAIPTcjDECX--
```

**Comment by evazion** [comment]
I believe this was fixed in #4018.
