### ISSUE TITLE
IP banned myself

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3803]
Attempted to IP ban someone to see what would happen (I knew it was admin-restricted) and apparently got IP-banned myself instead.

halp

**Comment by r888888888** [comment]
Fixed

**Comment by nonamethanks** [comment]
@r888888888 this happened again today with another moderator. There probably should be some system that stops you from IP banning yourself.

**Comment by r888888888** [comment]
Yeah it's a bug with IpBan. A fix is in progress.
