### ISSUE TITLE
Leaked IP addresses

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3804]
User ampzz ([forum #149347](https://danbooru.donmai.us/forum_posts/149347)) and user Damian0358 (Discord) brought up a new upload error that they are experiencing, however beyond the error itself, I noticed that it is leaking the user's IP addresses in the upload records, which is a huge concern for privacy.

https://danbooru.donmai.us/uploads?search%5Bstatus%5D=error%3A+ActiveRecord%3A%3ANotNullViolation*

There could be other places where the IP address is placed in the error message like that, but I don't believe it is stored in a visible record like uploads are, or is there?

**Comment by lllusion3469** [comment]
I experienced the same issue when trying to upload a file manually without a source.

Solved it on my end with this change:
```diff
-- a/app/logical/upload_service/preprocessor.rb
+++ b/app/logical/upload_service/preprocessor.rb
@@ -112,6 +112,7 @@ class UploadService
       # we went through a lot of trouble normalizing the source,
       # so don't overwrite it with whatever the user provided
       pred.attributes = self.params.except(:source)
+      pred.source ||= ''
 
       # if a file was uploaded after the preprocessing occurred,
       # then process the file and overwrite whatever the preprocessor
```

I don't know whether this is the proper change, but it is necessary for me since specifying any source at all (for an manual upload) always produces this error:
```
ActiveRecord::RecordInvalid exception raised

    Validation failed: Md5 confirmation doesn't match Md5
    app/logical/upload_service.rb:42:in `start!'
    app/controllers/uploads_controller.rb:54:in `create'
```

**Comment by BrokenEagle** [comment]
Beyond solving the error as above though, I believe that such errors should also mask or leave out the IP address.

**Comment by Bapabooiee** [comment]
While we're on the topic of IP addresses and privacy, is there any particular reason that (unsanitized) IP addresses should be shown publicly for [ban creations](https://danbooru.donmai.us/mod_actions?commit=Search&search%5Bcategory%5D=160) and [ban deletions](https://danbooru.donmai.us/mod_actions?commit=Search&search[category]=162) under /mod_actions?

Seems like something that should be reserved for Mod+ only.

**Comment by evazion** [comment]
Original issue was fixed. Moving the issue with IP bans to #4105.
