### ISSUE TITLE
Tumblr raw images are no longer accessible

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3810]
It looks like the http://data.tumblr.com domain doesn't work anymore. They seem to be obfuscating the original so it may not be possible to download anymore.

Ref:

* https://www.reddit.com/r/userscripts/comments/9605e8/anyone_using_tumblr_raw_image_scripts_tumblr/
* https://greasyfork.org/en/forum/discussion/41099/x

**Comment by evazion** [comment]
In some cases the 500h version is better than the 1280 version:

* http://media.tumblr.com/b74a1f737c550a55d79b7c11e6914805/tumblr_pdoj7qIim31xb72fuo1_500h.jpg
 (2560x456, 438,555 bytes)
* http://media.tumblr.com/b74a1f737c550a55d79b7c11e6914805/tumblr_pdoj7qIim31xb72fuo1_1280.jpg (1280x228, 167,859 bytes)

In some cases there's a better version on a.tumblr.com:

* https://media.tumblr.com/tumblr_lnya8otvBr1qik2kro1_1280.jpg (1237x956, 333,331 bytes)
* https://a.tumblr.com/tumblr_lnya8otvBr1qik2kro1_1280.jpg (1237x956, 963,456 bytes)

Most of the time though, a.tumblr.com returns a 404.
