### ISSUE TITLE
Adjust notes positions/sizes after post replacement

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3815]
Notes aren't being automatically adjusted after post replacements.  Didn't they used to do that?

**Comment by RaisingK** [comment]
EB brought this up after replacing post #3218976 and post #3218975.  I just replaced post #3224182 and post #3224185 and had the same thing happen.

**Comment by evazion** [comment]
It turns out this happens only when the "Final Source" field is set during the replacement. It worked when the final source wasn't set.
