### ISSUE TITLE
Blacklist and mod queue

### ISSUE THREAD

**Issue by Unbreaky** [r888888888/danbooru#3821]
Is there a reason the blacklist isn't working in the mod queue? It's quite annoying to get guro and other things in my face when trying to find stuff to approve, granted it's only thumbnails but I have it blacklisted for a reason and would never approve an image with it anyway.

**Comment by evazion** [comment]
I assume it's so that approvers have to look at all posts. I don't think that makes a lot of sense though. It just means approvers will use the search bar to filter things out instead, or moderate from `status:pending` instead of the queue.
