### ISSUE TITLE
Move favorites (while deleting) fails if user has also favorited destination

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3822]
I tried to delete post #3226653 and move its favorites to its parent, but because the same user had favorited both posts, I got an error instead and the post wasn't deleted:

    Favorite::Error exception raised

    You have already favorited this post
    app/models/favorite.rb:15:in `block in add'
    app/models/favorite.rb:9:in `add'
    app/models/post.rb:962:in `add_favorite!'
    app/models/post.rb:1290:in `block (2 levels) in give_favorites_to_parent'
    app/models/post.rb:1288:in `block in give_favorites_to_parent'
    app/models/post.rb:1287:in `give_favorites_to_parent'
    app/models/post.rb:1371:in `block in delete!'
    app/models/post.rb:1360:in `delete!'
    app/controllers/moderator/post/posts_controller.rb:17:in `delete'

**Comment by evazion** [comment]
Regressed in bcaee199f when `Post#add_favorite!` was changed to raise an error on failure instead of silently ignoring failures.
