### ISSUE TITLE
Add Photozou source normalization

### ISSUE THREAD

**Issue by DoomTay** [r888888888/danbooru#3823]
Danbooru has a few Photozou uploads, though getting their page from them is pretty simple. All you need is two numbers

http://kura3.photozou.jp/pub/794/1481794/photo/161537258_org.v1364829097.jpg
http://photozou.jp/photo/show/1481794/161537258

http://art5.photozou.jp/pub/383/3197383/photo/255595927_624.v1534608193.jpg
http://photozou.jp/photo/show/3197383/255595927

**Comment by evazion** [comment]
More examples:

https://docs.google.com/spreadsheets/d/1vvUHvQGVJeSi9aU4PA3MMRORKd3witwyZq4fPQ9r8RI/edit?usp=sharing

```
SELECT id, source
FROM `danbooru-data.danbooru.posts`
WHERE REGEXP_CONTAINS(source, 'photozou')
ORDER BY id DESC;
```
