### ISSUE TITLE
Increase maximum number of actions for inactive approvers report to 49

### ISSUE THREAD

**Issue by crs00** [r888888888/danbooru#3828]
The maximum number of actions on pending posts to be listed under inactive approvers on isshiki is 30, while the minimum number of actions on pending posts to be listed under approvers on isshiki is 50. This creates a weird hole in the reports for people who leave actions on 31-49 pending posts. I was wondering if we could increase the maximum number of actions for inactive approvers to 49 in order to rectify this.

**Comment by r888888888** [comment]
This is fixed in reportbooru.
