### ISSUE TITLE
JS Upload ignores set Max-Filesize bigger than 265 MB

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3830]
G'day It appears that the JavaScript uploader is blocking files bigger than 265MB, I allow 512MB uploads on my fork and I'd like to increase it.

Blocking JavaScript gives me the regular button and with that I can upload the bigger files but it's a hassle for the members that wan't to upload the items.

Could you point me in the direction where it decides that since I haven't found it yet.

**Comment by evazion** [comment]
See a616224; you can set `maxFilesize` inside `app/views/uploads/new.html.erb` if you need to fix it manually.
