### ISSUE TITLE
Fully ID specify the links in the menu

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3844]
Currently, the only way to hide the links in either the main or the sub menu is to use a combination of position and/or composition selectors, both of which are very fragile.  It would be nice to be able to fully control which links show up on which page without having to worry about site updates or userscripts messing with that scheme.

The idea would be that for every type of link in the main and submenus, there would be a corresponding unique ID link on each ``<li>`` element.

To help control it on the basis of page, the page would need to be specified like it currently is under the ``#page`` ID.  For this, data items ``data-controller``, ``data-action``, and ``data-partial`` could be added to either the ``<body>`` element or the ``<nav>`` element.  If it's the former, then that might even allow for the eventual removal of the two to three standard DIVs under the ``#page`` element, although that should be phased over some time period along with some kind of announcement to give people a chance to update their CSS or scripts.

**Comment by evazion** [comment]
Added html IDs to all subnav menu items: 

![image](https://user-images.githubusercontent.com/8430473/44696393-047fa000-aa3d-11e8-9a13-b688d4eafbe8.png)

The `/posts` index already had IDs for some menu items; these have been changed from e.g. `#secondary-links-posts-help` to `#subnav-help`.
