### ISSUE TITLE
Can't fetch twitter metadata in upload page & bookmarklet

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3850]
Returns a "This feature isn't available: NotImplementedError" alert.

```
/var/www/danbooru2/releases/20180829182924/app/logical/sources/strategies/base.rb:78:
in `artist_name'","/var/www/danbooru2/releases/20180829182924/app/logical/sources/strategies/base.rb:183:
in `to_h'","/var/www/danbooru2/releases/20180829182924/app/controllers/sources_controller.rb:7:
in `show'","/var/www/danbooru2/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6
<code snipped>
```

**Comment by evazion** [comment]
Works when using the bookmarklet on the html page. Doesn't work when using it on the image.

**Comment by nonamethanks** [comment]
@evazion it's broken for me for the batch bookmarklet. For example any page opened by https://danbooru.donmai.us/uploads/batch?utf8=%E2%9C%93&batch%5Burl%5D=https%3A%2F%2Ftwitter.com%2Febifly857%2Fstatus%2F1032008034006982656&commit=Fetch

**Comment by evazion** [comment]
Looks like a combination of several issues:

- [ ] The /source.json call isn't getting the referer passed in.
- [ ] The twitter strategy had a typo that kept it from matching direct twitter images without a referer. The null strategy was getting chosen instead.
- [ ] The null strategy errors out inside /source.json.

**Comment by r888888888** [comment]
@nonamethanks I assume your version of the bookmarklet sets the `ref` parameter, and it's set to the status page. Pasting what the bookmarklet redirects you to would be useful.

**Comment by nonamethanks** [comment]
The link I posted above returns [this kind of upload page](https://danbooru.donmai.us/uploads/new?ref=https%3A%2F%2Ftwitter.com%2Febifly857%2Fstatus%2F1032008034006982656&url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDlJtOfIUcAAn_qO.jpg%3Aorig). Aren't they the same for everyone? I thought they were generated server-side.

**Comment by r888888888** [comment]
Some additional fixes in ab220f295c88f4bbd1eb2ef32b9ed22a654293d4 and eac5a57c0b408e8f70bbf8770b69e5f7f63f6101 have been deployed.

**Comment by evazion** [comment]
ab220f2 has a new bug: if you don't use the bookmarklet, and you paste an url into the source field manually, then the `Fetch source data` button won't do anything. In this case the `#url` field gets chosen before the `#upload_source` field, but the field is blank so it does nothing.

**Comment by evazion** [comment]
I think this is working now.
