### ISSUE TITLE
Blacklist minscore is broken

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3853]
Currently the minscore when used by itself blocks all posts.  That is because when all of the requirements arrays are all empty, then it all resolves to be true.

- Require: ``[ ]`` is always a subset of any array
- Optional: The length is zero, so that portion holds true
- Exclude: The length of the intersection with ``[ ]`` is always zero, which resolves to true

Probably need to move the results of the minscore test and incorporate it into the Require test.

```javascript
Blacklist.post_match = function(post, entry) {
  if (entry.disabled) {
    return false;
  }

  var $post = $(post);
  var score = parseInt($post.attr("data-score"));
  var score_test = entry.min_score === null || score < entry.min_score;

  var tags = String($post.attr("data-tags")).match(/\S+/g) || [];
  tags = tags.concat(String($post.attr("data-pools")).match(/\S+/g) || []);
  tags.push("rating:" + $post.data("rating"));
  if ($post.attr("data-uploader")) {
    tags.push("user:" + $post.attr("data-uploader").toLowerCase());
  }
  tags.push("uploaderid:" + $post.attr("data-uploader-id"));
  tags.push("toptaggerid:" + $post.attr("data-top-tagger"));
  $.each(String($post.data("flags")).match(/\S+/g) || [], function(i, v) {
    tags.push("status:" + v);
  });

  return (Utility.is_subset(tags, entry.require) && score_test)
    && (!entry.optional.length || Utility.intersect(tags, entry.optional).length)
    && !Utility.intersect(tags, entry.exclude).length;
}
```

So when the min_score is ``null`` the value is true and it plays no part, but when the min_score is non-null and is greater than the score it will be false and override the results of the Require test.

**Comment by evazion** [comment]
Fixed (and attributed authorship to you).
