### ISSUE TITLE
Post replacements: ActiveRecord::NotNullViolation exception raised

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3855]
Attempting to replace post #3239866 with https://pbs.twimg.com/media/Cm4hyXwUEAAON93.jpg:orig got me:

    ActiveRecord::NotNullViolation exception raised

    PG::NotNullViolation: ERROR: null value in column "replacement_url" violates not-null constraint DETAIL: Failing row contains (14496, 3239866, 13506, https://twitter.com/yuzuno35/status/751575355832475648, null, 2018-08-30 01:42:53.108678, 2018-08-30 01:42:57.301064, jpg, 70550, 640, 953, 76fa7fca57d67b6f4ff9af918cc69f8f, jpg, 68695, 640, 953, e29fc8f41b99e79cf98fe06dd78b7f3a). : UPDATE "post_replacements" SET "replacement_url" = $1, "updated_at" = $2, "file_ext" = $3, "file_size" = $4, "image_width" = $5, "image_height" = $6, "md5" = $7 WHERE "post_replacements"."id" = $8
    app/logical/upload_service/replacer.rb:111:in `process!'
    app/models/post.rb:1429:in `block in replace!'
    app/models/post.rb:1426:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by r888888888** [comment]
I assume you're using the twimg.com URL. Doesn't that update the post's source also? Do you subsequently update the post's source to the status URL?
