### ISSUE TITLE
URLs are broken for various Pixiv links

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3856]
The artist search is currently broken for at least Pixiv stacc links, even if that links for that artist.

https://danbooru.donmai.us/artists?search%5Burl_matches%5D=https%3A%2F%2Fwww.pixiv.net%2Fstacc%2Faino3751484

```
Couldn't get illust ID from URL (http://www.pixiv.net/stacc/aino3751484, )
app/logical/sources/strategies/pixiv.rb:216:in `illust_id'
app/logical/sources/strategies/pixiv.rb:124:in `normalizable_for_artist_finder?'
app/models/artist_url.rb:37:in `normalize'
app/models/artist.rb:152:in `find_all_by_url'
app/models/artist.rb:472:in `url_matches'
app/models/artist.rb:568:in `search'
app/controllers/artists_controller.rb:40:in `index'
```
It's possible it may be broken for other site links, but the above was just the first I came across.

I use this function a lot when creating new artists with my script to check for existing artists so that I don't create duplicate entries.  For now I'll remove stacc links from the URL search, and also see if any other site links trigger an error.

**Comment by BrokenEagle** [comment]
Actually, nevermind, I can't create artists either with stacc links.
```
Sources::Error exception raised
Couldn't get illust ID from URL (http://www.pixiv.net/stacc/aino3751484, )
app/logical/sources/strategies/pixiv.rb:216:in `illust_id'
app/logical/sources/strategies/pixiv.rb:124:in `normalizable_for_artist_finder?'
app/models/artist_url.rb:37:in `normalize'
app/models/artist_url.rb:109:in `normalize'
app/models/artist.rb:187:in `block (2 levels) in save_urls'
app/models/artist.rb:186:in `map'
app/models/artist.rb:186:in `block in save_urls'
app/models/artist.rb:184:in `save_urls'
app/controllers/artists_controller.rb:59:in `create'
```
Which pretty much does kill my workflow for creating artists, since most of them have Pixiv links.

**Comment by evazion** [comment]
c689a16 fixes the immediate issue of not being able to search or edit artist entries containing stacc links.

There's still an issue that the Pixiv source strategy raises an error if it can't find an illust id in the url (or if the api call fails due to a bad id). So if an artist entry contains a garbage Pixiv link (`http://www.pixiv.net/blah`), then editing it will still fail.

Pixiv should do the same thing as in #3852 and not error out if it can't make the api call.

**Comment by nonamethanks** [comment]
This seems to be a problem with posts too. Trying to add a pixiv fanbox source to https://danbooru.donmai.us/posts/3244117 returns 

```
Couldn't get illust ID from URL (https://www.pixiv.net/fanbox/creator/163536, )
app/logical/sources/strategies/pixiv.rb:216:in `illust_id'
app/models/post.rb:1688:in `parse_pixiv_id'
app/controllers/posts_controller.rb:52:in `update'
```
(The source is the artist's fanbox cover page)

**Comment by BrokenEagle** [comment]
As first discovered by @nonamethanks and confirmed by myself, Pixiv Fanbox links are also broke in the same fashion as the STACC links:
```
Sources::Error exception raised
Couldn't get illust ID from URL (http://www.pixiv.net/fanbox/creator/3113804, )
app/logical/sources/strategies/pixiv.rb:217:in `illust_id'
app/logical/sources/strategies/pixiv.rb:125:in `normalizable_for_artist_finder?'
app/models/artist_url.rb:37:in `normalize'
app/models/artist_url.rb:109:in `normalize'
app/models/artist.rb:187:in `block (2 levels) in save_urls'
app/models/artist.rb:186:in `map'
app/models/artist.rb:186:in `block in save_urls'
app/models/artist.rb:184:in `save_urls'
app/controllers/artists_controller.rb:64:in `update'
```
