### ISSUE TITLE
When browsing to recommended page, I get a "certificate has expired" error

### ISSUE THREAD

**Issue by mseymour** [r888888888/danbooru#3860]
When I go to https://danbooru.donmai.us/recommended_posts?context=user, I see the following error instead of the page:

````
SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
````

**Comment by mseymour** [comment]
Even though I did post this first, the issue has spread to the entire site, so I'm going to close this as a dupe of issue #3865.

**Comment by evazion** [comment]
Reopening because this case is still broken.

**Comment by r888888888** [comment]
Fixed.
