### ISSUE TITLE
Adding a source is broken on post editing if Danbooru can't trace an ID to it

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3861]
> CodeKyuubi said ([forum #1234](https://danbooru.donmai.us/forum_posts/150000)):
> Looks like you're no longer allowed to put a link in the source box after uploading from computer if Danbooru can't trace an image through it. 
> 
> https://i.imgur.com/Omj9njI.png

```
Couldn't get illust ID from URL (https://www.pixiv.net/fanbox/creator/554149/post/82555, )
app/logical/sources/strategies/pixiv.rb:216:in `illust_id'
app/models/post.rb:1688:in `parse_pixiv_id'
app/controllers/posts_controller.rb:52:in `update'
```

**Comment by evazion** [comment]
Fixed in 736c22c3ce3df03f53f0362db337a41bae6470f7.
