### ISSUE TITLE
"Danbooru's certificate has expired" on post pages

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3865]
Getting the following message when going to the ``/posts`` page:
```
ActionView::Template::Error exception raised
SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
app/logical/popular_search_service.rb:32:in `block in fetch_data'
app/logical/cache.rb:18:in `get'
app/logical/popular_search_service.rb:30:in `fetch_data'
app/logical/popular_search_service.rb:22:in `tags'
app/presenters/post_set_presenters/post.rb:38:in `popular_tags'
app/presenters/post_set_presenters/post.rb:30:in `related_tags'
app/presenters/post_set_presenters/post.rb:11:in `tag_set_presenter'
app/presenters/post_set_presenters/post.rb:75:in `tag_list_html'
app/views/posts/index.html.erb:12:in `_app_views_posts_index_html_erb___947622601242322325_47302437421240'
app/controllers/posts_controller.rb:17:in `index'
```
I'm not getting that when a tag search query is used or on an actual post, however on those pages I do get a notice up in the address bar that "Your connection to this site is not secure".  Also, I'm not getting that error message or warning on any of the other pages.  It seems to only be happening with the posts controller.

**Comment by evazion** [comment]
Looks like fetching popular tags for the sidebar on the frontpage is failing because the Let's Encrypt certificate for https://isshiki.donmai.us expired.
