### ISSUE TITLE
Add namespaces to all Javascript events

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3867]
This will facilitate additional flexibility in event handling for both Danbooru and userscripts.

Currently, only the presence of different event types is detectable, not whether any one particular function has been bound or not.  This makes it impossible to unbind those events without the use of the all-encompassing ``off()`` function which unbinds all events, potentially clobbering other's userscripts.  The same holds true for if Danbooru ever needs to rebind events.

However, if namespaces were used, then users would be free to only turn off only that event, while leaving all other events in-place.  Additionally, the presence of that namespace can also be used to detect whether that particular event was in place for a userscript to use.  An example would be checking that a particular click event has been added before clicking it with Javascript.

As far as I know this isn't possible with jQuery-UI events, but those already have detectable items that are queryable.  But for every other event, this should be possible.

**Comment by evazion** [comment]
Namespaced all events bound by Danbooru. For events bound by libraries (including Rails, jQuery UI, qTip2, and Hammer.js), namespacing is up to the library.
