### ISSUE TITLE
Add sta.sh strategy

### ISSUE THREAD

**Issue by lllusion3469** [r888888888/danbooru#3877]
There are currently [at least 5 pages](https://danbooru.donmai.us/posts?utf8=%E2%9C%93&tags=source%3Ahttp%3A%2F%2Fsta.sh&ms=1) of sta.sh posts on `danbooru.donmai.us`.

[Example](https://sta.sh/01gxn3r2dnp2), [danbooru](https://danbooru.donmai.us/posts/2733498)

Sta.sh
* is part of deviantart
* uses random-looking ids (case insensitive) as part of the url so you can only find them if the uploader posts a link elsewhere
* uses virtually the same page layout (even has the `<meta property="da:appurl">`)
* can be accessed using exactly the same api as DA

the only problems are:
* it doesn't seem to be possible to reconstruct the page url from the image url (even the [url](https://www.deviantart.com/artbookisland/art/tribute-by-SaekiShun-654463438) which [the api returns](https://www.deviantart.com/developers/console/deviation/deviation_single/bcc296bdf3b5e40636825a942a514816?url%3Adeviationid=B5B5DA48-BFA5-C98A-D61F-6C0F61A64E3A&da_version=&expand=&grant_type=authorization_code&endpoint=%2Fdeviation%2F%7Bdeviationid%7D) leads to a 404)
* the url to a picture and a [folder (NSFW)](https://sta.sh/2kahtwc1ogd) look the same (from what I've seen, the former starts with a `0` and the latter with a `2`, but I wouldn't rely on it)

**Comment by lllusion3469** [comment]
I hacked together an implementation on top of the deviantart strategy (still haven't bothered to actually learn any ruby):
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -49,8 +49,10 @@ module Sources
       PATH_PROFILE = %r{\Ahttps?://(www\.)?deviantart\.com/#{ARTIST}/?\z}i
       SUBDOMAIN_PROFILE = %r{\Ahttps?://#{ARTIST}\.deviantart\.com/?\z}i
 
+      STASH = %r{\Ahttps?://sta\.sh/(?<post_id>[0-9a-zA-Z]{12})}i
+
       def self.match?(*urls)
-        urls.compact.any? { |x| x.match?(/^https?:\/\/(?:.+?\.)?deviantart\.(?:com|net)/) }
+        urls.compact.any? { |x| x.match?(/^https?:\/\/(?:.+?\.)?deviantart\.(?:com|net)/) || x =~ STASH }
       end
 
       def site_name
@@ -58,7 +60,9 @@ module Sources
       end
 
       def canonical_url
-        if self.class.deviation_id_from_url(image_url).present? || page_url.blank?
+        if stash_page.present?
+          page_url
+        elsif self.class.deviation_id_from_url(image_url).present? || page_url.blank?
           image_url
         else
           page_url
@@ -87,6 +91,7 @@ module Sources
       end
 
       def page_url
+        return stash_page if stash_page.present?
         return "" if api_deviation.blank?
         api_deviation[:url]
       end
@@ -190,6 +195,14 @@ module Sources
         end
       end
 
+      def self.stash_id_from_url(url)
+        if url =~ STASH
+          $~[:post_id].downcase
+        else
+          nil
+        end
+      end
+
       def deviation_id
         self.class.deviation_id_from_url(url) || self.class.deviation_id_from_url(referer_url)
       end
@@ -199,8 +212,12 @@ module Sources
       end
 
       def page
-        return nil if deviation_id.blank?
-        deviation_url = "https://www.deviantart.com/deviation/#{deviation_id}"
+        if stash_id.blank?
+          return nil if deviation_id.blank?
+          deviation_url = "https://www.deviantart.com/deviation/#{deviation_id}"
+        else
+          deviation_url = stash_page
+        end
 
         options = Danbooru.config.httparty_options.deep_merge(
           format: :plain, 
@@ -263,7 +280,18 @@ module Sources
         api_client.download(uuid)
       end
       memoize :api_download
+      
+      def stash_id
+        [url, referer_url].map{ |x| self.class.stash_id_from_url(x) }.compact.first
+      end
+      memoize :stash_id
 
+      def stash_page
+        if stash_id.present?
+          "https://sta.sh/#{stash_id}"
+        end
+      end
+      memoize :stash_page
     end
   end
 end
```

**Comment by evazion** [comment]
Thanks for doing this research. Some more notes:

* I think the url starting with a `0` for single items and `2` for folders always holds true.

* There are a few stash-specific api endpoints: `/stash/{stackid}`, `/stash/{stackid}/contents`, `/stash/item/{itemid}`.

* The id in https://sta.sh/0wxs31o7nn2 is a base 36 id. This can be used as the `itemid` after converting to base 10: `/stash/item/3345216068411246`. If it's a folder, you can strip the `2` off and use it as the `stackid`.

* The docs for the `/stash/delta` endpoint say this:

> The Sta.sh data is organized into stacks and items. A stack contains either a list of children stacks or a single item, that is, a stack can't contain more than one item or a mix of stacks and items. Stacks can be moved into another stack or positioned within a parent. An item represents a Sta.sh submission and is always contained within some stack.

* The stash page has a `deviantART.pageData` javascript object with a few bits of information.

* There's an https://backend.deviantart.com/oembed?url=https://sta.sh/0wxs31o7nn2&format=json endpoint that gives some information. This seems to work on any deviantart page url.

* Image urls for sta.sh images are indistinguishable from image urls for regular deviantart.com images. So if all you have is the image url, and the page url is a 404, then I don't think you can tell whether it's a sta.sh post or a deleted deviantart.com post.

**Comment by evazion** [comment]
Added in 7d5d098.
