### ISSUE TITLE
'Related tags' not appearing automatically on uploads page

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3895]
https://danbooru.donmai.us/forum_topics/9127?page=253#forum_post_150304

**Comment by evazion** [comment]
The bug was that we were clicking the related tags button before the button was bound. It wasn't bound because 10ca4dd3ad13781c52e8cdc18bbb0370cef145a3 added an import statement that, as a side effect, changed the initialization order of the javascript modules. This caused related_tags.js to be initialized *after* uploads.js, not before.

It was pretty much an accident that this ever worked to begin with. JS modules need to be careful about relying on event handlers bound by other modules.

**Comment by evazion** [comment]
@r888888888 some people aren't adding artist tags on new uploads because of this, you might want to redeploy soon.

**Comment by r888888888** [comment]
This was deployed.
