### ISSUE TITLE
Filter user's favorites from Recommended Posts results

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3897]
Since it's based on a user's favorites, there should be no reason to show them the same thing they probably already know.

**Comment by r888888888** [comment]
It should be doing this already. Keep in mind it won't work on dupes or parent/child related posts that weren't favorited.

The implicit library does let you pass in an arbitrary set of posts to remove from the recommendations, but there would need to be some sort of secondary data store to keep track of these.

**Comment by BrokenEagle** [comment]
Yeah, after speaking with other users, it seems like it is affecting others as well to varying degrees. 
 @nonamethanks reported earlier that he was having favorites showing up, so I checked earlier and 1/30 were favorites, which was neither a parent or child.  Also, I have some CSS effects that gives my favorites a 0.5 opacity unless I'm hovering over them, so it's pretty easy to tell that they are indeed favorites.  

I just checked now, and 2/30 of mine are favorites, and @Unbreaky says that 24/30 of his are favorites.

**Comment by r888888888** [comment]
It might be the time delay? It won't filter out favorites that were made recently.

**Comment by nonamethanks** [comment]
That can't be, I've favorited https://danbooru.donmai.us/posts/3117256 on the day it was uploaded and https://danbooru.donmai.us/posts/2847383 back in 2017, and both show up in my recommended.

**Comment by evazion** [comment]
The majority of my recommendations are posts that I favorited a long time ago.

Would it be feasible to just periodically dump the full set of recommendations to some table in the database? Ideally you could see more than 30 recommendations at once, and you could do whatever filtering you like using normal tag searches (e.g. `recommended:evazion -user:evazion rating:safe`).

**Comment by BrokenEagle** [comment]
Yeah, same here.  The two favorites that do show up in the **Recommended Posts** were favorited months ago.

> Would it be feasible to just periodically dump the full set of recommendations to some table in the database? 

Could we implement this using favorite groups?  Just give everyone a N+1 favorite group (so 11 for Platinum+, 6 for Gold, 4 for Member) that is dedicated solely for this, and would be updated periodically by Danbooru itself.  In that way, it could be a lot like the [Curated](https://danbooru.donmai.us/pools/12514) pool.  

To make permissions checking easier, just block the deletion event and perhaps renaming the name of it, and allow everything else since it'll be updated by DanbooruBot (or whatever) periodically anyways.  

Also, to minimize the amount of overhead there would be to create such a favorite group for every member on this site, just have its creation tied to clicking that **Recommended Posts** link for the first time.  That way, only those users that are interested in that service will have a favorite group created for them.

**Comment by r888888888** [comment]
I fixed a bug in recommender that should resolve the favorites bug now. It'll take an hour for the cache to expire and renew.
