### ISSUE TITLE
Fuzzy matching doesn't work when the first letter is missing

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3898]
- First letter missing:
  - https://danbooru.donmai.us/tags/autocomplete.json?search%5Bname_matches%5D=ace_of_all_the_people_that_sank_their_money_into_the_fx 
  - 0 results
- Second letter missing:
  - https://danbooru.donmai.us/tags/autocomplete.json?search%5Bname_matches%5D=fce_of_all_the_people_that_sank_their_money_into_the_fx
  - 1 result

**Comment by r888888888** [comment]
This is intentional. IME misspellings of the first character aren't common, and help drastically narrow down the selection of results.

**Comment by BrokenEagle** [comment]
Well, that makes sense.  As long as it's intentional then.
