### ISSUE TITLE
Include datetime when populating Artist Commentary

### ISSUE THREAD

**Issue by john1980a** [r888888888/danbooru#3899]
When populating the Artist Commentary fields, also include the date and time of the source post.

The datetime is sometimes important to understanding the image or the rest of the commentary. Examples:
* Images around holidays, number pun days
* Deciding if a post should be included in "Hilarious in Hindsight"
* post 2083295.  The date is important for understanding the image is related to the Love Live movie that was released at the time.

Even when it's not critical, it's interesting to know when the artist originally posted the work as opposed to when it was uploaded to Danbooru.   Especially when the difference in time is large.

**Comment by BrokenEagle** [comment]
This would be a pretty intensive coding task for such a small gain, as every site is different and places the times of the posts in different places.

Instead, if the user feels like such information would be useful to the image, then it should be their responsibility to add this information themselves.  Just add something manually like the following to the tail end of the commentary.

```
[tn]
Image date: 2018-12-31
[/tn]
```

**Comment by john1980a** [comment]
* We wouldn't need to do every site. Just doing the top few sites, like Pixiv and Twitter, would cover many posts.
* Adding the date manually to one post doesn't take a lot of time.  Adding it across 1000s does. 
* If the source is deleted, then the datetime is lost. There are cases where we have the original commentary text, but can no longer get the datetime.
* A user adding commentary may not realize the datetime is important, especially if they don't know Japanese.  Another user may eventually come along who does realize this, but as more time passes the chances of the original source being deleted increases.

**Comment by john1980a** [comment]
I'm not sure how Danbooru gets the commentary text from different sites.

If it's JSON API's, there are fields:
* Pixiv - "created_time": "2013-09-15 04:06:54"
* Twitter - "created_at":"Thu Apr 06 15:24:15 +0000 2017"
* DeviantArt - "published_time": 1397059526

**Comment by evazion** [comment]
The general request here is to store the original upload date from Twitter / Pixiv etc. #4113 generalizes this idea.
