### ISSUE TITLE
"syntax error in tsquery" when accessing a certain artist

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3901]
While looping through the artist database I came across [this artist](https://danbooru.donmai.us/artists/151525), whose profile never loads and ends up in a 504 after a couple of minutes.
[The json](https://danbooru.donmai.us/artists/151525.json) shows a SQL syntax error.

```json
"message": "PG::SyntaxError: ERROR:  syntax error in tsquery: \"''\"\n: SELECT \"posts\".\"source\" FROM \"posts\" WHERE (posts.tag_index @@ to_tsquery('danbooru', E''''''))",
```

Not sure if there's others which return the same error.

**Comment by evazion** [comment]
The artist had a blank name. Blank artist names were fixed in 4b2dcca8a2 but this artist predated the fix.
