### ISSUE TITLE
Installation again

### ISSUE THREAD

**Issue by KarelWintersky** [r888888888/danbooru#3903]
Where i can find ACTUAL installation script or Docker image / docker compose script? 

```
# git clone https://github.com/r888888888/danboorus.git
Cloning into 'danboorus'...
remote: Counting objects: 56946, done.
remote: Total 56946 (delta 0), reused 0 (delta 0), pack-reused 56946
Receiving objects: 100% (56946/56946), 43.22 MiB | 8.35 MiB/s, done.
Resolving deltas: 100% (36902/36902), done.

# cd danboorus/
# docker-compose up

Creating network "danboorus_default" with the default driver
Pulling memcached (memcached:1.5-alpine)...
1.5-alpine: Pulling from library/memcached
4fe2ade4980c: Pull complete
7db529ff9ba7: Pull complete
032d0aca6e3e: Pull complete
4f13599c5a59: Pull complete
7fa96593f298: Pull complete
Digest: sha256:949dcc9ca9ab2c8e48a42f29990fb33f2a75ebe2d0310939a2c6451f3f5bd4b0
Status: Downloaded newer image for memcached:1.5-alpine
Building postgres
ERROR: Cannot locate specified Dockerfile: Dockerfile.postgres

```
WTF?
Where is this file?

**Comment by r888888888** [comment]
You're cloning DanbooruS, not Danbooru. DanbooruS hasn't been updated in awhile.

**Comment by KarelWintersky** [comment]
@r888888888 , Danbooru have NO docker file. And `INSTALL.debian` does not work. 

Install own danbooru - is it possible?

**Comment by r888888888** [comment]
So what is your goal with the Docker setup? Is it just for development or are you actually trying to launch this on production?

**Comment by KarelWintersky** [comment]
> So what is your goal with the Docker setup?

I tryed launch dannoorus for something! For testing.

>  are you actually trying to launch this on production?

I would like launch danbooru for 'production' on my home server: I have A LOT of images for my tabletop games and Danboooru engine is a **most effective** solution for storing images with tags.

Will be most effective solution, but I Can't launch it. 

Not under centos, not under ubuntu, not under debian 9.5.0, not with danboorus docker image :(((

PS sorrry for poor english

**Comment by r888888888** [comment]
Well then I do not recommend running Danbooru under Docker. Debugging will be much harder and performance (especially for Postgres) will be worse. It's only useful for development and there's a supplied docker compose config you can use for that. The only scenario where it'd be useful is a multi-server deployment.

I recommend a clean Debian or Ubuntu box and using the INSTALL.debian script as a guide.

**Comment by KarelWintersky** [comment]
> I recommend a clean Debian or Ubuntu box and using the INSTALL.debian script as a guide.

installation failed. 

You want complete log? Step by step ?

**Comment by KarelWintersky** [comment]
```
* Almost done! You are now ready to deploy Danbooru onto this server.
* Log into Github and fork https://github.com/r888888888/danbooru into
* your own repository. Clone your fork onto your local development
* machine and modify the following files:
*
*   config/deploy.rb (github repo url)
*   config/deploy/production.rb (servers and users)
*   config/unicorn/production.rb (users)
*   config/application.rb (time zone)
*
* On the remote server you will want to modify this file:
*
*   /var/www/danbooru2/shared/config/danbooru_local_config.rb
*

* Commit your changes and push them to your fork. You are now ready to
* deploy with the following command:
*
*   bundle exec capistrano production deploy
*
* You can also run a server locally without having to deal with deploys
* by running the following command:
*
*   bundle install
*   bundle exec rake db:create db:migrate
*   bundle exec rails server
*
* This will start a web process running on port 3000 that you can
* connect to. This is useful for development and testing purposes.
* If something breaks post about it on the Danbooru Github. Good luck!
```

`http://danbooru.towers.local/` gives me 
```
502 Bad Gateway
nginx/1.10.3
```
Really, `/var/www/danbooru2/current/public/` is empty.

**Comment by KarelWintersky** [comment]
`git clone https://github.com/r888888888/danbooru /var/www/danbooru2/current`
then `http://danbooru.towers.local/`

-> 
```

Something broke

Return to index

```

Also, 
```
root@danbooru:/var/www/danbooru2# bundle install
bash: bundle: command not found
root@danbooru:/var/www/danbooru2# gem install bundle
bash: gem: command not found
```

**Comment by r888888888** [comment]
You shouldn't clone into current. Capistrano is supposed to manage that.

It doesn't look like you ran a Capistrano deployment. These things are somewhat necessary for a production instance. If you're not expecting high traffic you can just run a dev instance instead.

Just clone the git repo into a directory somewhere, copy and update the config files as mentioned in the readme, and then run bin/rails server. The web process should be accessible on port 3000.
