### ISSUE TITLE
Should the site redirect a user to a "This post has been expunged" page when trying to access an expunged post?

### ISSUE THREAD

**Issue by crs00** [r888888888/danbooru#3908]
Trying to access an expunged post currently gives the following.
`ActiveRecord::RecordNotFound exception raised
Couldn't find Post with 'id'=xxxxxxx
app/controllers/posts_controller.rb:27:in `show'`
I think it should redirect to some sort of "This post has been expunged" page for clarification, as the current error page makes it look like there's a problem with the site instead of informing the user that the post has been expunged.

**Comment by evazion** [comment]
The trouble is that a post id is being missing doesn't necessarily mean the post was expunged. Missing ids are almost always caused by failed uploads. The post id counter is bumped every time someone tries to create a post, even if creating the post fails.

**Comment by crs00** [comment]
> The trouble is that a post id being missing doesn't necessarily mean the post was expunged. Missing ids are almost always caused by failed uploads. The post id counter is bumped every time someone tries to create a post, even if creating the post fails.

Then could we have one redirect page for expunged posts, and a different redirect page for missing posts?
