### ISSUE TITLE
Add option to load time/date approximation as exact time-date strings

### ISSUE THREAD

**Issue by crs00** [r888888888/danbooru#3916]
It would be a nice feature to have to be able to load time/date approximations present in post info, forum posts, the feedback page, DMails, etc. as exact time-date strings instead of loading as "over x years ago" or "about 10 minutes ago".
[It already loads like this on my phone for some reason, and no, responsive mode is not enabled.](https://cdn.discordapp.com/attachments/341289125233819650/492434245365792773/image0.png)

**Comment by evazion** [comment]
Timestamps are already formatted as exact times in most places. Switching everything to relative times ("X minutes ago") is a Danbooru EX / Danbooru Miscellanous Tweaks option.
