### ISSUE TITLE
Consider implementing twitter equivalent of "pixiv:" metatag

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3924]
With the rising prevalence of twitter as a source, having a metatag similar to pixiv's to search for twitter IDs would be pretty helpful for numerous reasons.

The main one would be allowing users to create their own userscripts to find unuploaded material, like the ones already existing for pixiv. It'd also be a much more reliable and faster way to verify if a tweet is already uploaded, as opposed to relying on IQDB, which is unfortunately prone to failures and not reliable in cases such as pictures with alpha transparency, animated videos and similar hard-to-index content.

Not sure how hard this would be, given that (if I understand it correctly) the pixiv ID metatag has its own SQL column, but I'm going to throw it here because this has been asked several times in the past, though not only for twitter but for other sites as well (mainly nicoseiga).

**Comment by crs00** [comment]
Would an :any metatag for tumblr be worth it?

**Comment by evazion** [comment]
Closing in favor of #4113. This generalizes this idea as described in my previous comment.
