### ISSUE TITLE
Paginator is sometimes broken for certain searches

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3925]
> MAGNUS-8M said ([forum #150841](https://danbooru.donmai.us/forum_posts/150841) & [forum #150845](https://danbooru.donmai.us/forum_posts/150845)):
> 
> Not sure if it's a known issue, or if there's a new version rolling out causing issue(or maybe just high traffic?), but sometimes a pool or a search-page will lose its page-numbers at the bottom of each page. Like at first it might have all the usual numbers, but at some point later, no matter what page I'm on, it will only show Page 1 and left-and-right arrows, but only the left-arrow works as a hyperlink. If I'm on Page 1 the number isn't a hyperlink obviously... if I'm on any other page then 1 is a hyperlink to page one...but it still acts like the current page or any other further-pages don't exist(so it just looks like < 1 > no matter how many pages there are). Of course I can manually edit the URL to go to each separate page, but it's getting a little annoying/cumbersome.
> 
> Last I tried I couldn't replicate it either, but I just tried it again and it gave me the one-page thing again.
> 
> Search is "super_crown -bowsette", without Gold Membership of course, so I can only do two searches. (As far as the search goes, I was just interested in any new characters aside from the usual Bowser I guess.)
> 
> Same search as (the redundant) "super_crown bowsette" works. Actually, using "bowser -super_crown" works. And still gives me Bowsette pictures.... figures.
> 
> But yeah at the moment, specifically using "-Bowsette super_crown" sometimes refuses to give me more than one page.
> 
> ....annnnd then I closed that tab, middle-clicked a random image to get a new-tab, searched for "super_crown -bowsette" and then it worked correctly. And another one that didn't.. huh. Just seems random.

I have confirmed that the above also holds true for Builder members, though it's easiest to trigger as a Member-level user or as Anonymous.

https://danbooru.donmai.us/posts?tags=-Bowsette+super_crown

![image](https://user-images.githubusercontent.com/21149935/46176859-a7f2e900-c265-11e8-9f14-fdb40baa496b.png)

The same issue also shows up if you manually apply the page numbers.

https://danbooru.donmai.us/posts?tags=-Bowsette+super_crown&page=5

![image](https://user-images.githubusercontent.com/21149935/46176811-79750e00-c265-11e8-9d9e-b4e9405734c3.png)

Even as Anonymous, it seems to only trigger about half the time, and when it doesn't trigger, it consistently doesn't trigger, and vice versa.  Also, when it does trigger as Anonymous, it also triggers as Builder.

**Comment by evazion** [comment]
https://hijiribe.donmai.us/counts/posts?tags=super_crown+-bowsette

When this was first reported, I checked Hijiribe and it returned a cached count of 12 for `super_crown -bowsette`. This was weird because a cached count of 12 is supposed to expire in 12 seconds, but instead it didn't expire for at least a day.

...actually, now that I look, I think it's because the cache `expiry` is never actually set:

https://github.com/r888888888/danbooru/blob/2cc4e35cc9e0dc9a71089ad7e74d91fbdb6a756c/app/models/post.rb#L1269-L1275

Not setting an expiration means post counts would be cached forever, or at least until the cache was full and Memcache purged the oldest entries.

**Comment by evazion** [comment]
The cache expiry formula might need some tuning, given that it hasn't actually been used in production before. For now I raised the minimum lifetime to 3 minutes.
