### ISSUE TITLE
Uploads not redirecting to the post page

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3929]
Most of my uploads today have something really weird going on.  Instead of redirecting to the post page, they redirect to the /uploads page with a blank uploads form instead of the uploads listing.  I did a packet capture for many of them, and instead of an HTTP 302 response that it's supposed to give to the POST request, it instead just gives an HTTP 200 response.

There's something also weird going on with my upload records.  It appears that the uploads aren't recording the post numbers, even though the posts are being created.

The following are my uploads from today:

https://danbooru.donmai.us/uploads?search[uploader_id]=23799

![image](https://user-images.githubusercontent.com/21149935/46187082-b1487980-c296-11e8-9323-2f8a3d506f06.png)

From the above, it looks like only one of the uploads completed.

However, the following are all of the uploads from today:

https://danbooru.donmai.us/posts?tags=id%3A3269165%2C3269155%2C3269142%2C3269135%2C3269129%2C3269126%2C3269117%2C3269113

![image](https://user-images.githubusercontent.com/21149935/46187238-7c88f200-c297-11e8-9fd0-f19372f99ba0.png)

So there's a discrepancy between the two.  The one upload that does appear to have worked, is the only upload today that I can remember redirecting correctly to the post page after the upload.

I used the **Post** bookmarklet for all of the uploads, and all of the uploads are from Pixiv.  The only difference for the one that "worked" is that it is a ``mode=manga`` type of post instead of a ``mode=medium`` type of post.

### Edit:

In case the above upload records get deleted, I downloaded the XML: [uploads.xml.txt](https://github.com/r888888888/danbooru/files/2426709/uploads.xml.txt).

**Comment by BrokenEagle** [comment]
I can confirm the above, as reported by Unbreakable.

When specifying the rating via the tag box, it responded with the blank uploads page.

- Network response: [upload_tag_rating.har.txt](https://github.com/r888888888/danbooru/files/2430233/upload_tag_rating.har.txt)

When specifying the rating via the radio button, it redirects as normally.  First to the numbered upload, and then which redirects to the numbered post.

- Network response: [upload_button_rating.har.txt](https://github.com/r888888888/danbooru/files/2430236/upload_button_rating.har.txt)

**Comment by deusexcalamus** [comment]
when I upload something using the rating:blah metatag, it gives me this instead of redirecting/not redirecting:

**Comment by evazion** [comment]
I think the cause was `rating:safe` not being recognized, but I'm not sure why it wasn't redirecting.
