### ISSUE TITLE
Can't remove children from a parent post through child: metatag

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3930]
Using "child:none" on any post with children displays the following error:
```ruby
app/models/post.rb:845:in `block in apply_post_metatags'
app/models/post.rb:813:in `each'
app/models/post.rb:813:in `apply_post_metatags'
app/controllers/posts_controller.rb:48:in `update'
```

And using the metatag "-child:<child_id>" has no effect.

There's no reason not to have these work, if the parent: equivalent works just fine.

**Comment by evazion** [comment]
2cc4e35 also allows adding/removing multiple child posts at once with e.g. `child:1..10` or `-child:1,2,3`. This supports the same range syntax as the `id:` metatag. You can add at most 10 children at once.
