### ISSUE TITLE
Add additional capabilities to the count posts endpoint

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3936]
Due to issue #3935, the timeout for the count mechanism, to include the ``/counts/posts`` endpoint, has been reduced to 1 second.  This could cause issues for one of my user scripts, CurrentUploads ([topic #15169](https://danbooru.donmai.us/forum_topics/15169)), which heavily relies on that endpoint, and uses anywhere from 2-4 tags, with 0-2 of them being metatags.  One of the tags is always a dummy tag, to get the latest count and avoid getting a cached result.

After speaking with @evazion on Discord, there should be a couple of parameters added to the count posts endpoint which allows a user to bypass those system mechanics.

- [ ] ``user_timeout`` - Would set the timeout to be the user's default timeout (12s Platinum, 6s Gold, 2s Member) instead of the system timeout of 1s.
- [ ] ``query_actual`` - Would avoid using cached results, negating the need for using dummy tags.

**Comment by r888888888** [comment]
The param for skipping the cache is called `skip_cache`.
