### ISSUE TITLE
Blank lines in tagbox if no tags from certain taggroups are present

### ISSUE THREAD

**Issue by crs00** [r888888888/danbooru#3937]
Noticed that there will be blank lines in the tagbox when editing a post's tags if no tags from a certain group are present.
EX: https://danbooru.donmai.us/posts/3273714 has no character tags, therefore, the line where character tags would go is empty in the tagbox.
EX 2: https://danbooru.donmai.us/posts/3272714 has no meta tags, therefore, the line where meta tags would go is empty in the tagbox.
Is this intentional behavior, or unintentional?

**Comment by evazion** [comment]
This was a bug.
