### ISSUE TITLE
Batch bookmarklet sometimes selects the first image for Tumblr

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3944]
Brought up by @Unbreaky on Discord. It seems like when using the Batch bookmarklet, even though it pulls up all the images, sometimes it will only bring up the first image, even if you select the second or other images.

https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Fnatsuki-teru.tumblr.com%2Fpost%2F178728919271

However, that is not always the case, as seen with the following.

https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Fnatsuki-teru.tumblr.com%2Fpost%2F177190312386

One thing I noted about the above links, is that the first contains an image of the ``_640`` size, whereas the second one doesn't. I'm wondering if that is what's causing the issue, as the **640** size was causing issues several months ago with the bookmarklets (issue #3732).

**Comment by evazion** [comment]
Fixed in 184a5ebf3e7b0791acc9b87b6eac6c74776289e0.
