### ISSUE TITLE
http://danbooru.donmai.us redirects to Safebooru.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3945]
ref: https://danbooru.donmai.us/forum_topics/15631.

http://danbooru.donmai.us redirects to https://safebooru.donmai.us instead of https://danbooru.donmai.us.

If you've visited https://danbooru.donmai.us previously, this won't happen because HSTS will redirect you from http://danbooru.donmai.us to https://danbooru.donmai.us at the browser level. This will happen though if you open http://danbooru.donmai.us in an incognito window.

**Comment by r888888888** [comment]
That is really strange.

I don't even think HSTS is enabled because I'm not sending a `Strict-Transport-Security` header in Nginx. The redirect block for port 80 looks straightforward:

```
server {
  listen 80;
  server_name safebooru.donmai.us danbooru.donmai.us shima.donmai.us sonohara.donmai.us;
  return 301 https://$server_name$request_uri;
}
```

**Comment by r888888888** [comment]
Ok, I should have been using `$host` instead of `$server_name`. Problem is fixed now.
