### ISSUE TITLE
A/D shortcuts should skip status:any and collection pools when series pools are available

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3949]
Example: https://danbooru.donmai.us/posts/2722864
Basically the status:any pool interferes with the A/D keys. The site should prioritize series (purple) pools when these shortcuts are called. In case of multiple present, it should pick the first one, but when there's only one it should always have precedence over collection (blue) pools, which are ordered by theme rather than plot/actual order.

**Comment by evazion** [comment]
This would mean you can't go to the front page and click a post and start browsing with A/D. As soon as you hit something in a series pool you would start navigating the pool instead.

**Comment by nonamethanks** [comment]
How about having some shortcut to switch the "active" pool then? Or any other way to select one of them as a priority. AFAIK status:any always ends up being the top pool, so it basically makes A/D useless for any other use.

**Comment by BrokenEagle** [comment]
Would it be possible to have another pair of keys that cycled through the active pools?    Best would be if the active pool could be changed without reloading the page.
