### ISSUE TITLE
Bookmarklets for Moebooru sometimes don't show a preview image

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3953]
- Post bookmarklet:
![image](https://user-images.githubusercontent.com/21149935/46691266-53cafb80-cbb9-11e8-9d6d-a6053de2f3d3.png)
- Batch bookmarklet:
![image](https://user-images.githubusercontent.com/21149935/46691319-7c52f580-cbb9-11e8-9096-3de63b69c0f6.png)

The image links look to be okay, but the problem might be that external links to those images will get denied sometimes.  They might need to be proxied like the Pixiv images.

**Comment by evazion** [comment]
This was fixed in 7eee77d520438922c4831b681f3bef195d1bcc9e. Moebooru sometimes redirects hotlinked image urls to the html page.
