### ISSUE TITLE
Many images of various sizes broken

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3954]
> Unbreakable said:
> 
> I'm seeing a bunch of samples being broken (or just loading really slow) but full sizes working, like post #2986891 and post #2972399 for example. Anyone else?

> fossilnix said:
> 
> Same here, I'm also seeing a bunch of posts that are stored on raikou2 where the sample doesn't load and the full size is 404. It doesn't seem to be for any entire range, though, just a lot every here and there.

Not sure if this is related to issue #3610 or not, but ever since the migration, it has been noticed that there a multitude of images missing on Danbooru.  There doesn't seem to be any discernible pattern either, with most of the affected posts being random.  It also doesn't affect just one size but any/all of the sizes.

I've started the same scanning as I did in #3610, but that can take several weeks do do all 3M+ images.  Is there another quicker way to fix the errant missing images in the meantime?

**Comment by evazion** [comment]
Flash thumbnails are broken too. https://raikou4.donmai.us/images/download-preview.png is missing.

**Comment by r888888888** [comment]
`download-preview` has been restored.

**Comment by iamtakingiteasy** [comment]
More examples:

https://danbooru.donmai.us/posts/2980040
https://danbooru.donmai.us/posts/2962708 (this one is deleted, but i understand that should not affect storage)
https://danbooru.donmai.us/posts/2908984 
https://danbooru.donmai.us/posts/2907850 (deleted)
https://danbooru.donmai.us/posts/2906953
https://danbooru.donmai.us/posts/2905179
https://danbooru.donmai.us/posts/2898562
https://danbooru.donmai.us/posts/2881398
https://danbooru.donmai.us/posts/2840953
https://danbooru.donmai.us/posts/2812221
https://danbooru.donmai.us/posts/2805894

All seems to be hosted on raikou2, but not all raikou2 links are broken

**Comment by r888888888** [comment]
@iamtakingiteasy's list has been redistributed. It may take some time for the cloudflare cache to expire.

**Comment by deusexcalamus** [comment]
> 
> 
> @iamtakingiteasy's list has been redistributed. It may take some time for the cloudflare cache to expire.

Can you take a look at the posts in https://danbooru.donmai.us/pools/84 and https://danbooru.donmai.us/pools/279 ?

**Comment by iamtakingiteasy** [comment]
@r888888888 

I wonder, how long could it take? It has been over 24h now and none of examples above is up yet.

**Comment by iamtakingiteasy** [comment]
Also, someone on forums did research and determined which ranges are most suseptible to such outages: https://danbooru.donmai.us/forum_posts/new?post_id=151278

**Comment by Inverness** [comment]
I'm still seeing broken images everywhere. Is there an ETA on when this will be fixed.

If this is a cloudfare caching issue, couldn't they be contacted directly to fix the issue?

**Comment by r888888888** [comment]
Sorry this took so long. I've redistributed all the files in the pools 84 and 279. About 200 images in total were distributed.

**Comment by deusexcalamus** [comment]
> 
> 
> Sorry this took so long. I've redistributed all the files in the pools 84 and 279. About 200 images in total were distributed.

https://danbooru.donmai.us/posts/2937390 is still broken, perhaps others.

**Comment by iamtakingiteasy** [comment]
Images from my post list above are still not available.
> https://danbooru.donmai.us/posts/2937390 is still broken, perhaps others.
This one however showing already

**Comment by r888888888** [comment]
These load for me now.

**Comment by iamtakingiteasy** [comment]
I confirm, they do now.

**Comment by deusexcalamus** [comment]
https://danbooru.donmai.us/posts/2813493?pool_id=84 this still doesn't work, as well as this 
https://danbooru.donmai.us/posts/2631912?pool_id=84

**Comment by deusexcalamus** [comment]
> 
> 
> I've seen a great number of images that are still broken. There is no way I could provide a full list.
> 
> I think an automated method will be needed to actually fix this problem, whatever it is.

Yep, can confirm, Invy. There's lots of pics that are still broken.

**Comment by BrokenEagle** [comment]
Based on the indications above that it seems to only affect the 2.8-3.0M range, I changed my image scanner to skip ahead to 2.8M and have started collecting from there.  I'll post what I have tomorrow, once it's had a full day to process, but thus far it scanned 27K+ images, and out of all of those, 18K+ images are bad.  Or to give more precise numbers, 69.1% of the images scanned so far are bad.

**Comment by BrokenEagle** [comment]
Range scanned: 2800001..2856306
Preview missing: 0
Sample missing: 39319
Fullsize missing: 12403
JSON Data: [checkallimagejson.1.txt](https://github.com/r888888888/danbooru/files/2493177/checkallimagejson.1.txt)

The JSON has data keys "previewsize", "samplesize", and "fullsize", for the various sizes. Each key under those is the post number, and the value is the HTTP error code (pretty much all 404).

One thing to note, is that I realized I forgot to not check the sample size when the post doesn't have a large image (``has_large == False``), so some of the posts under the "samplesize" key may not need to be fixed.  I'll correct this mistake for future scans though.

**Comment by r888888888** [comment]
It looks like raikou2 ran out of disk space which explains a lot of this. I'll take 2.8m-3.0m out and serve those from the app servers instead.

**Comment by deusexcalamus** [comment]
> 
> 
> It looks like raikou2 ran out of disk space which explains a lot of this. I'll take 2.8m-3.0m out and serve those from the app servers instead.

How long will that take to take effect?

**Comment by deusexcalamus** [comment]
https://danbooru.donmai.us/posts/2947762 this image and https://danbooru.donmai.us/posts/2891573 this one plus its child are broken for me.

**Comment by BrokenEagle** [comment]
Ranges scanned: 2856307..2945221
Preview missing: 0
Sample missing: 39915
Fullsize missing: 53329
JSON Data: [checkallimagejson.2.txt](https://github.com/r888888888/danbooru/files/2497068/checkallimagejson.2.txt)

**Comment by deusexcalamus** [comment]
These images are starting to show back up.

**Comment by BrokenEagle** [comment]
Ranges scanned: 2945222..3022037
Preview missing: 0
Sample missing: 13345
Fullsize missing: 21657
JSON Data: [checkallimagejson.3.txt](https://github.com/r888888888/danbooru/files/2498312/checkallimagejson.3.txt)

**Comment by BrokenEagle** [comment]
Ranges scanned: 3022037..3065090
Preview missing:  0
Sample missing: 0
Fullsize missing: 0

So it looks like the 2.8-3.0M had the issues. Still, I'm going to restart scanning where I left off from the beginning again, just to make sure there aren't other ranges being so affected.

**Comment by r888888888** [comment]
The old servers were running out of space, which precipitated the move to dedicated asset servers. This was before my decision to bite the bullet and switch data centers. They were also specialized hardware with the storage being 4x1TB SSD raids which meant they could easily serve the thumbnails without causing iowait problems.

The new servers are more commodity hardware, and although they have 4TB of storage it's spinning disk, so they weren't suitable for serving the thumbnails.

Anyway, the images from the 2.8m-3.0m range should be downloaded on all the app servers now.
