### ISSUE TITLE
Sometimes pool versions aren't being merged creating superfluous versions

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3958]
Discovered this recently with the creation of [pool #14380](https://danbooru.donmai.us/pools/14380) (**warning NSFW**).

https://danbooru.donmai.us/pool_versions?search%5Bpool_id%5D=14380

The following are the order of actions that I undertook, all within a couple of minutes of each other.

1. Discretely created a new pool, i.e. not using the ``newpool:`` metatag.
2. Added the posts to the pool using the tag script function from the post index page and the ``pool:`` metatag.  The posts were selected rapidly, so there was about several queued network requests for some of the time.
3. Reordered the pool as some posts were out of order due to being processed at different times.

**Comment by evazion** [comment]
Same bug as #3587. As explained in https://github.com/r888888888/danbooru/issues/3587#issuecomment-377356037, the way that post/pool archives finds the previous version is broken. It misses versions when two version have the same timestamp.

**Comment by r888888888** [comment]
The id sorting has been fixed in the archives app.
