### ISSUE TITLE
Testbooru is down

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3959]
> CodeKyuubi said ([forum #151253](https://danbooru.donmai.us/forum_posts/151253)):
> 
> Any replacement for testbooru?

I've heard various rumors, and I'm not sure whether it's down or gone.  If it's the latter, is there a plan to eventually replace it with the same setup as before (e.g. non-minimized/compiled Javascript)?

**Comment by r888888888** [comment]
The directory shuffling was causing the deploys to fail. Testbooru should be up now.
