### ISSUE TITLE
Danbooru will sometimes upload the wrong image despite the image preview

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3968]
> BrokenEagle98 said ([forum #151956](https://danbooru.donmai.us/forum_posts/151956)):
> 
> [post #3305708](https://danbooru.donmai.us/posts/3305708)
> 
> https://twitter.com/Mityubi/status/849630665603665920
> https://pbs.twimg.com/media/C8p-gPhVoAMZupS.png:orig
> 
> As noted on that post, Danbooru somehow uploaded the wrong image. I don't know how. The image I wanted to upload is the Katyusha image from the above post.

The following is the series of steps that went to create the above error.

1. Navigated directly from a Pixiv post ([pixiv #56735489](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=56735489)) to a Twitter post ([twitter #849630665603665920](https://twitter.com/Mityubi/status/849630665603665920)) using Javascript
2. Used the post bookmarklet on the Twitter post
3. Noticed that the image preview was wrong, as it was using the image from the prior Pixiv page
4. Opened a fresh tab and navigated to the same Twitter post
5. Used the post bookmarklet again on that Twitter post
6. Completed the upload
7. Noticed that the wrong image was uploaded

I'm not sure what is going on, but I believe that for some reason the post bookmarklet decided to use the **Ref** field instead of the **URL** field.  Then, when I tried the post bookmarklet again, it saw that the source field was the same as the prior upload record, and so used that image instead.

The following are the upload records links and the XML (for if the records get deleted before this gets handled).

https://danbooru.donmai.us/uploads.xml?search[id]=2098881,2098883

```xml
<uploads type="array">
<upload>
<id type="integer">2098883</id>
<source>https://twitter.com/Mityubi/status/849630665603665920</source>
<file-path nil="true" />
<content-type nil="true" />
<rating>q</rating>
<uploader-id type="integer">23799</uploader-id>
<tag-string>tagme</tag-string>
<status>preprocessed</status>
<backtrace nil="true" />
<post-id type="integer" nil="true" />
<md5-confirmation nil="true" />
<created-at type="dateTime">2018-11-02T18:25:49Z</created-at>
<updated-at type="dateTime">2018-11-02T18:25:58Z</updated-at>
<server>oogaki</server>
<parent-id type="integer" nil="true" />
<md5>2efa89db126ad2a6cc8d0b422f58f56c</md5>
<file-ext>png</file-ext>
<file-size type="integer">853786</file-size>
<image-width type="integer">914</image-width>
<image-height type="integer">1000</image-height>
<artist-commentary-desc nil="true" />
<artist-commentary-title nil="true" />
<include-artist-commentary type="boolean" nil="true" />
<context nil="true" />
<referer-url />
<uploader-name>BrokenEagle98</uploader-name>
</upload>
<upload>
<id type="integer">2098881</id>
<source>https://twitter.com/Mityubi/status/849630665603665920</source>
<file-path nil="true" />
<content-type nil="true" />
<rating>s</rating>
<uploader-id type="integer">23799</uploader-id>
<tag-string>
mityubi girls_und_panzer 1girl solo katyusha looking_away alternate_hairstyle hair_bobbles short_twintails fang upper_body short_hair bangs frown open_mouth blush commentary_request artist_name snowflakes v-shaped_eyebrows eyebrows_visible_through_hair crossed_arms pravda_school_uniform no_jacket school_uniform shirt red_shirt turtleneck rating:safe cropped_torso
</tag-string>
<status>completed</status>
<backtrace nil="true" />
<post-id type="integer">3305708</post-id>
<md5-confirmation nil="true" />
<created-at type="dateTime">2018-11-02T18:25:19Z</created-at>
<updated-at type="dateTime">2018-11-02T18:27:18Z</updated-at>
<server>saitou</server>
<parent-id type="integer" nil="true" />
<md5>1d0af4684e2a8d9ca2274d3407c5b713</md5>
<file-ext>png</file-ext>
<file-size type="integer">511085</file-size>
<image-width type="integer">1400</image-width>
<image-height type="integer">800</image-height>
<artist-commentary-desc>
よこみちカチューシャ様 "#ガルパン版深夜のお絵描き60分一本勝負":[https://twitter.com/hashtag/ガルパン版深夜のお絵描き60分一本勝負] "#ガルパン版深夜のお絵描き60分一本勝負_20170405":[https://twitter.com/hashtag/ガルパン版深夜のお絵描き60分一本勝負_20170405]
</artist-commentary-desc>
<artist-commentary-title />
<include-artist-commentary type="boolean">true</include-artist-commentary>
<context nil="true" />
<referer-url />
<uploader-name>BrokenEagle98</uploader-name>
</upload>
</uploads>
```

**Comment by evazion** [comment]
This is effectively what was uploaded:

* https://danbooru.donmai.us/uploads/new?url=https://twitter.com/Mityubi/status/849630665603665920&ref=https://www.pixiv.net/member_illust.php%3Fmode%3Dmedium%26illust_id%3D56735489

Danbooru chooses the wrong strategy here. When detecting sites we check both the url and the referer, and since Pixiv happens to be checked before Twitter, the Pixiv strategy is chosen.

I think for most sites, we don't need to check the referer when detecting the strategy. The only exception is http://sta.sh (since sta.sh images are hosted on deviantart.net).

**Comment by BrokenEagle** [comment]
What about instances where somebody opens up an image on a site, and the uses the **Post** bookmarklet from the image link? I've done that myself a number of times.

Wouldn't a better strategy be to check the **URL** field first, and if that fails then check the **Ref** field?

**Comment by evazion** [comment]
If you use the bookmarklet on, say, a twimg.net image, then we know it's a Twitter image just from that, no matter what the referer is.

This is true for everything except for Sta.sh images. Sta.sh and DeviantArt images are both hosted on deviantart.net, so that's the only case where we have to fallback to the referer to tell which strategy to use.

**Comment by BrokenEagle** [comment]
I was thinking more that it is impossible to determine the post ID links for many sites just from the image link. In those cases, using the **Ref** field would still allow users to use the **Post** bookmarklet from the image link while still retrieving the picture/artist information using the post ID link.

**Comment by evazion** [comment]
The referer is still passed in and used to find the post ID. It's just not used in the initial "which strategy should we use to handle this url?" check.

**Comment by BrokenEagle** [comment]
Ah okay.  Looks like I misunderstood.
