### ISSUE TITLE
Mod Queue: mangled HTML

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3972]
The div.mod-queue-preview items are a little... off:

     <div id="post-3307173" class="post mod-queue-preview [&quot;post-preview&quot;, &quot;post-status-pending&quot;]" {&quot;data-id&quot;=&gt;3307173, &quot;data-has-sound&quot;=&gt;false, &quot;data-tags&quot;=&gt;&quot;commentary_request enemy_lifebuoy_(kantai_collection) enjaku_izuku highres holding_stick jumping kantai_collection las_vegas no_humans selfie_stick welcome_to_fabulous_las_vegas_sign&quot;, &quot;data-pools&quot;=&gt;&quot;&quot;, &quot;data-approver-id&quot;=&gt;nil, &quot;data-rating&quot;=&gt;&quot;s&quot;, &quot;data-width&quot;=&gt;1297, &quot;data-height&quot;=&gt;1920, &quot;data-flags&quot;=&gt;&quot;pending&quot;, &quot;data-parent-id&quot;=&gt;nil, &quot;data-has-children&quot;=&gt;false, &quot;data-score&quot;=&gt;2, &quot;data-views&quot;=&gt;nil, &quot;data-fav-count&quot;=&gt;4, &quot;data-pixiv-id&quot;=&gt;nil, &quot;data-file-ext&quot;=&gt;&quot;jpg&quot;, &quot;data-source&quot;=&gt;&quot;https://twitter.com/enjk_idk/status/1058034088655769600&quot;, &quot;data-top-tagger&quot;=&gt;516394, &quot;data-uploader-id&quot;=&gt;516394, &quot;data-normalized-source&quot;=&gt;&quot;https://twitter.com/enjk_idk/status/1058034088655769600&quot;, &quot;data-is-favorited&quot;=&gt;false, &quot;data-uploader&quot;=&gt;&quot;Jnglmpera&quot;, &quot;data-md5&quot;=&gt;&quot;863a77bb5998b52e97a7b209c148f5ef&quot;, &quot;data-file-url&quot;=&gt;&quot;https://danbooru.donmai.us/data/863a77bb5998b52e97a7b209c148f5ef.jpg&quot;, &quot;data-large-file-url&quot;=&gt;&quot;https://danbooru.donmai.us/data/sample/sample-863a77bb5998b52e97a7b209c148f5ef.jpg&quot;, &quot;data-preview-file-url&quot;=&gt;&quot;https://raikou4.donmai.us/preview/86/3a/863a77bb5998b52e97a7b209c148f5ef.jpg&quot;}>
  <aside>

**Comment by evazion** [comment]
Fixed in 1d3eb584c7d38956c22b1f1e47ba4469d6fdcc99. 00f36605c49d6f2853a96e9111376f6d23b36ef0 fixes a typo that broke the modqueue page (cc @r888888888).
