### ISSUE TITLE
DText external links appear broken

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3976]
I've recently noticed that the icon for external DText links is not longer appearing correctly.

![image](https://user-images.githubusercontent.com/21149935/48104212-4b310980-e1e7-11e8-8261-23599c3caf2a.png)
https://danbooru.donmai.us/wiki_pages/43047#dtext-general-links

Confirmed this issue with Unbreakable (@Unbreaky) on Discord. @evazion brought up that it's because the site was switched to the Pro version of Font Awesome 5, however the DText external links are still with the Free version of Font Awesome 5.

**Comment by r888888888** [comment]
So the pro version is restricted by domain and I had only enabled it for danbooru.donmai.us which might explain this. I've enabled it for safebooru and the individual servers also but it might take a few minutes to propogate.

**Comment by evazion** [comment]
External links had their font-family hardcoded to use the free version instead of the pro version.
