### ISSUE TITLE
Font Awesome icons broken for safebooru.donmai.us

### ISSUE THREAD

**Issue by DoomTay** [r888888888/danbooru#3977]
Font Awesome icons are invisible, due to the related CSS not appearing

The biggest result of this is that next/prev buttons are invisible. On mobile, they're unclickable.

**Comment by r888888888** [comment]
What URL are you seeing this behavior?

**Comment by DoomTay** [comment]
Literally everywhere under safebooru.donmai.us (I only just now realized that only that's affected). Here's the front page.

![screenshot_2018-11-06 - danbooru](https://user-images.githubusercontent.com/9124594/48105261-c0f79e00-e204-11e8-9e44-91b151f5653b.png)

**Comment by DoomTay** [comment]
Aaaand now it's fixed. Thanks.
