### ISSUE TITLE
Convert more columns to arrays

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3987]
As with #3979, here are some other columns that should be stored as arrays instead of strings:

* `artists.other_names`
* `artist_versions.other_names`
* `artist_versions.url_string`
* `wiki_pages.other_names`
* `wiki_page_versions.other_names`
* `tag_implications.descendant_names`

**Comment by BrokenEagle** [comment]
What about many of the post columns?

- ``posts.tag_string``
- ``posts.tag_string_general``
- ....all other post tag strings...
If the above were done, then all of the **tag_count** columns could be removed and replaced with a function that just returns the size of the array.

- ``posts.pool_string``
Would allow the creation of a **pool_count** variable, as well as ``pools:>=4``.

- ``posts.fav_string``
The **fav_count** column could be removed and replaced with a function.

**Comment by evazion** [comment]
Those definitely should be arrays too. Those will be more involved though, so I plan on tackling them last.

I think it would technically be possible to drop the pool_string and fav_string columns entirely. This would save a lot of space in the posts table, but it would involve some other tradeoffs.
