### ISSUE TITLE
ordpool:<name> fails for large pools

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3988]
Example: https://danbooru.donmai.us/posts?tags=ordpool:Disgustingly_Adorable. The query we're generating here is way too large.

See https://gist.github.com/cpjolicoeur/3590737 for discussion of other ways to order rows in a custom order. The `array_position` technique is probably the best option, but it requires Postgres 9.5+. @r888888888 Which version of Postgres is Danbooru running in production?

**Comment by r888888888** [comment]
Production is running on Postgres 10 now.
