### ISSUE TITLE
Search functions broken on pools gallery

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3992]
From [topic #15738](/forum_topics/15738):

> freecom said:
> 
> so, this is kind of an oddly specific issue and i don't know if it's widespread, but i noticed the "Googling yourself" pool (pool #14334) doesn't show up when you try to search for it (searching part of the pool's name doesn't bring it up either). one would have to do something like pool:Googling_yourself to get in and browse it.

> BrokenEagle98 said:
> 
> It seems like the search functions underneath the /pools/gallery listing are broken.
> 
> Compare:
> 
> - Doesn't work: https://danbooru.donmai.us/pools/gallery?search%5Bname_matches%5D=Googling_yourself
> - Works: https://danbooru.donmai.us/pools?search%5Bname_matches%5D=Googling_yourself
> 
> So for now, navigate to the pool listing (Listing in the pool submenu) and use that search form instead.

**Comment by evazion** [comment]
The gallery listing is hardcoded to show only series pools. I guess it makes sense to show only series pools by default, but they shouldn't be filtered out of searches.

**Comment by evazion** [comment]
29fdfc4 addresses this by still showing only series pools by default, when not doing a search, but showing both series + collections when you do a search.

On second thought, though, I think it'd better to not filter out collection pools. It's not very obvious that the gallery page is filtering out collection pools by default.

**Comment by BrokenEagle** [comment]
Having series show by default makes some sense, when the first post for most collection pools really aren't representative of the pool as a whole. Perhaps mentioning this on the page somewhere as a hint would be useful to users though. Another alternative would be to have the **Category** default to **Series** on the gallery page, which would then *hopefully* be clear enough.
