### ISSUE TITLE
Prevent users from seeing banned artist posts

### ISSUE THREAD

**Issue by ampersham** [r888888888/danbooru#3993]
I think it could be viewed as an incentive to getting gold/platinum in order to see banned artist posts. My view is that only builders should be able to see that content or—more preferred—only the uploader of such a post + moderation.

**Comment by BrokenEagle** [comment]
For the easy option of just limiting it by level, I'd say Builder+, unless we never want those posts to tag gardened again.

A potential alternative would be giving the moderators the ability to give out temporary access tokens to users that would let those users garden one particular banned artist.  So for that limited duration, the users would be able to see the images, but afterward they would be closed off as before. This would require much more coding, but it wouldn't leave all of the work to the already overworked moderators.

**Comment by chinatsu-chan** [comment]
> 
> 
> For the easy option of just limiting it by level, I'd say Builder+, unless we never want those posts to tag gardened again.
> 
> A potential alternative would be giving the moderators the ability to give out temporary access tokens to users that would let those users garden one particular banned artist. So for that limited duration, the users would be able to see the images, but afterward they would be closed off as before. This would require much more coding, but it wouldn't leave all of the work to the already overworked moderators.

It does sound troubling to add the functionality, I'm not sure the right suggestion. If I get the time I hope to learn the languages DB uses to contribute to these issues.
