### ISSUE TITLE
Add additional order by metatags for posts

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4004]
Brought up in [topic #15787](https://danbooru.donmai.us/forum_topics/15787) with a modicum of support.

Mentioned in the topic is order post by comment count. After thinking about it a bit, a couple other order metatags that might prove interesting would be order by pool count and order by note count. Others that might prove both interesting and useful would be flag count, appeal count, and approval count. A stretch goal would be tagger count (i.e. how many users have contributed to the tags on a post), however since that involves the post versions table, that may not be very resource friendly.

So all told:

- ``order:comment_count``
- ``order:pool_count``
- ``order:note_count``
- ``order:flag_count``
- ``order:appeal_count``
- ``order:approval_count``
- ``order:tagger_count``

I'm not sure the reverse order would be interesting/useful for any of the above orderings though.

**Comment by Type-kun** [comment]
>A stretch goal would be tagger count (i.e. how many users have contributed to the tags on a post), however since that involves the post versions table, that may not be very resource friendly.

Honestly, none of these are resource friendly either since it involves running count(*)/group by post_id queries against another table. That was the reason such metatags were rejected back in the days, iirc. Though all of those tables should already have index on post_id, so it'll be index-only as opposed to full-scan; that's as fast as such a query can get, short of denormalizing or caching the results for a while.

**Comment by evazion** [comment]
They're slow in general, but they should be feasible for smaller searches. I tested it on my dev instance:

```ruby
[7] pry(main)> Post.tag_match("love_live! order:comments").paginate(1).explain
(1643.9ms)  SELECT COUNT(*) FROM (SELECT posts.*, COUNT(comments.id) AS comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = TRUE)  AS deleted_comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = FALSE) AS active_comment_count FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY "posts"."id") posts WHERE (posts.tag_index @@ to_tsquery('danbooru', E'(''love_live!'')'))

Post Load (3547.3ms)  SELECT  "posts".* FROM (SELECT posts.*, COUNT(comments.id) AS comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = TRUE)  AS deleted_comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = FALSE) AS active_comment_count FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY "posts"."id") posts WHERE (posts.tag_index @@ to_tsquery('danbooru', E'(''love_live!'')')) ORDER BY "posts"."comment_count" DESC, "posts"."id" DESC LIMIT $1 OFFSET $2  [["LIMIT", 20], ["OFFSET", 0]]
(5211.9ms) => EXPLAIN for: SELECT  "posts".* FROM (SELECT posts.*, COUNT(comments.id) AS comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = TRUE)  AS deleted_comment_count, COUNT(comments.id) FILTER (WHERE comments.is_deleted = FALSE) AS active_comment_count FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY "posts"."id") posts WHERE (posts.tag_index @@ to_tsquery('danbooru', E'(''love_live!'')')) ORDER BY "posts"."comment_count" DESC, "posts"."id" DESC LIMIT $1 OFFSET $2 [["LIMIT", 20], ["OFFSET", 0]]

                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=198420.69..198420.74 rows=20 width=1229)
   ->  Sort  (cost=198420.69..198477.72 rows=22809 width=1229)
         Sort Key: (count(comments.id)) DESC, posts.id DESC
         ->  GroupAggregate  (cost=197072.46..197585.67 rows=22809 width=1210)
               Group Key: posts.id
               ->  Sort  (cost=197072.46..197129.49 rows=22809 width=1210)
                     Sort Key: posts.id
                     ->  Hash Right Join  (cost=77120.60..183335.90 rows=22809 width=1210)
                           Hash Cond: (comments.post_id = posts.id)
                           ->  Seq Scan on comments  (cost=0.00..81802.13 rows=1542313 width=9)
                           ->  Hash  (cost=73404.49..73404.49 rows=22809 width=1205)
                                 ->  Bitmap Heap Scan on posts  (cost=232.77..73404.49 rows=22809 width=1205)
                                       Recheck Cond: (tag_index @@ '''love_live!'''::tsquery)
                                       ->  Bitmap Index Scan on index_posts_on_tags_index  (cost=0.00..227.07 rows=22809 width=0)
                                             Index Cond: (tag_index @@ '''love_live!'''::tsquery)
(15 rows)
```

A potential improvement here would be to use materialized views to cache the counts. This way the counts could be indexed without having to maintain a bunch of denormalized columns in the posts table.
