### ISSUE TITLE
Bulk revert tool seems broken

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#4026]
https://danbooru.donmai.us/moderator/bulk_revert/new
The preview after pressing "test" always shows the same (very early) versions of posts, regardless of what you input. I wasn't exactly keen on finding out whether just the preview is broken or it would actually revert every change on the site.

**Comment by evazion** [comment]
I don't know if this is the cause, but I do know that bulk revert depends on BigQuery and that the post versions export in BigQuery has some data quality issues. I've found some cases where the post_versions_flat_part table is missing rows and other cases where it contains duplicate rows.

Honestly I think using BigQuery here is probably slower than just doing the query directly on the post archives database.

**Comment by evazion** [comment]
I removed the bulk revert system in favor of the mass undo system added in #4178. Mass undo is simpler and should be sufficient for most cases.
