### ISSUE TITLE
The Related Tag JSON endpoint is returning the wrong information

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4035]
I just noticed this recently when looking into using the **related_tag** endpoint.  For the **other_wikis** field, instead of returning the list of tags and their categories in array form like it does for all of the other tags, it instead returns the wiki entries.

https://danbooru.donmai.us/related_tag.json?query=girls_und_panzer&category=

```json
{
  "query": "girls_und_panzer",
  "category": "",
  "tags": [
    ["girls_und_panzer",3],
    ["nishizumi_miho",4],
    ["ooarai_school_uniform",0],
    ["darjeeling",4],
    ["nishizumi_maho",4],
    ["anchovy",4],
    ["itsumi_erika",4],
    ["katyusha",4],
    ["akiyama_yukari",4],
    ["emblem",0],
    ["tank",0],
    ["military",0],
    ["military_vehicle",0],
    ["military_uniform",0],
    ["black_neckwear",0],
    ["uniform",0],
    ["motor_vehicle",0],
    ["miniskirt",0],
    ["bangs",0],
    ["dress_shirt",0],
    ["ground_vehicle",0],
    ["pleated_skirt",0],
    ["brown_eyes",0],
    ["standing",0],
    ["long_sleeves",0]
  ],
  "wiki_page_tags": [
    ["saitaniya_ryouichi",1],
    ["shimada_fumikane",1],
    ["girls_und_panzer_gekitou!_maginot-sen_desu!!",3],
    ["girls_und_panzer_ribbon_no_musha",3],
    ["girls_und_panzer_phase_erika",3]
  ],
  "other_wikis": [
    {
      "id": 93250,
      "created_at": "2017-12-21T03:05:48.359Z",
      "updated_at": "2018-11-29T08:23:30.849Z",
      "title": "list_of_girls_und_panzer_characters",
      "body": "A VERY LONG WIKI ENTRY (NOT INCLUDED)",
      "creator_id": 23799,
      "is_locked": false,
      "updater_id": 23799,
      "other_names": [],
      "is_deleted": false,
      "creator_name": "BrokenEagle98",
      "category_name": 0
    }
  ]
}
```

So as of right now, anybody that wants to use that endpoint will be forced to parse each "other wiki" body plus do a separate lookup on the categories for all of the tags it finds.  It would be much preferable though if it worked like it used to and the server did this processing, since it has all the information it needs readily available.

**Comment by evazion** [comment]
The output will look like this:

![image](https://user-images.githubusercontent.com/8430473/50789100-e6466e00-1280-11e9-993b-b380b0e372f7.png)
