### ISSUE TITLE
Include initials for translated tags

### ISSUE THREAD

**Issue by ampersham** [r888888888/danbooru#4037]
If you type `snk` it completes to shingeki_no_kyojin. On many sites people will tag there works with snk and other initials, so the tag translation should consider these initials tags as well.

**Comment by evazion** [comment]
I think doing this automatically would be too error-prone. Simple tags like `hat` or `bow` could be misinterpreted as abbreviations for random obscure copyright tags. Better to add them manually for copyrights that need them.
