### ISSUE TITLE
Attempting to create an IP-ban bans the creator

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#4038]
OOZ662 tried to IP ban someone and got banned instead.  This has happened to myself and at least one other user in the past.

**Comment by evazion** [comment]
`belongs_to_creator` has a line that overwrites the `ip_addr` field if it exists. This is meant for tables like comments that have an `ip_addr` field instead of `creator_ip_addr`, but it does the wrong thing for ip bans.
