### ISSUE TITLE
Add disapproval index improvements

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4053]
> Lacrimos said ([forum#1234](https://danbooru.donmai.us/forum_posts/154208)): 
> 
> https://danbooru.donmai.us/moderator/post/disapprovals
> Can we add the following options to this:
> 
> - Make it possible to search by time spans and that you can look for the latest actions on page 1.
> - Make do search for "No interest", "Poor Quality" etc. only
> 
> E: May I ask how this list is ordered btw? The post IDs on the left are random. That's not really helpful tbh. You should be able to order the posts by ID.

- Add search orders
  - Post ID
- Add search options
  - Disapproval type
  - Creator
- Add search inputs to disapprovals page
  - By post ID
  - By disapproval type
  - By date range
  - By creator

I imagine that the search input for the date range might be the most involved item unless there's something ready to go that Rails has, so if it does get added, perhaps that search input could be added onto other endpoints?

Also, for the index display, put a [code]>>>[/code] next to some of the items with links to a search by that item.

- Post
- Creator

**Comment by evazion** [comment]
Added these options:

![image](https://user-images.githubusercontent.com/8430473/62406356-6a8b7600-b570-11e9-97b0-f08bd13b2c0e.png)

Searching by dates wasn't added. Well, technically it's possible with `search[created_at]`, but for the UI we'd need a datepicker widget, and dealing with that is outside the scope of this issue.
