### ISSUE TITLE
Exceptions when uploading from Nicoseiga Manga

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4060]
> NNescio said ([forum #154511](https://danbooru.donmai.us/forum_posts/154511)):
> 
> the bookmarklet still fails with the following error message:

```
ActionView::Template::Error exception raised

nico seiga api call failed (code=404, body=<?xml version="1.0" encoding="UTF-8"?> <response />)

    app/logical/nico_seiga_api_client.rb:37:in `illust_xml'
    app/logical/nico_seiga_api_client.rb:16:in `user_id'
    app/logical/nico_seiga_api_client.rb:43:in `artist_xml'
    app/logical/nico_seiga_api_client.rb:28:in `moniker'
    app/logical/sources/strategies/nico_seiga.rb:86:in `artist_name'
    app/views/sources/_info.html.erb:12:in `_app_views_sources__info_html_erb___2028538793142371862_47066943791040'
    app/views/uploads/new.html.erb:16:in `_app_views_uploads_new_html_erb__1726287990514805882_47066967622720'
    app/controllers/uploads_controller.rb:12:in `new'
```

> Pasting the source in manually still works, but once uploaded it will then throw up the following error whenever the tags are edited:
>
> ``nico seiga api call failed (code=404, body= )``
> It's a 404 error, so I think Danbooru is parsing it as a normal 'illustrations' page and requesting the wrong (and nonexistent) page from Nicoseiga. In a related manner, the automated direct source URL -> HTML conversion will also point to a nonexistent 'im' page (format: seiga.nicovideo.jp/seiga/im[NUMBER STRING]), as though it's a Nico Nico illustration.
> 
> Modifying the source post-upload as per 'standard' practice to the appropriate HTML manga page (format: seiga.nicovideo.jp/watch/mg[NUMBER STRING]) will cause another api call error:
>
> ``nico seiga api call failed (code=400, body= 画像IDが入力されていません )
A 400 (Bad Request) error, with an error message of "No image ID specified."``
>
> The above can be seen in action in [post #3409370](https://danbooru.donmai.us/posts/3409370).

> Continued in [forum #1154582234](https://danbooru.donmai.us/forum_posts/154582):
> 
> Is it feasible to add some sort of exception in the code to avoid the API errors though? Like, say, don't call the Nicoseiga API if the source is a manga page? (i.e. in the format "seiga.nicovideo.jp/watch/mg[MANGA ID]") Basically treat the subdirectory like a non-nicoseiga website that Danbooru doesn't have any special support for.
> 
> Likewise if the image is retrievable from a lohas.nicoseiga.jp/priv/[ALPHANUMERIC]/[NUMERIC]/[IMAGE ID] url, could the bookmarklet just forge ahead with the upload preview and ignore the 404 error from the Nicoseiga API call?
> 
> I mean, it's definitely isn't good practice, but it would seem that if the image is retrievable but the API throws up an error, that means it's not an illustration page and shouldn't be treated as one. (so all the other fields can be left blank)
> 
> Basically I'm fine with needing to manually query Nicoseiga for the source, and to swap out the source url post-upload to point to the HTML manga page. It would basically be like uploading from a non-supported website (like from an artist blog or a third party repository). For Nicoseiga though, currently Danbooru's (partial) support seems to assume everything is an Illustration, so it works at cross purposes when trying to upload something (from Nicoseiga) that is not hosted as an Illustration, causing some problems. (e.g. can't use bookmarlet for previewing uploads, unresolvable API error messages)

**Comment by r888888888** [comment]
Some notes for future reference:

https://gist.github.com/7cc/c608fe778defd0357d9d1b75d1956816
http://seiga.nicovideo.jp/api/theme/data?theme_id=316708 might be the source to get the images.
