### ISSUE TITLE
Related tag results off for some tags

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4063]
I noticed this first with the defunct **splatoon** tag which seems to exist on all related Splatoon tags to include **iida_(splatoon)** and even **splatoon_(series)** to name a few.
![image](https://user-images.githubusercontent.com/21149935/52761031-a2a0fb80-2fc6-11e9-921b-bae9cede1356.png)

The issue also shows up in the post index when searching for one of those tags.
![image](https://user-images.githubusercontent.com/21149935/52761066-c9f7c880-2fc6-11e9-9f35-5ee55bb9f08b.png)

The related tag calculations for the **splatoon_(series)** tag are all integers, when they should be floats.
https://danbooru.donmai.us/tags/1500438.xml

So perhaps that and other tags aren't being updated.

Another example, **bird_focus**:

https://danbooru.donmai.us/tags/1510680.xml

The post count for that is 576, which is over 300 so it should be calculated by Reportbooru and have Float values but it has integers still.

A final example is **hip_focus**:

https://danbooru.donmai.us/tags/1509969.xml

The post count for that is 14540, however there is nothing in the related tags field at all.

**Comment by r888888888** [comment]
The postgres connection had failed. I'll add the same retry logic the export service has.
