### ISSUE TITLE
Creating a "group" artist entry not possible unless name is lowercase/without spaces

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#4067]
If user adds an entry into Artist entry -> Group, the name becomes selectable & editable.  

However, if this Group Name is entered as anything except "all lower case / without spaces" (underscore/hyphens are ok) on Artist entry, attempting to click this link takes them again to "Edit artist" page (for Group), which cannot be saved.

**Comment by Kikimaru** [comment]
Screenshot: https://imgur.com/5hzR0VQ

**Comment by BrokenEagle** [comment]
Yeah, group names should have to follow the same rules as artist names (i.e. tagname validation) since they can be created as artist entries, i.e. no spaces, printable ASCII only, and normalized to lowercase.
