### ISSUE TITLE
DeviantArt non-downloadable posts broken

### ISSUE THREAD

**Issue by lllusion3469** [r888888888/danbooru#4069]
Example: https://www.deviantart.com/citizenfresh/art/Hverarond-14-the-beauty-of-the-earth-789295466

The image url is a 404

Related to the hack from #3997 (described in #3994) which modifies the preview url to return the original image instead:
https://github.com/r888888888/danbooru/blob/e8c3d92696654c8f0e2afe917a74c24df9255080/app/logical/sources/strategies/deviant_art.rb#L95

Apparently deviantart changed their preview urls, they now look like this:
`https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4deb0f1a-cdef-444e-b194-c8d6b3f7e933/dd1xca2-7f835e62-6fd3-4b99-92c7-2bfd4e1b296f.jpg/v1/fill/w_1280,h_854,q_70,strp/hverarond_14_the_beauty_of_the_earth_by_citizenfresh_dd1xca2-fullview.jpg?token=$TOKEN`

(token removed, even though it doesn't seem to be identifiable or private in any way)

The token is needed but even when preserving it the original modification still shows a 401.

What still seems to work for now is this url:
`https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/4deb0f1a-cdef-444e-b194-c8d6b3f7e933/dd1xca2-7f835e62-6fd3-4b99-92c7-2bfd4e1b296f.jpg`

obtained by replacing the `gsub` call above with this:
```rb
src = src.gsub(%r!(/f/.+?/.+?)/v1/(?:fit|fill)/.*!, '/intermediary\1')
```
i.e. removing everything from `/v1/` onwards (as we did before) and then placing a `/intermediary` before `/f/`

Who knows how long this is going to last, but the method is kind of questionable anyways.

Update: `/intermediary` apparently stopped working (for new uploads)
Update2: even though it stopped working, there's still another way to get a (at least slightly) higher quality image: https://github.com/Kent-Lee/deviantart-scraper/commit/b59effd70e8e06d3fb1f60e7fd97b6efdf026b3c

**Comment by r888888888** [comment]
I'm a little confused why we're using the `image_url` as the `canonical_url` for DeviantArt posts. Is it to facilitate source searches? Seems like saving the `/deviation/\d+` url is cleaner.

**Comment by evazion** [comment]
It's to try to preserve more information. If the image url contains the deviation id (which is usually the case for old image urls, but not always), then the page url can be derived from it (see `Post#normalized_source`). If all you have is the page url though, it's not possible to derive the image url.

The other reason is so that the artist finder still works on posts that have been deleted from DeviantArt (see [bad_deviantart_id](https://danbooru.donmai.us/posts?tags=bad_deviantart_id)). If we save an url that contains the artist name, then the artist finder can use that instead of relying on an api call (which will fail on deleted or private posts).

**Comment by lllusion3469** [comment]
If you were willing to, you could still use the method described above for old posts.

One way to test if it still works is this: https://github.com/mikf/gallery-dl/commit/9587aea98f65bd2e0f02f9697e6a5d03c73d635a (credit @mikf)

id=790677560 does seem to be the last one that works:
for the next applicable one (790677571), it doesn't work anymore.

**Comment by r888888888** [comment]
Some updates in 8a16e089d2ca46e28c3a8deb80d891ffafe459f7

**Comment by evazion** [comment]
This requires more investigation. For samples it's possible to increase the `/v1/fill/w_NNN,h_NNN` params to grab a larger image:

* Sample: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ab917938-d8c1-4b58-933d-0d38c390461f/ddd6ytj-64b9d9ef-6529-4b40-8b3b-5bceb408bb58.jpg/v1/fill/w_779,h_1026,q_70,strp/summer_musashi_by_chubymi_ddd6ytj-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjEwNiIsInBhdGgiOiJcL2ZcL2FiOTE3OTM4LWQ4YzEtNGI1OC05MzNkLTBkMzhjMzkwNDYxZlwvZGRkNnl0ai02NGI5ZDllZi02NTI5LTRiNDAtOGIzYi01YmNlYjQwOGJiNTguanBnIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.1OhpJJtLKk1dUsLCLUcjn4CzvUuCrYsijh6uF4O7VcU
* Full: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ab917938-d8c1-4b58-933d-0d38c390461f/ddd6ytj-64b9d9ef-6529-4b40-8b3b-5bceb408bb58.jpg/v1/fill/w_1600,h_2106,q_75,strp/summer_musashi_by_chubymi_ddd6ytj-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjEwNiIsInBhdGgiOiJcL2ZcL2FiOTE3OTM4LWQ4YzEtNGI1OC05MzNkLTBkMzhjMzkwNDYxZlwvZGRkNnl0ai02NGI5ZDllZi02NTI5LTRiNDAtOGIzYi01YmNlYjQwOGJiNTguanBnIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.1OhpJJtLKk1dUsLCLUcjn4CzvUuCrYsijh6uF4O7VcU

It's not possible to increase beyond 1600x2016. Note that on the DeviantArt page (http://fav.me/ddd6ytj) the file is listed as 2000x2632, 1.9 MB.
