### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by jafetma357** [r888888888/danbooru#4070]
I get an error code on Danbooru after like 20 pages in but there's probably at least 700+ pages available to look through. Error is below.

The database timed out running your query.
Running Danbooru (c051103d35c4836586dc98e9efeb9bf5970dee07) – Rules – Contact – Keyboard shortcuts available

**Comment by jafetma357** [comment]
Please help.

I get an error code on Danbooru after like 20 pages in but there's probably at least 700+ pages available to look through. Error is below.

The database timed out running your query.
Running Danbooru (c051103) – Rules – Contact – Keyboard shortcuts available

**Comment by BrokenEagle** [comment]
It would help to know what search you are running.

Also, Member-level users have a timeout of only 3 seconds, which can cause the above error in multiple places. Limiting the scope of the search can help, such as adding the ``limit:`` metatags along with one of the scope limiting metatags, such as ``age:``, ``date:``, and ``id:``. See [Help:Cheatsheet](https://danbooru.donmai.us/wiki_pages/43049#dtext-n2-2) for more information.

**Comment by jafetma357** [comment]
What do you mean what search? Here's the link.

https://danbooru.donmai.us/posts?page=27&tags=akemi_homura

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BrokenEagle** [comment]
Yeah, that's what I meant. That's a post search.

As I brought up in the prior post, certain searches can timeout in certain places, especially when you're a Member-level user. You can use the metatags that I mentioned in order to reduce the chance of this happening. Either that, or you can upgrade your account.

**Comment by BrokenEagle** [comment]
> I see how do that? Could you give me an example? Like let's say using dragon Ball z.

### Result limited:

- Search examples:
    - **dragon_ball_z limit:10**
    - **dragon_ball_z limit:20**

### Scope limited:

- Search examples:
   - **dragonball_z age:1mo..2mo**
   - **dragonball_z date:2019-01-01..2019-02-01**
   - **dragonball_z id:3430000..3440000**

### Both:

- Search examples:
   - **dragonball_z age:1mo..2mo limit:10**
   - **dragonball_z date:2019-01-01..2019-02-01 limit:10**
   - **dragonball_z id:3430000..3440000 limit:10**

Check out the [cheatsheet](https://danbooru.donmai.us/wiki_pages/43049) for more information.

> How much is it for the upgrade?

$20 for Gold. $40 for platinum.

https://danbooru.donmai.us/user_upgrade/new

**Comment by jafetma357** [comment]
Ah I see, so using the link I sent earlier. If I got stuck on page 28 for example. What should I enter on search bar to view pages 20-30, ect?

________________________________

**Comment by BrokenEagle** [comment]
Find the ID of the last post on the page. Let's say it's 3014424. Try out various ID ranges/limits until you get something that works.

- **akemi_homura id:..3014423 limit:20**
- **akemi_homura id:3000000..3014423 limit:10**
- etc. etc.

**Comment by jafetma357** [comment]
Thanks, I got it figured out now. I'm doing the limit method, works like a charm.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
