### ISSUE TITLE
Artist entries without creator_id can't be edited

### ISSUE THREAD

**Issue by tsudoko** [r888888888/danbooru#4071]
Example: https://danbooru.donmai.us/artists/4692.json
When I try to add an URL, I get this error: ![image](https://user-images.githubusercontent.com/2314894/55271698-e3b84b00-52a8-11e9-8bd2-29e989b79465.png)
I get a similar error when I try update the artist via the API: `{"errors":{"creator":["must exist"]}}` (HTTP 422)

**Comment by Kikimaru** [comment]
Similar error arising when someone has auto-created a wiki entry.

**Comment by r888888888** [comment]
For artists I've assigned all the blank creator ones to DanbooruBot. I don't see any for wiki pages.

**Comment by evazion** [comment]
Fixing the blank creator ids fixed it.
