### ISSUE TITLE
Requested resource not found error in Jobs.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#4078]
Heya, I'm having a small issue after updating everything to the latest commit.

`Requested resource not found /var/www/danbooru2/releases/20190419213005/app/logical/automod/update_dynamo_db_job.rb:90:in `perform' `

Checking in the database to see what post it pointed to it seems to be a post that does exist so I'm unsure what resource it's looking for.

**Comment by r888888888** [comment]
You can just disable this by shortcircuiting the perform method.
