### ISSUE TITLE
Broken BUR causing multiple daily rejection messages

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4081]
The last several days, there have been phantom postings in the first topic with no apparent source of what's causing it.

https://danbooru.donmai.us/forum_topics/1

There was the 5 day warning 7 days ago, and then for the last few days it's been giving the same rejection warning everyday.

It probably has something to do with the following BUR...

https://danbooru.donmai.us/bulk_update_requests/1953

...though I don't know why it's not able to complete the rejection process.

Also, it's weird because I wasn't able to find the BUR forum post anywhere on the forum, and the user that created it doesn't have any created forum posts around the time period that the BUR was created.

- https://danbooru.donmai.us/users/516394
- https://danbooru.donmai.us/forum_posts?search%5Bcreator_id%5D=516394

**Comment by r888888888** [comment]
I've manually rejected the BUR.

**Comment by BrokenEagle** [comment]
@r888888888 There is another request, this time an alias request, that is causing daily rejection messages.

https://danbooru.donmai.us/forum_topics/16052
https://danbooru.donmai.us/tag_aliases/15840
