### ISSUE TITLE
Backlogged post versions

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4083]
Something weird is going on with post versions. They've been backlogged for 5-10 minutes for the past day or so. At the same time, [post #253193](https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=253193) is constantly gaining duplicate post versions, over 400 since yesterday. Note that the timestamps are wrong, they're all set to 2019-05-06 04:33, but the post is still gaining new versions.

**Comment by r888888888** [comment]
The queue was backed up. I ran vacuum analyze on the archive database, seems to have helped.
