### ISSUE TITLE
Improvements: Replacing JQuery and JQuery-UI

### ISSUE THREAD

**Issue by DonaldTsang** [r888888888/danbooru#4084]
There are many alternatives out there that can replace JQuery by being more "lightweight"
- https://github.com/madrobby/zepto (most common JQuery alternative)
- https://github.com/kenwheeler/cash (another JQuery-esque library)
- https://github.com/franciscop/umbrella and https://github.com/dojo/dojo

Also http://youmightnotneedjquery.com/ would be a good note on miscellaneous functions 

While we are at it, maybe Danbooru can get a face-lift from replacing JQuery-UI
- https://github.com/pure-css/pure (4KB gzipped, made by Yahoo)
- https://github.com/milligram/milligram (2 KB gzipped)

Also http://www.creativeweblogix.com/blog/12-lightweight-css-frameworks has good metrics on which libraries are lightweight

**Comment by r888888888** [comment]
We use jQuery and jQuery plugins pretty heavily, so there needs to be a better reason than "it's possible" to switch it out. If size is the concern, the scripts are cached and given that this is an image site a few extra dozen kilobytes shouldn't be a major concern.

It would be great to swap out jQuery UI, but it's used heavily in the notes system and dialog modals.

**Comment by DonaldTsang** [comment]
@r888888888 I might need to read in on the parts which uses jQuery, and see if it can directly use Zepto or Cash without needing to change the jQuery scripts.
Are all the places that uses JQuery in https://github.com/r888888888/danbooru/tree/master/app/javascript/src/javascripts only or are there jQuery in the erb files?

**Comment by r888888888** [comment]
You could search for `$(` to see places where it's used.

**Comment by evazion** [comment]
Reducing dependence on jQuery UI would be beneficial, since it's not well-maintained any more, but eliminating jQuery entirely would be high effort / low reward.

The best way to approach this would be to focus on replacing one widget at a time. Some things though, like autocomplete and notes, have very complicated behavior and would be a lot of work to replace.

**Comment by DonaldTsang** [comment]
@evazion agreed, JQuery UI should be removed gradually through testing.
JQuery itself can be replaced with Zepto which is somewhat compatible I think, that would be a start.
