### ISSUE TITLE
Installation for low-maintenance "personal booru"?

### ISSUE THREAD

**Issue by GlassedSilver** [r888888888/danbooru#4085]
Hello fellow booru aficionados!

(sorry for the lengthy intro, skip past the fold if you feel like it. I added section markers for easy reference. :) )

First of all I want to apologize, because I'm not bringing in a lot of experience with PostgreSQL nor Ruby or anything else. A long time ago I got an introduction to MySQL, however through WAMP/XAMP and the bits of PHP etc won't help me here either. I'm new to server application deployments and lengthy install scripts, so please bear with me and excuse me for needing the helping hand possibly a little more than the devs that mingle around here.
I plan to deploy danbooru on my own personal server, I'll certainly try to give back to development once I figured everything out and come up with my own ideas, but for today's install I have a rather "selfish" goal...

---

**What is this set up for?** (section 1)
Deploying a local danbooru for safekeeping and storing associated metadata like tags, artists etc... reliably, independent of which platform I'm browsing from within my own local network. MAYBE I would occasionally open up the server to outside access, but not sure yet. If it adds much complexity to the setup, I'll skip on that and figure it out later. I know how to setup firewall exceptions.

(1b)
If I could use IQDB with this VM as well, that'd be nice... Basically a quick means of checking if I already have an image stored in my local booru. :) (maybe also to add another source later on to check against)

**Who am I?** (2)
Just a college student with hobbyist terminal experience and the like. Not afraid of it, but when I see 800 lines of a sample config file I'll be "that guy" to kindly request assistance.

**Production/staging/dev?** (3)
Well... you tell me! I do certainly want reliability and don't necessarily want this instance to be bleeding edge and want to deal with maintenance as little as possible. It's going to function as "image manager on steroids" mostly for my own use and maybe a second client connecting if someone comes over to my place. Sounds like production to me, but I saw dev recommended for easier deployment? I'm a bit lost at this point.

**What OS am I deploying to?** (4)
Ubuntu Server using Ext4. But I'm totally ready to switch to whatever else. I only went with Ubuntu because I know their repos are pretty up to date and its a trusted server distro. This is a vanilla VM under unRAID. (Qemu)

(4b)
If possible I'd love to store the actual mass of data (so the pictures themselves) in a custom location. That's going to be a network share. Since the VM uses bridged networking it'll be speedy enough. The database itself should be within the VM.

**Extra** (5)
Will need the database exposed to my LAN, because I'll be using a program to save images to the booru through it.
Updates for dependencies or the database should be rather easy if possible. :)

---

(6)
Sorry for this selfish request. I swear I invested hours into trying to make this work, but I assume I need to install various things before even going for the INSTALL script. I saw it echoing several errors however it marched through... Kinda makes me ponder... How can it claim to be ready for deployment using bundler and the (lengthy) deployment config file if there have been errors?

Also, my setup has PostgreSQL 10 installed. If I really need version 9, I think I didn't see it available on the Ubuntu repo. Guess if 9 is really needed I'll add the official repo and install from there, however if someone can verify I might as well try with 10 I'd fancy trying that first.

Thank you so much for whoever is willing to hold my hand here for a day and make said day for me.

**Comment by r888888888** [comment]
There are honestly too many services involved at this point to make it easy to set up a local installation. The `INSTALL.debian` script is a good start. You may also want to check out the `config/docker/compose.yml` which is used to set up the basic services needed to run CI. The `config/docker/danbooru-base` script is the most up-to-date thing needed to set up a machine since we need to run it all the time for CI.

You can see that you'll need Redis, the Archives service, and appropriate Amazon AWS and Google Cloud Platform accounts.

**Comment by GlassedSilver** [comment]
First of all thank you so much for taking the time to help me out, it's greatly appreciated!

> There are honestly too many services involved at this point to make it easy to set up a local installation.
Hmm, how many of those are crucial though? For example, my use case hardly needs stuff like number outsourced crunching and you yourself write that mock services can be used. Now I understand they don't replace the functionality and merely fill a gap to make the core run at all, but seems good enough for me?

Pardon my complete ignorance, but I don't think a use-case like mine needs pool versions, for example?

Other features I **believe** aren't required. (please correct me if I'm wrong or if it seems like I'm underestimating great utility):
IQDB (if I understand this right, this would like my hosted images to making them searchable with IQDB (publicly hosted), right? I would however love to run a local version of IQDB to verify something's in my database already. If this bit isn't needed for it, I'm happy enough. :)
Bulk revert - sounds like fixing grand scale erroneous edits being made easier. If I don't do a lot of mass editing I should be fine?

Reportbooru - if I understand this right, isn't crucial, but nice-to-have and can be set up later on still and locally, independent of other services not under my control, right? (my main goal is to have the booru be independent of other services. I don't mind one-off tasks, but keeping it up and running "for a damn long time" should work without dependencies. :)

The wording is a bit unclear to me here:

> Reportbooru also runs daemon processes that listen on Amazon SQS for jobs.
Is Amazon SQS optional or required and if so for all of Reportbooru's features?

> The `INSTALL.debian` script is a good start.
Hmm, well that's how I started and why I faced some errors. I ran the script multiple times after, I guess I might just start fresh and ignore all errors as long as the script itself says I'm ready, I should be, right? e.g. I didn't have PostgreSQL setup. It was installed, but the initial configuration was missing and some dev tools were missing too, so that returned some errors.

I should have screencapped what I found, but at this point I might just wipe my VM's virtual drive and start anew.

Any distro you'd recommend?

> You may also want to check out the `config/docker/compose.yml` which is used to set up the basic services needed to run CI. The `config/docker/danbooru-base` script is the most up-to-date thing needed to set up a machine since we need to run it all the time for CI.

Maybe it's my lack of sleep, but help me out here: what does CI stand for? :P

> 
> You can see that you'll need Redis, the Archives service, and appropriate Amazon AWS and Google Cloud Platform accounts.

Are third-party hosted (Google and Amazon) dependencies really REQUIRED? As in, I know this may sound far-fetched, but please bear with me: If Amazon decided tomorrow to shut down AWS for something "better" (but breaking backwards compatibility), would my local booru become a digital paperweight? (I know you'd probably be all over it and fix it soon, but the main point here is: how independent is a local danbooru once it's set up and running if we assume I'm not interested in the obvious external dependencies?


Sorry for the very long text again, I just wanna make sure we're on the same page here and I understand you correctly and vice versa. :)

Again thank you so much for the entire project and for taking the time. ^3^

**Comment by GlassedSilver** [comment]
Alright so I'm following INSTALL.deb line by line and executing the commands manually to easily spot and fix errors along the way, so far I made it all the way to line 105.

Line 106 is where the trouble begins: (I am in the correct directory, I just truncated it)

`$ sudo -u danbooru bash -l -c "rbenv install $RUBY_VERSION"
[sudo] password for xyz: 
ruby-build: definition not found: 2.5.1

The following versions contain `2.5.1' in the name:
  rbx-2.5.1

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build.`

Funnily enough, I think Ubuntu Server 18.04 (which is what I'm using for my danbooru VM, I since started from scratch) already came with Ruby installed:

`$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`
