### ISSUE TITLE
Usernames with consecutive spaces broken in DM form

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#4087]
Sending DMs to users with consecutive spaces in their name is partly broken ([topic #16114](https://danbooru.donmai.us/forum_topics/16114)). When trying to send a message to such a user via their profile, consecutive spaces are compressed and only a single one is used in the To form field. Sending the message to the incorrect username then fails.

Manually adding as many spaces as necessary will allow the message to be sent.

The user’s name in their profile is also shown with compressed spaces, so maybe the userid-to-string function is bugged.

Previous issue with spaces in usernames for DMs: #762

**Comment by BrokenEagle** [comment]
This would also be fixed by resolving #4086, as tags do not allow for consecutive underscores (i.e. spaces) in the name field.

**Comment by evazion** [comment]
This was fixed as a side effect of 59b277ead12. `Dmail#to_name` used `User.id_to_pretty_name` instead of the raw name.
