### ISSUE TITLE
Post API occasionally returns status 405

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#4088]
Using the Post API sometimes returns status 405 (Not Allowed).  If this is from the new throttling, the status ought to be 429 (Too Many Requests).

**Comment by r888888888** [comment]
It should be returning 503 according to the Nginx docs. It may be Cloudflare throttling or throwing a CAPTCHA at you as well.

**Comment by evazion** [comment]
@RaisingK is this still happening?
