### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by SakurabaKiyoka** [r888888888/danbooru#4091]
when i complete the script install,running the command "bundle exec rails server",then it shows me "uninitialized constant Danbooru::EnvironmentConfiguration::CustomConfiguration (NameError)"
I try to modify config file but it did't work.

**Comment by r888888888** [comment]
You need to create a file called `danbooru_local_config.rb`. The command in the `INSTALL.debian` that does this is:

> curl -L -s $GITHUB_INSTALL_SCRIPTS/danbooru_local_config.rb.templ -o /var/www/danbooru2/shared/config/danbooru_local_config.rb

**Comment by SakurabaKiyoka** [comment]
> You need to create a file called `danbooru_local_config.rb`. The command in the `INSTALL.debian` that does this is:
> 
> > curl -L -s $GITHUB_INSTALL_SCRIPTS/danbooru_local_config.rb.templ -o /var/www/danbooru2/shared/config/danbooru_local_config.rb

That's work,thanks a lot!
