### ISSUE TITLE
Wiki pages are broken

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4093]
> fossilnix said ([forum #157537](https://danbooru.donmai.us/forum_posts/157537)):
> 
> help:home (https://danbooru.donmai.us/wiki_pages/5650) and several other wiki pages are broken
> 
```
ActionView::Template::Error exception raised

undefined method `>' for nil:NilClass

app/helpers/wiki_pages_helper.rb:9:in `wiki_page_post_previews'
app/views/wiki_pages/show.html.erb:37:in `_app_views_wiki_pages_show_html_erb___3369885448999410384_47294422904240'
 app/controllers/wiki_pages_controller.rb:53:in `show'
```
> 
> EDIT: Seems like it's every page that starts with help:, howto:, about:, or tag_group:

This is kind of weird since nothing has been deployed recently (that I know of), and the wiki was working the other day I believe.

**Comment by evazion** [comment]
This happened because `Post.fast_count` returns nil on db errors. It should probably return zero instead.

https://github.com/r888888888/danbooru/blob/0999e7a71a1e4eb555c781415ce6d3e554932175/app/models/post.rb#L1166-L1185
