### ISSUE TITLE
Preprocessing and saved searches not working

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4095]
> inkuJerr said ([forum #157758](https://danbooru.donmai.us/forum_posts/157758)):
> Post preprocessing seems to be broken again (most recent being [about 3 hours ago](https://danbooru.donmai.us/uploads?search%5Bstatus%5D=preprocessed)).

> Moonspeaker said ([forum #157768](https://danbooru.donmai.us/forum_posts/157768)):
> > alyss said:
> > Saved searches seem to be working again.
>
> Now they're not again, or at least mine isn't loading anything.

Looks like it may be because the delayed jobs worker is dead.

https://danbooru.donmai.us/delayed_jobs?limit=1000&page=339

339000+ jobs at last count and rising.

**Comment by BrokenEagle** [comment]
@r888888888 

Looks like the delayed jobs worker is dead again.

https://danbooru.donmai.us/delayed_jobs?limit=1000&page=403

403000+ jobs at last count and rising.

**Comment by evazion** [comment]
Closing in favor of #4108.
