### ISSUE TITLE
IQDB is not indexing newer pics

### ISSUE THREAD

**Issue by fredgido** [r888888888/danbooru#4098]
most of them but for example:
https://danbooru.donmai.us/iqdb_queries?post_id=3556468
https://danbooru.donmai.us/iqdb_queries?post_id=3555499
https://danbooru.donmai.us/iqdb_queries?post_id=3554136
https://danbooru.donmai.us/iqdb_queries?post_id=3554889
https://danbooru.donmai.us/iqdb_queries?post_id=3553414

**Comment by BrokenEagle** [comment]
I'm currently doing a much more thorough scan as done in issue #3386, but for now at least, I've noticed that every post above ID 3553127 does not have an IQDB index match. Most of the ones before that one have a match, whereas most of those after do not have a match.  It might be easiest to just reindex all posts >3553127.

**Comment by r888888888** [comment]
I've queued updates for all of them.

**Comment by BrokenEagle** [comment]
As pointed out by @evazion on Discord, posts still aren't being regularly indexed. The last post to be indexed was 3 hours ago ([post #3562468](https://danbooru.donmai.us/iqdb_queries?post_id=3562468)), about the same time you queued the updates.

**Comment by evazion** [comment]
Last outage was fixed. See #4108.
