### ISSUE TITLE
Allow moderators to IP ban subnets

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4106]
Mods should be able to IP ban entire subnets, up to /24 for IPv4 or /64 for IPv6. See the recent bans by RaisingK for an example of where this would have been useful:

https://danbooru.donmai.us/mod_actions?commit=Search&page=1&search%5Bcategory%5D=160

**Comment by BrokenEagle** [comment]
Can there be an extra warning for banning subnets? That seems like something to be extra careful about.

**Comment by evazion** [comment]
You have to manually type in the full address, e.g. `1.2.3.4/24`, so it's not something you can do by accident.
