### ISSUE TITLE
Can't create artist entry if tag already has a wiki

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4107]
Creating a new artist entry fails if a wiki with the same name already exists. This should be allowed. See discussion in #2717.

**Comment by BrokenEagle** [comment]
Well, to avoid the problem brought up in the above issue, the type of the wiki should be checked for the right type. That is, unless the wiki is of type artist, then disallow naming an artist as such.

**Comment by evazion** [comment]
The rule now is that you can't create artist entries for character/copyright/meta tags. You can only create artist entries for artist tags or general tags. General tags will automatically be changed to artist tags. General tags are allowed so that users don't get errors if they make a normal gentag first and make the artist entry second.
