### ISSUE TITLE
Autorestart microservices on failure

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4108]
It's not uncommon for the delayed jobs worker or for certain microservices (namely archives and IQDB) to go down. These services should 1) have monitoring and 2) be configured to autorestart on failure. Running under systemd would probably be the easiest thing.

**Comment by evazion** [comment]
This is what I've determined after investigating the most recent failure in delayed jobs. The job server briefly lost its connection to the database, which caused jobs to start failing. When a job fails, the worker tries to mark it as failed in the database, but it can't do that when the database is unavailable, so the worker just crashes instead.

When a worker crashes it also leaves the job in a locked state, meaning that it has to be manually unlocked or deleted or it will stay stuck in the jobs table forever.

I'm not sure why oogaki (the job server) apparently sometimes loses its database connection. Maybe vRack on OVH is flaky. The app servers don't seem to have a problem with it.

This problem of workers crashing is a known issue in the delayed jobs repo, and basically the answer is that it's by design and you're expected to use a process monitor to deal with it.

We still need monitoring, but I think the narrow issue of jobs randomly dying should be fixed.

**Comment by GlassedSilver** [comment]
I could work on process monitors in bash maybe if that's still needed. Well I could try at least.

**Comment by evazion** [comment]
This is mostly handled nowadays by running services in Docker+Kubernetes or in systemd.

**Comment by GlassedSilver** [comment]
Ah right, good idea! Thank you!
