### ISSUE TITLE
Colorize tags in DText

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4112]
Wiki links in DText should be colorized by tag type (e.g. `[[touhou]]` should be purple). See past discussion in #2755.

This will require reworking the DText parser so that it can do things that require database calls.

**Comment by r888888888** [comment]
I guess this is doable, although it adds a lot of complexity to the dtext parser gem. Maybe some sort of intermediate code could be generated that Danbooru could then replace with the color coding.

**Comment by evazion** [comment]
I was thinking to basically pass a hash down to the dtext parser containing the tag info. Something like:

```
DText.parse("[[touhou]]", tags: { "touhou" => "copyright" })
```

So the dtext parser itself wouldn't need to make database calls. Rather the lookups would be done on Danbooru's end and the results would be passed on to the parser.
