### ISSUE TITLE
iphone functionality issues 

### ISSUE THREAD

**Issue by zestubou** [r888888888/danbooru#4126]
I don’t know if anybody else is experiencing this issue, but I am unable to save images from the site (I can only save them, if there’s a link to the original size) and I can’t  open any drop menus when I press and hold an item on the screen that would normally appear when pressing a link to open a new background tab or image selection options. I couldn’t find anyplace else on the internet to bring this issue to, so if anybody has any help that’d be greatly appreciated.

**Comment by evazion** [comment]
I can't reproduce this on Android. Pressing and holding on an image opens the menu as normal.

**Comment by zestubou** [comment]
I wouldn’t expect you to be able to. This is an issue that I’m having on my XR, the menu doesn’t open when I press and hold any part of the website. I can confirm that it works on my old iPhone 7, though. I think it might have something to do with the lack of 3D Touch on the XR.

**Comment by evazion** [comment]
On post pages we have a gesture where swiping left makes you go back to the previous page. It might be interfering. Try  going to your Danbooru account settings (`My Account -> Settings -> Advanced`) and setting the `Disable mobile gestures` option to `Yes`, then test it again.

**Comment by zestubou** [comment]
That did the trick. It works! Thanks a lot

**Comment by evazion** [comment]
This was fixed in eb80d4f36ee6a03faf77138c704b680f0dcaf70e by removing the "swipe to go back" gesture.
