### ISSUE TITLE
Optimize related tags

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4134]
Related tags can be calculated pretty quickly in a single SQL query. Even tags up to 25k posts can be calculated in about a second or less. Larger tags can be approximated by operating on a small sample of the full tag.

This would make related tags an order of magnitude faster and the implementation simpler. We don't have to offload large tags to Reportbooru, we can do it all in delayed jobs on Danbooru.

This also tends to give better results, since it finds small tags that the current method tends to miss due to undersampling.

```
-- monster_girl, 25k posts
SELECT
  tag,
  count(*),
  count(*) / (sqrt(25031.0 * tags.post_count)+0.00001) as cosine_sim
FROM posts, unnest(string_to_array(tag_string, ' ')) tag
JOIN tags on tags.name = tag
WHERE tag_index @@ 'monster_girl'
GROUP BY tag, tags.post_count
ORDER by cosine_sim DESC
LIMIT 100;

                  tag                  | count |       cosine_sim
---------------------------------------+-------+------------------------
 monster_girl                          | 25031 | 0.99999999960049538588
 mermaid                               |  5843 | 0.48314650545850923041
 head_fins                             |  3538 | 0.32660657738893507326
 lamia                                 |  2148 | 0.29293956870473529281
 wakasagihime                          |  2430 | 0.28365156888126750165
 monster_girl_encyclopedia             |  2319 | 0.26389676343888820123
 goo_girl                              |  1494 | 0.24430716153640192567
 scales                                |  2701 | 0.24371230359126778246
 monster_musume_no_iru_nichijou        |  1816 | 0.23543018974897058610
 harpy                                 |  1370 | 0.23394899437526761605
 insect_girl                           |  1756 | 0.23028243127000465695
 plant_girl                            |   870 | 0.18643202861432030962
 spider_girl                           |  1005 | 0.18360304757238975398
 kenkou_cross                          |   726 | 0.16173334896089661840
 centaur                               |   741 | 0.15366368719514002475
 miia_(monster_musume)                 |   581 | 0.15105784707847674151
 monsterification                      |   595 | 0.14184048319721711827
 arachne                               |   493 | 0.14034093263116872556
 extra_eyes                            |   999 | 0.13861726859996715691
 fins                                  |   785 | 0.13635986523093149717
 fish_girl                             |   489 | 0.12169981011580615716
 multiple_legs                         |   414 | 0.12121832577557585777
 dragon_girl                           |  1526 | 0.12091619478774899993
 blue_skin                             |  1654 | 0.11806967653800120442
 talons                                |   522 | 0.11173086461119717746
 rachnera_arachnera                    |   316 | 0.11113394211779918043
 centorea_shianus                      |   311 | 0.10903843433417879459
 scylla                                |   287 | 0.10707839345185582255
 claws                                 |  2115 | 0.10701027252663585165
 papi_(monster_musume)                 |   280 | 0.10520241556977752685
 carapace                              |   297 | 0.10092047788180225168
 shell_bikini                          |   395 | 0.09822945521554505997
 suu_(monster_musume)                  |   232 | 0.09565660253840222014
 gills                                 |   306 | 0.09494197826171912818
 pointy_ears                           |  4840 | 0.08974122330161811389
 bee_girl                              |   258 | 0.08766829391752518833

Time: 1291.083 ms (00:01.291)
```

**Comment by BrokenEagle** [comment]
Would the results still be stored in the tag for a certain time-period, like a day?

Also, for the related tag results by category, I've found that the accuracy can be improved pretty significantly in some cases by increasing the sample-size to 500 instead of 300. Additionally, filtering out results that don't meet a certain cutoff also increased accuracy.

https://danbooru.donmai.us/forum_topics/14051

Finally, I know that the category-less related tag search uses a cosine similarity, and I suppose that works for certain situations. However, I've found quite often I have to go to the category tag search since many of the desired tags are usually absent from those results. An example would be general tags like hair or eye color for a character. Since the cosine similarity between any hair/eye color tag would be significantly low regardless of character, those useful results would never show up. Therefore, it's just my opinion, but I believe it would be better to leave the category related tag searches as just a frequency ranking.

**Comment by evazion** [comment]
> Would the results still be stored in the tag for a certain time-period, like a day?

The related_tags field in the tags table is no longer used. Instead the related tags are now cached in Redis for a fixed 4 hours. Regenerating them is fast so they don't need to be cached for a long time.

> Also, for the related tag results by category, I've found that the accuracy can be improved pretty significantly in some cases by increasing the sample-size to 500 instead of 300. Additionally, filtering out results that don't meet a certain cutoff also increased accuracy.

The sample size is now 1000. I found this provides a good tradeoff between speed and accuracy. It's possible to go significantly higher but in most cases it's just slower without noticeably improving accuracy.

One situation where a high simple size does help is when trying to find rare character or copyright tags. For example, if you're looking for Touhou copyright tags, you need a very high sample size because most of them have very few posts (e.g. `the_embodiment_of_scarlet_devil` makes up only 0.01% the `touhou` tag). It takes a very high sample size to deal with cases like this though, which usually isn't worth it.

> Finally, I know that the category-less related tag search uses a cosine similarity, and I suppose that works for certain situations. However, I've found quite often I have to go to the category tag search since many of the desired tags are usually absent from those results. An example would be general tags like hair or eye color for a character. Since the cosine similarity between any hair/eye color tag would be significantly low regardless of character, those useful results would never show up. Therefore, it's just my opinion, but I believe it would be better to leave the category related tag searches as just a frequency ranking.

The behavior of the related tags buttons should be unchanged. I'm just focused on the implementation here. I do think the interface needs work though. Constantly switching between different buttons while tagging is cumbersome to use and it's unclear to non-expert users what all the buttons even do.
