### ISSUE TITLE
some artist history pages show error instead

### ISSUE THREAD

**Issue by Krabbyos** [r888888888/danbooru#4138]
some artist history pages show the message
`uninitialized constant DidYouMean::Levenshtein`
instead of the actual artist history page

Shows Error
- https://danbooru.donmai.us/artist_versions?search[artist_id]=161533
- https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=40102
- https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=5225

Shows Artist History Page
- https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=170061
- https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=190425
- https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=190366

**Comment by evazion** [comment]
Should be fixed by 13dbdd5 and ca2e2c92b971c936c1559c7c84a074021caeaec1.
