### ISSUE TITLE
Comment unvote link only shown until page refresh

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4143]
Unlike the post vote link (old behavior), the comment vote link does not show the unvote link and hide the vote links upon a failure of the vote links.

Either make it act like the old post vote link (shown upon failure), or the new post vote link (shown upon page load).

**Comment by evazion** [comment]
Fixed in 2cf929a. I incidentally changed the html IDs for vote links and the data attributes on comments, which may affect userscripts or custom CSS dealing with comments.
