### ISSUE TITLE
Deviantart Eclipse update broke strategy

### ISSUE THREAD

**Issue by lllusion3469** [r888888888/danbooru#4144]
[Example](https://www.deviantart.com/citizenfresh/art/Hverarond-14-the-beauty-of-the-earth-789295466)
[source.json](https://danbooru.donmai.us/source.json?url=https://www.deviantart.com/citizenfresh/art/Hverarond-14-the-beauty-of-the-earth-789295466) - notice how the `image_url` is just the url parameter

The new [eclipse](https://www.deviantarteclipse.com/) redesign appears to have been rolled out to all new accounts and *users that aren't logged in*, which breaks the strategy *again* because the new HTML doesn't appear to include the deviation_id (uuid) (needed for the api) anywhere

I don't see a good solution unless they include it again (it was there for a purpose after all), but maybe I just overlooked something obvious.

The only solutions I see are:
* going back to web scraping (note that sta.sh still works, i.e. uses the old design)
* use the apparently intended way of searching the [gallery api](https://www.deviantart.com/developers/http/v1/20160316/gallery_all/bdb19761e6debcc6609356d6b78f4a5d) until we do or do not find a matching post
* maybe (possibly) there's a endpoint at the new javascript backends at `https://www.deviantart.com/_napi/???` (undocumented obviously) that would get us the uuid, but probably not
* maybe use those endpoints to somehow bypass the old API altogether somehow
* figure out how to generate the uuids (probably virtually impossible)
* logging into an old account with the old design just to get to the uuid (probably not possible for much longer) (easier to just web-scrape)

Non-solutions:
* no helpful information in [oembed](https://www.deviantart.com/developers/oembed)

**Comment by evazion** [comment]
Looks like the new frontend is React-based. Meaning that we really don't want to scrape the HTML, it's all generated by Javascript with dynamically generated CSS classes. But it also means that everything on the frontend has to come from some public endpoint on the backend.

And indeed, it looks like everything comes from `https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch`, which appears to give us everything we need:

Regular works:
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=685436408&type=art&include_session=false
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=627759995&type=art&include_session=false
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=506319432&type=art&include_session=false

Download disabled work:
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=697415967&type=art&include_session=false

Download enabled work:
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=774592781&type=art&include_session=false

Login-only work:
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=685458369&type=art&include_session=false

Mature work (NSFW):
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=769913164&type=art&include_session=false

Deleted work (older):

* https://pre00.deviantart.net/423b/th/pre/i/2017/281/e/0/mindflayer_girl01_by_nickbeja-dbpxdt8.png
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=708675884&type=art&include_session=false

Deleted work (newer):

* https://danbooru.donmai.us/posts/3304906
* https://www.deviantart.com/revolmxd/art/welcome-master-767547531
* https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=767547531&type=art&include_session=false

Some observations:

* You don't have to be logged in.
* In fact, it returns 404 if you are logged in to the old DeviantArt.
* Even login-only, mature, and download-disabled works don't require a login.
* We don't need a UUID, we just need the deviation ID.
* Everything we need appears to be in this one API call. We don't need separate calls to find the download url.
* Deleted works return an error. The two works above return different errors.
* The `type=art` param might be interesting to play with. `art` is the only value I've seen.

**Comment by lllusion3469** [comment]
Some other observations:
* some urls are more liberal - those all lead to the same page *if you have the redesign* - otherwise only the first one works:
```
https://www.deviantart.com/citizenfresh/art/Hverarond-14-the-beauty-of-the-earth-789295466
https://www.deviantart.com/citizenfresh/art/--789295466
https://www.deviantart.com/citizenfresh/art/-789295466
https://www.deviantart.com/citizenfresh/art/789295466
https://www.deviantart.com/citizenfresh/art/foo789295466bar
```

**Comment by lllusion3469** [comment]
This `extended_fetch` doesn't seem to work for sta.sh though (which would have enabled you to get rid of the API client entirely):

[Example: your pepe](https://sta.sh/0wxs31o7nn2)
The old api (using the uuid) and the javascript expression `document.querySelector("div[gmi-deviationid]").getAttribute("gmi-deviationid")` both give `763305148`

But calling `curl 'https://www.deviantart.com/_napi/da-deviation/shared_api/deviation/extended_fetch?deviationid=763305148&type=art&include_session=false' | jq .` gives
```json
{
  "error": "server_error",
  "errorDescription": "Internal server error",
  "status": "error"
}
```

**Comment by evazion** [comment]
Honestly, I'm inclined to drop support for sta.sh. It never got much use and keeping the old strategy around just for sta.sh isn't worth the hassle. It was fine when it shared most of its code with Deviant Art, but now that's not going to be the case.

**Comment by lllusion3469** [comment]
Dropping sta.sh would be perfectly understandable, I expected as much.

I think the error is caused by the server trying to generate some information that's not available for sta.sh (e.g. recommendations) since normal `deviation/fetch` works (though no download url there unfortunately)

---

Their source map (including dependencies and everything) is publicly available at [source map](https://static.parastorage.com/services/da-browse/1.631.0/app.bundle.min.js.map).

the `extended_fetch` call is at `node_modules/@wix/da-shared-react/dist/es/src/Duperbrowse/redux/loader.js:111`

**Comment by evazion** [comment]
> Since the download page 302 redirects to the actual image we may want to keep the final url as the source url

I'm using the page url as the source since the new download urls have less information and they contain download tokens that I think are time limited. Unfortunately http://origin-orig.deviantart.net urls don't seem to be available any more.

Page:
https://www.deviantart.com/aeror404/art/Holiday-Elincia-424551484

Old download url:
http://origin-orig.deviantart.net/d533/f/2014/004/8/d/holiday_elincia_by_aeror404-d70rm0s.jpg

New download url (before redirect):
https://www.deviantart.com/download/424551484/d70rm0s-e5b6b5e6-5795-44bb-a0ba-27b5c2349be7.jpg?token=b70509998c0df71ac58ab90979a46fe439c89a35&ts=1567055486

New download url (after redirect):
https://api-da.wixmp.com/_api/download/file?downloadToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTU2NzA1NTQ4NywiaWF0IjoxNTY3MDU0ODc3LCJqdGkiOiI1ZDY3NWMyNzBmM2FlIiwib2JqIjpudWxsLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdLCJwYXlsb2FkIjp7InBhdGgiOiJcL2ZcLzExYTI0Mzk1LTBmMjQtNDQ2ZC1hZTczLWE5ZjgxMmU3OWU1NVwvZDcwcm0wcy1lNWI2YjVlNi01Nzk1LTQ0YmItYTBiYS0yN2I1YzIzNDliZTcuanBnIiwiYXR0YWNobWVudCI6eyJmaWxlbmFtZSI6ImhvbGlkYXlfZWxpbmNpYV9ieV9hZXJvcjQwNF9kNzBybTBzLmpwZyJ9fX0.IvHYdcJbOwh6lh2cq2mySVaC8YdV13yh0NKww3oBIZw

**Comment by lllusion3469** [comment]
Is there any reason not to cache the results of `extended_fetch` and `download_url` (#3874)?

[I hacked something together](https://github.com/lllusion3469/danbooru/commit/05a9b4ff8ce9abc796342299d7c50b821209e34a) though I don't think `app/logical/deviant_art_api_client.rb` is the appropriate place to do it

**Comment by evazion** [comment]
I skipped it mainly because dealing with cookies and caching was painful and  `HttpartyCache` needs to be rewritten to deal with it cleanly. I'll take another look at it though if it's doing that many requests.

**Comment by lllusion3469** [comment]
Is it worth it to make HttpartyCache more complex and store more data in cache when headers and cookies aren't needed in any of the current 8 call sites (including pixiv strategy, which is probably the most used one)?

Wouldn't it be easier to just call `Cache.get` explicitly somewhat like I did [here](https://github.com/lllusion3469/danbooru/commit/da_napi_cache)?

**Comment by lllusion3469** [comment]
So apparently those download links that `extended_fetch` returns don't work anymore if you're not logged in / DA thinks you might possibly be a bot.

Automating the login process apparently also got harder than it was back when we switched to the API.
