### ISSUE TITLE
Add support for metatags with category-less related tags calls

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4146]
Currently, category-less results are only returned on tags where they are populated, whereas category results can be gotten with any relevant tag/metatag combination. This makes getting relevant tags for items like pools a 2-3 related tag lookups.

An example use case would be the weekly upload I do of [pool #7425](https://danbooru.donmai.us/pools/7425).  I usually do a general related tag category lookup on ``pool:7425``, but then have to add the common copyright, artist and meta tags, which I usually do by using autocomplete since selecting the ``pool:`` metatag and clicking each category takes more time then just using autocomplete (plus there's no meta category). It would be nice however to have all of the most common tags show up under the category-less setting.

https://danbooru.donmai.us/posts?tags=pool%3A7425
![image](https://user-images.githubusercontent.com/21149935/63646192-aaeb9900-c6c3-11e9-8325-1cebbd911f51.png)

Those are the tags that show up when doing a post search for ``pool:7425``, and there are several tags from each category that goes on every post in that pool (including a few from the meta category). It would be convenient to have those all show up with only a single click. I can imagine that would prove useful on many series pools, which usually have a common copyright/artist and often general tags as well, and perhaps even meta tags.

Might I suggest that if the category-less related tag search isn't a tag, then just fall back to doing a random sample of posts and returning the most common tags regardless of category. As seen by the tags display from the above image, it's already being done in some fashion.

**Comment by evazion** [comment]
Fixed in 6dd3317.
