### ISSUE TITLE
Remove non-relevant bookmarklet info

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4147]
This is in regards to the bookmarklet page.

https://danbooru.donmai.us/static/bookmarklet

The following line can be removed.

> Note: If you use Firefox, the bookmarklet may not work on certain sites, including Twitter. You must install the Bookmarklets Context Menu (version 1.1.3) addon in order to use the bookmarklet. Install version 1.1.3; version 1.1.4.1 does not work.

I'm having no issues using the bookmarklet on either old Twitter or new Twitter. Current Firefox version is 67.0 on Windows 64-bit.

While we're at the, the rest of that page could use updating as well. Perhaps explicitly mention all of the sites that it works on for both post and batch. Use a bullet list rather than just listing them in a sentence.

Or as an alternative, have two wikis that are user editable that will get displayed on that page.

**help:post_bookmarklet**
**help:batch_bookmarklet**

That way, any changes in the future like the Firefox thing can just be handled by the users instead of having to be hard-coded in.

**Comment by evazion** [comment]
I moved it to [help:bookmarklet_notice](https://danbooru.donmai.us/wiki_pages/help:bookmarklet_notice). Both links are above the wiki text so the wiki has to be written with that in mind.
