### ISSUE TITLE
Add missing post search options on applicable models

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4149]
Artist commentary (missed the refactor from https://github.com/r888888888/danbooru/commit/7b8584e3b08819a9bc1a126811940dee8d1393c5) and artist commentary versions. Also if possible, post versions.

**Comment by evazion** [comment]
Most attributes on most models should be searchable now. Searching post versions by a tag search currently isn't possible because posts and post versions live in separate databases. This would require bringing post versions back to the main database, which is something I want to do eventually.
