### ISSUE TITLE
Add profile endpoint for user detection off-site

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4151]
Having something like ``/profile.json`` that returns the current user's record would be useful, as it's currently impossible to determine who the user is passively from off-site, especially for userscripts. The user would have to actively either enter their username or user ID, which would be prone to mistakes or other issues.

**Comment by evazion** [comment]
Added both `/profile` and `/settings`. `My Account` in the navbar now links to `/profile` and `Settings` now links to `/settings`. `/settings` is useful so it's easier to tell people how to get to their account settings.
