### ISSUE TITLE
Pixiv source strategy is broken

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4152]
https://danbooru.donmai.us/forum_topics/9127?page=278#forum_post_159418

```
Error
Pixiv API access token call failed (status=400 body={"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}})

Details
PixivApiClient::Error exception raised
app/logical/pixiv_api_client.rb:242:in `block in access_token'
app/logical/cache.rb:18:in `get'
app/logical/pixiv_api_client.rb:221:in `access_token'
app/logical/pixiv_api_client.rb:163:in `work'
app/logical/sources/strategies/pixiv.rb:361:in `metadata'
app/logical/sources/strategies/pixiv.rb:249:in `image_urls_sub'
app/logical/sources/strategies/pixiv.rb:98:in `image_urls'
app/logical/sources/strategies/base.rb:75:in `image_url'
app/views/uploads/_image.html.erb:3
app/views/uploads/new.html.erb:14
app/controllers/uploads_controller.rb:12:in `new'
```

The call to authenticate at https://oauth.secure.pixiv.net/auth/token is suddenly failing for some reason.

**Comment by lllusion3469** [comment]
Same problem with pixivpy: upbit/pixivpy#83

**Comment by DaRealFreak** [comment]
well same here:
X-Client-Time and X-Client-Hash header are now required and validated server side
X-Client-Time: RFC3339 converted timestamp
X-Client-Hash: md5([X-Client_Time]+28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c)

so f.e. with X-Client-Time: 2019-09-02T20:51:57+02:00
the X-Client-Hash is: md5(2019-09-02T20:51:57+02:0028c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c)
--> 5bb0b1ec0b6e1a86d7dc18dbea2c80bf

the authentication works with these headers as usual, other values didn't get any additional validation

**Comment by evazion** [comment]
Thanks. It looks like they're just validating that the hash is correct, not that the timestamp makes sense. Even timestamps very far in the past or in the future work:

```
X-Client-Time: 1970-01-01T00:00:00+00:00
X-Client-Hash: ff6c6c416f0de6a5d8cf83d63d78ce31

X-Client-Time: 3000-01-01T00:00:00+00:00
X-Client-Hash: 93771864335ef0c8e52db10be563eab3
```
