### ISSUE TITLE
Fix profile/settings metadata discrepancy

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4155]
With the change to the ``/settings`` and ``/profile`` endpoints (issue #4151), it altered the attributes set on the ``<body>`` element but not the containers in the HTML. So for the profile page, ``data-action = "profile"`` yet the ID of the container is ``a-show``, and for the settings page ``data-action = "settings"`` yet the ID of the container is ``a-edit.``. These action values and container IDs should be the same, and my preference would be to go back to "show" and "edit" since that would make it consistent with the other controllers.

**Comment by evazion** [comment]
Doing this is pretty hacky, and kind of a lie since the profile and settings endpoints really are separate actions.

**Comment by BrokenEagle** [comment]
I didn't think it would be so difficult to implement. Would it be better then to change the views instead?

- ``a-edit`` -> ``a-settings``
- ``a-show`` -> ``a-profile``

An issue with the above though is that the page containers have been around a lot longer than the body attributes, so some users may have old CSS/userscripts that will stop working properly, including your own [Danbooru-EX](https://github.com/evazion/danbooru-ex) script.

https://github.com/evazion/danbooru-ex/blob/master/dist/danbooru-ex.user.js#L199-L201

There were several other places I found an issue in just that repository alone.  Some of these old CSS/userscripts may still have active maintainers, though probably not all.

Another issue is that the original profile and settings page are still visitable.

https://danbooru.donmai.us/users/23799
https://danbooru.donmai.us/users/23799/edit

Both of those still work for me, and both still display the correct attributes/classes on the body element. If the container IDs are changed over but those are left alone, then there would be an even bigger discrepancy between what is basically the same page.

Another issue is that it would split the profile page selectors depending on who is visiting the profile. 
 However some CSS/userscripts may only be processing the more common elements between profiles, and so would either need to double up the selectors or somehow account for the difference.

So I'm not sure that changing the container IDs would be the right path.

Another course of action could be to just regress the changes and have the attributes be different. However, to avoid discrepancies depending on which URL you're visiting the page with, the "/users/USER_ID" and "/users/USER_ID/edit" pages for the user should redirect as "/profile" and "/settings" instead.  Since the body attributes/classes are newer it should cause less trouble, but it should still be documented in the API and perhaps have some kind of PSA. I'm not sure if a site-wide PSA is needed, or just posting in the forum would be sufficient?
