### ISSUE TITLE
Pool diff undefined method exception

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4164]
> DreamFromTheLayer said ([forum #159633](https://danbooru.donmai.us/forum_posts/159633)):
> 
> The diff link in a pool's history under Desc Chg gives the following error (and no description):
 ```
Error

undefined method `pool_version_diff' for #<#<Class:0x00005611fff43d20>:0x0000561200a0cd10> Did you mean? pool_versions_url post_version_diff pool_versions_path
Details

ActionView::Template::Error exception raised
app/views/pool_versions/diff.html.erb:6
```
> Happens on any pool and diff, the only difference being the Class:... part.
> 
> Thanks for all the other updates.

Looks like it was because the pool versions helper was deleted in 8198c610ccc5bde94653a727f9413290d5babb89, however the `diff` view wasn't updated with the new `_diff` partial view.

https://github.com/r888888888/danbooru/blob/0e26d0e77e0576d6f8af85243bebf94efd6aad79/app/views/pool_versions/diff.html.erb#L6

That line should be the following instead:

```ruby
<%= render "diff" %>
```

**Comment by evazion** [comment]
Fixed in 372fd7df1bfd51cae8199d7ff4421fda30a53774.
