### ISSUE TITLE
Tag operators not working with autocomplete

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4169]
Looks like the fix for #4166 (4915690c6d3491f6391e8b17fa8c89ea492d4391) caused the regular tag operators to be disregarded.

This can be fixed by just changing the following.

https://github.com/r888888888/danbooru/blob/4915690c6d3491f6391e8b17fa8c89ea492d4391/app/javascript/src/javascripts/autocomplete.js.erb#L101-L107

It just needs to check the tag prefixes as well for the normal source autocompletion:

```javascript
      if (!metatag && !term) {
        this.close();
        return;
      } else if ((!metatag || ['-','~'].concat(Object.keys(Danbooru.Autocomplete.TAG_CATEGORIES)).includes(metatag)) && term) {
        Autocomplete.normal_source(term, resp);
        return;
      }
```

To be a bit cleaner, that array could be added as a global array to the beginning:

```javascript
Autocomplete.TAG_PREFIX_LIST = ['-','~'].concat(Object.keys(Autocomplete.TAG_CATEGORIES))
```

Then it could just be:

```javascript
      if (!metatag && !term) {
        this.close();
        return;
      } else if ((!metatag || Autocomplete.TAG_PREFIX_LIST.includes(metatag)) && term) {
        Autocomplete.normal_source(term, resp);
        return;
      }
```

**Comment by evazion** [comment]
I chose to deal with this in the parser so that we only have to check for tag prefixes in a single place. I also added some browser-based autocomplete tests in 02354e83fe61c68a7edfc11555ea66097a3b1717 to avoid regressions like this is in the future.
