### ISSUE TITLE
Add more search options and sequential pagination to saved searches index

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4171]
Currently only the `label` parameter works, which significantly restricts the ability to do things like get saved searches in ID order.

Additionally, sequential navigation doesn't seem to work for that endpoint, which makes it difficult to readily grab all or a group of items. I use sequential navigation frequently for all endpoints as it provides a good mechanism to reliably get posts in a sorted ID range.

For example, to get all items of a particular type:
```
page = a0

submit request

record highest ID

page = a + highest ID

repeat loop until no results are returned
```

**Comment by evazion** [comment]
I added a couple more order options. I can't reproduction sequential pagination not working. This works for me:

    https://danbooru.donmai.us/saved_searches?page=a0&search[label]=artist

**Comment by BrokenEagle** [comment]
Yeah, I think I was somehow mistaken, both in the currently existing list of search parameters and with the sequential navigation.
