### ISSUE TITLE
Fix error handling for overly large uploads

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4172]
![image](https://user-images.githubusercontent.com/8430473/65163678-f7936d00-da00-11e9-8880-fc70cf1ce87c.png)

- [ ] Display a better error in the dropzone widget.
- [ ] Show the upload limitations (max file size, max resolution, supported file types) somewhere on the upload page.

**Comment by BrokenEagle** [comment]
Couldn't that last one just be done on the Upload Notice? It's true that it won't auto-update, but it won't change that often either.

**Comment by evazion** [comment]
The upload notice is pretty bloated already so I'm reluctant to add more to it. I put it in the drag and drop widget, since it has room to spare:

![image](https://user-images.githubusercontent.com/8430473/65403886-a3d7a980-dd9b-11e9-87cd-d4dd1b2bf279.png)
