### ISSUE TITLE
Poster for Videos

### ISSUE THREAD

**Issue by Nikey646** [r888888888/danbooru#4196]
While video's are loading, it might be a better UX if the sample of a Post object was actually a poster that the HTML5 Video Player could display until the video is started / loaded.

A screenshot is already being generated for the preview / crop, so it wouldn't be that much more to have it as the sample as well.

**Comment by evazion** [comment]
Unfortunately the only screenshot we store is for the thumbnail, which is only 150x150. In my tests using the thumbnail image for the poster gives a much lower quality preview than what the browser can generate natively.

![image](https://user-images.githubusercontent.com/8430473/67536613-9b75d580-f69d-11e9-8dcf-cc5a75471e39.png)

![image](https://user-images.githubusercontent.com/8430473/67536627-afb9d280-f69d-11e9-8799-6b8ea5d28a5a.png)

**Comment by Nikey646** [comment]
It seems that i forgot to mention an important part of this, which was to make the sample link the larger screenshot, and then using the original link as the video, so as far as i can tell they are identical links anyways.

**Comment by evazion** [comment]
Unfortunately the 150x150 preview is the largest screenshot we have. We don't generate any larger samples for video files.
