### ISSUE TITLE
Allow wildcard searches on IP addresses

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#4207]
Let `/moderator/ip_addrs?search[ip_addr]=` work with wildcards, e.g. `1234:2345:3456:4567:*` or `123.32.*`.

**Comment by evazion** [comment]
This is allowed using either CIDR notation or subnet masks, so `123.32.*` would be `123.32.0.0/16` or `123.32.0.0/255.255.0.0`. `1234:2345:3456:4567:*` would be `1234:2345:3456:4567::/64`.

https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation
https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#Subnet_masks
