### ISSUE TITLE
/moderator/ip_addrs?search[user_id] only uses first ID

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#4208]
When `/moderator/ip_addrs?search[user_id]=` is given multiple IDs (like with the "Search for IP addresses with these users" link), only the first ID is used; `X,Y` != `Y,X`.

**Comment by evazion** [comment]
Fixed by adding a new `/ip_addresses` endpoint where this works. The old endpoint is still available but will be removed soon.

The bug here was that the old endpoint used spaces to separate IDs, not commas. The new endpoint supports both spaces and commas.
