### ISSUE TITLE
Empty Last IP link

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#4213]
user 20 and user 366012 currently have `/ip_addresses?search%5Bip_addr%5D=` for their Last IP link; the `search[ip_addr]=` parameter is also empty for the `users` link.

**Comment by evazion** [comment]
The Last IP field tracks the last IP used to login or seen during normal browsing. It was added in August 2016 by f41c362bf40ebcef58a980a6b23915fbceafb3d4, so users who haven't logged in since that time will have a null last IP.
