### ISSUE TITLE
Some post's sample images do not load

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#529]
If samples (Default image size: large) are enabled, some images don't load, such as http://danbooru.donmai.us/posts/1352056

It seems that the sample doesn't exist, as it gives me "That page does not exist" when I go to the direct URL of the image: http://danbooru.donmai.us/data/sample/sample-de2f6d733510aae3751a10759294e8f5.jpg

The full image loads fine: http://danbooru.donmai.us/data/de2f6d733510aae3751a10759294e8f5.jpg

**Comment by r888888888** [comment]
These two posts were fixed (only an issue on hijiribe).
