### ISSUE TITLE
Favorite groups / Private pools

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#635]
Some users use the "Favorites" feature to track, say, all the posts they've downloaded, posts to translate, or something other than the stated purpose.  The Pointless Pools thread has seen quite a few cases of pools that were essentially themed-extensions of Favorites.

How about a private pool ("bookmarked posts"?) feature?  You could put a link under Options on post pages that pops up a window like the "Add to pool" link with the ability to add the post to a new/existing ppool or remove it from one.  And you could list/access them all from your user page.

They don't have to be refreshed like subscriptions and they don't factor in to things like favcount, so you could give at least a few to all levels, without the limits applied to subs/favs.

**Comment by kxz** [comment]
There should be some indication of who owns a favorite group on the group's page and the overall listing.
