### ISSUE TITLE
Pagination links shown in pages with no results

### ISSUE THREAD

**Issue by sbluen** [r888888888/danbooru#870]
In http://danbooru.donmai.us/posts?utf8=%E2%9C%93&tags=touhou+score%3A%3E1000&commit=Go, a search for "touhou score:>1000", there seem to be no results. However, we still have pagination links, rather than an obvious indicator that there are no results to show.

**Comment by evazion** [comment]
This doesn't seem to be a problem any more. If counting the number of pages takes too long, you just get a timeout instead of wrong pagination links.

**Comment by evazion** [comment]
Closing, no longer an issue.
