### ISSUE TITLE
Some pool histories still have old ordering numbers listed as posts

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#880]
#854 was mostly fixed, but some pools still suffer from it.

Examples: [Pool 4234](http://danbooru.donmai.us/pool_versions?search[pool_id]=4234), [Pool 4125](http://danbooru.donmai.us/pool_versions?search[pool_id]=4125), [Pool 1691](http://danbooru.donmai.us/pool_versions?search[pool_id]=1691), [Pool 1527](http://danbooru.donmai.us/pool_versions?search[pool_id]=1527)

**Edit:** Of those four examples, three are now working properly. But [Pool 1527](http://danbooru.donmai.us/pool_versions?search[pool_id]=1527) still isn't.

**Comment by r888888888** [comment]
Seems someone fixed 413 manually.

**Comment by ToksT** [comment]
> Seems someone fixed 413 manually.

They're still in the history `3 9 11 20 31 58 59 60 61 69 71 72 79 80 81 82 83 84 85 86 87 88 89 90 91 93 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 125 126 127 128 129 130 131 132 133 135 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154`

**Comment by r888888888** [comment]
Fixed
