### ISSUE TITLE
Attempting to save more than 20 tags in a subscription goes nowhere

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#889]
If you try to submit a change to a tag subscription with more than 20 tags, the page will "load" infinitely. It goes nowhere, but the tab icon says it's working.

Saving up to 20 tags works as expected.

**Comment by kittey** [comment]
I'm seeing this again for most tag combinations. Note that this now applies to more than 20 tag <i>combinations</i>.

This gives me a failbooru after 60 seconds:
<pre>1abcdefghijklmnopqr
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21</pre>

Removing letters from the first line one by one gradually speeds it up and I see the expected error message that I can only use up to 20 queries:
Up to q: after 54s; p: 37s; o: 24s; n: 16s; m: 12s; l: 8s; k: 5s; j: 4s; i: 3s; h: 2s.

If I remove the 21st line, the update goes through after 2 seconds, no matter how long the other lines are or how many tags they have.

Making the bottom lines longer has little to no measurable influence. Adding the whole alphabet to lines 16 to 20 (but not to 1-15) gives me the expected error message after 2s, adding it only to 15 introduces some slowdown, adding it only to 12 or less gives a failbooru after 60s.

**Comment by ToksT** [comment]
It seems that since the regex is composed of only two "match zero or more" `*`s and no required characters, the regex engine tries to match nothing over and over again which takes forever for it to go through every combination of nothing. Or something silly like that.

It might be possible to fix the regex by replacing the `*`s with `+`s, but then there'd be cases of valid subscriptions not being matched when they should that we'd have to deal with somehow. I'm just going to change it to count them the normal way instead of with regex.
