### ISSUE TITLE
Provide database dump

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#907]
The hard part is stripping out any sensitive user data such as ip addresses, emails, etc. I unfortunately don't have a beefy enough computer available to do something like this. I may need to spin up an Amazon EC2 instance.

**Comment by ToksT** [comment]
The links are dead.

Also, it might be nice to have a new dump since it's been nearly 2 years and there are now new tables and more records in the existing tables.

**Comment by r888888888** [comment]
I now have a replicated database. Interested users should contact me for accounts.
