### ISSUE TITLE
Update wiki help pages for Danbooru 2

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#981]
All of the help pages I know of from Danbooru 1 have been imported to Danbooru 2's wiki. But they still need to be updated to more accurately reflect the site's current state.

The following list will keep track of whether each help page is up-to-date or not. Anyone can feel free to help update them.
- [x] [help:posts](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:posts)
- [x] [help:artists](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:artists)
- [x] [help:tags](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:tags)
- [x] [help:notes](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:notes)
- [x] [help:pools](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:pools)
- [x] [help:comments](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:comments)
- [x] [help:forum](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:forum)
- [x] [help:wiki](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:wiki)
- [x] [help:users](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:users) (Half-finished.)
- [x] [help:dtext](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:dtext)
- [x] [help:tag_scripts](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:tag_scripts)
- [x] [help:tag_subscriptions](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:tag_subscriptions)
- [x] [help:api](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:api)
- [x] [help:blacklists](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:blacklists)
- [x] [help:cheatsheet](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:cheatsheet)
- [x] [help:favorites](http://danbooru.donmai.us/wiki_pages/show_or_new?title=help:favorites)

**Comment by evazion** [comment]
Went through the remaining two items on the above list (`help:artists` and `help:tags`). Everything looks reasonably up-to-date now, so closing.
